-- Development-only seed. Run after creating demo auth users through Supabase Auth.
-- Never store passwords in this repository. Create users from the local Studio or:
-- supabase auth users create demo-owner@example.test --password-prompt
-- The handle_new_user trigger creates an organization when organization_name is supplied
-- in user metadata. Use a non-production local project for this seed.

insert into public.system_settings(key,value,is_public)
values ('phase', '{"number":1,"name":"Identity and access foundation"}'::jsonb, true)
on conflict (key) do update set value=excluded.value, updated_at=now();

-- Safe sample audit records are generated by actual actions. No fabricated user UUIDs
-- are inserted here because all user-owned rows must reference auth.users.
