import type { InventoryData, InventoryMovement, InventoryUser } from "./types";

export const inventoryPermissions = ["inventory.view", "inventory.items.view", "inventory.items.manage", "inventory.warehouses.view", "inventory.warehouses.manage", "inventory.stock.view", "inventory.costs.view", "inventory.valuation.view", "inventory.requests.create", "inventory.requests.review", "inventory.requests.approve", "inventory.reservations.manage", "inventory.receipts.view", "inventory.receipts.post", "inventory.issues.create", "inventory.issues.approve", "inventory.issues.pick", "inventory.issues.post", "inventory.returns.create", "inventory.returns.approve", "inventory.returns.post", "inventory.transfers.create", "inventory.transfers.approve", "inventory.transfers.dispatch", "inventory.transfers.receive", "inventory.counts.create", "inventory.counts.perform", "inventory.counts.approve", "inventory.adjustments.create", "inventory.adjustments.approve", "inventory.adjustments.post", "inventory.damage.manage", "inventory.reorder.view", "inventory.requisitions.create_draft", "inventory.reversal.approve", "inventory.export", "inventory.print", "inventory.audit.view"];
const read = ["inventory.view", "inventory.items.view", "inventory.warehouses.view", "inventory.stock.view", "inventory.receipts.view", "inventory.reorder.view"];
const orgA = "org-madar-demo", orgB = "org-other-demo", at = "2026-08-08T08:00:00.000Z";
const users = (org: string): InventoryUser[] => [
  { id: org === orgA ? "u-owner" : "u-other", organizationId: org, name: "مستخدم مالك تجريبي", role: "owner", permissions: [...inventoryPermissions] },
  { id: `${org}-inventory-manager`, organizationId: org, name: "مدير مخزون تجريبي", role: "inventory_manager", permissions: inventoryPermissions.filter(x => !["inventory.warehouses.manage"].includes(x)) },
  { id: `${org}-keeper`, organizationId: org, name: "أمين مستودع تجريبي", role: "warehouse_keeper", permissions: [...read, "inventory.requests.create", "inventory.requests.review", "inventory.reservations.manage", "inventory.issues.create", "inventory.issues.pick", "inventory.issues.post", "inventory.returns.create", "inventory.transfers.create", "inventory.transfers.dispatch", "inventory.counts.perform", "inventory.print"] },
  { id: `${org}-cost`, organizationId: org, name: "مراقب تكلفة تجريبي", role: "finance_cost_controller", permissions: [...read, "inventory.costs.view", "inventory.valuation.view", "inventory.adjustments.approve", "inventory.reversal.approve", "inventory.audit.view"] },
  { id: `${org}-viewer`, organizationId: org, name: "مشاهد تجريبي", role: "viewer", permissions: [...read] },
];

export function createInventorySeed(): InventoryData {
  const categories = [
    { id: "cat-board-a", organizationId: orgA, code: "BOARD", name: "ألواح وأخشاب", nameEn: "Boards & timber", active: true },
    { id: "cat-finish-a", organizationId: orgA, code: "FIN", name: "مواد تشطيب", nameEn: "Finishes", active: true },
    { id: "cat-board-b", organizationId: orgB, code: "BOARD", name: "فئة معزولة", nameEn: "Isolated category", active: true },
  ];
  const units = [
    { id: "uom-pc-a", organizationId: orgA, code: "PC", name: "قطعة", nameEn: "Piece", precision: 0, active: true },
    { id: "uom-sheet-a", organizationId: orgA, code: "SHEET", name: "لوح", nameEn: "Sheet", precision: 0, active: true },
    { id: "uom-l-a", organizationId: orgA, code: "L", name: "لتر", nameEn: "Liter", precision: 3, active: true },
    { id: "uom-pc-b", organizationId: orgB, code: "PC", name: "قطعة", nameEn: "Piece", precision: 0, active: true },
  ];
  const items = [
    { id: "item-ply-a", organizationId: orgA, sku: "PLY-18-DEMO", name: "خشب أبلكاش 18 مم تجريبي", nameEn: "Demo 18mm plywood", categoryId: "cat-board-a", baseUnitId: "uom-sheet-a", tracking: "lot" as const, currency: "SAR" as const, status: "active" as const, description: "بيانات مصطنعة لتجهيز المعارض", recordVersion: 1, createdBy: "u-owner", createdAt: at },
    { id: "item-paint-a", organizationId: orgA, sku: "PNT-WH-DEMO", name: "دهان أبيض تجريبي", nameEn: "Demo white paint", categoryId: "cat-finish-a", baseUnitId: "uom-l-a", tracking: "lot" as const, currency: "SAR" as const, status: "active" as const, description: "دهان تشطيبات مصطنع", recordVersion: 1, createdBy: "u-owner", createdAt: at },
    { id: "item-led-a", organizationId: orgA, sku: "LED-DEMO", name: "وحدة إضاءة تجريبية", nameEn: "Demo LED unit", categoryId: "cat-finish-a", baseUnitId: "uom-pc-a", tracking: "serial" as const, currency: "SAR" as const, status: "active" as const, description: "صنف مسلسل مصطنع", recordVersion: 1, createdBy: "u-owner", createdAt: at },
    { id: "item-finished-a", organizationId: orgA, sku: "BOOTH-MOD-DEMO", name: "وحدة جناح معرض تجريبية", nameEn: "Demo exhibition booth module", categoryId: "cat-board-a", baseUnitId: "uom-pc-a", tracking: "none" as const, currency: "SAR" as const, status: "active" as const, description: "منتج تام مصطنع لاختبار استلام الإنتاج", recordVersion: 1, createdBy: "u-owner", createdAt: at },
    { id: "item-private-b", organizationId: orgB, sku: "ISO-B-001", name: "صنف شركة ب", nameEn: "Tenant B item", categoryId: "cat-board-b", baseUnitId: "uom-pc-b", tracking: "none" as const, currency: "SAR" as const, status: "active" as const, description: "لاختبار العزل", recordVersion: 1, createdBy: "u-other", createdAt: at },
  ];
  const warehouses = [
    { id: "wh-main-a", organizationId: orgA, code: "MAIN", name: "المستودع الرئيسي التجريبي", nameEn: "Demo main warehouse", type: "main" as const, status: "active" as const, recordVersion: 1 },
    { id: "wh-prod-a", organizationId: orgA, code: "PROD", name: "مستودع الإنتاج التجريبي", nameEn: "Demo production warehouse", type: "production" as const, status: "active" as const, recordVersion: 1 },
    { id: "wh-site-a", organizationId: orgA, code: "SITE", name: "مستودع الموقع التجريبي", nameEn: "Demo site warehouse", type: "site" as const, status: "active" as const, recordVersion: 1 },
    { id: "wh-quarantine-a", organizationId: orgA, code: "QUAR", name: "منطقة الحجر التجريبية", nameEn: "Demo quarantine", type: "quarantine" as const, status: "active" as const, recordVersion: 1 },
    { id: "wh-main-b", organizationId: orgB, code: "MAIN", name: "مستودع شركة ب", nameEn: "Tenant B warehouse", type: "main" as const, status: "active" as const, recordVersion: 1 },
  ];
  const zones = warehouses.map((w, i) => ({ id: `zone-${i + 1}`, organizationId: w.organizationId, warehouseId: w.id, code: "Z01", name: "منطقة 01", status: "active" as const }));
  const bins = zones.map((z, i) => ({ id: `bin-${i + 1}`, organizationId: z.organizationId, warehouseId: z.warehouseId, zoneId: z.id, code: z.warehouseId.includes("quarantine") ? "Q-01" : "A-01", name: "موقع تخزين تجريبي", bucket: z.warehouseId.includes("quarantine") ? "quarantine" as const : "available" as const, status: "active" as const }));
  const opening: InventoryMovement = { id: "mov-opening-a", organizationId: orgA, number: "OPN-2026-00001", type: "opening", status: "posted", occurredAt: "2026-08-01T08:00:00.000Z", sourceType: "documented_demo_opening", sourceId: "seed-opening-a", idempotencyKey: "seed-opening-a", recordVersion: 1, createdBy: "u-owner", approvedBy: `${orgA}-inventory-manager`, lines: [
    { id: "movl-open-ply", itemId: "item-ply-a", warehouseId: "wh-main-a", binId: "bin-1", quantityMills: 120_000n, direction: 1, bucket: "available", unitCostMinorSnapshot: 12_500n, currency: "SAR", lotId: "lot-ply-a", serialIds: [] },
    { id: "movl-open-paint", itemId: "item-paint-a", warehouseId: "wh-main-a", binId: "bin-1", quantityMills: 48_000n, direction: 1, bucket: "available", unitCostMinorSnapshot: 2_750n, currency: "SAR", lotId: "lot-paint-a", serialIds: [] },
    { id: "movl-open-led", itemId: "item-led-a", warehouseId: "wh-main-a", binId: "bin-1", quantityMills: 12_000n, direction: 1, bucket: "available", unitCostMinorSnapshot: 8_900n, currency: "SAR", serialIds: ["serial-led-001", "serial-led-002", "serial-led-003", "serial-led-004", "serial-led-005", "serial-led-006", "serial-led-007", "serial-led-008", "serial-led-009", "serial-led-010", "serial-led-011", "serial-led-012"] },
  ] };
  const openingB: InventoryMovement = { id: "mov-opening-b", organizationId: orgB, number: "OPN-2026-00001", type: "opening", status: "posted", occurredAt: at, sourceType: "documented_demo_opening", sourceId: "seed-opening-b", idempotencyKey: "seed-opening-b", recordVersion: 1, createdBy: "u-other", approvedBy: "u-other", lines: [{ id: "movl-open-b", itemId: "item-private-b", warehouseId: "wh-main-b", binId: "bin-5", quantityMills: 5_000n, direction: 1, bucket: "available", unitCostMinorSnapshot: 1_000n, currency: "SAR", serialIds: [] }] };
  return {
    users: [...users(orgA), ...users(orgB)], categories, units, conversions: [{ id: "conv-ply-a", organizationId: orgA, itemId: "item-ply-a", fromUnitId: "uom-sheet-a", toUnitId: "uom-pc-a", numerator: 1n, denominator: 1n, rounding: "half_up" }], items, warehouses, zones, bins,
    settings: [{ id: "set-ply-main", organizationId: orgA, itemId: "item-ply-a", warehouseId: "wh-main-a", minimumMills: 40_000n, maximumMills: 160_000n, safetyMills: 25_000n, leadTimeDays: 7, reorderEnabled: true }, { id: "set-paint-main", organizationId: orgA, itemId: "item-paint-a", warehouseId: "wh-main-a", minimumMills: 60_000n, maximumMills: 140_000n, safetyMills: 20_000n, leadTimeDays: 5, reorderEnabled: true }],
    lots: [{ id: "lot-ply-a", organizationId: orgA, itemId: "item-ply-a", lotNumber: "LOT-DEMO-PLY-01", manufacturedAt: "2026-07-01", expiresAt: "2028-07-01", status: "active" }, { id: "lot-paint-a", organizationId: orgA, itemId: "item-paint-a", lotNumber: "LOT-DEMO-PNT-01", manufacturedAt: "2026-06-01", expiresAt: "2027-06-01", status: "active" }],
    serials: Array.from({ length: 12 }, (_, i) => ({ id: `serial-led-${String(i + 1).padStart(3, "0")}`, organizationId: orgA, itemId: "item-led-a", serialNumber: `DEMO-LED-${String(i + 1).padStart(4, "0")}`, status: "available" as const })), movements: [opening, openingB],
    requests: [{ id: "mr-a-1", organizationId: orgA, number: "MR-2026-00001", projectId: "project-1", status: "approved", purpose: "مواد إنتاج تجريبية", lines: [{ id: "mrl-a-1", itemId: "item-ply-a", requestedMills: 30_000n, approvedMills: 30_000n, allocatedMills: 20_000n, issuedMills: 0n, requiredDate: "2026-08-12", warehouseId: "wh-main-a", wbsId: "wbs-2", taskId: "task-2", productionJobId: "prod-1" }], recordVersion: 2, idempotencyKey: "seed-mr-a-1", createdBy: `${orgA}-keeper`, approvedBy: `${orgA}-inventory-manager`, createdAt: at }],
    reservations: [{ id: "res-a-1", organizationId: orgA, number: "RSV-2026-00001", materialRequestId: "mr-a-1", projectId: "project-1", expiresAt: "2026-08-15", status: "active", lines: [{ id: "resl-a-1", itemId: "item-ply-a", warehouseId: "wh-main-a", binId: "bin-1", quantityMills: 20_000n, releasedMills: 0n, issuedMills: 0n, lotId: "lot-ply-a", serialIds: [] }], recordVersion: 1, createdBy: `${orgA}-inventory-manager` }],
    documents: [{ id: "receipt-post-a-1", organizationId: orgA, number: "SRP-2026-00001", kind: "receipt", status: "draft", sourceType: "procurement_receipt", sourceId: "grn-1", lines: [{ id: "docl-rec-a-1", itemId: "item-ply-a", quantityMills: 20_000n, warehouseId: "wh-main-a", binId: "bin-1", unitCostMinorSnapshot: 12_800n, currency: "SAR", lotId: "lot-ply-a", serialIds: [], projectId: "project-1", sourceLineId: "grnl-1" }], reason: "Procurement receipt awaiting stock posting", recordVersion: 1, idempotencyKey: "seed-receipt-draft", createdBy: `${orgA}-keeper`, createdAt: at }],
    transfers: [{ id: "tr-a-1", organizationId: orgA, number: "TRF-2026-00001", fromWarehouseId: "wh-main-a", toWarehouseId: "wh-prod-a", status: "approved", lines: [{ id: "trl-a-1", itemId: "item-ply-a", quantityMills: 10_000n, receivedMills: 0n, warehouseId: "wh-main-a", binId: "bin-1", unitCostMinorSnapshot: 12_500n, currency: "SAR", lotId: "lot-ply-a", serialIds: [], projectId: "project-1", productionJobId: "prod-1" }], recordVersion: 2, idempotencyKey: "seed-transfer-a", createdBy: `${orgA}-keeper`, approvedBy: `${orgA}-inventory-manager` }],
    counts: [{ id: "count-a-1", organizationId: orgA, number: "CNT-2026-00001", warehouseId: "wh-main-a", blind: true, status: "in_progress", lines: [{ id: "countl-a-1", itemId: "item-paint-a", warehouseId: "wh-main-a", binId: "bin-1", unitCostMinorSnapshot: 2_750n, currency: "SAR" }], recordVersion: 1, createdBy: `${orgA}-keeper` }],
    damage: [{ id: "dmg-a-1", organizationId: orgA, number: "DMG-2026-00001", itemId: "item-paint-a", warehouseId: "wh-main-a", binId: "bin-1", quantityMills: 2_000n, reason: "عبوة متضررة تجريبية", evidence: [{ name: "demo-evidence.jpg", mimeType: "image/jpeg", sizeBytes: 12000 }], decision: "hold", status: "pending_approval", costMinorSnapshot: 2_750n, currency: "SAR", responsibleId: `${orgA}-keeper`, recordVersion: 1 }],
    costEvents: [], approvals: [{ id: "approval-dmg-a", organizationId: orgA, entityType: "damage", entityId: "dmg-a-1", requestedBy: `${orgA}-keeper`, status: "pending", createdAt: at }], timeline: [], notifications: [], idempotencyKeys: ["seed-opening-a", "seed-opening-b", "seed-mr-a-1", "seed-receipt-draft", "seed-transfer-a"], sequences: { [`${orgA}:item`]: 3, [`${orgA}:request`]: 1, [`${orgA}:reservation`]: 1, [`${orgA}:receipt`]: 1, [`${orgA}:transfer`]: 1, [`${orgA}:count`]: 1, [`${orgA}:damage`]: 1 }
  };
}
