import type { CurrencyCode } from "@/lib/sales/types";

export type InventoryRole = "owner" | "system_admin" | "operations_manager" | "inventory_manager" | "warehouse_keeper" | "warehouse_receiver" | "material_controller" | "procurement_manager" | "project_manager" | "production_manager" | "site_engineer" | "qa_qc" | "finance_cost_controller" | "internal_auditor" | "viewer";
export type ItemStatus = "draft" | "active" | "blocked" | "archived";
export type TrackingMode = "none" | "lot" | "serial";
export type StockBucket = "available" | "reserved" | "quarantine" | "damaged" | "in_transit";
export type MovementType = "opening" | "receipt" | "issue" | "return" | "transfer_out" | "transfer_in" | "adjustment_in" | "adjustment_out" | "damage" | "scrap" | "reversal";
export type DocumentStatus = "draft" | "submitted" | "pending_approval" | "approved" | "rejected" | "allocated" | "picked" | "posted" | "dispatched" | "partially_received" | "received" | "cancelled" | "reversed";

export interface InventoryUser { id: string; organizationId: string; name: string; role: InventoryRole; permissions: string[] }
export interface ItemCategory { id: string; organizationId: string; code: string; name: string; nameEn: string; parentId?: string; active: boolean }
export interface UnitOfMeasure { id: string; organizationId: string; code: string; name: string; nameEn: string; precision: number; active: boolean }
export interface UnitConversion { id: string; organizationId: string; itemId: string; fromUnitId: string; toUnitId: string; numerator: bigint; denominator: bigint; rounding: "half_up" | "down" }
export interface InventoryItem { id: string; organizationId: string; sku: string; name: string; nameEn: string; categoryId: string; baseUnitId: string; tracking: TrackingMode; currency: CurrencyCode; status: ItemStatus; description: string; recordVersion: number; createdBy: string; createdAt: string; deletedAt?: string }
export interface Warehouse { id: string; organizationId: string; code: string; name: string; nameEn: string; type: "main" | "production" | "site" | "quarantine"; status: "active" | "blocked" | "archived"; recordVersion: number }
export interface WarehouseZone { id: string; organizationId: string; warehouseId: string; code: string; name: string; status: "active" | "blocked" }
export interface StorageBin { id: string; organizationId: string; warehouseId: string; zoneId: string; code: string; name: string; bucket: StockBucket; status: "active" | "blocked" }
export interface ItemWarehouseSetting { id: string; organizationId: string; itemId: string; warehouseId: string; minimumMills: bigint; maximumMills: bigint; safetyMills: bigint; leadTimeDays: number; reorderEnabled: boolean }
export interface StockLot { id: string; organizationId: string; itemId: string; lotNumber: string; manufacturedAt?: string; expiresAt?: string; status: "active" | "quality_hold" | "expired" | "closed" }
export interface SerialRecord { id: string; organizationId: string; itemId: string; serialNumber: string; status: "available" | "reserved" | "issued" | "returned" | "damaged" }
export interface InventoryMovementLine { id: string; itemId: string; warehouseId: string; binId: string; quantityMills: bigint; direction: 1 | -1; bucket: StockBucket; unitCostMinorSnapshot: bigint; currency: CurrencyCode; lotId?: string; serialIds: string[]; projectId?: string; wbsId?: string; taskId?: string; productionJobId?: string; sourceMovementLineId?: string }
export interface InventoryMovement { id: string; organizationId: string; number: string; type: MovementType; status: "posted" | "reversed"; occurredAt: string; sourceType: string; sourceId: string; idempotencyKey: string; recordVersion: number; createdBy: string; approvedBy?: string; reversalOfId?: string; lines: InventoryMovementLine[] }
export interface MaterialRequestLine { id: string; itemId: string; requestedMills: bigint; approvedMills: bigint; allocatedMills: bigint; issuedMills: bigint; requiredDate: string; warehouseId: string; wbsId?: string; taskId?: string; productionJobId?: string }
export interface MaterialRequest { id: string; organizationId: string; number: string; projectId: string; status: DocumentStatus; purpose: string; lines: MaterialRequestLine[]; recordVersion: number; idempotencyKey: string; createdBy: string; approvedBy?: string; createdAt: string }
export interface ReservationLine { id: string; itemId: string; warehouseId: string; binId: string; quantityMills: bigint; releasedMills: bigint; issuedMills: bigint; lotId?: string; serialIds: string[] }
export interface Reservation { id: string; organizationId: string; number: string; materialRequestId: string; projectId: string; expiresAt: string; status: "draft" | "active" | "partially_issued" | "fulfilled" | "expired" | "released" | "cancelled"; lines: ReservationLine[]; recordVersion: number; createdBy: string }
export interface InventoryDocumentLine { id: string; itemId: string; quantityMills: bigint; warehouseId: string; binId: string; unitCostMinorSnapshot: bigint; currency: CurrencyCode; lotId?: string; serialIds: string[]; projectId?: string; wbsId?: string; taskId?: string; productionJobId?: string; sourceLineId?: string }
export interface InventoryDocument { id: string; organizationId: string; number: string; kind: "receipt" | "issue" | "return" | "adjustment" | "damage" | "reversal"; status: DocumentStatus; sourceType: string; sourceId: string; lines: InventoryDocumentLine[]; reason: string; recordVersion: number; idempotencyKey: string; createdBy: string; approvedBy?: string; postedMovementId?: string; createdAt: string }
export interface StockTransfer { id: string; organizationId: string; number: string; fromWarehouseId: string; toWarehouseId: string; status: "draft" | "pending_approval" | "approved" | "dispatched" | "partially_received" | "received" | "cancelled"; lines: Array<InventoryDocumentLine & { receivedMills: bigint }>; recordVersion: number; idempotencyKey: string; createdBy: string; approvedBy?: string; dispatchMovementId?: string; receiptMovementId?: string }
export interface CountLine { id: string; itemId: string; warehouseId: string; binId: string; systemMillsSnapshot?: bigint; countedMills?: bigint; recountMills?: bigint; varianceMills?: bigint; unitCostMinorSnapshot: bigint; currency: CurrencyCode }
export interface CountSession { id: string; organizationId: string; number: string; warehouseId: string; blind: boolean; status: "draft" | "in_progress" | "submitted" | "recount_requested" | "pending_approval" | "approved" | "posted" | "cancelled"; lines: CountLine[]; recordVersion: number; createdBy: string; approvedBy?: string }
export interface DamageRecord { id: string; organizationId: string; number: string; itemId: string; warehouseId: string; binId: string; quantityMills: bigint; reason: string; evidence: Array<{ name: string; mimeType: string; sizeBytes: number }>; decision: "rework" | "return_interface" | "scrap" | "hold" | "release"; status: DocumentStatus; costMinorSnapshot: bigint; currency: CurrencyCode; responsibleId: string; recordVersion: number }
export interface InventoryCostEvent { id: string; organizationId: string; projectId: string; currency: CurrencyCode; sourceType: "inventory_issue" | "inventory_return" | "inventory_reversal"; sourceId: string; sourceLineId: string; amountMinor: bigint; kind: "recognized" | "reversed"; idempotencyKey: string; occurredAt: string }
export interface InventoryEvent { id: string; organizationId: string; entityType: string; entityId: string; action: string; summary: string; createdBy: string; createdAt: string; links: Record<string, string> }
export interface InventoryNotification { id: string; organizationId: string; userId: string; type: string; entityType: string; entityId: string; title: string; dedupeKey: string; read: boolean; createdAt: string }
export interface InventoryApproval { id: string; organizationId: string; entityType: string; entityId: string; requestedBy: string; status: "pending" | "approved" | "rejected" | "returned"; decidedBy?: string; comment?: string; createdAt: string }
export interface InventoryData { users: InventoryUser[]; categories: ItemCategory[]; units: UnitOfMeasure[]; conversions: UnitConversion[]; items: InventoryItem[]; warehouses: Warehouse[]; zones: WarehouseZone[]; bins: StorageBin[]; settings: ItemWarehouseSetting[]; lots: StockLot[]; serials: SerialRecord[]; movements: InventoryMovement[]; requests: MaterialRequest[]; reservations: Reservation[]; documents: InventoryDocument[]; transfers: StockTransfer[]; counts: CountSession[]; damage: DamageRecord[]; costEvents: InventoryCostEvent[]; approvals: InventoryApproval[]; timeline: InventoryEvent[]; notifications: InventoryNotification[]; idempotencyKeys: string[]; sequences: Record<string, number> }
export interface StockBalance { organizationId: string; itemId: string; warehouseId: string; binId: string; bucket: StockBucket; onHandMills: bigint; reservedMills: bigint; availableMills: bigint; averageUnitCostMinor: bigint; currency: CurrencyCode }
export interface ReorderSuggestion { itemId: string; warehouseId: string; availableMills: bigint; reservedMills: bigint; openRequestMills: bigint; openPurchaseMills: bigint; acceptedNotPostedMills: bigint; inTransitMills: bigint; safetyMills: bigint; minimumMills: bigint; maximumMills: bigint; suggestedMills: bigint; stockoutRiskDate?: string; explanation: string }
