import{describe,expect,it}from"vitest";import{agingBucket,buildStatement,calculateInvoice,formatMoney,roundRatio,settlementStatus}from"./calculations";import type{BillingAdjustment,Invoice,PaymentAllocation}from"./types";
describe("billing calculations",()=>{
 it("uses integer half-up rounding",()=>{expect(roundRatio(1n,1n,2n)).toBe(1n);expect(roundRatio(10n,15n,100n)).toBe(2n)});
 it("calculates discount tax fees without floats",()=>{expect(calculateInvoice([{id:"1",description:"x",quantityMills:1250n,unit:"u",unitPriceMinor:999n,discountBps:1000,taxBps:1500,feeMinor:7n}])).toEqual({subtotalMinor:1249n,discountMinor:125n,taxableMinor:1124n,taxMinor:169n,feesMinor:7n,totalMinor:1300n})});
 it("rejects invalid lines",()=>expect(()=>calculateInvoice([{id:"1",description:"x",quantityMills:0n,unit:"u",unitPriceMinor:1n,discountBps:0,taxBps:0,feeMinor:0n}])).toThrow());
 it.each([[100n,0n,0n,0n,"unpaid"],[100n,50n,0n,0n,"partially_paid"],[100n,100n,0n,0n,"paid"],[100n,0n,200n,0n,"overpaid_adjustment"]] as const)("derives settlement",(t,a,c,d,s)=>expect(settlementStatus(t,a,c,d)).toBe(s));
 it.each([["2026-09-01","not_due"],["2026-08-06","1_30"],["2026-07-01","31_60"],["2026-06-01","61_90"],["2026-01-01","over_90"]] as const)("buckets aging",(due,b)=>expect(agingBucket(due,"2026-08-07")).toBe(b));
 it("formats 0, 2 and 3 decimal currencies",()=>{expect(formatMoney(12n,"JPY")).toBe("12 JPY");expect(formatMoney(1234n,"SAR")).toBe("12.34 SAR");expect(formatMoney(1234n,"KWD")).toBe("1.234 KWD")});
 it("builds a running balance from issued activity",()=>{const invoice={id:"i",organizationId:"o",number:"INV",customerId:"c",contractId:"ct",currency:"SAR",workflowStatus:"issued",settlementStatus:"unpaid",deliveryStatus:"not_sent",snapshot:{number:"INV",customerId:"c",customerName:"C",contractId:"ct",contractNumber:"CTR",contractVersionId:"v",quotationNumber:"Q",salesRequestId:"S",ownerId:"u",department:"d",city:"x",currency:"SAR",issueDate:"2026-01-01",dueDate:"2026-01-31",language:"ar",lines:[],totals:{subtotalMinor:100n,discountMinor:0n,taxableMinor:100n,taxMinor:0n,feesMinor:0n,totalMinor:100n},paymentInstructions:"",sourceIds:[],changeOrderIds:[],notice:""},openBalanceMinor:60n,allocatedMinor:40n,creditAppliedMinor:0n,debitAppliedMinor:0n,recordVersion:1,createdBy:"u",createdAt:"2026-01-01T00:00:00Z",updatedAt:"2026-01-01T00:00:00Z"} as Invoice;const alloc={id:"a",organizationId:"o",receiptId:"r",invoiceId:"i",amountMinor:40n,status:"active",snapshot:{receiptNumber:"REC",invoiceNumber:"INV",customerId:"c",currency:"SAR",invoiceBalanceBefore:100n},idempotencyKey:"k",createdBy:"u",createdAt:"2026-01-02T00:00:00Z"} as PaymentAllocation;const rows=buildStatement([invoice],[alloc],[] as BillingAdjustment[],"2026-01-01","2026-01-31");expect(rows.map(r=>r.balanceMinor)).toEqual([100n,60n])});
});
