import type { AgingRow, Invoice, InvoiceLine, InvoiceTotals, PaymentAllocation, BillingAdjustment, StatementRow } from "./types";

export const CURRENCY_DECIMALS:Record<string,number>={JPY:0,KRW:0,SAR:2,AED:2,USD:2,EUR:2,KWD:3,BHD:3,OMR:3};
export function roundRatio(value:bigint,numerator:bigint,denominator:bigint){if(denominator<=0n)throw new Error("Invalid denominator");const product=value*numerator;return (product+denominator/2n)/denominator}
export function calculateInvoice(lines:InvoiceLine[]):InvoiceTotals{
  let subtotalMinor=0n,discountMinor=0n,taxMinor=0n,feesMinor=0n;
  for(const line of lines){if(line.quantityMills<=0n||line.unitPriceMinor<0n||line.feeMinor<0n||line.discountBps<0||line.discountBps>10000||line.taxBps<0||line.taxBps>10000)throw new Error("Invalid invoice line");const base=roundRatio(line.unitPriceMinor,line.quantityMills,1000n);const discount=roundRatio(base,BigInt(line.discountBps),10000n);const taxable=base-discount;subtotalMinor+=base;discountMinor+=discount;taxMinor+=roundRatio(taxable,BigInt(line.taxBps),10000n);feesMinor+=line.feeMinor}
  const taxableMinor=subtotalMinor-discountMinor;return{subtotalMinor,discountMinor,taxableMinor,taxMinor,feesMinor,totalMinor:taxableMinor+taxMinor+feesMinor};
}
export function settlementStatus(total:bigint,allocated:bigint,credit:bigint,debit:bigint){const due=total+debit-credit;if(due<0n)return"overpaid_adjustment" as const;if(allocated<=0n)return"unpaid" as const;if(allocated<due)return"partially_paid" as const;return"paid" as const}
export function openBalance(invoice:Invoice){return invoice.snapshot.totals.totalMinor+invoice.debitAppliedMinor-invoice.creditAppliedMinor-invoice.allocatedMinor}
export function agingBucket(dueDate:string,asOf:string):AgingRow["bucket"]{const due=Date.parse(`${dueDate}T00:00:00Z`),at=Date.parse(`${asOf}T00:00:00Z`);const days=Math.floor((at-due)/86400000);if(days<=0)return"not_due";if(days<=30)return"1_30";if(days<=60)return"31_60";if(days<=90)return"61_90";return"over_90"}
export function buildStatement(invoices:Invoice[],allocations:PaymentAllocation[],adjustments:BillingAdjustment[],from:string,to:string){const rows:{date:string;reference:string;description:string;debitMinor:bigint;creditMinor:bigint}[]=[];for(const i of invoices)if(i.workflowStatus==="issued"&&i.snapshot.issueDate>=from&&i.snapshot.issueDate<=to)rows.push({date:i.snapshot.issueDate,reference:i.number,description:"فاتورة داخلية",debitMinor:i.snapshot.totals.totalMinor,creditMinor:0n});for(const a of adjustments)if(a.status==="issued"&&a.issuedAt&&a.issuedAt.slice(0,10)>=from&&a.issuedAt.slice(0,10)<=to)rows.push({date:a.issuedAt.slice(0,10),reference:a.number,description:a.type==="credit_note"?"إشعار خصم داخلي":"إشعار إضافة داخلي",debitMinor:a.type==="debit_note"?a.totals.totalMinor:0n,creditMinor:a.type==="credit_note"?a.totals.totalMinor:0n});for(const a of allocations)if(a.status==="active"&&a.createdAt.slice(0,10)>=from&&a.createdAt.slice(0,10)<=to)rows.push({date:a.createdAt.slice(0,10),reference:a.snapshot.receiptNumber,description:`تحصيل موزع على ${a.snapshot.invoiceNumber}`,debitMinor:0n,creditMinor:a.amountMinor});rows.sort((a,b)=>a.date.localeCompare(b.date)||a.reference.localeCompare(b.reference));let balance=0n;return rows.map((r):StatementRow=>{balance+=r.debitMinor-r.creditMinor;return{...r,balanceMinor:balance}})}
export function formatMoney(minor:bigint,currency:string){const decimals=CURRENCY_DECIMALS[currency]??2;const factor=10n**BigInt(decimals),whole=minor/factor,fraction=(minor<0n?-minor:minor)%factor;const sign=minor<0n?"-":"";return`${sign}${whole<0n?-whole:whole}${decimals?`.${fraction.toString().padStart(decimals,"0")}`:""} ${currency}`}
