import { calculateInvoice } from "./calculations";
import type { BillingData, BillingRole, InvoiceLine } from "./types";

export const BILLING_PERMISSIONS=["billing.dashboard.view","billing.settings.view","billing.settings.manage","invoices.view","invoices.create","invoices.create_manual","invoices.update_draft","invoices.submit","invoices.approve","invoices.issue","invoices.void","invoices.export","invoices.print","invoices.view_financials","receipts.view","receipts.create","receipts.confirm","receipts.allocate","receipts.unallocate","receipts.reverse","receipts.export","credit_notes.view","credit_notes.create","credit_notes.approve","credit_notes.issue","debit_notes.view","debit_notes.create","debit_notes.approve","debit_notes.issue","aging.view","aging.export","customer_statements.view","customer_statements.export","collections.view","collections.create_followup","collections.assign","collections.escalate"] as const;
const read=["billing.dashboard.view","invoices.view","receipts.view","aging.view","customer_statements.view","collections.view"];
export const billingPermissionsByRole:Record<BillingRole,string[]>={
 owner:[...BILLING_PERMISSIONS],admin:[...BILLING_PERMISSIONS],accountant:[...BILLING_PERMISSIONS.filter(x=>x!=="billing.settings.manage")],
 sales_manager:[...read,"invoices.print","collections.create_followup","collections.assign","collections.escalate"],sales_agent:["invoices.view","collections.view","collections.create_followup"],customer_service:["invoices.view","collections.view","collections.create_followup"],viewer:read,marketing:[]};
const org="org-madar-demo",other="org-other-demo",now="2026-08-07T09:00:00.000Z";
const users=(Object.entries({"u-owner":["عبدالعزيز الجندي","owner"],"u-admin":["مدير النظام التجريبي","admin"],"u-accountant":["أحمد فؤاد","accountant"],"u-sales":["محمد علي","sales_manager"],"u-agent":["ريم خالد","sales_agent"],"u-service":["سارة أحمد","customer_service"],"u-viewer":["مشاهد تجريبي","viewer"],"u-marketing":["مسوق تجريبي","marketing"]}) as [string,[string,BillingRole]][]).map(([id,[name,role]])=>({id,organizationId:org,name,role,permissions:billingPermissionsByRole[role]}));users.push({id:"u-other",organizationId:other,name:"مالك شركة أخرى",role:"owner",permissions:billingPermissionsByRole.owner});
const lines:InvoiceLine[]=[{id:"il-1",description:"دفعة بدء التصميم والتنفيذ",quantityMills:1000n,unit:"دفعة",unitPriceMinor:4800000n,discountBps:0,taxBps:1500,feeMinor:0n}];const totals=calculateInvoice(lines);
export function createBillingSeed():BillingData{return{
 users,settings:[{organizationId:org,defaultLanguage:"bilingual",invoicePrefix:"INV",receiptPrefix:"REC",adjustmentPrefix:"ADJ",defaultDueDays:30,defaultTaxBps:1500,paymentInstructions:"تحويل بنكي — بيانات تجريبية غير مخصصة للدفع",internalDocumentNotice:"مستند داخلي تجريبي — ليس فاتورة ضريبية معتمدة من ZATCA",recordVersion:1}],
 sources:[
  {id:"src-pay-1",organizationId:org,contractId:"ctr-1",contractNumber:"CTR-2026-00001",contractVersionId:"ctrv-1",quotationNumber:"QUO-2026-00002",salesRequestId:"sr-contract-source",customerId:"customer-demo-2",customerName:"شركة رؤية الفعاليات",ownerId:"u-sales",department:"المشاريع",city:"جدة",currency:"SAR",label:"دفعة مقدمة 40%",amountMinor:4800000n,dueDate:"2026-08-15",eligible:false,reason:"تمت فوترتها",changeOrderIds:[]},
  {id:"src-pay-2",organizationId:org,contractId:"ctr-1",contractNumber:"CTR-2026-00001",contractVersionId:"ctrv-1",quotationNumber:"QUO-2026-00002",salesRequestId:"sr-contract-source",customerId:"customer-demo-2",customerName:"شركة رؤية الفعاليات",ownerId:"u-sales",department:"المشاريع",city:"جدة",currency:"SAR",label:"دفعة اكتمال التصنيع 40%",amountMinor:4800000n,dueDate:"2026-09-05",eligible:true,changeOrderIds:[]},
  {id:"src-pay-3",organizationId:org,contractId:"ctr-1",contractNumber:"CTR-2026-00001",contractVersionId:"ctrv-1",quotationNumber:"QUO-2026-00002",salesRequestId:"sr-contract-source",customerId:"customer-demo-2",customerName:"شركة رؤية الفعاليات",ownerId:"u-sales",department:"المشاريع",city:"جدة",currency:"SAR",label:"دفعة التسليم 20%",amountMinor:2400000n,dueDate:"2026-09-20",eligible:false,reason:"المعلم غير مكتمل",changeOrderIds:[]},
  {id:"src-other",organizationId:other,contractId:"ctr-other",contractNumber:"CTR-2026-00999",contractVersionId:"ctrv-other",quotationNumber:"QUO-OTHER",salesRequestId:"sr-other",customerId:"customer-other",customerName:"عميل شركة أخرى",ownerId:"u-other",department:"sales",city:"Riyadh",currency:"USD",label:"Other tenant",amountMinor:10000n,dueDate:"2026-08-20",eligible:true,changeOrderIds:[]}],
 invoices:[{id:"inv-1",organizationId:org,number:"INV-2026-00001",customerId:"customer-demo-2",contractId:"ctr-1",currency:"SAR",workflowStatus:"issued",settlementStatus:"partially_paid",deliveryStatus:"not_sent",snapshot:{number:"INV-2026-00001",customerId:"customer-demo-2",customerName:"شركة رؤية الفعاليات",contractId:"ctr-1",contractNumber:"CTR-2026-00001",contractVersionId:"ctrv-1",quotationNumber:"QUO-2026-00002",salesRequestId:"sr-contract-source",ownerId:"u-sales",department:"المشاريع",city:"جدة",currency:"SAR",issueDate:"2026-07-01",dueDate:"2026-07-31",language:"bilingual",lines,totals,paymentInstructions:"تحويل بنكي — بيانات تجريبية غير مخصصة للدفع",sourceIds:["src-pay-1"],changeOrderIds:[],notice:"مستند داخلي تجريبي — ليس فاتورة ضريبية معتمدة من ZATCA"},openBalanceMinor:3520000n,allocatedMinor:2000000n,creditAppliedMinor:0n,debitAppliedMinor:0n,recordVersion:2,createdBy:"u-accountant",approvedBy:"u-owner",issuedAt:"2026-07-01T10:00:00.000Z",createdAt:"2026-06-30T10:00:00.000Z",updatedAt:now}],
 approvals:[],receipts:[{id:"rec-1",organizationId:org,number:"REC-2026-00001",customerId:"customer-demo-2",customerName:"شركة رؤية الفعاليات",date:"2026-07-15",currency:"SAR",amountMinor:2500000n,method:"bank_transfer",reference:"DEMO-REF-001",accountLabel:"حساب تجريبي",notes:"تأكيد داخلي فقط؛ لا يثبت القيد البنكي",createdBy:"u-accountant",confirmedBy:"u-owner",status:"confirmed_internal",allocatedMinor:2000000n,unallocatedMinor:500000n,recordVersion:2,createdAt:"2026-07-15T09:00:00.000Z"}],
 allocations:[{id:"alloc-1",organizationId:org,receiptId:"rec-1",invoiceId:"inv-1",amountMinor:2000000n,status:"active",snapshot:{receiptNumber:"REC-2026-00001",invoiceNumber:"INV-2026-00001",customerId:"customer-demo-2",currency:"SAR",invoiceBalanceBefore:5520000n},idempotencyKey:"seed-allocation",createdBy:"u-accountant",createdAt:"2026-07-15T09:30:00.000Z"}],adjustments:[],followups:[{id:"fol-1",organizationId:org,invoiceId:"inv-1",customerId:"customer-demo-2",ownerId:"u-sales",followupDate:"2026-08-05",channel:"phone",outcome:"وعد بالسداد",promised:true,expectedPaymentDate:"2026-08-12",expectedAmountMinor:3520000n,nextAction:"متابعة تأكيد التحويل",nextActionDate:"2026-08-12",notes:"بيانات تجريبية",status:"promise_to_pay",createdBy:"u-sales",createdAt:"2026-08-05T11:00:00.000Z"}],
 timeline:[],audit:[],notifications:[],sequences:{[`${org}:2026:invoice`]:1,[`${org}:2026:receipt`]:1,[`${org}:2026:adjustment`]:0},idempotencyKeys:["seed-allocation"]};}
