import type { CurrencyCode, SalesRole } from "@/lib/sales/types";

export type BillingRole = SalesRole;
export type InvoiceWorkflowStatus = "draft" | "under_review" | "changes_requested" | "approved" | "issued" | "voided";
export type SettlementStatus = "unpaid" | "partially_paid" | "paid" | "overpaid_adjustment";
export type DeliveryStatus = "not_sent" | "queued_demo" | "delivered_demo" | "failed_demo";
export type ReceiptStatus = "draft" | "pending_confirmation" | "confirmed_internal" | "reversed";
export type AdjustmentType = "credit_note" | "debit_note";
export type AdjustmentStatus = "draft" | "under_review" | "approved" | "issued" | "rejected" | "voided";

export interface BillingUser { id:string; organizationId:string; name:string; role:BillingRole; permissions:string[] }
export interface BillingSettings { organizationId:string; defaultLanguage:"ar"|"en"|"bilingual"; invoicePrefix:string; receiptPrefix:string; adjustmentPrefix:string; defaultDueDays:number; defaultTaxBps:number; paymentInstructions:string; internalDocumentNotice:string; recordVersion:number }
export interface BillingSource {
  id:string; organizationId:string; contractId:string; contractNumber:string; contractVersionId:string; quotationNumber:string; salesRequestId:string; customerId:string; customerName:string; ownerId:string; department:string; city:string; currency:CurrencyCode; label:string; amountMinor:bigint; dueDate:string; eligible:boolean; reason?:string; changeOrderIds:string[];
}
export interface InvoiceLine { id:string; description:string; quantityMills:bigint; unit:string; unitPriceMinor:bigint; discountBps:number; taxBps:number; feeMinor:bigint }
export interface InvoiceTotals { subtotalMinor:bigint; discountMinor:bigint; taxableMinor:bigint; taxMinor:bigint; feesMinor:bigint; totalMinor:bigint }
export interface InvoiceSnapshot { number:string; customerId:string; customerName:string; contractId:string; contractNumber:string; contractVersionId:string; quotationNumber:string; salesRequestId:string; ownerId:string; department:string; city:string; currency:CurrencyCode; issueDate:string; dueDate:string; language:"ar"|"en"|"bilingual"; lines:InvoiceLine[]; totals:InvoiceTotals; paymentInstructions:string; sourceIds:string[]; changeOrderIds:string[]; notice:string }
export interface Invoice { id:string; organizationId:string; number:string; customerId:string; contractId:string; currency:CurrencyCode; workflowStatus:InvoiceWorkflowStatus; settlementStatus:SettlementStatus; deliveryStatus:DeliveryStatus; snapshot:InvoiceSnapshot; openBalanceMinor:bigint; allocatedMinor:bigint; creditAppliedMinor:bigint; debitAppliedMinor:bigint; recordVersion:number; createdBy:string; approvedBy?:string; issuedAt?:string; voidReason?:string; createdAt:string; updatedAt:string }
export interface BillingApproval { id:string; organizationId:string; entityType:"invoice"|"adjustment"; entityId:string; status:"pending"|"approved"|"rejected"|"changes_requested"; requestedBy:string; requestedAt:string; decidedBy?:string; decidedAt?:string; comment?:string }
export interface PaymentReceipt { id:string; organizationId:string; number:string; customerId:string; customerName:string; date:string; currency:CurrencyCode; amountMinor:bigint; method:"bank_transfer"|"cash"|"card"|"cheque"|"other"; reference:string; accountLabel:string; notes:string; attachmentMetadata?:string; createdBy:string; confirmedBy?:string; status:ReceiptStatus; allocatedMinor:bigint; unallocatedMinor:bigint; recordVersion:number; reversalReason?:string; createdAt:string }
export interface PaymentAllocation { id:string; organizationId:string; receiptId:string; invoiceId:string; amountMinor:bigint; status:"active"|"reversed"; snapshot:{receiptNumber:string; invoiceNumber:string; customerId:string; currency:CurrencyCode; invoiceBalanceBefore:bigint}; idempotencyKey:string; createdBy:string; createdAt:string; reversedAt?:string }
export interface BillingAdjustment { id:string; organizationId:string; number:string; invoiceId:string; customerId:string; currency:CurrencyCode; type:AdjustmentType; reason:string; lines:InvoiceLine[]; totals:InvoiceTotals; status:AdjustmentStatus; beforeBalanceMinor:bigint; afterBalanceMinor?:bigint; recordVersion:number; createdBy:string; approvedBy?:string; issuedAt?:string; createdAt:string }
export interface CollectionFollowup { id:string; organizationId:string; invoiceId:string; customerId:string; ownerId:string; followupDate:string; channel:string; outcome:string; promised:boolean; expectedPaymentDate?:string; expectedAmountMinor?:bigint; nextAction:string; nextActionDate:string; notes:string; status:"new"|"contacted"|"promise_to_pay"|"disputed"|"escalated"|"resolved"|"closed"; attachmentMetadata?:string; createdBy:string; createdAt:string }
export interface BillingEvent { id:string; organizationId:string; customerId:string; contractId?:string; invoiceId?:string; receiptId?:string; allocationId?:string; adjustmentId?:string; followupId?:string; action:string; summary:string; createdBy:string; createdAt:string }
export interface BillingAudit { id:string; organizationId:string; actorId:string; entityType:string; entityId:string; action:string; details:string; createdAt:string }
export interface BillingNotification { id:string; organizationId:string; userId:string; type:string; entityType:string; entityId:string; title:string; dedupeKey:string; read:boolean; createdAt:string }
export interface BillingData { users:BillingUser[]; settings:BillingSettings[]; sources:BillingSource[]; invoices:Invoice[]; approvals:BillingApproval[]; receipts:PaymentReceipt[]; allocations:PaymentAllocation[]; adjustments:BillingAdjustment[]; followups:CollectionFollowup[]; timeline:BillingEvent[]; audit:BillingAudit[]; notifications:BillingNotification[]; sequences:Record<string,number>; idempotencyKeys:string[] }
export interface InvoiceFilters { query?:string; workflowStatus?:InvoiceWorkflowStatus; settlementStatus?:SettlementStatus; currency?:CurrencyCode; customerId?:string; overdue?:boolean; page?:number; pageSize?:number; sort?:"newest"|"due_date"|"balance" }
export interface Paged<T> { rows:T[]; page:number; pageSize:number; total:number; pages:number }
export interface AgingRow { invoiceId:string; invoiceNumber:string; customerId:string; customerName:string; currency:CurrencyCode; dueDate:string; openBalanceMinor:bigint; bucket:"not_due"|"1_30"|"31_60"|"61_90"|"over_90" }
export interface StatementRow { date:string; reference:string; description:string; debitMinor:bigint; creditMinor:bigint; balanceMinor:bigint }
