import type { ProductionData, ProductionUser } from "./types";

export const productionPermissions = ["production.view","production.manage_master_data","production.manage_bom","production.approve_bom","production.manage_routing","production.approve_routing","production.manage_work_centers","production.plan","production.run_mrp","production.approve_plan","production.create_order","production.release_order","production.execute_operation","production.pause_operation","production.override_sequence","production.record_output","production.post_completion","production.record_scrap","production.approve_scrap","production.record_quality","production.approve_quality","production.manage_subcontract","production.view_cost","production.manage_rates","production.close_order","production.reverse","production.export","production.print","production.view_audit"];
const users = (org: string): ProductionUser[] => [
  { id:org==="org-madar-demo"?"u-owner":`${org}-owner`,organizationId:org,name:"Demo Owner",role:"owner",permissions:[...productionPermissions] },
  { id:`${org}-planner`,organizationId:org,name:"Demo Planner",role:"planner",permissions:["production.view","production.manage_bom","production.manage_routing","production.plan","production.run_mrp","production.create_order","production.export","production.print"] },
  { id:`${org}-manager`,organizationId:org,name:"Demo Production Manager",role:"production_manager",permissions:["production.view","production.approve_bom","production.approve_routing","production.approve_plan","production.release_order","production.close_order","production.approve_scrap","production.view_cost","production.print"] },
  { id:`${org}-operator`,organizationId:org,name:"Demo Operator",role:"operator",permissions:["production.view","production.execute_operation","production.pause_operation","production.record_output"] },
  { id:`${org}-quality`,organizationId:org,name:"Demo Quality Inspector",role:"quality",permissions:["production.view","production.record_quality","production.approve_quality"] },
  { id:`${org}-viewer`,organizationId:org,name:"Demo Viewer",role:"viewer",permissions:["production.view"] },
];
export function createProductionSeed(): ProductionData {
  const org="org-madar-demo", other="org-other-demo";
  const workCenters = [
    {id:"wc-carp-a",organizationId:org,code:"WC-CARP",name:"نجارة",nameEn:"Carpentry",type:"internal" as const,workingDays:[0,1,2,3,4],shiftMinutes:480,parallelResources:2,efficiencyBps:9000,hourlyRateMinor:7500n,currency:"SAR" as const,status:"active" as const,recordVersion:1},
    {id:"wc-assembly-a",organizationId:org,code:"WC-ASM",name:"تجميع",nameEn:"Assembly",type:"assembly" as const,workingDays:[0,1,2,3,4],shiftMinutes:480,parallelResources:1,efficiencyBps:8500,hourlyRateMinor:6000n,currency:"SAR" as const,status:"active" as const,recordVersion:1},
    {id:"wc-quality-a",organizationId:org,code:"WC-QA",name:"جودة",nameEn:"Quality",type:"quality" as const,workingDays:[0,1,2,3,4],shiftMinutes:420,parallelResources:1,efficiencyBps:10000,currency:"SAR" as const,status:"active" as const,recordVersion:1},
  ];
  const boms = [{id:"bom-a-1",organizationId:org,number:"BOM-2026-00001",outputItemId:"item-finished-a",outputQuantityMills:1000n,unitId:"uom-pc-a",revision:1,status:"released" as const,effectiveFrom:"2026-08-01",recordVersion:4,createdBy:`${org}-planner`,approvedBy:`${org}-manager`,lines:[{id:"boml-a-1",itemId:"item-ply-a",quantityMills:2000n,fixedQuantityMills:0n,scrapBps:500,issueMethod:"staging" as const,procurementMode:"buy" as const,warehouseId:"wh-main-a",binId:"bin-1",alternativeItemIds:[]},{id:"boml-a-2",itemId:"item-paint-a",quantityMills:500n,fixedQuantityMills:100n,scrapBps:200,issueMethod:"manual" as const,procurementMode:"buy" as const,warehouseId:"wh-main-a",binId:"bin-1",alternativeItemIds:[]}]}];
  const routings = [{id:"routing-a-1",organizationId:org,number:"RT-2026-00001",itemId:"item-finished-a",revision:1,status:"released" as const,recordVersion:4,createdBy:`${org}-planner`,approvedBy:`${org}-manager`,operations:[{id:"op-a-10",sequence:10,code:"CUT",name:"قص وتجهيز",nameEn:"Cut and prepare",workCenterId:"wc-carp-a",setupMinutes:30,runMinutesPerUnit:25,queueMinutes:20,moveMinutes:10,inspectionRequired:false,subcontracted:false,instructions:"اعتماد المخطط قبل القص"},{id:"op-a-20",sequence:20,code:"ASM",name:"التجميع",nameEn:"Assembly",workCenterId:"wc-assembly-a",setupMinutes:20,runMinutesPerUnit:40,queueMinutes:15,moveMinutes:10,inspectionRequired:true,subcontracted:false,instructions:"مطابقة الأبعاد"}]}];
  const order={id:"po-prod-a-1",organizationId:org,number:"MO-2026-00001",projectId:"project-1",wbsId:"wbs-1-2",taskId:"task-1-2",productionJobId:"prod-1",finishedItemId:"item-finished-a",plannedQuantityMills:10_000n,completedGoodMills:2_000n,completedScrapMills:500n,reworkMills:500n,currency:"SAR" as const,plannedStart:"2026-08-08",plannedEnd:"2026-08-14",requiredDate:"2026-08-15",priority:"high" as const,productionWarehouseId:"wh-prod-a",outputWarehouseId:"wh-prod-a",outputBinId:"bin-2",status:"in_progress" as const,bomRevision:1,routingRevision:1,bomSnapshot:boms[0].lines.map(x=>({...x,sourceBomLineId:x.id})),routingSnapshot:routings[0].operations.map(x=>({...x,sourceOperationId:x.id})),materialReadiness:"issued" as const,recordVersion:7,idempotencyKey:"seed-production-order-a",createdBy:`${org}-planner`,approvedBy:`${org}-manager`,releasedBy:`${org}-manager`,completionIds:["completion-a-1"]};
  return { users:[...users(org),...users(other)], profiles:[{id:"profile-finished-a",organizationId:org,itemId:"item-finished-a",productionType:"finished_good",procurementMode:"make",stocked:true,defaultWarehouseId:"wh-production-a",defaultBinId:"bin-production-a",minimumBatchMills:1000n,batchMultipleMills:1000n,scrapBps:500,leadTimeDays:5,status:"active",recordVersion:1}], boms, routings, workCenters, orders:[order], jobCards:routings[0].operations.map((x,index)=>({id:`card-a-${index+1}`,organizationId:org,number:`JC-2026-0000${index+1}`,orderId:order.id,operationSequence:x.sequence,workCenterId:x.workCenterId,status:index===0?"completed":"started",plannedQuantityMills:10_000n,inputMills:index===0?10_000n:2_500n,goodMills:index===0?9_500n:2_000n,scrapMills:index===0?500n:500n,reworkMills:index===0?0n:500n,setupMinutes:x.setupMinutes,runMinutes:index===0?250:100,laborMinutes:index===0?260:110,resourceMinutes:index===0?250:100,pauseMinutes:index===0?20:30,inspectionStatus:index===0?"not_required":"pending",recordVersion:2,assignedUserId:`${org}-operator`,startedAt:"2026-08-08T08:00:00Z",endedAt:index===0?"2026-08-08T13:00:00Z":undefined})), mrpRuns:[], completions:[{id:"completion-a-1",organizationId:org,number:"PC-2026-00001",orderId:order.id,jobCardId:"card-a-2",goodMills:2_000n,scrapMills:500n,reworkMills:500n,qualityStatus:"pass",status:"posted",idempotencyKey:"seed-completion-a",createdBy:`${org}-operator`,approvedBy:`${org}-quality`,inventoryMovementId:"movement-interface-seed",createdAt:"2026-08-08T14:00:00Z"}], downtimes:[{id:"down-a-1",organizationId:org,number:"DT-2026-00001",orderId:order.id,jobCardId:"card-a-2",workCenterId:"wc-assembly-a",startAt:"2026-08-08T10:00:00Z",endAt:"2026-08-08T10:30:00Z",minutes:30,category:"material_shortage",planned:false,note:"Synthetic shortage"}], scrap:[{id:"scrap-a-1",organizationId:org,number:"SC-2026-00001",orderId:order.id,jobCardId:"card-a-2",quantityMills:500n,reason:"Synthetic cutting loss",recoverable:false,status:"approved",createdBy:`${org}-operator`,approvedBy:`${org}-manager`}], subcontract:[], timeline:[], notifications:[], idempotencyKeys:["seed-production-order-a","seed-completion-a"], sequences:{[`${org}:order`]:1,[`${org}:job_card`]:2,[`${org}:completion`]:1,[`${org}:mrp`]:0} };
}
