import type { CurrencyCode } from "@/lib/sales/types";

export type ProductionRole = "owner" | "production_manager" | "planner" | "supervisor" | "operator" | "quality" | "warehouse" | "cost_controller" | "viewer";
export type RevisionStatus = "draft" | "under_review" | "approved" | "released" | "superseded" | "archived";
export type ProductionOrderStatus = "draft" | "planned" | "material_check" | "awaiting_approval" | "released" | "in_progress" | "on_hold" | "partially_completed" | "completed" | "closed" | "cancelled";
export type JobCardStatus = "pending" | "ready" | "started" | "paused" | "blocked" | "completed" | "failed_inspection" | "rework_required" | "cancelled";

export interface ProductionUser { id: string; organizationId: string; name: string; role: ProductionRole; permissions: string[] }
export interface ProductionProfile { id: string; organizationId: string; itemId: string; productionType: "raw_material" | "component" | "subassembly" | "finished_good" | "consumable" | "service"; procurementMode: "make" | "buy" | "subcontract" | "mixed"; stocked: boolean; defaultWarehouseId?: string; defaultBinId?: string; minimumBatchMills: bigint; batchMultipleMills: bigint; scrapBps: number; leadTimeDays: number; status: "active" | "blocked" | "obsolete"; recordVersion: number }
export interface BomLine { id: string; itemId: string; quantityMills: bigint; fixedQuantityMills: bigint; scrapBps: number; issueMethod: "manual" | "staging" | "backflush_preview"; procurementMode: "make" | "buy" | "subcontract"; warehouseId: string; binId: string; alternativeItemIds: string[] }
export interface Bom { id: string; organizationId: string; number: string; outputItemId: string; outputQuantityMills: bigint; unitId: string; revision: number; status: RevisionStatus; effectiveFrom: string; lines: BomLine[]; recordVersion: number; createdBy: string; approvedBy?: string }
export interface RoutingOperation { id: string; sequence: number; code: string; name: string; nameEn: string; workCenterId: string; setupMinutes: number; runMinutesPerUnit: number; queueMinutes: number; moveMinutes: number; inspectionRequired: boolean; subcontracted: boolean; instructions: string }
export interface Routing { id: string; organizationId: string; number: string; itemId: string; revision: number; status: RevisionStatus; operations: RoutingOperation[]; recordVersion: number; createdBy: string; approvedBy?: string }
export interface WorkCenter { id: string; organizationId: string; code: string; name: string; nameEn: string; type: "internal" | "external" | "assembly" | "quality" | "packing"; workingDays: number[]; shiftMinutes: number; parallelResources: number; efficiencyBps: number; hourlyRateMinor?: bigint; currency: CurrencyCode; status: "active" | "maintenance" | "blocked" | "retired"; recordVersion: number }
export interface BomSnapshotLine extends BomLine { sourceBomLineId: string }
export interface OperationSnapshot extends RoutingOperation { sourceOperationId: string }
export interface ProductionOrder { id: string; organizationId: string; number: string; projectId: string; wbsId: string; taskId: string; productionJobId: string; finishedItemId: string; plannedQuantityMills: bigint; completedGoodMills: bigint; completedScrapMills: bigint; reworkMills: bigint; currency: CurrencyCode; plannedStart: string; plannedEnd: string; requiredDate: string; priority: "low" | "normal" | "high" | "urgent"; productionWarehouseId: string; outputWarehouseId: string; outputBinId: string; status: ProductionOrderStatus; bomRevision: number; routingRevision: number; bomSnapshot: BomSnapshotLine[]; routingSnapshot: OperationSnapshot[]; materialReadiness: "not_checked" | "shortage" | "partially_available" | "available" | "reserved" | "staged" | "issued" | "blocked_by_quality"; recordVersion: number; idempotencyKey: string; createdBy: string; approvedBy?: string; releasedBy?: string; completionIds: string[]; closedAt?: string }
export interface JobCard { id: string; organizationId: string; number: string; orderId: string; operationSequence: number; workCenterId: string; status: JobCardStatus; plannedQuantityMills: bigint; inputMills: bigint; goodMills: bigint; scrapMills: bigint; reworkMills: bigint; setupMinutes: number; runMinutes: number; laborMinutes: number; resourceMinutes: number; pauseMinutes: number; inspectionStatus: "not_required" | "pending" | "pass" | "conditional" | "fail"; recordVersion: number; assignedUserId?: string; startedAt?: string; endedAt?: string }
export interface MrpRequirement { id: string; itemId: string; grossMills: bigint; onHandUsableMills: bigint; reservedMills: bigint; openSupplyMills: bigint; safetyMills: bigint; netMills: bigint; shortageMills: bigint; requiredDate: string; suggestion: "none" | "purchase_requisition" | "production_order" | "transfer" | "expedite"; pegging: { orderId: string; projectId: string; wbsId: string; taskId: string }; firm: boolean }
export interface MrpRun { id: string; organizationId: string; number: string; status: "draft" | "calculated" | "reviewed" | "firm" | "archived"; runAt: string; horizonEnd: string; requirements: MrpRequirement[]; parameters: { includeOpenPurchases: boolean; includeOpenProduction: boolean; depthLimit: number }; createdBy: string }
export interface Completion { id: string; organizationId: string; number: string; orderId: string; jobCardId: string; goodMills: bigint; scrapMills: bigint; reworkMills: bigint; qualityStatus: "pass" | "conditional" | "fail"; status: "draft" | "approved" | "posted" | "reversed"; idempotencyKey: string; createdBy: string; approvedBy?: string; inventoryMovementId?: string; createdAt: string }
export interface Downtime { id: string; organizationId: string; number: string; orderId: string; jobCardId: string; workCenterId: string; startAt: string; endAt: string; minutes: number; category: "material_shortage" | "quality_hold" | "machine_unavailable" | "resource_unavailable" | "drawing_delay" | "subcontract_delay"; planned: boolean; note: string }
export interface ScrapRecord { id: string; organizationId: string; number: string; orderId: string; jobCardId: string; quantityMills: bigint; reason: string; recoverable: boolean; status: "draft" | "pending_approval" | "approved" | "posted"; createdBy: string; approvedBy?: string }
export interface SubcontractOperation { id: string; organizationId: string; orderId: string; jobCardId: string; supplierId: string; purchaseOrderId?: string; quantitySentMills: bigint; acceptedMills: bigint; rejectedMills: bigint; expectedReturnDate: string; status: "planned" | "dispatched" | "partially_received" | "received" | "quality_hold"; currency: CurrencyCode; costMinor?: bigint }
export interface ProductionCost { orderId: string; currency: CurrencyCode; plannedMaterialMinor?: bigint; actualMaterialMinor?: bigint; plannedResourceMinor?: bigint; actualResourceMinor?: bigint; subcontractMinor?: bigint; reworkMinor?: bigint; totalPlannedMinor?: bigint; totalActualMinor?: bigint; varianceMinor?: bigint; costPerGoodUnitMinor?: bigint; unavailableReason?: string }
export interface ProductionEvent { id: string; organizationId: string; entityType: string; entityId: string; action: string; summary: string; createdBy: string; createdAt: string; links: Record<string, string> }
export interface ProductionData { users: ProductionUser[]; profiles: ProductionProfile[]; boms: Bom[]; routings: Routing[]; workCenters: WorkCenter[]; orders: ProductionOrder[]; jobCards: JobCard[]; mrpRuns: MrpRun[]; completions: Completion[]; downtimes: Downtime[]; scrap: ScrapRecord[]; subcontract: SubcontractOperation[]; timeline: ProductionEvent[]; notifications: ProductionEvent[]; idempotencyKeys: string[]; sequences: Record<string, number> }
