import type { LeaveLedgerEntry, PayrollReadinessLine, ShiftTemplate, TimeReconciliation } from "./types";
export function shiftDuration(shift:Pick<ShiftTemplate,"startMinute"|"endMinute"|"breakMinutes"|"crossesMidnight">){const gross=shift.endMinute>shift.startMinute?shift.endMinute-shift.startMinute:1440-shift.startMinute+shift.endMinute;return Math.max(0,gross-shift.breakMinutes);}
export function attendanceMetrics(shift:ShiftTemplate,firstIn?:string,lastOut?:string){if(!firstIn||!lastOut)return {workedMinutes:0,lateMinutes:0,earlyLeaveMinutes:0,missingMinutes:shiftDuration(shift)};const start=new Date(firstIn),end=new Date(lastOut);const worked=Math.max(0,Math.floor((end.getTime()-start.getTime())/60000)-shift.breakMinutes);const localStart=start.getUTCHours()*60+start.getUTCMinutes(),localEnd=end.getUTCHours()*60+end.getUTCMinutes();const late=Math.max(0,localStart-shift.startMinute-shift.graceMinutes);const expectedEnd=shift.endMinute+(shift.crossesMidnight?1440:0),actualEnd=localEnd+(shift.crossesMidnight&&localEnd<shift.startMinute?1440:0);const early=Math.max(0,expectedEnd-actualEnd-shift.graceMinutes);return {workedMinutes:worked,lateMinutes:late,earlyLeaveMinutes:early,missingMinutes:Math.max(0,shiftDuration(shift)-worked)};}
export function leaveBalance(entries:LeaveLedgerEntry[],workerId:string,typeId:string){return entries.filter(x=>x.workerId===workerId&&x.leaveTypeId===typeId&&x.status==="posted").reduce((sum,x)=>sum+x.unitsMills,0n);}
export function reconcileTime(input:{workerId:string;periodStart:string;periodEnd:string;attendanceMinutes:number;timesheetMinutes:number;jobCardMinutes:number;jobCardsLinkedToProjectMinutes?:number;leaveMinutes:number;overtimeMinutes:number;missingData?:string[];projectIds?:string[]}):TimeReconciliation{const productive=input.timesheetMinutes+input.jobCardMinutes-(input.jobCardsLinkedToProjectMinutes??0),available=input.attendanceMinutes+input.leaveMinutes+input.overtimeMinutes,diff=available-productive;return{id:`rec-${input.workerId}-${input.periodStart}`,organizationId:"",workerId:input.workerId,periodStart:input.periodStart,periodEnd:input.periodEnd,attendanceMinutes:input.attendanceMinutes,timesheetMinutes:input.timesheetMinutes,jobCardMinutes:input.jobCardMinutes,approvedLeaveMinutes:input.leaveMinutes,approvedOvertimeMinutes:input.overtimeMinutes,unallocatedMinutes:Math.max(0,diff),overAllocatedMinutes:Math.max(0,-diff),missingData:input.missingData??[],status:diff===0&&!(input.missingData?.length)?"matched":"unreconciled",projectIds:input.projectIds??[],updatedAt:new Date().toISOString()};}
export function readinessBlockers(lines:PayrollReadinessLine[]){return lines.reduce((sum,line)=>sum+line.unresolvedExceptions+(line.reconciliationStatus==="unreconciled"?1:0)+line.missingPunches,0);}
export function headcountAt<T extends {status:string;joinDate:string;lastWorkingDate?:string}>(workers:T[],date:string){return workers.filter(x=>x.joinDate<=date&&(!x.lastWorkingDate||x.lastWorkingDate>=date)&&!["draft","archived"].includes(x.status)).length;}
export function certificationStatus(expiryDate:string,today:string,windowDays=30){const days=Math.ceil((new Date(expiryDate).getTime()-new Date(today).getTime())/86400000);return days<0?"expired":days<=windowDays?"expiring":"valid";}
export function safeCsvCell(value:string|number|bigint){const valueText=String(value).replaceAll('"','""');return `"${/^[=+\-@\t\r]/.test(valueText)?"'"+valueText:valueText}"`;}
