import { attendanceMetrics, leaveBalance, readinessBlockers, reconcileTime, safeCsvCell, shiftDuration } from "./calculations";
import { createWorkerSchema, periodSchema, punchSchema } from "./schemas";
import { createHrSeed } from "./seed";
import type { AttendanceCorrection, HrData, LeaveLedgerEntry, LeaveRequest, OvertimeRecord, PayrollReadinessBatch, PunchEvent, TimeReconciliation, Worker } from "./types";

export class HrError extends Error{constructor(public code:"FORBIDDEN"|"NOT_FOUND"|"CROSS_TENANT"|"INVALID"|"CONFLICT"|"DUPLICATE",message:string){super(message);}}
const now=()=>new Date().toISOString(),clean=(value:string)=>value.replace(/[<>]/g,"").trim();
export interface HrRepository{
 snapshot(org:string,actorId:string):HrData;
 createWorker(input:unknown):Worker;
 linkUser(org:string,actorId:string,workerId:string,userId:string,version:number):Worker;
 changeManager(org:string,actorId:string,workerId:string,managerId:string|undefined,effectiveDate:string,reason:string,version:number):Worker;
 terminateWorker(org:string,actorId:string,workerId:string,effectiveDate:string,reason:string,version:number):Worker;
 recordPunch(input:unknown):PunchEvent;
 submitCorrection(input:{organizationId:string;actorId:string;attendanceId:string;requestedFirstIn?:string;requestedLastOut?:string;reason:string;idempotencyKey:string}):AttendanceCorrection;
 approveCorrection(org:string,actorId:string,id:string):AttendanceCorrection;
 requestLeave(input:{organizationId:string;actorId:string;workerId:string;leaveTypeId:string;start:string;end:string;unitsMills:bigint;reason:string;handoverNotes:string;idempotencyKey:string}):LeaveRequest;
 approveLeave(org:string,actorId:string,id:string,stage:"manager"|"hr",version:number):LeaveRequest;
 adjustLeave(input:{organizationId:string;actorId:string;workerId:string;leaveTypeId:string;unitsMills:bigint;reason:string;approvedBy:string;idempotencyKey:string}):LeaveLedgerEntry;
 reverseLeave(org:string,actorId:string,entryId:string,idempotencyKey:string):LeaveLedgerEntry;
 createOvertime(input:{organizationId:string;actorId:string;workerId:string;date:string;start:string;end:string;minutes:number;reason:string;projectId?:string;productionOrderId?:string;workCenterId?:string;idempotencyKey:string}):OvertimeRecord;
 approveOvertime(org:string,actorId:string,id:string,attendanceReconciled:boolean,version:number):OvertimeRecord;
 reconcile(input:{organizationId:string;actorId:string;workerId:string;periodStart:string;periodEnd:string;attendanceMinutes:number;timesheetMinutes:number;jobCardMinutes:number;linkedJobCardMinutes?:number;leaveMinutes:number;overtimeMinutes:number;missingData?:string[];projectIds?:string[]}):TimeReconciliation;
 preparePayroll(input:unknown):PayrollReadinessBatch;
 freezePayroll(org:string,actorId:string,id:string,version:number,overrideReason?:string):PayrollReadinessBatch;
 reopenPayroll(org:string,actorId:string,id:string,version:number,reason:string):PayrollReadinessBatch;
 exportPayrollCsv(org:string,actorId:string,id:string):string;
}
export class LocalHrRepository implements HrRepository{
 private data:HrData;constructor(seed=createHrSeed()){this.data=structuredClone(seed);}
 private owned<T extends {id:string;organizationId:string}>(rows:T[],org:string,id:string){const row=rows.find(x=>x.id===id);if(!row)throw new HrError("NOT_FOUND","HR record not found");if(row.organizationId!==org)throw new HrError("CROSS_TENANT","Cross-organization HR access denied");return row;}
 private user(org:string,id:string,permission?:string){const row=this.owned(this.data.users,org,id);if(permission&&!row.permissions.includes(permission))throw new HrError("FORBIDDEN",`Missing permission: ${permission}`);return row;}
 private once(key:string){if(!key.trim())throw new HrError("INVALID","Idempotency key required");if(this.data.idempotencyKeys.includes(key))throw new HrError("DUPLICATE","Duplicate idempotency key");this.data.idempotencyKeys.push(key);}
 private version(actual:number,expected:number){if(actual!==expected)throw new HrError("CONFLICT","Record changed by another user");}
 private next(org:string,type:string,prefix:string){const key=`${org}:${type}`,value=(this.data.sequences[key]??0)+1;this.data.sequences[key]=value;return `${prefix}-${new Date().getUTCFullYear()}-${String(value).padStart(5,"0")}`;}
 private trace(org:string,actor:string,entityType:string,entityId:string,action:string,summary:string,before?:Record<string,unknown>,after?:Record<string,unknown>){const event={id:`hre-${crypto.randomUUID()}`,organizationId:org,entityType,entityId,action,summary:clean(summary),createdBy:actor,createdAt:now(),before,after};this.data.timeline.push(event);this.data.notifications.push({...event,id:`hrn-${crypto.randomUUID()}`});}
 snapshot(org:string,actorId:string){const actor=this.user(org,actorId,"hr.view"),copy=structuredClone(this.data);for(const key of Object.keys(copy) as Array<keyof HrData>){const value=copy[key];if(Array.isArray(value))(copy[key] as unknown[])=value.filter(row=>typeof row==="object"&&row!==null&&"organizationId" in row?(row as {organizationId:string}).organizationId===org:true);}if(!actor.permissions.includes("hr.view_sensitive"))copy.workers=copy.workers.map(x=>({...x,nationalIdMasked:undefined,emergencyContactMasked:undefined,workMobile:x.workMobile?"***":undefined}));if(!actor.permissions.includes("performance.view_sensitive"))copy.performance=[];if(!actor.permissions.includes("payroll_readiness.view"))copy.payrollBatches=[];return copy;}
 createWorker(raw:unknown){const input=createWorkerSchema.parse(raw),actor=this.user(input.organizationId,input.actorId,"hr.manage_workers");this.once(input.idempotencyKey);if(this.data.workers.some(x=>x.organizationId===input.organizationId&&x.employeeNumber.toLowerCase()===input.employeeNumber.toLowerCase()&&x.status!=="archived"))throw new HrError("DUPLICATE","Employee number already exists");this.owned(this.data.departments,input.organizationId,input.departmentId);this.owned(this.data.positions,input.organizationId,input.positionId);this.owned(this.data.locations,input.organizationId,input.locationId);this.owned(this.data.calendars,input.organizationId,input.calendarId);this.owned(this.data.shifts,input.organizationId,input.defaultShiftId);if(input.managerId)this.owned(this.data.workers,input.organizationId,input.managerId);if(input.userId){this.user(input.organizationId,input.userId);if(this.data.workers.some(x=>x.organizationId===input.organizationId&&x.userId===input.userId))throw new HrError("DUPLICATE","User is already linked to a worker");}const row:Worker={id:`worker-${crypto.randomUUID()}`,organizationId:input.organizationId,employeeNumber:input.employeeNumber,nameAr:clean(input.nameAr),nameEn:clean(input.nameEn),displayName:clean(input.nameAr),workerType:input.workerType,status:"draft",joinDate:new Date().toISOString().slice(0,10),serviceStartDate:new Date().toISOString().slice(0,10),departmentId:input.departmentId,positionId:input.positionId,managerId:input.managerId,locationId:input.locationId,workMode:"on_site",calendarId:input.calendarId,defaultShiftId:input.defaultShiftId,projectEligible:true,workCenterEligible:true,userId:input.userId,membershipId:input.userId?this.user(input.organizationId,input.userId).membershipId:undefined,recordVersion:1,createdBy:actor.id,createdAt:now()};this.data.workers.push(row);this.trace(input.organizationId,actor.id,"worker",row.id,"worker.created",row.employeeNumber);return structuredClone(row);}
 linkUser(org:string,actorId:string,workerId:string,userId:string,version:number){const actor=this.user(org,actorId,"hr.link_user"),worker=this.owned(this.data.workers,org,workerId),user=this.user(org,userId);this.version(worker.recordVersion,version);if(worker.createdBy===actor.id)throw new HrError("FORBIDDEN","Maker cannot approve own sensitive worker link");if(this.data.workers.some(x=>x.organizationId===org&&x.id!==worker.id&&x.userId===user.id))throw new HrError("DUPLICATE","User is already linked");const before={userId:worker.userId??""};worker.userId=user.id;worker.membershipId=user.membershipId;worker.recordVersion++;this.trace(org,actor.id,"worker",worker.id,"worker.user_linked",worker.employeeNumber,before,{userId:user.id});return structuredClone(worker);}
 private managerCycle(workerId:string,managerId:string){let cursor:string|undefined=managerId;const seen=new Set<string>([workerId]);while(cursor){if(seen.has(cursor))return true;seen.add(cursor);cursor=this.data.workers.find(x=>x.id===cursor)?.managerId;}return false;}
 changeManager(org:string,actorId:string,workerId:string,managerId:string|undefined,effectiveDate:string,reason:string,version:number){const actor=this.user(org,actorId,"hr.manage_structure"),worker=this.owned(this.data.workers,org,workerId);this.version(worker.recordVersion,version);if(managerId){this.owned(this.data.workers,org,managerId);if(managerId===workerId||this.managerCycle(workerId,managerId))throw new HrError("INVALID","Reporting line cycle detected");}const before={managerId:worker.managerId??""};worker.managerId=managerId;worker.recordVersion++;this.data.employmentEvents.push({id:`hee-${crypto.randomUUID()}`,organizationId:org,workerId,type:"manager_change",effectiveDate,reason:clean(reason),before,after:{managerId:managerId??""},createdBy:actor.id,approvedBy:actor.id});this.trace(org,actor.id,"worker",worker.id,"worker.manager_changed",reason,before,{managerId:managerId??""});return structuredClone(worker);}
 terminateWorker(org:string,actorId:string,workerId:string,effectiveDate:string,reason:string,version:number){const actor=this.user(org,actorId,"hr.manage_workers"),worker=this.owned(this.data.workers,org,workerId);this.version(worker.recordVersion,version);if(worker.createdBy===actor.id)throw new HrError("FORBIDDEN","Maker cannot approve worker termination");worker.status="terminated";worker.lastWorkingDate=effectiveDate;worker.recordVersion++;this.data.employmentEvents.push({id:`hee-${crypto.randomUUID()}`,organizationId:org,workerId,type:"termination",effectiveDate,reason:clean(reason),before:{status:"active"},after:{status:"terminated"},createdBy:worker.createdBy,approvedBy:actor.id});this.trace(org,actor.id,"worker",worker.id,"worker.terminated",reason);return structuredClone(worker);}
 recordPunch(raw:unknown){const input=punchSchema.parse(raw),actor=this.user(input.organizationId,input.actorId,"attendance.record"),worker=this.owned(this.data.workers,input.organizationId,input.workerId);this.once(input.idempotencyKey);if(worker.status!=="active")throw new HrError("INVALID","Active worker required");const same=this.data.punches.filter(x=>x.organizationId===input.organizationId&&x.workerId===worker.id);if(same.some(x=>x.type===input.type&&Math.abs(new Date(x.occurredAt).getTime()-new Date(input.occurredAt).getTime())<60000))throw new HrError("DUPLICATE","Overlapping punch detected");const punch:PunchEvent={id:`punch-${crypto.randomUUID()}`,organizationId:input.organizationId,workerId:worker.id,occurredAt:input.occurredAt,type:input.type,source:input.source,idempotencyKey:input.idempotencyKey,createdBy:actor.id};this.data.punches.push(punch);const workDate=input.occurredAt.slice(0,10),shift=this.owned(this.data.shifts,input.organizationId,worker.defaultShiftId);let attendance=this.data.attendance.find(x=>x.organizationId===input.organizationId&&x.workerId===worker.id&&x.workDate===workDate);if(!attendance){attendance={id:`att-${crypto.randomUUID()}`,organizationId:input.organizationId,workerId:worker.id,shiftId:shift.id,workDate,workedMinutes:0,lateMinutes:0,earlyLeaveMinutes:0,missingMinutes:shiftDuration(shift),status:"missing_punch",source:input.source,idempotencyKey:`attendance:${worker.id}:${workDate}`,recordVersion:1};this.data.attendance.push(attendance);}if(input.type==="in")attendance.firstIn=input.occurredAt;if(input.type==="out")attendance.lastOut=input.occurredAt;const metric=attendanceMetrics(shift,attendance.firstIn,attendance.lastOut);Object.assign(attendance,metric,{status:attendance.firstIn&&attendance.lastOut?(metric.lateMinutes>0?"late":"present"):"missing_punch",recordVersion:attendance.recordVersion+1});this.trace(input.organizationId,actor.id,"attendance",attendance.id,"attendance.punch_recorded",input.type);return structuredClone(punch);}
 submitCorrection(input:Parameters<HrRepository["submitCorrection"]>[0]){const actor=this.user(input.organizationId,input.actorId,"attendance.request_correction"),attendance=this.owned(this.data.attendance,input.organizationId,input.attendanceId);this.once(input.idempotencyKey);if(this.data.corrections.some(x=>x.attendanceId===attendance.id&&x.status==="submitted"))throw new HrError("DUPLICATE","Pending correction already exists");const row:AttendanceCorrection={id:`cor-${crypto.randomUUID()}`,organizationId:input.organizationId,attendanceId:attendance.id,requestedFirstIn:input.requestedFirstIn,requestedLastOut:input.requestedLastOut,reason:clean(input.reason),requestedBy:actor.id,status:"submitted",before:{firstIn:attendance.firstIn,lastOut:attendance.lastOut,workedMinutes:attendance.workedMinutes},createdAt:now()};this.data.corrections.push(row);attendance.status="pending_correction";attendance.recordVersion++;this.trace(input.organizationId,actor.id,"attendance_correction",row.id,"correction.submitted",row.reason,row.before);return structuredClone(row);}
 approveCorrection(org:string,actorId:string,id:string){const actor=this.user(org,actorId,"attendance.approve_correction"),row=this.owned(this.data.corrections,org,id);if(row.status!=="submitted")throw new HrError("INVALID","Submitted correction required");if(row.requestedBy===actor.id)throw new HrError("FORBIDDEN","Maker cannot approve own correction");const attendance=this.owned(this.data.attendance,org,row.attendanceId),shift=this.owned(this.data.shifts,org,attendance.shiftId);attendance.firstIn=row.requestedFirstIn??attendance.firstIn;attendance.lastOut=row.requestedLastOut??attendance.lastOut;Object.assign(attendance,attendanceMetrics(shift,attendance.firstIn,attendance.lastOut),{status:"corrected",correctionId:row.id,recordVersion:attendance.recordVersion+1});row.status="approved";row.approvedBy=actor.id;row.after={firstIn:attendance.firstIn,lastOut:attendance.lastOut,workedMinutes:attendance.workedMinutes};this.trace(org,actor.id,"attendance_correction",row.id,"correction.approved",row.reason,row.before,row.after);return structuredClone(row);}
 requestLeave(input:Parameters<HrRepository["requestLeave"]>[0]){const actor=this.user(input.organizationId,input.actorId,"leave.request"),worker=this.owned(this.data.workers,input.organizationId,input.workerId),type=this.owned(this.data.leaveTypes,input.organizationId,input.leaveTypeId);this.once(input.idempotencyKey);if(input.unitsMills<=0n||input.end<input.start)throw new HrError("INVALID","Valid leave dates and units required");const balance=leaveBalance(this.data.leaveLedger,worker.id,type.id);if(type.requiresBalance&&!type.allowNegative&&balance<input.unitsMills)throw new HrError("INVALID","Insufficient leave balance");const row:LeaveRequest={id:`leave-${crypto.randomUUID()}`,organizationId:input.organizationId,workerId:worker.id,leaveTypeId:type.id,start:input.start,end:input.end,requestedUnitsMills:input.unitsMills,reason:clean(input.reason),handoverNotes:clean(input.handoverNotes),balanceSnapshotMills:balance,status:"pending_manager",createdBy:actor.id,recordVersion:1};this.data.leaveRequests.push(row);this.trace(input.organizationId,actor.id,"leave_request",row.id,"leave.submitted",row.reason);return structuredClone(row);}
 approveLeave(org:string,actorId:string,id:string,stage:"manager"|"hr",version:number){const permission=stage==="manager"?"leave.approve_manager":"leave.approve_hr",actor=this.user(org,actorId,permission),row=this.owned(this.data.leaveRequests,org,id);this.version(row.recordVersion,version);if(row.createdBy===actor.id)throw new HrError("FORBIDDEN","Maker cannot approve own leave");if(stage==="manager"){if(row.status!=="pending_manager")throw new HrError("INVALID","Manager approval is not pending");row.status="pending_hr";}else{if(row.status!=="pending_hr")throw new HrError("INVALID","HR approval is not pending");const type=this.owned(this.data.leaveTypes,org,row.leaveTypeId),balance=leaveBalance(this.data.leaveLedger,row.workerId,type.id);if(type.requiresBalance&&!type.allowNegative&&balance<row.requestedUnitsMills)throw new HrError("INVALID","Leave balance changed and is insufficient");const key=`leave-consumption:${row.id}`;if(this.data.leaveLedger.some(x=>x.idempotencyKey===key))throw new HrError("DUPLICATE","Leave already consumed");this.data.leaveLedger.push({id:`lle-${crypto.randomUUID()}`,organizationId:org,workerId:row.workerId,leaveTypeId:type.id,type:"consumption",unitsMills:-row.requestedUnitsMills,sourceId:row.id,status:"posted",createdBy:row.createdBy,approvedBy:actor.id,occurredAt:now(),idempotencyKey:key});row.status="approved";row.approvedBy=actor.id;}row.recordVersion++;this.trace(org,actor.id,"leave_request",row.id,`leave.${stage}_approved`,row.reason);return structuredClone(row);}
 adjustLeave(input:Parameters<HrRepository["adjustLeave"]>[0]){const maker=this.user(input.organizationId,input.actorId,"leave.adjust_balance"),checker=this.user(input.organizationId,input.approvedBy,"leave.adjust_balance");if(maker.id===checker.id)throw new HrError("FORBIDDEN","Maker cannot approve own leave adjustment");this.owned(this.data.workers,input.organizationId,input.workerId);this.owned(this.data.leaveTypes,input.organizationId,input.leaveTypeId);this.once(input.idempotencyKey);if(input.unitsMills===0n||!input.reason.trim())throw new HrError("INVALID","Non-zero adjustment and reason required");const row:LeaveLedgerEntry={id:`lle-${crypto.randomUUID()}`,organizationId:input.organizationId,workerId:input.workerId,leaveTypeId:input.leaveTypeId,type:"adjustment",unitsMills:input.unitsMills,sourceId:`adjustment:${crypto.randomUUID()}`,status:"posted",createdBy:maker.id,approvedBy:checker.id,occurredAt:now(),idempotencyKey:input.idempotencyKey};this.data.leaveLedger.push(row);this.trace(input.organizationId,checker.id,"leave_ledger",row.id,"leave.adjusted",input.reason);return structuredClone(row);}
 reverseLeave(org:string,actorId:string,entryId:string,idempotencyKey:string){const actor=this.user(org,actorId,"leave.adjust_balance"),source=this.owned(this.data.leaveLedger,org,entryId);this.once(idempotencyKey);if(this.data.leaveLedger.some(x=>x.reversalOfId===source.id))throw new HrError("DUPLICATE","Leave entry already reversed");if(source.createdBy===actor.id)throw new HrError("FORBIDDEN","Maker cannot reverse own entry");const row:LeaveLedgerEntry={id:`lle-${crypto.randomUUID()}`,organizationId:org,workerId:source.workerId,leaveTypeId:source.leaveTypeId,type:"reversal",unitsMills:-source.unitsMills,sourceId:source.id,reversalOfId:source.id,status:"posted",createdBy:actor.id,approvedBy:actor.id,occurredAt:now(),idempotencyKey};this.data.leaveLedger.push(row);this.trace(org,actor.id,"leave_ledger",row.id,"leave.reversed",source.id);return structuredClone(row);}
 createOvertime(input:Parameters<HrRepository["createOvertime"]>[0]){const actor=this.user(input.organizationId,input.actorId,"overtime.request"),worker=this.owned(this.data.workers,input.organizationId,input.workerId);this.once(input.idempotencyKey);if(input.minutes<=0||new Date(input.end)<=new Date(input.start))throw new HrError("INVALID","Valid overtime interval required");if(this.data.overtime.some(x=>x.organizationId===input.organizationId&&x.workerId===worker.id&&x.status!=="rejected"&&new Date(input.start)<new Date(x.end)&&new Date(input.end)>new Date(x.start)))throw new HrError("INVALID","Overlapping overtime is prohibited");const row:OvertimeRecord={id:`ot-${crypto.randomUUID()}`,organizationId:input.organizationId,workerId:worker.id,date:input.date,start:input.start,end:input.end,minutes:input.minutes,reason:clean(input.reason),projectId:input.projectId,productionOrderId:input.productionOrderId,workCenterId:input.workCenterId,attendanceReconciled:false,status:"submitted",createdBy:actor.id,recordVersion:1};this.data.overtime.push(row);this.trace(input.organizationId,actor.id,"overtime",row.id,"overtime.submitted",row.reason);return structuredClone(row);}
 approveOvertime(org:string,actorId:string,id:string,attendanceReconciled:boolean,version:number){const actor=this.user(org,actorId,"overtime.approve"),row=this.owned(this.data.overtime,org,id);this.version(row.recordVersion,version);if(row.createdBy===actor.id)throw new HrError("FORBIDDEN","Maker cannot approve own overtime");if(row.status!=="submitted"||!attendanceReconciled)throw new HrError("INVALID","Reconciled submitted overtime required");row.status="approved";row.attendanceReconciled=true;row.approvedBy=actor.id;row.recordVersion++;this.trace(org,actor.id,"overtime",row.id,"overtime.approved",row.reason);return structuredClone(row);}
 reconcile(input:Parameters<HrRepository["reconcile"]>[0]){const actor=this.user(input.organizationId,input.actorId,"workforce.reconcile_time");this.owned(this.data.workers,input.organizationId,input.workerId);const result=reconcileTime({...input,jobCardsLinkedToProjectMinutes:input.linkedJobCardMinutes});result.organizationId=input.organizationId;const existing=this.data.reconciliations.findIndex(x=>x.organizationId===input.organizationId&&x.workerId===input.workerId&&x.periodStart===input.periodStart&&x.periodEnd===input.periodEnd);if(existing>=0)this.data.reconciliations[existing]=result;else this.data.reconciliations.push(result);this.trace(input.organizationId,actor.id,"time_reconciliation",result.id,"time.reconciled",result.status);return structuredClone(result);}
 preparePayroll(raw:unknown){const input=periodSchema.parse(raw),actor=this.user(input.organizationId,input.actorId,"payroll_readiness.prepare");this.once(input.idempotencyKey);const workers=this.data.workers.filter(x=>x.organizationId===input.organizationId&&x.status==="active");const lines=workers.map(worker=>{const attendance=this.data.attendance.filter(x=>x.organizationId===input.organizationId&&x.workerId===worker.id&&x.workDate>=input.periodStart&&x.workDate<=input.periodEnd),reconciliation=this.data.reconciliations.find(x=>x.organizationId===input.organizationId&&x.workerId===worker.id&&x.periodStart===input.periodStart&&x.periodEnd===input.periodEnd),overtime=this.data.overtime.filter(x=>x.organizationId===input.organizationId&&x.workerId===worker.id&&x.status==="approved"&&x.date>=input.periodStart&&x.date<=input.periodEnd),leave=this.data.leaveRequests.filter(x=>x.organizationId===input.organizationId&&x.workerId===worker.id&&x.status==="approved"&&x.start<=input.periodEnd&&x.end>=input.periodStart);return{workerId:worker.id,scheduledMinutes:attendance.length*shiftDuration(this.owned(this.data.shifts,input.organizationId,worker.defaultShiftId)),attendanceMinutes:attendance.reduce((s,x)=>s+x.workedMinutes,0),approvedRegularMinutes:attendance.reduce((s,x)=>s+x.workedMinutes,0),overtimeMinutes:overtime.reduce((s,x)=>s+x.minutes,0),paidLeaveMills:leave.filter(x=>this.owned(this.data.leaveTypes,input.organizationId,x.leaveTypeId).paid).reduce((s,x)=>s+x.requestedUnitsMills,0n),unpaidLeaveMills:leave.filter(x=>!this.owned(this.data.leaveTypes,input.organizationId,x.leaveTypeId).paid).reduce((s,x)=>s+x.requestedUnitsMills,0n),absenceMinutes:attendance.filter(x=>x.status==="absent").reduce((s,x)=>s+x.missingMinutes,0),lateMinutes:attendance.reduce((s,x)=>s+x.lateMinutes,0),earlyMinutes:attendance.reduce((s,x)=>s+x.earlyLeaveMinutes,0),missingPunches:attendance.filter(x=>x.status==="missing_punch"||x.status==="pending_correction").length,manualAdjustmentMinutes:0,unresolvedExceptions:reconciliation?.missingData.length??1,reconciliationStatus:reconciliation?.status??"unreconciled",sourceIds:[...attendance.map(x=>x.id),...overtime.map(x=>x.id),...leave.map(x=>x.id),...(reconciliation?[reconciliation.id]:[])]};});const blockers=readinessBlockers(lines),row:PayrollReadinessBatch={id:`prb-${crypto.randomUUID()}`,organizationId:input.organizationId,number:this.next(input.organizationId,"payroll_readiness","PRB"),periodStart:input.periodStart,periodEnd:input.periodEnd,timezone:input.timezone,status:blockers?"exceptions_pending":"ready",lines,snapshotVersion:1,drift:false,recordVersion:1,createdBy:actor.id};this.data.payrollBatches.push(row);this.trace(input.organizationId,actor.id,"payroll_readiness",row.id,"payroll_readiness.prepared",`${row.number}; blockers=${blockers}`);return structuredClone(row);}
 freezePayroll(org:string,actorId:string,id:string,version:number,overrideReason?:string){const actor=this.user(org,actorId,"payroll_readiness.freeze"),row=this.owned(this.data.payrollBatches,org,id);this.version(row.recordVersion,version);if(row.createdBy===actor.id)throw new HrError("FORBIDDEN","Maker cannot freeze own readiness batch");const blockers=readinessBlockers(row.lines);if(blockers&&!overrideReason?.trim())throw new HrError("INVALID","Blocking exceptions require an audited override reason");if(!["ready","exceptions_pending","under_review"].includes(row.status))throw new HrError("INVALID","Reviewable batch required");row.status="frozen";row.frozenBy=actor.id;row.overrideReason=overrideReason&&clean(overrideReason);row.snapshotHash=`hr-${row.snapshotVersion}-${row.lines.map(x=>`${x.workerId}:${x.attendanceMinutes}:${x.overtimeMinutes}:${x.sourceIds.join(".")}`).join("|")}`;row.recordVersion++;this.trace(org,actor.id,"payroll_readiness",row.id,"payroll_readiness.frozen",row.overrideReason??"rules passed");return structuredClone(row);}
 reopenPayroll(org:string,actorId:string,id:string,version:number,reason:string){const actor=this.user(org,actorId,"payroll_readiness.reopen"),row=this.owned(this.data.payrollBatches,org,id);this.version(row.recordVersion,version);if(row.status!=="frozen"||row.frozenBy===actor.id||!reason.trim())throw new HrError("FORBIDDEN","Independent approved reopen with reason required");row.status="reopened";row.snapshotVersion++;row.drift=true;row.recordVersion++;this.trace(org,actor.id,"payroll_readiness",row.id,"payroll_readiness.reopened",reason);return structuredClone(row);}
 exportPayrollCsv(org:string,actorId:string,id:string){this.user(org,actorId,"payroll_readiness.export");const row=this.owned(this.data.payrollBatches,org,id);if(row.status!=="frozen"&&!row.exportedAt)throw new HrError("INVALID","Frozen readiness snapshot required");row.status="exported";row.exportedAt=now();const header=["worker_id","scheduled_minutes","attendance_minutes","overtime_minutes","paid_leave_units_mills","unpaid_leave_units_mills","exceptions","status"];return `\uFEFF${header.map(safeCsvCell).join(",")}\n${row.lines.map(x=>[x.workerId,x.scheduledMinutes,x.attendanceMinutes,x.overtimeMinutes,x.paidLeaveMills,x.unpaidLeaveMills,x.unresolvedExceptions,x.reconciliationStatus].map(safeCsvCell).join(",")).join("\n")}`;}
}
export class SupabaseHrRepository implements HrRepository{private unavailable():never{throw new HrError("INVALID","Supabase HR adapter is a contract stub: Migration 012 is not applied or integration-tested");}snapshot():HrData{return this.unavailable();}createWorker():Worker{return this.unavailable();}linkUser():Worker{return this.unavailable();}changeManager():Worker{return this.unavailable();}terminateWorker():Worker{return this.unavailable();}recordPunch():PunchEvent{return this.unavailable();}submitCorrection():AttendanceCorrection{return this.unavailable();}approveCorrection():AttendanceCorrection{return this.unavailable();}requestLeave():LeaveRequest{return this.unavailable();}approveLeave():LeaveRequest{return this.unavailable();}adjustLeave():LeaveLedgerEntry{return this.unavailable();}reverseLeave():LeaveLedgerEntry{return this.unavailable();}createOvertime():OvertimeRecord{return this.unavailable();}approveOvertime():OvertimeRecord{return this.unavailable();}reconcile():TimeReconciliation{return this.unavailable();}preparePayroll():PayrollReadinessBatch{return this.unavailable();}freezePayroll():PayrollReadinessBatch{return this.unavailable();}reopenPayroll():PayrollReadinessBatch{return this.unavailable();}exportPayrollCsv():string{return this.unavailable();}}
let singleton:LocalHrRepository|undefined;
export function resetHrDemoRepository(){singleton=new LocalHrRepository();return singleton;}
export function getHrDemoRepository(){return singleton??=new LocalHrRepository();}
