export type WorkerType = "employee" | "contractor" | "temporary" | "intern" | "consultant" | "daily_labor";
export type WorkerStatus = "draft" | "active" | "on_leave" | "suspended" | "notice_period" | "terminated" | "archived";
export type AttendanceStatus = "expected" | "present" | "late" | "partial" | "absent" | "approved_leave" | "holiday" | "rest_day" | "missing_punch" | "pending_correction" | "corrected";
export type ApprovalStatus = "draft" | "submitted" | "pending_manager" | "pending_hr" | "approved" | "rejected" | "cancelled" | "completed" | "adjusted";
export type PayrollReadinessStatus = "open" | "collecting" | "under_review" | "exceptions_pending" | "ready" | "frozen" | "exported" | "reopened" | "superseded";
export interface HrUser { id:string; organizationId:string; name:string; membershipId?:string; role:string; permissions:string[] }
export interface Department { id:string; organizationId:string; code:string; name:string; nameEn:string; parentId?:string; active:boolean }
export interface Position { id:string; organizationId:string; code:string; name:string; nameEn:string; departmentId:string; capacity?:number; active:boolean }
export interface WorkLocation { id:string; organizationId:string; code:string; name:string; timezone:string; active:boolean }
export interface WorkCalendar { id:string; organizationId:string; name:string; timezone:string; workingDays:number[]; holidays:string[] }
export interface ShiftTemplate { id:string; organizationId:string; name:string; startMinute:number; endMinute:number; breakMinutes:number; graceMinutes:number; calendarId:string; crossesMidnight:boolean }
export interface Worker { id:string; organizationId:string; employeeNumber:string; userId?:string; membershipId?:string; nameAr:string; nameEn:string; displayName:string; workerType:WorkerType; status:WorkerStatus; joinDate:string; serviceStartDate:string; expectedEndDate?:string; lastWorkingDate?:string; departmentId:string; positionId:string; managerId?:string; locationId:string; workMode:"on_site"|"office"|"hybrid"|"remote"; calendarId:string; defaultShiftId:string; projectEligible:boolean; workCenterEligible:boolean; workEmail?:string; workMobile?:string; nationalIdMasked?:string; emergencyContactMasked?:string; recordVersion:number; createdBy:string; createdAt:string; archivedAt?:string }
export interface EmploymentEvent { id:string; organizationId:string; workerId:string; type:"hire"|"activate"|"department_transfer"|"position_change"|"manager_change"|"location_change"|"worker_type_change"|"renewal"|"suspension"|"return_to_work"|"termination"|"archive"; effectiveDate:string; reason:string; before:Record<string,string>; after:Record<string,string>; createdBy:string; approvedBy?:string }
export interface ShiftAssignment { id:string; organizationId:string; workerId:string; shiftId:string; effectiveFrom:string; effectiveTo?:string; locationId:string; recordVersion:number }
export interface PunchEvent { id:string; organizationId:string; workerId:string; occurredAt:string; type:"in"|"out"|"break_start"|"break_end"; source:"manual_authorized"|"web_demo"|"csv_preview"|"external_stub"; idempotencyKey:string; createdBy:string }
export interface AttendanceRecord { id:string; organizationId:string; workerId:string; shiftId:string; workDate:string; firstIn?:string; lastOut?:string; workedMinutes:number; lateMinutes:number; earlyLeaveMinutes:number; missingMinutes:number; status:AttendanceStatus; source:string; projectId?:string; workCenterId?:string; correctionId?:string; idempotencyKey:string; recordVersion:number }
export interface AttendanceCorrection { id:string; organizationId:string; attendanceId:string; requestedFirstIn?:string; requestedLastOut?:string; reason:string; requestedBy:string; status:"submitted"|"approved"|"rejected"; before:Record<string,string|number|undefined>; after?:Record<string,string|number|undefined>; approvedBy?:string; createdAt:string }
export interface LeaveType { id:string; organizationId:string; code:string; name:string; paid:boolean; unit:"days"|"hours"; requiresBalance:boolean; requiresAttachment:boolean; allowHalfDay:boolean; allowHourly:boolean; allowNegative:boolean; active:boolean }
export interface LeaveRequest { id:string; organizationId:string; workerId:string; leaveTypeId:string; start:string; end:string; requestedUnitsMills:bigint; reason:string; handoverNotes:string; projectId?:string; taskId?:string; balanceSnapshotMills:bigint; status:ApprovalStatus; createdBy:string; approvedBy?:string; recordVersion:number }
export interface LeaveLedgerEntry { id:string; organizationId:string; workerId:string; leaveTypeId:string; type:"opening"|"accrual"|"consumption"|"reversal"|"adjustment"|"carry_forward"|"expiry"; unitsMills:bigint; sourceId:string; reversalOfId?:string; status:"posted"; createdBy:string; approvedBy:string; occurredAt:string; idempotencyKey:string }
export interface OvertimeRecord { id:string; organizationId:string; workerId:string; date:string; start:string; end:string; minutes:number; reason:string; projectId?:string; wbsId?:string; taskId?:string; productionOrderId?:string; workCenterId?:string; attendanceReconciled:boolean; status:"submitted"|"approved"|"rejected"; createdBy:string; approvedBy?:string; recordVersion:number }
export interface TimeReconciliation { id:string; organizationId:string; workerId:string; periodStart:string; periodEnd:string; attendanceMinutes:number; timesheetMinutes:number; jobCardMinutes:number; approvedLeaveMinutes:number; approvedOvertimeMinutes:number; unallocatedMinutes:number; overAllocatedMinutes:number; missingData:string[]; status:"unreconciled"|"matched"|"approved_override"; projectIds:string[]; updatedAt:string }
export interface WorkforceAssignment { id:string; organizationId:string; workerId:string; projectId?:string; wbsId?:string; taskId?:string; workCenterId?:string; effectiveFrom:string; effectiveTo?:string; plannedMinutes:number; shiftId:string; locationId:string; requiredCertificationTypeIds:string[]; status:"planned"|"active"|"completed"|"blocked" }
export interface WorkerSkill { id:string; organizationId:string; workerId:string; skillId:string; level:number; verifiedAt?:string; verifiedBy?:string }
export interface WorkerCertification { id:string; organizationId:string; workerId:string; typeId:string; issueDate:string; expiryDate:string; status:"valid"|"expiring"|"expired"; verified:boolean; overrideBy?:string; overrideReason?:string }
export interface TrainingRecord { id:string; organizationId:string; workerId:string; course:string; sessionDate:string; result:"planned"|"attended"|"completed"|"failed" }
export interface Checklist { id:string; organizationId:string; workerId:string; kind:"onboarding"|"offboarding"; status:"open"|"completed"; tasks:Array<{id:string;title:string;ownerId:string;done:boolean;reference?:string}> }
export interface PerformanceReview { id:string; organizationId:string; workerId:string; reviewerId:string; period:string; rating:number; comments:string; acknowledged:boolean; status:"draft"|"submitted"|"final"|"revised"; revision:number }
export interface PayrollReadinessLine { workerId:string; scheduledMinutes:number; attendanceMinutes:number; approvedRegularMinutes:number; overtimeMinutes:number; paidLeaveMills:bigint; unpaidLeaveMills:bigint; absenceMinutes:number; lateMinutes:number; earlyMinutes:number; missingPunches:number; manualAdjustmentMinutes:number; adjustmentReason?:string; unresolvedExceptions:number; reconciliationStatus:string; sourceIds:string[] }
export interface PayrollReadinessBatch { id:string; organizationId:string; number:string; periodStart:string; periodEnd:string; timezone:string; status:PayrollReadinessStatus; lines:PayrollReadinessLine[]; snapshotHash?:string; snapshotVersion:number; frozenBy?:string; exportedAt?:string; drift:boolean; recordVersion:number; createdBy:string; overrideReason?:string }
export interface HrEvent { id:string; organizationId:string; entityType:string; entityId:string; action:string; summary:string; createdBy:string; createdAt:string; before?:Record<string,unknown>; after?:Record<string,unknown> }
export interface HrData { users:HrUser[]; departments:Department[]; positions:Position[]; locations:WorkLocation[]; calendars:WorkCalendar[]; shifts:ShiftTemplate[]; workers:Worker[]; employmentEvents:EmploymentEvent[]; shiftAssignments:ShiftAssignment[]; punches:PunchEvent[]; attendance:AttendanceRecord[]; corrections:AttendanceCorrection[]; leaveTypes:LeaveType[]; leaveRequests:LeaveRequest[]; leaveLedger:LeaveLedgerEntry[]; overtime:OvertimeRecord[]; reconciliations:TimeReconciliation[]; assignments:WorkforceAssignment[]; skills:WorkerSkill[]; certifications:WorkerCertification[]; training:TrainingRecord[]; checklists:Checklist[]; performance:PerformanceReview[]; payrollBatches:PayrollReadinessBatch[]; timeline:HrEvent[]; notifications:HrEvent[]; idempotencyKeys:string[]; sequences:Record<string,number> }
