import { calculatePaymentSchedule } from "./calculations";
import type {
  ContractRole,
  ContractSnapshot,
  ContractSnapshotData,
  ContractUser,
} from "./types";

export const CONTRACT_PERMISSIONS = [
  "contracts.view",
  "contracts.create",
  "contracts.update_draft",
  "contracts.submit_for_approval",
  "contracts.approve",
  "contracts.activate",
  "contracts.suspend",
  "contracts.terminate",
  "contracts.complete",
  "contracts.create_revision",
  "contracts.view_financials",
  "contracts.export",
  "change_orders.create",
  "change_orders.approve",
  "work_orders.view",
  "work_orders.create",
  "work_orders.assign",
  "work_orders.update",
  "work_orders.start",
  "work_orders.complete",
  "work_orders.approve_closure",
  "work_orders.reopen",
  "work_orders.export",
] as const;
const read = ["contracts.view", "work_orders.view"];
export const contractPermissionsByRole: Record<ContractRole, string[]> = {
  owner: [...CONTRACT_PERMISSIONS],
  admin: [...CONTRACT_PERMISSIONS],
  sales_manager: [
    ...read,
    "contracts.create",
    "contracts.update_draft",
    "contracts.submit_for_approval",
    "contracts.create_revision",
    "contracts.export",
    "change_orders.create",
    "work_orders.create",
  ],
  sales_agent: [
    ...read,
    "contracts.create",
    "contracts.update_draft",
    "contracts.submit_for_approval",
  ],
  customer_service: read,
  accountant: [...read, "contracts.view_financials", "contracts.export"],
  viewer: read,
  marketing: [],
};
const org = "org-madar-demo",
  other = "org-other-demo",
  now = "2026-08-07T09:00:00.000Z";
const users: ContractUser[] = [
  {
    id: "u-owner",
    organizationId: org,
    name: "عبدالعزيز الجندي",
    role: "owner",
    permissions: contractPermissionsByRole.owner,
  },
  {
    id: "u-admin",
    organizationId: org,
    name: "مدير النظام التجريبي",
    role: "admin",
    permissions: contractPermissionsByRole.admin,
  },
  {
    id: "u-sales",
    organizationId: org,
    name: "محمد علي",
    role: "sales_manager",
    permissions: contractPermissionsByRole.sales_manager,
  },
  {
    id: "u-agent",
    organizationId: org,
    name: "ريم خالد",
    role: "sales_agent",
    permissions: contractPermissionsByRole.sales_agent,
  },
  {
    id: "u-service",
    organizationId: org,
    name: "سارة أحمد",
    role: "customer_service",
    permissions: contractPermissionsByRole.customer_service,
  },
  {
    id: "u-accountant",
    organizationId: org,
    name: "أحمد فؤاد",
    role: "accountant",
    permissions: contractPermissionsByRole.accountant,
  },
  {
    id: "u-viewer",
    organizationId: org,
    name: "مشاهد تجريبي",
    role: "viewer",
    permissions: contractPermissionsByRole.viewer,
  },
  {
    id: "u-marketing",
    organizationId: org,
    name: "مسوق تجريبي",
    role: "marketing",
    permissions: contractPermissionsByRole.marketing,
  },
  {
    id: "u-other",
    organizationId: other,
    name: "مالك شركة أخرى",
    role: "owner",
    permissions: contractPermissionsByRole.owner,
  },
];
const source = {
  id: "qv-contract-source",
  organizationId: org,
  quotationId: "q-contract-source",
  salesRequestId: "sr-contract-source",
  quotationNumber: "QUO-2026-00002",
  versionNumber: 2,
  status: "accepted_demo" as const,
  requestStatus: "won" as const,
  customerId: "customer-demo-2",
  customerName: "شركة رؤية الفعاليات",
  customerEmail: "contracts@example.test",
  customerMobile: "+966500000002",
  currency: "SAR" as const,
  title: "تصميم وتنفيذ جناح معرض",
  valueMinor: 12000000n,
  acceptedOptionalItemIds: ["ql-optional"],
  lineItems: [
    {
      id: "ql-main",
      description: "تصميم وتنفيذ جناح بمساحة 60 م²",
      quantityMills: 60000n,
      unit: "م²",
      unitPriceMinor: 180000n,
      optional: false,
      selected: true,
    },
    {
      id: "ql-optional",
      description: "شاشة عرض إضافية",
      quantityMills: 1000n,
      unit: "قطعة",
      unitPriceMinor: 1200000n,
      optional: true,
      selected: true,
    },
  ],
  scope: "التصميم، المخططات التنفيذية، التصنيع، التركيب، والتسليم.",
  terms: "العقد تجريبي ويتطلب مراجعة قانونية قبل الاستخدام.",
  paymentTerms: "40% مقدم، 40% عند اكتمال التصنيع، 20% عند التسليم.",
  duration: "45 يومًا",
};
function snapshot(): ContractSnapshot {
  const milestones = [
    {
      id: "mil-1",
      title: "البدء",
      dueDate: "2026-08-15",
      status: "completed" as const,
    },
    {
      id: "mil-2",
      title: "اكتمال التصنيع",
      dueDate: "2026-09-05",
      status: "pending" as const,
    },
    {
      id: "mil-3",
      title: "التسليم",
      dueDate: "2026-09-20",
      status: "pending" as const,
    },
  ];
  return {
    quotationVersionId: source.id,
    quotationNumber: source.quotationNumber,
    salesRequestId: source.salesRequestId,
    customerId: source.customerId,
    customerName: source.customerName,
    customerEmail: source.customerEmail,
    customerMobile: source.customerMobile,
    acceptedOptionalItemIds: source.acceptedOptionalItemIds,
    title: source.title,
    scope: source.scope,
    terms: source.terms,
    duration: source.duration,
    currency: source.currency,
    valueMinor: source.valueMinor,
    lineItems: source.lineItems,
    sections: [
      {
        id: "sec-1",
        titleAr: "نطاق العمل",
        titleEn: "Scope of Work",
        bodyAr: source.scope,
        bodyEn:
          "Design, shop drawings, fabrication, installation and handover.",
        sortOrder: 1,
      },
      {
        id: "sec-2",
        titleAr: "الشروط",
        titleEn: "Terms",
        bodyAr: source.terms,
        bodyEn: "Demo contract; legal review is required.",
        sortOrder: 2,
      },
    ],
    deliverables: [
      {
        id: "del-1",
        title: "المخططات التنفيذية",
        description: "حزمة رسومات معتمدة داخليًا",
        dueDate: "2026-08-18",
        ownerId: "u-sales",
        status: "completed",
        mandatory: true,
        completedAt: "2026-08-17T12:00:00.000Z",
      },
      {
        id: "del-2",
        title: "الجناح المركب",
        description: "تسليم الجناح بالموقع",
        dueDate: "2026-09-20",
        ownerId: "u-sales",
        status: "in_progress",
        mandatory: true,
      },
    ],
    milestones,
    paymentSchedule: calculatePaymentSchedule(source.valueMinor, [
      {
        id: "pay-1",
        label: "دفعة مقدمة",
        percentageBps: 4000,
        dueRule: "عند التفعيل",
        milestoneId: "mil-1",
        status: "paid_demo",
      },
      {
        id: "pay-2",
        label: "دفعة التصنيع",
        percentageBps: 4000,
        dueRule: "عند اكتمال التصنيع",
        milestoneId: "mil-2",
        status: "planned",
      },
      {
        id: "pay-3",
        label: "دفعة التسليم",
        percentageBps: 2000,
        dueRule: "عند التسليم",
        milestoneId: "mil-3",
        status: "planned",
      },
    ]),
    obligations: [
      {
        id: "obl-1",
        party: "company",
        title: "تقديم المخططات التنفيذية",
        dueDate: "2026-08-18",
        ownerId: "u-sales",
        status: "completed",
        mandatory: true,
      },
      {
        id: "obl-2",
        party: "customer",
        title: "اعتماد العينات",
        dueDate: "2026-08-25",
        ownerId: "u-sales",
        status: "open",
        mandatory: true,
      },
    ],
  };
}
export function createContractSeed(): ContractSnapshotData {
  const snap = snapshot();
  return {
    users,
    sourceQuotations: [
      source,
      {
        ...source,
        id: "qv-contract-new",
        quotationId: "q-contract-new",
        salesRequestId: "sr-contract-new",
        quotationNumber: "QUO-2026-00003",
        customerId: "customer-demo-3",
        customerName: "شركة أفق جدة",
        title: "خدمات تصميم هندسي متكاملة",
        valueMinor: 8500000n,
      },
      {
        ...source,
        id: "qv-other",
        organizationId: other,
        quotationId: "q-other",
        salesRequestId: "sr-other",
        quotationNumber: "QUO-OTHER-1",
        customerId: "customer-other",
        customerName: "عميل شركة أخرى",
      },
    ],
    contracts: [
      {
        id: "ctr-1",
        organizationId: org,
        number: "CTR-2026-00001",
        currentVersionId: "cv-1",
        quotationId: source.quotationId,
        quotationVersionId: source.id,
        salesRequestId: source.salesRequestId,
        customerId: source.customerId,
        ownerId: "u-sales",
        department: "التنفيذ",
        type: "تصميم وتنفيذ",
        startDate: "2026-08-10",
        endDate: "2026-09-24",
        currency: "SAR",
        valueMinor: source.valueMinor,
        createdAt: now,
        updatedAt: now,
        createdBy: "u-owner",
      },
    ],
    versions: [
      {
        id: "cv-1",
        organizationId: org,
        contractId: "ctr-1",
        versionNumber: 1,
        displayNumber: "CTR-2026-00001-V1",
        status: "active",
        language: "bilingual",
        snapshot: snap,
        recordVersion: 1,
        approvedAt: "2026-08-07T10:00:00.000Z",
        createdAt: now,
        createdBy: "u-owner",
      },
    ],
    approvals: [],
    changeOrders: [],
    workOrders: [
      {
        id: "wo-1",
        organizationId: org,
        contractId: "ctr-1",
        deliverableId: "del-2",
        number: "WO-2026-00001",
        title: "تنفيذ وتركيب الجناح",
        description: "التصنيع والتركيب وفق المخططات المعتمدة",
        type: "تنفيذ",
        priority: "high",
        department: "التنفيذ",
        ownerId: "u-sales",
        participantIds: ["u-agent"],
        startDate: "2026-08-19",
        dueDate: "2026-09-20",
        status: "in_progress",
        progress: 55,
        checklist: [
          {
            id: "woc-1",
            title: "اعتماد المخططات",
            mandatory: true,
            completed: true,
            completedAt: "2026-08-17T12:00:00.000Z",
            completedBy: "u-sales",
          },
          {
            id: "woc-2",
            title: "فحص الجودة النهائي",
            mandatory: true,
            completed: false,
          },
        ],
        notes: "بيانات تشغيل تجريبية فقط",
        recordVersion: 1,
        createdAt: now,
        createdBy: "u-owner",
      },
    ],
    attachments: [
      {
        id: "att-1",
        organizationId: org,
        fileName: "contract-scope-v1.pdf",
        mimeType: "application/pdf",
        sizeBytes: 245000,
        category: "scope",
        version: 1,
        createdAt: now,
        confidentiality: "confidential",
        storageMetadata: "demo://metadata-only/no-file-upload",
      },
    ],
    timeline: [
      {
        id: "ctl-1",
        organizationId: org,
        customerId: source.customerId,
        contractId: "ctr-1",
        quotationId: source.quotationId,
        salesRequestId: source.salesRequestId,
        action: "contract.activated",
        summary: "تفعيل العقد التجريبي CTR-2026-00001",
        createdAt: now,
        createdBy: "u-owner",
      },
    ],
    notifications: [],
    audit: [],
    sequences: {
      [`${org}:2026:contract`]: 1,
      [`${org}:2026:work_order`]: 1,
      [`${org}:2026:change_order`]: 0,
    },
    idempotencyKeys: [],
  };
}
