import type { CurrencyCode, QuotationCharge, QuotationLineItem, QuotationTotals } from "./types";

export const currencyDigits:Record<CurrencyCode,number>={SAR:2,USD:2,EUR:2,EGP:2,KWD:3,JPY:0};
const pow10=(n:number)=>10n**BigInt(n);
export function roundDivide(value:bigint,divisor:bigint){if(divisor<=0n)throw new Error("Invalid divisor");return value>=0n?(value+divisor/2n)/divisor:-((-value+divisor/2n)/divisor);}
export function parseMoney(value:string,currency:CurrencyCode){const text=value.trim();if(!/^\d+(\.\d+)?$/.test(text))throw new Error("Invalid non-negative money value");const digits=currencyDigits[currency];const [whole,fraction=""]=text.split(".");if(fraction.length>digits)throw new Error(`Currency ${currency} supports ${digits} decimals`);return BigInt(whole)*pow10(digits)+BigInt((fraction+"0".repeat(digits)).slice(0,digits)||"0");}
export function formatMoney(minor:bigint,currency:CurrencyCode,locale="ar-SA"){const digits=currencyDigits[currency],negative=minor<0n,absolute=negative?-minor:minor,base=pow10(digits),whole=absolute/base,fraction=absolute%base,grouped=new Intl.NumberFormat(locale,{useGrouping:true,maximumFractionDigits:0}).format(whole),decimal=new Intl.NumberFormat(locale,{useGrouping:false,minimumIntegerDigits:digits||1}).format(fraction).padStart(digits,"0"),number=digits?`${grouped}${locale.startsWith("ar")?"٫":"."}${decimal}`:grouped;return`${negative?"-":""}${number} ${currency}`;}
export function parseQuantity(value:string){if(!/^\d+(\.\d{1,3})?$/.test(value.trim()))throw new Error("Quantity must be non-negative with at most 3 decimals");const [whole,fraction=""]=value.trim().split(".");return BigInt(whole)*1000n+BigInt((fraction+"000").slice(0,3));}
export function calculateLine(item:QuotationLineItem){if(item.quantityMills<0n||item.unitPriceMinor<0n||item.discountBps<0||item.discountBps>10000||item.taxBps<0||item.taxBps>10000)throw new Error("Invalid quotation line values");const gross=roundDivide(item.quantityMills*item.unitPriceMinor,1000n);const discount=roundDivide(gross*BigInt(item.discountBps),10000n);const taxable=gross-discount;const tax=roundDivide(taxable*BigInt(item.taxBps),10000n);const total=taxable+tax;const cost=item.costMinor===undefined?0n:roundDivide(item.quantityMills*item.costMinor,1000n);return{gross,discount,tax,total,cost};}
export function calculateQuotation(items:QuotationLineItem[],charges:QuotationCharge[],quoteDiscountBps:number,roundingMinor=0n):QuotationTotals{if(quoteDiscountBps<0||quoteDiscountBps>10000)throw new Error("Invalid quotation discount");let subtotal=0n,lineDiscount=0n,tax=0n,cost=0n,selectedOptional=0n;for(const item of items){const x=calculateLine(item);if(item.optional&&!item.selected)continue;subtotal+=x.gross-x.discount;lineDiscount+=x.discount;tax+=x.tax;cost+=x.cost;if(item.optional)selectedOptional+=x.total;}const quoteDiscount=roundDivide(subtotal*BigInt(quoteDiscountBps),10000n);if(subtotal>0n&&quoteDiscount>0n)tax-=roundDivide(tax*BigInt(quoteDiscountBps),10000n);let chargeMinor=0n;for(const charge of charges){if(charge.amountMinor<0n||charge.taxBps<0||charge.taxBps>10000)throw new Error("Invalid charge");chargeMinor+=charge.amountMinor;tax+=roundDivide(charge.amountMinor*BigInt(charge.taxBps),10000n);}const netRevenue=subtotal-quoteDiscount+chargeMinor,grandTotal=netRevenue+tax+roundingMinor,margin=netRevenue-cost;return{subtotalMinor:subtotal,lineDiscountMinor:lineDiscount,quoteDiscountMinor:quoteDiscount,chargeMinor,taxMinor:tax,roundingMinor,grandTotalMinor:grandTotal,selectedOptionalMinor:selectedOptional,costMinor:cost,marginMinor:margin,marginBps:netRevenue>0n?Number(roundDivide(margin*10000n,netRevenue)):0};}
