import { calculateQuotation } from "./calculations";
import { quotationsCsv, requestsCsv } from "./csv";
import { dispatchSchema, quotationLineSchema, salesRequestSchema, sanitizeText } from "./schemas";
import { createSalesSeed } from "./seed";
import type {
  ApprovalDecision, CatalogItem, CatalogPackage, CustomerResponse, Paged, Quotation,
  QuotationDispatch, QuotationFilters, QuotationLineItem, QuotationStatus, QuotationVersion,
  SalesRequest, SalesRequestFilters, SalesSnapshot,
} from "./types";

export class SalesError extends Error {
  constructor(public code: "UNAUTHORIZED"|"FORBIDDEN"|"NOT_FOUND"|"CROSS_TENANT"|"INVALID"|"CONFLICT"|"DUPLICATE", message: string) { super(message); }
}

type RequestInput = { organizationId:string; actorId:string; title:string; description:string; customerId:string; customerName?:string; customerEmail?:string; customerMobile?:string; contactId?:string; leadId?:string; conversationId?:string; source:string; priority:SalesRequest["priority"]; currency:SalesRequest["currency"]; expectedValueMinor?:bigint; requiredBy?:string };
type QuotationInput = { organizationId:string; actorId:string; salesRequestId:string; customerName:string; contactName?:string; title:string; lineItems:Omit<QuotationLineItem,"id"|"organizationId">[] };

export interface SalesRepository {
  snapshot(organizationId:string,actorId:string):SalesSnapshot;
  listRequests(organizationId:string,actorId:string,filters?:SalesRequestFilters):Paged<SalesRequest>;
  listQuotations(organizationId:string,actorId:string,filters?:QuotationFilters):Paged<{quotation:Quotation;version:QuotationVersion}>;
  exportRequests(organizationId:string,actorId:string,filters?:SalesRequestFilters):string;
  exportQuotations(organizationId:string,actorId:string,filters?:QuotationFilters):string;
  createRequest(input:RequestInput):SalesRequest;
  createQuotation(input:QuotationInput):QuotationVersion;
  updateDraft(input:{organizationId:string;actorId:string;versionId:string;expectedVersion:number;lineItems?:QuotationLineItem[];charges?:QuotationVersion["snapshot"]["charges"];quoteDiscountBps?:number;roundingAdjustmentMinor?:bigint}):QuotationVersion;
  submitForApproval(organizationId:string,actorId:string,versionId:string):void;
  decideApproval(input:{organizationId:string;actorId:string;approvalRequestId:string;decision:"approved"|"rejected"|"changes_requested"|"bypassed";comment:string}):ApprovalDecision;
  createRevision(organizationId:string,actorId:string,quotationId:string):QuotationVersion;
  dispatchDemo(input:{organizationId:string;actorId:string;versionId:string;channel:QuotationDispatch["channel"];recipient:string;subject:string;body:string;idempotencyKey:string;simulateFailure?:boolean}):QuotationDispatch;
  recordResponse(input:{organizationId:string;actorId:string;versionId:string;action:CustomerResponse["action"];responderName:string;reason?:string;notes?:string;acceptedOptionalItemIds?:string[]}):CustomerResponse;
  createCatalogItem(input:{organizationId:string;actorId:string;categoryId:string;code:string;nameAr:string;nameEn:string;descriptionAr:string;descriptionEn:string;unit:string;currency:CatalogItem["currency"];priceMinor:bigint;costMinor?:bigint;taxBps:number}):CatalogItem;
  createPackage(input:{organizationId:string;actorId:string;code:string;nameAr:string;nameEn:string;currency:CatalogItem["currency"];priceMinor:bigint;items:{catalogItemId:string;quantityMills:bigint}[]}):CatalogPackage;
  archiveCatalogItem(organizationId:string,actorId:string,itemId:string):CatalogItem;
  renderTemplate(organizationId:string,actorId:string,templateId:string,values:Record<string,string>):string;
}

const templateVariables = new Set(["quotation_number","quotation_version","customer_name","contact_name","company_name","issue_date","expiry_date","sales_representative","subtotal","tax_total","grand_total","currency","payment_terms","delivery_duration"]);
const statuses:QuotationStatus[] = ["draft","under_review","changes_requested","approved","rejected_internally","ready_to_send","sent","viewed_demo","accepted_demo","rejected_by_customer_demo","expired","superseded","cancelled"];

export class LocalSalesRepository implements SalesRepository {
  private data:SalesSnapshot;
  constructor(seed:SalesSnapshot=createSalesSeed()){ this.data=structuredClone(seed); }

  private user(org:string,actor:string,permission?:string){
    const user=this.data.users.find((item)=>item.id===actor);
    if(!user)throw new SalesError("UNAUTHORIZED","Unknown user");
    if(user.organizationId!==org)throw new SalesError("CROSS_TENANT","Cross-tenant actor denied");
    if(permission&&!user.permissions.includes(permission))throw new SalesError("FORBIDDEN",`Missing permission: ${permission}`);
    return user;
  }
  private owned<T extends {id:string;organizationId:string}>(rows:T[],org:string,id:string){
    const row=rows.find((item)=>item.id===id);
    if(!row)throw new SalesError("NOT_FOUND","Record not found");
    if(row.organizationId!==org)throw new SalesError("CROSS_TENANT","Cross-tenant access denied");
    return row;
  }
  private audit(org:string,actor:string,type:string,id:string,action:string,details=""){this.data.audit.push({id:`sa-${crypto.randomUUID()}`,organizationId:org,actorId:actor,entityType:type,entityId:id,action,details:sanitizeText(details).slice(0,500),createdAt:new Date().toISOString()});}
  private notify(org:string,userId:string,type:string,entityType:"sales_request"|"quotation"|"approval",entityId:string,title:string,dedupeKey:string){if(!this.data.notifications.some((n)=>n.organizationId===org&&n.dedupeKey===dedupeKey))this.data.notifications.push({id:`sn-${crypto.randomUUID()}`,organizationId:org,userId,type,entityType,entityId,title,read:false,dedupeKey,createdAt:new Date().toISOString()});}
  private next(org:string,type:"request"|"quotation"){const year=new Date().getUTCFullYear(),key=`${org}:${year}:${type}`,next=(this.data.sequences[key]??0)+1;this.data.sequences[key]=next;return`${type==="request"?"RFQ":"QUO"}-${year}-${String(next).padStart(5,"0")}`;}
  private page<T>(rows:T[],page=1,pageSize=20):Paged<T>{const size=Math.min(100,Math.max(1,pageSize)),requested=Math.max(1,page),total=rows.length,pages=Math.max(1,Math.ceil(total/size)),safePage=Math.min(requested,pages);return{rows:rows.slice((safePage-1)*size,safePage*size),page:safePage,pageSize:size,total,pages};}

  snapshot(org:string,actor:string){
    const user=this.user(org,actor),belongs=<T extends {organizationId:string}>(rows:T[])=>rows.filter((row)=>row.organizationId===org);
    const out:SalesSnapshot={...structuredClone(this.data),users:belongs(this.data.users),categories:belongs(this.data.categories),catalogItems:belongs(this.data.catalogItems),packages:belongs(this.data.packages),requests:belongs(this.data.requests),quotations:belongs(this.data.quotations),versions:belongs(this.data.versions),templates:belongs(this.data.templates),policies:belongs(this.data.policies),approvalRequests:belongs(this.data.approvalRequests),approvalDecisions:belongs(this.data.approvalDecisions),dispatches:belongs(this.data.dispatches),responses:belongs(this.data.responses),notifications:belongs(this.data.notifications),audit:belongs(this.data.audit),timeline:belongs(this.data.timeline),sequences:{}};
    if(!user.permissions.includes("quotations.view_cost"))out.catalogItems=out.catalogItems.map((item)=>{const safe={...item};delete safe.costMinor;return safe;});
    if(!user.permissions.includes("quotations.view_margin"))out.versions=out.versions.map((version)=>({...version,totals:{...version.totals,costMinor:0n,marginMinor:0n,marginBps:0},snapshot:{...version.snapshot,lineItems:version.snapshot.lineItems.map((line)=>{const safe={...line};delete safe.costMinor;return safe;})}}));
    return out;
  }

  listRequests(org:string,actor:string,f:SalesRequestFilters={}){
    const user=this.user(org,actor,"sales_requests.view");let rows=this.data.requests.filter((row)=>row.organizationId===org&&!row.archivedAt);
    if(user.role==="sales_agent")rows=rows.filter((row)=>row.ownerId===actor||row.createdBy===actor);
    if(f.query){const q=f.query.trim().toLowerCase();rows=rows.filter((row)=>[row.number,row.title,row.description,row.customerName,row.customerEmail,row.customerMobile].some((value)=>value?.toLowerCase().includes(q)));}
    if(f.status)rows=rows.filter((row)=>row.status===f.status);if(f.ownerId)rows=rows.filter((row)=>row.ownerId===f.ownerId);if(f.priority)rows=rows.filter((row)=>row.priority===f.priority);if(f.source)rows=rows.filter((row)=>row.source===f.source);if(f.currency)rows=rows.filter((row)=>row.currency===f.currency);
    if(f.createdFrom)rows=rows.filter((row)=>row.createdAt.slice(0,10)>=f.createdFrom!);if(f.createdTo)rows=rows.filter((row)=>row.createdAt.slice(0,10)<=f.createdTo!);if(f.valueMinMinor!==undefined)rows=rows.filter((row)=>(row.expectedValueMinor??0n)>=f.valueMinMinor!);if(f.valueMaxMinor!==undefined)rows=rows.filter((row)=>(row.expectedValueMinor??0n)<=f.valueMaxMinor!);
    rows.sort((a,b)=>f.sort==="value"?Number((b.expectedValueMinor??0n)-(a.expectedValueMinor??0n)):b.createdAt.localeCompare(a.createdAt));return this.page(structuredClone(rows),f.page,f.pageSize);
  }

  listQuotations(org:string,actor:string,f:QuotationFilters={}){
    const user=this.user(org,actor,"quotations.view");let rows=this.data.quotations.filter((row)=>row.organizationId===org&&!row.archivedAt).map((quotation)=>({quotation,version:this.owned(this.data.versions,org,quotation.currentVersionId),request:this.owned(this.data.requests,org,quotation.salesRequestId)}));
    if(user.role==="sales_agent")rows=rows.filter((row)=>row.version.salesRepresentativeId===actor||row.quotation.createdBy===actor);
    if(f.query){const q=f.query.trim().toLowerCase();rows=rows.filter((row)=>[row.quotation.number,row.version.displayNumber,row.version.title,row.version.snapshot.customerName,row.request.customerEmail,row.request.customerMobile].some((value)=>value?.toLowerCase().includes(q)));}
    if(f.status)rows=rows.filter((row)=>row.version.status===f.status);if(f.ownerId)rows=rows.filter((row)=>row.version.salesRepresentativeId===f.ownerId);if(f.source)rows=rows.filter((row)=>row.request.source===f.source);if(f.priority)rows=rows.filter((row)=>row.request.priority===f.priority);if(f.currency)rows=rows.filter((row)=>row.version.currency===f.currency);
    if(f.approval)rows=rows.filter((row)=>this.data.approvalRequests.some((approval)=>approval.organizationId===org&&approval.quotationVersionId===row.version.id&&approval.status===f.approval));if(f.createdFrom)rows=rows.filter((row)=>row.version.createdAt.slice(0,10)>=f.createdFrom!);if(f.createdTo)rows=rows.filter((row)=>row.version.createdAt.slice(0,10)<=f.createdTo!);if(f.expiryFrom)rows=rows.filter((row)=>row.version.expiryDate>=f.expiryFrom!);if(f.expiryTo)rows=rows.filter((row)=>row.version.expiryDate<=f.expiryTo!);if(f.valueMinMinor!==undefined)rows=rows.filter((row)=>row.version.totals.grandTotalMinor>=f.valueMinMinor!);if(f.valueMaxMinor!==undefined)rows=rows.filter((row)=>row.version.totals.grandTotalMinor<=f.valueMaxMinor!);
    const today=new Date().toISOString().slice(0,10);if(f.expiryState==="expired")rows=rows.filter((row)=>row.version.expiryDate<today);if(f.expiryState==="expiring_soon"){const limit=new Date(Date.now()+7*86400000).toISOString().slice(0,10);rows=rows.filter((row)=>row.version.expiryDate>=today&&row.version.expiryDate<=limit);}if(f.expiresWithinDays!==undefined){const limit=new Date(Date.now()+f.expiresWithinDays*86400000).toISOString().slice(0,10);rows=rows.filter((row)=>row.version.expiryDate<=limit);}
    rows.sort((a,b)=>f.sort==="value"?(b.version.totals.grandTotalMinor>a.version.totals.grandTotalMinor?1:b.version.totals.grandTotalMinor<a.version.totals.grandTotalMinor?-1:0):f.sort==="expiry"?a.version.expiryDate.localeCompare(b.version.expiryDate):b.version.createdAt.localeCompare(a.version.createdAt));
    return this.page(structuredClone(rows.map(({quotation,version})=>({quotation,version}))),f.page,f.pageSize);
  }
  exportRequests(org:string,actor:string,filters:SalesRequestFilters={}){this.user(org,actor,"sales_requests.export");return requestsCsv(this.listRequests(org,actor,{...filters,page:1,pageSize:100}));}
  exportQuotations(org:string,actor:string,filters:QuotationFilters={}){const user=this.user(org,actor,"quotations.export");return quotationsCsv(this.listQuotations(org,actor,{...filters,page:1,pageSize:100}),user);}

  createRequest(input:RequestInput){
    this.user(input.organizationId,input.actorId,"sales_requests.create");const parsed=salesRequestSchema.parse(input);if(parsed.conversationId&&this.data.requests.some((row)=>row.organizationId===input.organizationId&&row.conversationId===parsed.conversationId&&!row.archivedAt))throw new SalesError("DUPLICATE","A request already exists for this conversation");if(input.expectedValueMinor!==undefined&&input.expectedValueMinor<0n)throw new SalesError("INVALID","Expected value cannot be negative");
    const now=new Date().toISOString(),row:SalesRequest={id:`sr-${crypto.randomUUID()}`,organizationId:input.organizationId,number:this.next(input.organizationId,"request"),title:sanitizeText(parsed.title),description:sanitizeText(parsed.description),customerId:parsed.customerId,customerName:sanitizeText(input.customerName??parsed.customerId),customerEmail:input.customerEmail?sanitizeText(input.customerEmail):undefined,customerMobile:input.customerMobile?sanitizeText(input.customerMobile):undefined,contactId:parsed.contactId,leadId:parsed.leadId,conversationId:parsed.conversationId,source:parsed.source,status:"new",priority:parsed.priority,ownerId:input.actorId,expectedValueMinor:input.expectedValueMinor,currency:parsed.currency,requiredBy:parsed.requiredBy,version:1,createdAt:now,updatedAt:now,createdBy:input.actorId};
    this.data.requests.push(row);this.data.timeline.push({id:`st-${crypto.randomUUID()}`,organizationId:input.organizationId,customerId:row.customerId,salesRequestId:row.id,conversationId:row.conversationId,action:"sales_request.created",summary:`إنشاء ${row.number}`,createdAt:now,createdBy:input.actorId});this.audit(input.organizationId,input.actorId,"sales_request",row.id,"sales_request.created",row.number);return structuredClone(row);
  }

  createQuotation(input:QuotationInput){
    this.user(input.organizationId,input.actorId,"quotations.create");const request=this.owned(this.data.requests,input.organizationId,input.salesRequestId);if(input.lineItems.length===0)throw new SalesError("INVALID","Quotation requires at least one line");
    const number=this.next(input.organizationId,"quotation"),quotationId=`q-${crypto.randomUUID()}`,versionId=`qv-${crypto.randomUUID()}`,now=new Date().toISOString(),items=input.lineItems.map((line,index)=>({...quotationLineSchema.parse(line),id:`qli-${crypto.randomUUID()}`,organizationId:input.organizationId,sortOrder:index+1})),template=this.data.templates.find((row)=>row.organizationId===input.organizationId&&row.isDefault&&row.active);if(!template)throw new SalesError("INVALID","No default quotation template");
    const version:QuotationVersion={id:versionId,organizationId:input.organizationId,quotationId,versionNumber:1,displayNumber:`${number}-V1`,status:"draft",currency:request.currency,language:template.language,issueDate:now.slice(0,10),expiryDate:new Date(Date.now()+15*86400000).toISOString().slice(0,10),salesRepresentativeId:input.actorId,title:sanitizeText(input.title),duration:"حسب نطاق العمل",quoteDiscountBps:0,roundingAdjustmentMinor:0n,snapshot:{customerName:sanitizeText(input.customerName),contactName:input.contactName?sanitizeText(input.contactName):undefined,companyName:"شركة مدار التجريبية",lineItems:items,charges:[],introduction:template.introduction,scope:template.scope,exclusions:template.exclusions,assumptions:template.assumptions,paymentTerms:template.paymentTerms,terms:template.terms,templateId:template.id},totals:calculateQuotation(items,[],0),recordVersion:1,createdAt:now,createdBy:input.actorId};
    const quotation:Quotation={id:quotationId,organizationId:input.organizationId,number,salesRequestId:request.id,customerId:request.customerId,contactId:request.contactId,conversationId:request.conversationId,currentVersionId:versionId,createdAt:now,updatedAt:now,createdBy:input.actorId};this.data.quotations.push(quotation);this.data.versions.push(version);request.status="quotation_in_progress";request.updatedAt=now;this.data.timeline.push({id:`st-${crypto.randomUUID()}`,organizationId:input.organizationId,customerId:request.customerId,salesRequestId:request.id,quotationId,conversationId:request.conversationId,action:"quotation.created",summary:`إنشاء ${version.displayNumber}`,createdAt:now,createdBy:input.actorId});this.audit(input.organizationId,input.actorId,"quotation",quotationId,"quotation.created",version.displayNumber);return structuredClone(version);
  }

  updateDraft(input:Parameters<SalesRepository["updateDraft"]>[0]){const actor=this.user(input.organizationId,input.actorId,"quotations.update_draft"),version=this.owned(this.data.versions,input.organizationId,input.versionId);if(!["draft","changes_requested"].includes(version.status))throw new SalesError("CONFLICT","Only draft or changes-requested versions are editable");if(actor.role==="sales_agent"&&version.createdBy!==input.actorId)throw new SalesError("FORBIDDEN","Sales agents may edit only their own draft");if(version.recordVersion!==input.expectedVersion)throw new SalesError("CONFLICT","Quotation was updated by another user");if(input.lineItems)version.snapshot.lineItems=input.lineItems.map((line,index)=>({...quotationLineSchema.parse(line),id:line.id,organizationId:input.organizationId,sortOrder:index+1}));if(input.charges)version.snapshot.charges=structuredClone(input.charges);if(input.quoteDiscountBps!==undefined)version.quoteDiscountBps=input.quoteDiscountBps;if(input.roundingAdjustmentMinor!==undefined)version.roundingAdjustmentMinor=input.roundingAdjustmentMinor;version.totals=calculateQuotation(version.snapshot.lineItems,version.snapshot.charges,version.quoteDiscountBps,version.roundingAdjustmentMinor);version.recordVersion++;this.audit(input.organizationId,input.actorId,"quotation_version",version.id,"quotation.draft_updated",`version=${version.recordVersion}`);return structuredClone(version);}

  submitForApproval(org:string,actor:string,versionId:string){this.user(org,actor,"quotations.submit_for_approval");const version=this.owned(this.data.versions,org,versionId);if(!["draft","changes_requested"].includes(version.status))throw new SalesError("CONFLICT","Version cannot be submitted");const existing=this.data.approvalRequests.find((row)=>row.organizationId===org&&row.quotationVersionId===version.id&&row.status==="pending");if(existing)return;const policy=this.data.policies.find((row)=>row.organizationId===org&&row.active);if(!policy){version.status="approved";version.approvedAt=new Date().toISOString();return;}version.status="under_review";const approval={id:`apr-${crypto.randomUUID()}`,organizationId:org,quotationVersionId:version.id,policyId:policy.id,status:"pending" as const,currentStep:1,requestedBy:actor,requestedAt:new Date().toISOString()};this.data.approvalRequests.push(approval);for(const user of this.data.users.filter((row)=>row.organizationId===org&&row.role===policy.steps[0].role))this.notify(org,user.id,"approval_requested","approval",approval.id,`طلب اعتماد ${version.displayNumber}`,`approval:${approval.id}:1:${user.id}`);this.audit(org,actor,"quotation_version",version.id,"approval.submitted",approval.id);}

  decideApproval(input:Parameters<SalesRepository["decideApproval"]>[0]){const permission=input.decision==="bypassed"?"quotations.bypass_approval":input.decision==="approved"?"quotations.approve":"quotations.reject",user=this.user(input.organizationId,input.actorId,permission),approval=this.owned(this.data.approvalRequests,input.organizationId,input.approvalRequestId);if(approval.status!=="pending")throw new SalesError("CONFLICT","Approval is already completed");if(approval.requestedBy===input.actorId&&process.env.SALES_SEPARATE_APPROVER!=="false")throw new SalesError("FORBIDDEN","Creator cannot approve their own quotation");const policy=this.owned(this.data.policies,input.organizationId,approval.policyId),expected=policy.steps.find((step)=>step.order===approval.currentStep);if(input.decision!=="bypassed"&&expected&&user.role!==expected.role&&user.role!=="owner")throw new SalesError("FORBIDDEN","Actor is not the current approver");const decision:ApprovalDecision={id:`apd-${crypto.randomUUID()}`,organizationId:input.organizationId,approvalRequestId:approval.id,step:approval.currentStep,actorId:input.actorId,decision:input.decision,comment:sanitizeText(input.comment),createdAt:new Date().toISOString()};this.data.approvalDecisions.push(decision);const version=this.owned(this.data.versions,input.organizationId,approval.quotationVersionId);if(input.decision==="approved"&&approval.currentStep<policy.steps.length){approval.currentStep++;const role=policy.steps.find((step)=>step.order===approval.currentStep)?.role;for(const approver of this.data.users.filter((row)=>row.organizationId===input.organizationId&&row.role===role))this.notify(input.organizationId,approver.id,"approval_requested","approval",approval.id,`طلب اعتماد ${version.displayNumber}`,`approval:${approval.id}:${approval.currentStep}:${approver.id}`);}else{approval.status=input.decision;approval.completedAt=new Date().toISOString();version.status=input.decision==="approved"||input.decision==="bypassed"?"approved":input.decision==="changes_requested"?"changes_requested":"rejected_internally";if(version.status==="approved")version.approvedAt=approval.completedAt;}this.audit(input.organizationId,input.actorId,"approval",approval.id,`approval.${input.decision}`,input.comment);return structuredClone(decision);}

  createRevision(org:string,actor:string,quotationId:string){this.user(org,actor,"quotations.create_revision");const quotation=this.owned(this.data.quotations,org,quotationId),old=this.owned(this.data.versions,org,quotation.currentVersionId);if(old.status==="draft")throw new SalesError("CONFLICT","Edit the current draft instead");old.status="superseded";const now=new Date().toISOString(),version:QuotationVersion={...structuredClone(old),id:`qv-${crypto.randomUUID()}`,versionNumber:old.versionNumber+1,displayNumber:`${quotation.number}-V${old.versionNumber+1}`,status:"draft",recordVersion:1,approvedAt:undefined,sentAt:undefined,createdAt:now,createdBy:actor};quotation.currentVersionId=version.id;quotation.updatedAt=now;this.data.versions.push(version);this.audit(org,actor,"quotation",quotation.id,"quotation.revision_created",version.displayNumber);return structuredClone(version);}

  dispatchDemo(input:Parameters<SalesRepository["dispatchDemo"]>[0]){this.user(input.organizationId,input.actorId,"quotations.mark_sent");const parsed=dispatchSchema.parse(input),version=this.owned(this.data.versions,input.organizationId,input.versionId),duplicate=this.data.dispatches.find((row)=>row.organizationId===input.organizationId&&row.idempotencyKey===parsed.idempotencyKey);if(duplicate)return structuredClone(duplicate);if(!["approved","ready_to_send"].includes(version.status))throw new SalesError("CONFLICT","Only approved quotations can be sent");const row:QuotationDispatch={id:`qd-${crypto.randomUUID()}`,organizationId:input.organizationId,quotationVersionId:version.id,channel:parsed.channel,recipient:sanitizeText(parsed.recipient),subject:sanitizeText(parsed.subject),body:sanitizeText(parsed.body),status:input.simulateFailure?"failed":"delivered",failureReason:input.simulateFailure?"Simulated provider failure":undefined,idempotencyKey:parsed.idempotencyKey,createdBy:input.actorId,createdAt:new Date().toISOString()};this.data.dispatches.push(row);if(!input.simulateFailure){version.status="sent";version.sentAt=row.createdAt;const quotation=this.owned(this.data.quotations,input.organizationId,version.quotationId),request=this.owned(this.data.requests,input.organizationId,quotation.salesRequestId);request.status="quotation_sent";request.updatedAt=row.createdAt;this.data.timeline.push({id:`st-${crypto.randomUUID()}`,organizationId:input.organizationId,customerId:quotation.customerId,salesRequestId:request.id,quotationId:quotation.id,conversationId:quotation.conversationId,action:"quotation.sent_demo",summary:`إرسال تجريبي ${version.displayNumber}`,createdAt:row.createdAt,createdBy:input.actorId});}this.audit(input.organizationId,input.actorId,"quotation_dispatch",row.id,"quotation.dispatch_demo",row.status);return structuredClone(row);}

  recordResponse(input:Parameters<SalesRepository["recordResponse"]>[0]){this.user(input.organizationId,input.actorId,"quotations.record_customer_response");const version=this.owned(this.data.versions,input.organizationId,input.versionId),today=new Date().toISOString().slice(0,10);if(version.expiryDate<today)version.status="expired";if(["expired","superseded","cancelled"].includes(version.status))throw new SalesError("CONFLICT","This version cannot receive a response");if(!["sent","viewed_demo","rejected_by_customer_demo"].includes(version.status))throw new SalesError("CONFLICT","Quotation has not been sent");const validOptional=new Set(version.snapshot.lineItems.filter((line)=>line.optional).map((line)=>line.id));if((input.acceptedOptionalItemIds??[]).some((id)=>!validOptional.has(id)))throw new SalesError("INVALID","Unknown optional item");const row:CustomerResponse={id:`qcr-${crypto.randomUUID()}`,organizationId:input.organizationId,quotationVersionId:version.id,action:input.action,responderName:sanitizeText(input.responderName),reason:input.reason?sanitizeText(input.reason):undefined,notes:input.notes?sanitizeText(input.notes):undefined,acceptedOptionalItemIds:input.acceptedOptionalItemIds??[],isLegalAcceptance:false,createdAt:new Date().toISOString(),createdBy:input.actorId};this.data.responses.push(row);version.status=input.action==="accepted"?"accepted_demo":input.action==="rejected"?"rejected_by_customer_demo":input.action==="viewed"?"viewed_demo":"changes_requested";const quotation=this.owned(this.data.quotations,input.organizationId,version.quotationId),request=this.owned(this.data.requests,input.organizationId,quotation.salesRequestId);if(input.action==="accepted")request.status="won";this.data.timeline.push({id:`st-${crypto.randomUUID()}`,organizationId:input.organizationId,customerId:quotation.customerId,salesRequestId:request.id,quotationId:quotation.id,conversationId:quotation.conversationId,action:`quotation.${input.action}_demo`,summary:`رد تجريبي على ${version.displayNumber}`,createdAt:row.createdAt,createdBy:input.actorId});this.audit(input.organizationId,input.actorId,"quotation_response",row.id,`customer.${input.action}`,"Demo only; not a legal acceptance");return structuredClone(row);}

  createCatalogItem(input:Parameters<SalesRepository["createCatalogItem"]>[0]){this.user(input.organizationId,input.actorId,"catalog.manage");this.owned(this.data.categories,input.organizationId,input.categoryId);if(this.data.catalogItems.some((row)=>row.organizationId===input.organizationId&&row.code===input.code&&!row.archivedAt))throw new SalesError("DUPLICATE","Catalog code already exists");if(input.priceMinor<0n||input.costMinor!==undefined&&input.costMinor<0n||input.taxBps<0||input.taxBps>10000)throw new SalesError("INVALID","Invalid catalog pricing");const now=new Date().toISOString(),row:CatalogItem={id:`cat-${crypto.randomUUID()}`,organizationId:input.organizationId,categoryId:input.categoryId,code:sanitizeText(input.code),nameAr:sanitizeText(input.nameAr),nameEn:sanitizeText(input.nameEn),descriptionAr:sanitizeText(input.descriptionAr),descriptionEn:sanitizeText(input.descriptionEn),unit:sanitizeText(input.unit),currency:input.currency,priceMinor:input.priceMinor,costMinor:input.costMinor,taxBps:input.taxBps,active:true,version:1,createdAt:now,updatedAt:now,createdBy:input.actorId};this.data.catalogItems.push(row);this.audit(input.organizationId,input.actorId,"catalog_item",row.id,"catalog.created",row.code);return structuredClone(row);}
  createPackage(input:Parameters<SalesRepository["createPackage"]>[0]){this.user(input.organizationId,input.actorId,"catalog.manage");if(input.items.length===0)throw new SalesError("INVALID","Package requires at least one item");for(const item of input.items){this.owned(this.data.catalogItems,input.organizationId,item.catalogItemId);if(item.quantityMills<=0n)throw new SalesError("INVALID","Package quantity must be positive");}if(input.priceMinor<0n)throw new SalesError("INVALID","Invalid package price");const now=new Date().toISOString(),row:CatalogPackage={id:`pkg-${crypto.randomUUID()}`,organizationId:input.organizationId,code:sanitizeText(input.code),nameAr:sanitizeText(input.nameAr),nameEn:sanitizeText(input.nameEn),currency:input.currency,items:structuredClone(input.items),priceMinor:input.priceMinor,active:true,createdAt:now,updatedAt:now,createdBy:input.actorId};this.data.packages.push(row);this.audit(input.organizationId,input.actorId,"catalog_package",row.id,"package.created",row.code);return structuredClone(row);}
  archiveCatalogItem(org:string,actor:string,itemId:string){this.user(org,actor,"catalog.manage");const item=this.owned(this.data.catalogItems,org,itemId);item.archivedAt=new Date().toISOString();item.active=false;item.version++;item.updatedAt=item.archivedAt;item.updatedBy=actor;this.audit(org,actor,"catalog_item",item.id,"catalog.archived",item.code);return structuredClone(item);}
  renderTemplate(org:string,actor:string,templateId:string,values:Record<string,string>){this.user(org,actor,"quotation_templates.view");const template=this.owned(this.data.templates,org,templateId);return[template.introduction,template.scope,template.exclusions,template.assumptions,template.paymentTerms,template.terms].join("\n").replace(/\{\{([a-z_]+)\}\}/g,(_match,key:string)=>templateVariables.has(key)?sanitizeText(values[key]??""):"").replace(/[<>]/g,"");}
}

export class SupabaseSalesRepository implements SalesRepository {
  private unavailable():never{throw new SalesError("INVALID","Supabase sales adapter is a contract stub; apply migration and implement RPC binding in a later integration phase");}
  snapshot():SalesSnapshot{return this.unavailable();}listRequests():Paged<SalesRequest>{return this.unavailable();}listQuotations():Paged<{quotation:Quotation;version:QuotationVersion}>{return this.unavailable();}exportRequests():string{return this.unavailable();}exportQuotations():string{return this.unavailable();}createRequest():SalesRequest{return this.unavailable();}createQuotation():QuotationVersion{return this.unavailable();}updateDraft():QuotationVersion{return this.unavailable();}submitForApproval():void{return this.unavailable();}decideApproval():ApprovalDecision{return this.unavailable();}createRevision():QuotationVersion{return this.unavailable();}dispatchDemo():QuotationDispatch{return this.unavailable();}recordResponse():CustomerResponse{return this.unavailable();}createCatalogItem():CatalogItem{return this.unavailable();}createPackage():CatalogPackage{return this.unavailable();}archiveCatalogItem():CatalogItem{return this.unavailable();}renderTemplate():string{return this.unavailable();}
}
export function quotationStatusLabel(status:QuotationStatus){return statuses.includes(status)?status.replaceAll("_"," "):status;}
