export type SalesRequestStatus = "new" | "qualified" | "needs_pricing" | "quotation_in_progress" | "quotation_sent" | "negotiation" | "won" | "lost" | "cancelled";
export type QuotationStatus = "draft" | "under_review" | "changes_requested" | "approved" | "rejected_internally" | "ready_to_send" | "sent" | "viewed_demo" | "accepted_demo" | "rejected_by_customer_demo" | "expired" | "superseded" | "cancelled";
export type ApprovalStatus = "pending" | "approved" | "rejected" | "changes_requested" | "bypassed";
export type DispatchStatus = "draft" | "queued" | "sent" | "delivered" | "failed";
export type CurrencyCode = "SAR" | "USD" | "EUR" | "EGP" | "KWD" | "JPY";
export type SalesRole = "owner" | "admin" | "sales_manager" | "sales_agent" | "customer_service" | "accountant" | "viewer" | "marketing";

export interface SalesUser { id:string; organizationId:string; name:string; role:SalesRole; permissions:string[]; }
export interface ServiceCategory { id:string; organizationId:string; code:string; nameAr:string; nameEn:string; active:boolean; archivedAt?:string; createdAt:string; updatedAt:string; createdBy:string; }
export interface CatalogItem { id:string; organizationId:string; categoryId:string; code:string; nameAr:string; nameEn:string; descriptionAr:string; descriptionEn:string; unit:string; currency:CurrencyCode; priceMinor:bigint; costMinor?:bigint; taxBps:number; active:boolean; version:number; archivedAt?:string; createdAt:string; updatedAt:string; createdBy:string; updatedBy?:string; }
export interface CatalogPackageItem { catalogItemId:string; quantityMills:bigint; }
export interface CatalogPackage { id:string; organizationId:string; code:string; nameAr:string; nameEn:string; currency:CurrencyCode; items:CatalogPackageItem[]; priceMinor:bigint; active:boolean; archivedAt?:string; createdAt:string; updatedAt:string; createdBy:string; }

export interface SalesRequest { id:string; organizationId:string; number:string; title:string; description:string; customerId:string; customerName:string; customerEmail?:string; customerMobile?:string; contactId?:string; leadId?:string; conversationId?:string; source:string; status:SalesRequestStatus; priority:"low"|"medium"|"high"|"urgent"; ownerId:string; expectedValueMinor?:bigint; currency:CurrencyCode; requiredBy?:string; notes?:string; version:number; createdAt:string; updatedAt:string; createdBy:string; updatedBy?:string; archivedAt?:string; }
export interface QuotationLineItem { id:string; organizationId:string; sectionId?:string; catalogItemId?:string; code:string; description:string; quantityMills:bigint; unit:string; unitPriceMinor:bigint; costMinor?:bigint; discountBps:number; taxBps:number; optional:boolean; selected:boolean; sortOrder:number; notes?:string; }
export interface QuotationCharge { id:string; label:string; amountMinor:bigint; taxBps:number; }
export interface QuotationSnapshot { customerName:string; contactName?:string; companyName:string; companyTaxNumber?:string; lineItems:QuotationLineItem[]; charges:QuotationCharge[]; introduction:string; scope:string; exclusions:string; assumptions:string; paymentTerms:string; terms:string; templateId:string; }
export interface QuotationVersion { id:string; organizationId:string; quotationId:string; versionNumber:number; displayNumber:string; status:QuotationStatus; currency:CurrencyCode; language:"ar"|"en"|"bilingual"; issueDate:string; expiryDate:string; salesRepresentativeId:string; title:string; reference?:string; duration:string; quoteDiscountBps:number; roundingAdjustmentMinor:bigint; snapshot:QuotationSnapshot; totals:QuotationTotals; recordVersion:number; approvedAt?:string; sentAt?:string; createdAt:string; createdBy:string; }
export interface Quotation { id:string; organizationId:string; number:string; salesRequestId:string; customerId:string; contactId?:string; conversationId?:string; currentVersionId:string; createdAt:string; updatedAt:string; createdBy:string; archivedAt?:string; }
export interface QuotationTotals { subtotalMinor:bigint; lineDiscountMinor:bigint; quoteDiscountMinor:bigint; chargeMinor:bigint; taxMinor:bigint; roundingMinor:bigint; grandTotalMinor:bigint; selectedOptionalMinor:bigint; costMinor:bigint; marginMinor:bigint; marginBps:number; }

export interface ApprovalPolicy { id:string; organizationId:string; name:string; minTotalMinor?:bigint; minDiscountBps?:number; minMarginBps?:number; sequential:boolean; active:boolean; steps:{order:number;role:SalesRole}[]; }
export interface ApprovalRequest { id:string; organizationId:string; quotationVersionId:string; policyId:string; status:ApprovalStatus; currentStep:number; requestedBy:string; requestedAt:string; completedAt?:string; }
export interface ApprovalDecision { id:string; organizationId:string; approvalRequestId:string; step:number; actorId:string; decision:Exclude<ApprovalStatus,"pending">; comment:string; createdAt:string; }
export interface QuotationTemplate { id:string; organizationId:string; nameAr:string; nameEn:string; language:"ar"|"en"|"bilingual"; introduction:string; scope:string; exclusions:string; assumptions:string; paymentTerms:string; terms:string; color:string; active:boolean; isDefault:boolean; createdAt:string; updatedAt:string; }
export interface QuotationDispatch { id:string; organizationId:string; quotationVersionId:string; channel:"email_demo"|"whatsapp_demo"|"manual"; recipient:string; subject:string; body:string; status:DispatchStatus; idempotencyKey:string; failureReason?:string; createdBy:string; createdAt:string; }
export interface CustomerResponse { id:string; organizationId:string; quotationVersionId:string; action:"viewed"|"accepted"|"rejected"|"changes_requested"; responderName:string; reason?:string; notes?:string; acceptedOptionalItemIds:string[]; isLegalAcceptance:false; createdAt:string; createdBy:string; }
export interface SalesNotification { id:string; organizationId:string; userId:string; type:string; entityType:"sales_request"|"quotation"|"approval"; entityId:string; title:string; read:boolean; dedupeKey:string; createdAt:string; }
export interface SalesAuditEntry { id:string; organizationId:string; actorId:string; entityType:string; entityId:string; action:string; details:string; createdAt:string; }
export interface SalesTimelineEntry { id:string; organizationId:string; customerId:string; salesRequestId?:string; quotationId?:string; conversationId?:string; action:string; summary:string; createdAt:string; createdBy:string; }

export interface SalesSnapshot { users:SalesUser[]; categories:ServiceCategory[]; catalogItems:CatalogItem[]; packages:CatalogPackage[]; requests:SalesRequest[]; quotations:Quotation[]; versions:QuotationVersion[]; templates:QuotationTemplate[]; policies:ApprovalPolicy[]; approvalRequests:ApprovalRequest[]; approvalDecisions:ApprovalDecision[]; dispatches:QuotationDispatch[]; responses:CustomerResponse[]; notifications:SalesNotification[]; audit:SalesAuditEntry[]; timeline:SalesTimelineEntry[]; sequences:Record<string,number>; }

export interface SalesRequestFilters { query?:string; status?:SalesRequestStatus; ownerId?:string; priority?:SalesRequest["priority"]; source?:string; currency?:CurrencyCode; createdFrom?:string; createdTo?:string; valueMinMinor?:bigint; valueMaxMinor?:bigint; page?:number; pageSize?:number; sort?:"newest"|"value"; }
export interface QuotationFilters { query?:string; status?:QuotationStatus; ownerId?:string; source?:string; priority?:SalesRequest["priority"]; currency?:CurrencyCode; approval?:ApprovalStatus; createdFrom?:string; createdTo?:string; expiryFrom?:string; expiryTo?:string; valueMinMinor?:bigint; valueMaxMinor?:bigint; expiryState?:"expired"|"expiring_soon"; expiresWithinDays?:number; page?:number; pageSize?:number; sort?:"newest"|"value"|"expiry"; }
export interface Paged<T> { rows:T[]; page:number; pageSize:number; total:number; pages:number; }
