"use client";
import Link from "next/link";
import { useMemo,type ReactNode } from "react";
import { AlertTriangle,CalendarDays,Clock3,FileDown,GraduationCap,Network,Printer,ShieldCheck,UserCheck,UsersRound } from "lucide-react";
import { getHrRepository } from "@/lib/hr/provider";
import { headcountAt,leaveBalance,readinessBlockers,safeCsvCell } from "@/lib/hr/calculations";
import type { HrData,Worker } from "@/lib/hr/types";
const org="org-madar-demo",actor="u-owner";
const tabs=["workers","organization","positions","locations","shifts","attendance","attendance/corrections","leave","leave/balances","overtime","workforce","skills","training","onboarding","performance","payroll-readiness","reports"];
const ar:Record<string,string>={workers:"الموظفون والعاملون",organization:"الهيكل التنظيمي",positions:"المناصب",locations:"المواقع",shifts:"الورديات",attendance:"الحضور","attendance/corrections":"تصحيحات الحضور",leave:"الإجازات","leave/balances":"أرصدة الإجازات",overtime:"العمل الإضافي",workforce:"تخصيص القوى العاملة",skills:"المهارات والشهادات",training:"التدريب",onboarding:"التهيئة والمغادرة",performance:"الأداء التشغيلي","payroll-readiness":"جاهزية الرواتب",reports:"التقارير"};
const en:Record<string,string>={workers:"Workers",organization:"Organization",positions:"Positions",locations:"Locations",shifts:"Shifts",attendance:"Attendance","attendance/corrections":"Corrections",leave:"Leave","leave/balances":"Leave balances",overtime:"Overtime",workforce:"Workforce allocation",skills:"Skills & certifications",training:"Training",onboarding:"On/Offboarding",performance:"Performance","payroll-readiness":"Payroll readiness",reports:"Reports"};
const status=(x:string)=><span className={`project-badge ${/active|approved|completed|present|valid|frozen|ready|matched/.test(x)?"success":/expired|absent|missing|blocked|terminated|rejected|exceptions/.test(x)?"danger":"warning"}`}>{x.replaceAll("_"," ")}</span>;
function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="project-table-wrap"><table className="project-table"><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Kpi({label,value,icon,hint}:{label:string;value:string;icon:ReactNode;hint:string}){return <article className="project-kpi"><i>{icon}</i><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></article>}
function Empty({text}:{text:string}){return <section className="panel project-empty"><UsersRound/><strong>{text}</strong><span>لا تعرض الشاشة صفرًا وهميًا عند غياب المصدر.</span></section>}
function Shell({segment,locale,children}:{segment:string;locale:"ar"|"en";children:ReactNode}){const labels=locale==="ar"?ar:en;return <div className="production-space"><header className="production-hero"><div><small>HRIS · Workforce Operations</small><h2>{locale==="ar"?"الموارد البشرية والقوى العاملة":"HR & Workforce"}</h2><p>{locale==="ar"?"سجل عامل موحد، حضور وإجازات وتسوية وقت وجاهزية رواتب دون مبالغ أو دفع.":"Unified workers, attendance, leave, time reconciliation and payroll readiness without payroll amounts or payment."}</p></div><div><strong>Payroll Readiness</strong><small>No payroll engine</small></div></header><nav className="project-tabs"><Link href="/dashboard/hr">{locale==="ar"?"الرئيسية":"Dashboard"}</Link>{tabs.map(x=><Link key={x} className={segment===x?"active":""} href={`/dashboard/hr/${x}`}>{labels[x]}</Link>)}</nav>{children}</div>}
export function HrWorkspace({segments=[],locale}:{segments?:string[];locale:"ar"|"en"}){const repo=useMemo(()=>getHrRepository("local"),[]),data=repo.snapshot(org,actor),first=segments[0]??"dashboard",segment=first==="attendance"&&segments[1]==="corrections"?"attendance/corrections":first==="leave"&&segments[1]==="balances"?"leave/balances":first,id=segments[1],worker=id?data.workers.find(x=>x.id===id):undefined,today="2026-08-08",t=(a:string,e:string)=>locale==="ar"?a:e;
 if(segment==="dashboard")return <Shell segment={segment} locale={locale}><div className="project-kpis"><Kpi icon={<UsersRound/>} label={t("العاملون النشطون","Active workers")} value={String(headcountAt(data.workers,today))} hint={t("حسب تاريخ السريان","Effective dated")}/><Kpi icon={<UserCheck/>} label={t("الحضور اليوم","Present today")} value={String(data.attendance.filter(x=>x.workDate===today&&["present","late","corrected"].includes(x.status)).length)} hint={t("من سجلات الحضور","Attendance source")}/><Kpi icon={<AlertTriangle/>} label={t("بصمات ناقصة","Missing punches")} value={String(data.attendance.filter(x=>x.status==="missing_punch").length)} hint={t("تحتاج تسوية","Needs resolution")}/><Kpi icon={<ShieldCheck/>} label={t("عوائق الجاهزية","Readiness blockers")} value={String(data.payrollBatches[0]?readinessBlockers(data.payrollBatches[0].lines):data.attendance.filter(x=>x.status==="missing_punch").length)} hint={data.payrollBatches[0]?data.payrollBatches[0].number:t("لا توجد فترة محفوظة","No batch yet")}/></div><div className="project-grid"><section className="panel"><h3>{t("قائمة العاملين","Workers")}</h3><Workers data={data}/></section><section className="panel"><h3>{t("تنبيهات تشغيلية","Operational alerts")}</h3><ul className="project-alerts"><li><CalendarDays/>{data.leaveRequests.filter(x=>x.status.startsWith("pending")).length} {t("طلبات إجازة معلقة","pending leave requests")}</li><li><Clock3/>{data.overtime.filter(x=>x.status==="submitted").length} {t("طلبات وقت إضافي","overtime requests")}</li><li><GraduationCap/>{data.certifications.filter(x=>x.status!=="valid").length} {t("شهادات منتهية/قاربت","expiring certificates")}</li></ul></section></div></Shell>;
 if(segment==="workers"&&worker)return <Shell segment="workers" locale={locale}><WorkerDetail worker={worker} data={data}/></Shell>;
 if(segment==="workers")return <Shell segment={segment} locale={locale}><section className="panel"><Workers data={data}/><p className="notice">User ≠ Membership ≠ Worker ≠ Project Resource ≠ Shop-floor Assignee. {t("يجوز وجود عامل بلا حساب ومستخدم بلا عامل.","A worker may exist without login and a user without a worker.")}</p></section></Shell>;
 if(segment==="organization")return <Shell segment={segment} locale={locale}><section className="panel"><Table headers={[t("القسم","Department"),t("الأصل","Parent"),t("العاملون","Workers"),t("الحالة","Status")]}>{data.departments.map(x=><tr key={x.id}><td>{locale==="ar"?x.name:x.nameEn}</td><td>{data.departments.find(p=>p.id===x.parentId)?.name??"—"}</td><td>{data.workers.filter(w=>w.departmentId===x.id&&w.status==="active").length}</td><td>{status(x.active?"active":"inactive")}</td></tr>)}</Table><p className="notice">{t("الهيكل يمنع دورات المدير المباشر ويحفظ تغييرات Effective Date.","Reporting cycles are prohibited and changes are effective-dated.")}</p></section></Shell>;
 if(segment==="positions")return <Shell segment={segment} locale={locale}><section className="panel"><Table headers={[t("الكود","Code"),t("المسمى","Position"),t("القسم","Department"),t("السعة","Capacity"),t("الحالة","Status")]}>{data.positions.map(x=><tr key={x.id}><td>{x.code}</td><td>{locale==="ar"?x.name:x.nameEn}</td><td>{data.departments.find(d=>d.id===x.departmentId)?.name}</td><td>{x.capacity??t("غير متاح","N/A")}</td><td>{status(x.active?"active":"inactive")}</td></tr>)}</Table></section></Shell>;
 if(segment==="locations")return <Shell segment={segment} locale={locale}><section className="panel"><Table headers={[t("الكود","Code"),t("الموقع","Location"),t("المنطقة الزمنية","Timezone"),t("العاملون","Workers"),t("الحالة","Status")]}>{data.locations.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.name}</td><td>{x.timezone}</td><td>{data.workers.filter(w=>w.locationId===x.id).length}</td><td>{status(x.active?"active":"inactive")}</td></tr>)}</Table></section></Shell>;
 if(segment==="shifts")return <Shell segment={segment} locale={locale}><section className="panel"><Table headers={[t("الوردية","Shift"),t("البداية","Start"),t("النهاية","End"),t("الاستراحة","Break"),t("السماح","Grace"),t("عبر منتصف الليل","Cross-midnight")]}>{data.shifts.map(x=><tr key={x.id}><td>{x.name}</td><td>{Math.floor(x.startMinute/60)}:{String(x.startMinute%60).padStart(2,"0")}</td><td>{Math.floor(x.endMinute/60)}:{String(x.endMinute%60).padStart(2,"0")}</td><td>{x.breakMinutes}m</td><td>{x.graceMinutes}m</td><td>{x.crossesMidnight?t("نعم","Yes"):t("لا","No")}</td></tr>)}</Table><p className="notice">UTC timestamps + company/location timezone; Work Date مستقل للوردية العابرة لمنتصف الليل.</p></section></Shell>;
 if(segment==="attendance")return <Shell segment={segment} locale={locale}><section className="panel"><Table headers={[t("التاريخ","Date"),t("العامل","Worker"),t("الدخول","In"),t("الخروج","Out"),t("العمل","Worked"),t("تأخير","Late"),t("ناقص","Missing"),t("الحالة","Status")]}>{data.attendance.map(x=><tr key={x.id}><td>{x.workDate}</td><td>{data.workers.find(w=>w.id===x.workerId)?.displayName}</td><td>{x.firstIn??t("غير متاح","N/A")}</td><td>{x.lastOut??t("غير متاح","N/A")}</td><td>{x.workedMinutes}m</td><td>{x.lateMinutes}m</td><td>{x.missingMinutes}m</td><td>{status(x.status)}</td></tr>)}</Table><p className="notice">Manual/Web/CSV preview فقط؛ لا GPS ولا Biometrics ولا جهاز بصمة فعلي.</p></section></Shell>;
 if(segment==="attendance/corrections")return <Shell segment={segment} locale={locale}>{data.corrections.length?<section className="panel"><Table headers={[t("الحضور","Attendance"),t("السبب","Reason"),t("الطالب","Requester"),t("المعتمد","Approver"),t("الحالة","Status")]}>{data.corrections.map(x=><tr key={x.id}><td>{x.attendanceId}</td><td>{x.reason}</td><td>{x.requestedBy}</td><td>{x.approvedBy??"—"}</td><td>{status(x.status)}</td></tr>)}</Table></section>:<Empty text={t("لا توجد تصحيحات حضور","No attendance corrections")}/>}</Shell>;
 if(segment==="leave")return <Shell segment={segment} locale={locale}><section className="panel"><Table headers={[t("العامل","Worker"),t("النوع","Type"),t("الفترة","Period"),t("الوحدات","Units"),t("الرصيد عند الطلب","Balance snapshot"),t("الحالة","Status")]}>{data.leaveRequests.map(x=><tr key={x.id}><td>{data.workers.find(w=>w.id===x.workerId)?.displayName}</td><td>{data.leaveTypes.find(l=>l.id===x.leaveTypeId)?.name}</td><td>{x.start} — {x.end}</td><td>{Number(x.requestedUnitsMills)/1000}</td><td>{Number(x.balanceSnapshotMills)/1000}</td><td>{status(x.status)}</td></tr>)}</Table>{!data.leaveRequests.length&&<p>{t("لا توجد طلبات؛ أنواع الإجازة سياسات قابلة للإعداد وليست استشارة قانونية.","No requests; leave policies are configurable and not legal advice.")}</p>}</section></Shell>;
 if(segment==="leave/balances")return <Shell segment={segment} locale={locale}><section className="panel"><Table headers={[t("العامل","Worker"),t("نوع الإجازة","Leave type"),t("الرصيد","Balance"),t("الوحدة","Unit")]}>{data.workers.flatMap(w=>data.leaveTypes.filter(l=>l.requiresBalance).map(l=><tr key={`${w.id}-${l.id}`}><td>{w.displayName}</td><td>{l.name}</td><td>{Number(leaveBalance(data.leaveLedger,w.id,l.id))/1000}</td><td>{l.unit}</td></tr>))}</Table><p className="notice">الرصيد مشتق من Ledger غير قابل للتعديل المباشر، مع Reversal واحد لكل حركة.</p></section></Shell>;
 if(segment==="overtime")return <Shell segment={segment} locale={locale}>{data.overtime.length?<section className="panel"><Table headers={[t("العامل","Worker"),t("التاريخ","Date"),t("الدقائق","Minutes"),t("المشروع/الإنتاج","Project/Production"),t("مطابقة الحضور","Attendance match"),t("الحالة","Status")]}>{data.overtime.map(x=><tr key={x.id}><td>{data.workers.find(w=>w.id===x.workerId)?.displayName}</td><td>{x.date}</td><td>{x.minutes}</td><td>{x.projectId??x.productionOrderId??"—"}</td><td>{x.attendanceReconciled?t("نعم","Yes"):t("لا","No")}</td><td>{status(x.status)}</td></tr>)}</Table></section>:<Empty text={t("لا توجد ساعات إضافية معتمدة","No approved overtime")}/>}<p className="notice">لا يحسب مبلغًا أو أجر ساعة؛ دقائق تشغيلية فقط.</p></Shell>;
 if(segment==="workforce")return <Shell segment={segment} locale={locale}><section className="panel"><Table headers={[t("العامل","Worker"),t("المشروع","Project"),"WBS / Task",t("مركز العمل","Work center"),t("الدقائق المخططة","Planned"),t("الشهادات","Certificates"),t("الحالة","Status")]}>{data.assignments.map(x=><tr key={x.id}><td>{data.workers.find(w=>w.id===x.workerId)?.displayName}</td><td>{x.projectId??"—"}</td><td>{x.wbsId??"—"} / {x.taskId??"—"}</td><td>{x.workCenterId??"—"}</td><td>{x.plannedMinutes}</td><td>{x.requiredCertificationTypeIds.join(", ")||"—"}</td><td>{status(x.status)}</td></tr>)}</Table><h3>{t("تسوية الوقت","Time reconciliation")}</h3><Table headers={[t("العامل","Worker"),t("الحضور","Attendance"),"Timesheet","Job Card",t("غير موزع","Unallocated"),t("زيادة توزيع","Overallocated"),t("الحالة","Status")]}>{data.reconciliations.map(x=><tr key={x.id}><td>{data.workers.find(w=>w.id===x.workerId)?.displayName}</td><td>{x.attendanceMinutes}</td><td>{x.timesheetMinutes}</td><td>{x.jobCardMinutes}</td><td>{x.unallocatedMinutes}</td><td>{x.overAllocatedMinutes}</td><td>{status(x.status)}</td></tr>)}</Table><p className="notice">Attendance ≠ Productive Time؛ Job Card المرتبطة بمهمة لا تُحسب مرتين.</p></section></Shell>;
 if(segment==="skills")return <Shell segment={segment} locale={locale}><section className="panel"><Table headers={[t("العامل","Worker"),t("الشهادة","Certification"),t("الإصدار","Issue"),t("الانتهاء","Expiry"),t("التحقق","Verified"),t("الحالة","Status")]}>{data.certifications.map(x=><tr key={x.id}><td>{data.workers.find(w=>w.id===x.workerId)?.displayName}</td><td>{x.typeId}</td><td>{x.issueDate}</td><td>{x.expiryDate}</td><td>{x.verified?t("داخلي","Internal"):t("غير متاح","N/A")}</td><td>{status(x.status)}</td></tr>)}</Table><p className="notice">لا يُدّعى تحقق خارجي؛ Override الشهادة المنتهية يحتاج صلاحية وسببًا وتدقيقًا.</p></section></Shell>;
 if(segment==="training")return <Shell segment={segment} locale={locale}><section className="panel"><Table headers={[t("العامل","Worker"),t("الدورة","Course"),t("الجلسة","Session"),t("النتيجة","Result")]}>{data.training.map(x=><tr key={x.id}><td>{data.workers.find(w=>w.id===x.workerId)?.displayName}</td><td>{x.course}</td><td>{x.sessionDate}</td><td>{status(x.result)}</td></tr>)}</Table></section></Shell>;
 if(segment==="onboarding")return <Shell segment={segment} locale={locale}><section className="panel"><Table headers={[t("العامل","Worker"),t("النوع","Type"),t("المهام","Tasks"),t("المكتمل","Done"),t("الحالة","Status")]}>{data.checklists.map(x=><tr key={x.id}><td>{data.workers.find(w=>w.id===x.workerId)?.displayName}</td><td>{x.kind}</td><td>{x.tasks.length}</td><td>{x.tasks.filter(y=>y.done).length}</td><td>{status(x.status)}</td></tr>)}</Table><p className="notice">مراجعة الوصول مهمة مرجعية فقط؛ لا تعطيل تلقائي للحساب ولا نظام أصول ثابتة.</p></section></Shell>;
 if(segment==="performance")return <Shell segment={segment} locale={locale}><section className="panel"><Table headers={[t("العامل","Worker"),t("الفترة","Period"),t("المراجع","Reviewer"),t("التقييم","Rating"),t("إقرار الموظف","Acknowledgment"),t("الحالة","Status")]}>{data.performance.map(x=><tr key={x.id}><td>{data.workers.find(w=>w.id===x.workerId)?.displayName}</td><td>{x.period}</td><td>{x.reviewerId}</td><td>{x.rating}/5</td><td>{x.acknowledged?t("نعم","Yes"):t("لا","No")}</td><td>{status(x.status)}</td></tr>)}</Table><p className="notice">لا AI scoring ولا ربط آلي بالراتب أو الإنهاء؛ التقييم محمي بالصلاحية.</p></section></Shell>;
 if(segment==="payroll-readiness")return <Shell segment={segment} locale={locale}>{data.payrollBatches.length?<section className="panel"><Table headers={[t("الفترة","Period"),t("العمال","Workers"),t("العوائق","Blockers"),t("النسخة","Snapshot"),"Drift",t("الحالة","Status")]}>{data.payrollBatches.map(x=><tr key={x.id}><td>{x.periodStart} — {x.periodEnd}</td><td>{x.lines.length}</td><td>{readinessBlockers(x.lines)}</td><td>{x.snapshotHash??t("غير مجمدة","Not frozen")}</td><td>{x.drift?t("نعم","Yes"):t("لا","No")}</td><td>{status(x.status)}</td></tr>)}</Table></section>:<Empty text={t("لا توجد فترة جاهزية محفوظة","No payroll readiness batch")}/>}<p className="notice">لا Salary أو Allowances أو Deductions amounts أو Payslip أو GOSI/EOSB/WPS أو Bank File أو دفع أو GL.</p></Shell>;
 if(segment==="reports")return <Shell segment={segment} locale={locale}><section className="panel project-reports"><div className="section-head"><div><small>HTML A4 / UTF-8 CSV</small><h3>{t("تقارير الموارد البشرية","HR reports")}</h3></div><button className="secondary-button" onClick={()=>window.print()}><Printer/>{t("طباعة","Print")}</button></div><div>{["Employee Register","Headcount","Attendance Summary","Attendance Exceptions","Leave Balances","Overtime Hours","Time Reconciliation","Expiring Certifications","Training Matrix","On/Offboarding","Payroll Readiness Exceptions"].map(x=><article key={x}><FileDown/><strong>{x}</strong><small>Filtered · Internal demo</small></article>)}</div><button className="secondary-button" onClick={()=>{const rows=data.workers.map(x=>[x.employeeNumber,x.displayName,x.workerType,x.status].map(safeCsvCell).join(","));const blob=new Blob(["\uFEFF"+["employee_number","display_name","worker_type","status"].map(safeCsvCell).join(",")+"\n"+rows.join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="employee-register-demo.csv";a.click();URL.revokeObjectURL(a.href);}}><FileDown/>CSV</button></section></Shell>;
 return <Shell segment={segment} locale={locale}><Empty text={t("لا توجد بيانات لهذا العرض","No data for this view")}/></Shell>;
}
function Workers({data}:{data:HrData}){return <Table headers={["الرقم","العامل","النوع","User / Membership","القسم","المنصب","الموقع","المدير","الحالة"]}>{data.workers.map(x=><tr key={x.id}><td><Link className="table-link" href={`/dashboard/hr/workers/${x.id}`}>{x.employeeNumber}</Link></td><td>{x.displayName}<small>{x.nameEn}</small></td><td>{x.workerType}</td><td>{x.userId??"No login"}<small>{x.membershipId??"No membership"}</small></td><td>{data.departments.find(d=>d.id===x.departmentId)?.name}</td><td>{data.positions.find(p=>p.id===x.positionId)?.name}</td><td>{data.locations.find(l=>l.id===x.locationId)?.name}</td><td>{data.workers.find(w=>w.id===x.managerId)?.displayName??"—"}</td><td>{status(x.status)}</td></tr>)}</Table>}
function WorkerDetail({worker,data}:{worker:Worker;data:HrData}){const cards=["Summary","Employment","Organization / Assignments","Attendance","Leave & Balances","Overtime","Project / Production Time","Skills / Certifications","Training","Onboarding / Offboarding","Performance","Documents metadata","Timeline / Audit"];return <><section className="panel"><div className="section-head"><div><small>{worker.employeeNumber}</small><h3>{worker.displayName}</h3></div>{status(worker.status)}</div><div className="project-kpis"><Kpi icon={<UserCheck/>} label="Worker type" value={worker.workerType} hint={worker.userId?"Linked login":"No login required"}/><Kpi icon={<Network/>} label="Department" value={data.departments.find(x=>x.id===worker.departmentId)?.name??"N/A"} hint={data.positions.find(x=>x.id===worker.positionId)?.name??"N/A"}/><Kpi icon={<Clock3/>} label="Shift" value={data.shifts.find(x=>x.id===worker.defaultShiftId)?.name??"N/A"} hint={data.locations.find(x=>x.id===worker.locationId)?.timezone??"N/A"}/></div></section><section className="panel project-reports"><div>{cards.map(x=><article key={x}><ShieldCheck/><strong>{x}</strong><small>Permission-scoped source view</small></article>)}</div></section><p className="notice">الهوية وجهة الطوارئ والتقييمات لا تُعاد في القوائم دون صلاحية؛ لا توجد وثائق حقيقية في Seed.</p></>}
