"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState, type ReactNode } from "react";
import { AlertTriangle, Boxes, CheckCircle2, ClipboardList, Download, Factory, PackageCheck, Printer, RefreshCw, Search, ShieldCheck, Truck, Warehouse } from "lucide-react";
import { useLocale } from "./locale-runtime";
import { formatQuantity, multiplyQuantityCost } from "@/lib/inventory/calculations";
import { getInventoryDemoRepository } from "@/lib/inventory/provider";
import { InventoryError } from "@/lib/inventory/repository";
import type { InventoryData, InventoryMovement } from "@/lib/inventory/types";

const org = "org-madar-demo";
const nav = [["", "لوحة المخزون", "Inventory dashboard"], ["items", "الأصناف", "Items"], ["warehouses", "المستودعات", "Warehouses"], ["stock", "الأرصدة", "Stock"], ["movements", "الحركات", "Movements"], ["material-requests", "طلبات المواد", "Material requests"], ["reservations", "الحجوزات", "Reservations"], ["receipts", "الاستلام", "Receipts"], ["issues", "الصرف", "Issues"], ["returns", "المرتجعات", "Returns"], ["transfers", "التحويلات", "Transfers"], ["counts", "الجرد", "Counts"], ["adjustments", "التسويات", "Adjustments"], ["damage", "التالف", "Damage"], ["reorder", "إعادة الطلب", "Reorder"], ["approvals", "الموافقات", "Approvals"], ["reports", "التقارير", "Reports"]] as const;
const labels: Record<string, string> = { active: "نشط", blocked: "محجوب", draft: "مسودة", approved: "معتمد", pending_approval: "بانتظار الاعتماد", posted: "مرحل", dispatched: "في الطريق", received: "مستلم", partially_received: "مستلم جزئيًا", available: "متاح", reserved: "محجوز", quarantine: "حجر", damaged: "تالف", in_transit: "في الطريق", rejected: "مرفوض", quality_hold: "حجز جودة", expired: "منتهي" };
const badge = (value: string) => <span className={`inv-badge ${value}`}>{labels[value] ?? value.replaceAll("_", " ")}</span>;
const money = (minor: bigint, currency = "SAR") => `${new Intl.NumberFormat("en-US", { minimumFractionDigits: 2 }).format(Number(minor) / 100)} ${currency}`;
function Table({ headers, children }: { headers: string[]; children: ReactNode }) { return <div className="inv-table-wrap"><table className="inv-table"><thead><tr>{headers.map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Empty({ text = "لا توجد بيانات مطابقة" }: { text?: string }) { return <div className="inv-empty"><Boxes/><strong>{text}</strong><small>غيّر البحث أو الفلاتر، أو أنشئ مسودة جديدة إذا كانت لديك الصلاحية.</small></div>; }
function Kpi({ icon, label, value, hint }: { icon: ReactNode; label: string; value: string; hint: string }) { return <article className="inv-kpi"><i>{icon}</i><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></article>; }
function safeCsv(value: string) { const escaped = /^[=+\-@]/.test(value) ? `'${value}` : value; return `"${escaped.replaceAll('"', '""')}"`; }
function exportCsv(name: string, rows: string[][]) { const blob = new Blob(["\ufeff" + rows.map(r => r.map(safeCsv).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }), url = URL.createObjectURL(blob), a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }

export function InventoryWorkspace({ segments = [] }: { segments?: string[] }) {
  const locale = useLocale(), router = useRouter(), params = useSearchParams(), repo = getInventoryDemoRepository(), [actorId, setActor] = useState("u-owner"), [, redraw] = useState(0), [message, setMessage] = useState(""), [error, setError] = useState("");
  const t = (ar: string, en: string) => locale === "ar" ? ar : en, bootstrap = repo.snapshot(org, "u-owner"), actor = bootstrap.users.find(x => x.id === actorId)!, access = (() => { try { return { data: repo.snapshot(org, actorId), denied: "" }; } catch (reason) { return { data: bootstrap, denied: reason instanceof Error ? reason.message : "Access denied" }; } })(), data = access.data, balances = (() => { try { return repo.balances(org, actorId); } catch { return []; } })(), can = (p: string) => actor.permissions.includes(p), mode = segments[0] ?? "dashboard", id = segments[1], submode = segments[1] === "new" ? "new" : segments[2], query = params.get("q")?.toLowerCase() ?? "", state = params.get("state");
  const act = (fn: () => unknown, ok: string) => { try { fn(); redraw(x => x + 1); setMessage(ok); setError(""); } catch (reason) { setMessage(""); setError(reason instanceof InventoryError || reason instanceof Error ? reason.message : "Unknown error"); } };
  const setQuery = (value: string) => { const next = new URLSearchParams(params.toString()); if (value) next.set("q", value); else next.delete("q"); router.replace(`?${next}`); };
  const toolbar = <div className="inv-toolbar panel"><div><span className="demo-badge">{t("تشغيل محلي تجريبي — تقييم تشغيلي غير محاسبي", "Local demo — operational, non-accounting valuation")}</span><small>{t("لا GL، لا قيود يومية، لا مدفوعات موردين، لا MRP كامل", "No GL, journal entries, supplier payments, or full MRP")}</small></div><label>{t("اختبار الدور", "Test role")}<select value={actorId} onChange={e => setActor(e.target.value)}>{bootstrap.users.map(x => <option key={x.id} value={x.id}>{x.name} — {x.role}</option>)}</select></label><button className="secondary-button small" onClick={() => router.refresh()}><RefreshCw/> {t("تحديث", "Refresh")}</button></div>;
  const shell = (content: ReactNode) => <div className="inventory-space">{toolbar}<nav className="inv-tabs">{nav.map(([path, ar, en]) => <Link className={(mode === "dashboard" && !path) || mode === path ? "active" : ""} key={path} href={`/dashboard/inventory${path ? `/${path}` : ""}`}>{t(ar, en)}</Link>)}</nav>{message && <div className="form-message success"><CheckCircle2/>{message}</div>}{error && <div className="form-message error"><AlertTriangle/>{error}</div>}{content}</div>;
  if (access.denied) return shell(<div className="inv-state"><ShieldCheck/><strong>{t("لا توجد صلاحية", "Permission denied")}</strong><span>{access.denied}</span></div>);
  if (state === "loading" || state === "error" || state === "conflict" || state === "empty") return shell(state === "empty" ? <Empty/> : <div className={`inv-state ${state}`}><AlertTriangle/><strong>{state === "loading" ? t("جارٍ التحميل…", "Loading…") : state === "conflict" ? t("تعارض إصدار السجل", "Record version conflict") : t("تعذر تحميل البيانات", "Data could not be loaded")}</strong><span>{state === "conflict" ? t("حدّث الصفحة وراجع التعديلات قبل إعادة الحفظ.", "Refresh and review changes before retrying.") : t("حالة اختبار واجهة قابلة للاستعادة.", "Recoverable UI test state.")}</span></div>);
  const totalReserved = balances.reduce((s, x) => s + x.reservedMills, 0n), totalAvailable = balances.reduce((s, x) => s + x.availableMills, 0n), operationalValue = balances.reduce((s, x) => s + multiplyQuantityCost(x.onHandMills, x.averageUnitCostMinor), 0n), reorder = (() => { try { return repo.reorder(org, actorId); } catch { return []; } })();
  if (mode === "dashboard") return shell(<><div className="inv-kpis"><Kpi icon={<Boxes/>} label={t("الأصناف النشطة", "Active items")} value={String(data.items.filter(x => x.status === "active").length)} hint={t("ضمن الشركة الحالية", "Current organization")}/><Kpi icon={<Warehouse/>} label={t("المستودعات", "Warehouses")} value={String(data.warehouses.filter(x => x.status === "active").length)} hint={t("رئيسي وإنتاج وموقع وحجر", "Main, production, site, quarantine")}/><Kpi icon={<PackageCheck/>} label={t("المتاح", "Available")} value={formatQuantity(totalAvailable)} hint={`${t("المحجوز", "Reserved")}: ${formatQuantity(totalReserved)}`}/><Kpi icon={<Factory/>} label={t("القيمة التشغيلية", "Operational value")} value={can("inventory.valuation.view") ? money(operationalValue) : t("محجوبة", "Hidden")} hint={t("ليست قيمة محاسبية معتمدة", "Not approved accounting value")}/></div><div className="inv-grid"><section className="panel"><div className="section-head"><h3>{t("حالة المخزون", "Stock status")}</h3><Link href="/dashboard/inventory/stock">{t("عرض التفاصيل", "View details")}</Link></div><div className="inv-status-grid">{[...new Set(balances.map(x => x.bucket))].map(bucket => <article key={bucket}>{badge(bucket)}<strong>{formatQuantity(balances.filter(x => x.bucket === bucket).reduce((s, x) => s + x.onHandMills, 0n))}</strong></article>)}</div></section><section className="panel"><h3>{t("التنبيهات الحقيقية", "Data-backed alerts")}</h3><ul className="inv-alerts"><li><AlertTriangle/>{reorder.filter(x => x.suggestedMills > 0n).length} {t("أصناف تحتاج إعادة طلب", "items need reorder")}</li><li><Truck/>{data.transfers.filter(x => ["dispatched", "partially_received"].includes(x.status)).length} {t("تحويلات في الطريق", "transfers in transit")}</li><li><ClipboardList/>{data.requests.filter(x => !["posted", "rejected", "cancelled"].includes(x.status)).length} {t("طلبات مواد مفتوحة", "open material requests")}</li><li><PackageCheck/>{data.documents.filter(x => x.kind === "receipt" && x.status !== "posted").length} {t("استلامات شراء غير مرحلة", "unposted procurement receipts")}</li></ul></section></div><section className="panel"><h3>{t("آخر الحركات", "Latest movements")}</h3><MovementTable movements={data.movements.slice(-6).reverse()} data={data} showCosts={can("inventory.costs.view")}/></section></>);
  if (mode === "items" && submode === "new") return shell(<NewItem data={data} onCreate={input => act(() => repo.createItem({ ...input, organizationId: org, actorId, idempotencyKey: crypto.randomUUID() }), t("تم إنشاء مسودة الصنف", "Item draft created"))}/>);
  if (mode === "items" && id && id !== "new") { const item = data.items.find(x => x.id === id); return shell(item ? <div className="inv-grid"><section className="panel inv-detail"><div className="section-head"><div><small>{item.sku}</small><h3>{locale === "en" ? item.nameEn : item.name}</h3></div>{badge(item.status)}</div><dl><dt>{t("الفئة", "Category")}</dt><dd>{data.categories.find(x => x.id === item.categoryId)?.name}</dd><dt>{t("الوحدة", "Base unit")}</dt><dd>{data.units.find(x => x.id === item.baseUnitId)?.code}</dd><dt>{t("التتبع", "Tracking")}</dt><dd>{item.tracking}</dd><dt>{t("العملة", "Currency")}</dt><dd>{item.currency}</dd><dt>{t("الإصدار", "Version")}</dt><dd>v{item.recordVersion}</dd></dl>{can("inventory.items.manage") && item.status === "active" && <button className="danger-button" onClick={() => act(() => repo.transitionItem(org, actorId, item.id, "blocked", item.recordVersion), t("تم حجب الصنف", "Item blocked"))}>{t("حجب الصنف", "Block item")}</button>}</section><section className="panel"><h3>{t("بطاقة المخزون", "Stock card")}</h3><Table headers={[t("المستودع", "Warehouse"), t("الموقع", "Bin"), t("الحالة", "Bucket"), t("الرصيد", "Balance")]}>{balances.filter(x => x.itemId === item.id).map(x => <tr key={`${x.binId}-${x.bucket}`}><td>{data.warehouses.find(w => w.id === x.warehouseId)?.name}</td><td>{data.bins.find(b => b.id === x.binId)?.code}</td><td>{badge(x.bucket)}</td><td>{formatQuantity(x.onHandMills)}</td></tr>)}</Table></section></div> : <Empty text={t("الصنف غير موجود أو خارج الشركة", "Item not found or outside organization")}/>); }
  if (mode === "items") { const rows = data.items.filter(x => !query || `${x.sku} ${x.name} ${x.nameEn}`.toLowerCase().includes(query)); return shell(<><ListTools value={query} setValue={setQuery} canExport={can("inventory.export")} onExport={() => exportCsv("inventory-items.csv", [["SKU", "Name", "Status"], ...rows.map(x => [x.sku, x.name, x.status])])} newHref={can("inventory.items.manage") ? "/dashboard/inventory/items/new" : undefined}/><section className="panel"><Table headers={["SKU", t("الصنف", "Item"), t("الفئة", "Category"), t("الوحدة", "Unit"), t("التتبع", "Tracking"), t("الحالة", "Status")]}>{rows.map(item => <tr key={item.id}><td><Link className="table-link" href={`/dashboard/inventory/items/${item.id}`}>{item.sku}</Link></td><td><strong>{locale === "en" ? item.nameEn : item.name}</strong><small>{item.description}</small></td><td>{data.categories.find(x => x.id === item.categoryId)?.code}</td><td>{data.units.find(x => x.id === item.baseUnitId)?.code}</td><td>{item.tracking}</td><td>{badge(item.status)}</td></tr>)}</Table></section></>); }
  if (mode === "categories" || mode === "units") return shell(<section className="panel"><Table headers={[t("الكود", "Code"), t("الاسم", "Name"), t("الاسم الإنجليزي", "English name"), t("الحالة", "Status")]}>{(mode === "categories" ? data.categories : data.units).map(x => <tr key={x.id}><td>{x.code}</td><td>{x.name}</td><td>{x.nameEn}</td><td>{badge(x.active ? "active" : "blocked")}</td></tr>)}</Table></section>);
  if (mode === "warehouses") return shell(<section className="panel"><Table headers={[t("الكود", "Code"), t("المستودع", "Warehouse"), t("النوع", "Type"), t("المناطق", "Zones"), t("المواقع", "Bins"), t("الحالة", "Status")]}>{data.warehouses.map(w => <tr key={w.id}><td><Link className="table-link" href={`/dashboard/inventory/warehouses/${w.id}`}>{w.code}</Link></td><td>{locale === "en" ? w.nameEn : w.name}</td><td>{w.type}</td><td>{data.zones.filter(x => x.warehouseId === w.id).length}</td><td>{data.bins.filter(x => x.warehouseId === w.id).length}</td><td>{badge(w.status)}</td></tr>)}</Table></section>);
  if (mode === "stock") return shell(<><ListTools value={query} setValue={setQuery} canExport={can("inventory.export")} onExport={() => exportCsv("stock-balance.csv", [["Item", "Warehouse", "Bin", "Bucket", "On hand", "Reserved", "Available"], ...balances.map(x => [x.itemId, x.warehouseId, x.binId, x.bucket, String(x.onHandMills), String(x.reservedMills), String(x.availableMills)])])}/><section className="panel"><Table headers={[t("الصنف", "Item"), t("المستودع / الموقع", "Warehouse / bin"), t("الحالة", "Bucket"), t("الموجود", "On hand"), t("المحجوز", "Reserved"), t("المتاح", "Available"), t("متوسط التكلفة", "Average cost")]}>{balances.filter(x => !query || `${x.itemId} ${x.warehouseId}`.includes(query)).map(x => <tr key={`${x.itemId}-${x.binId}-${x.bucket}`}><td>{data.items.find(i => i.id === x.itemId)?.name}<small>{data.items.find(i => i.id === x.itemId)?.sku}</small></td><td>{data.warehouses.find(w => w.id === x.warehouseId)?.name}<small>{data.bins.find(b => b.id === x.binId)?.code}</small></td><td>{badge(x.bucket)}</td><td>{formatQuantity(x.onHandMills)}</td><td>{formatQuantity(x.reservedMills)}</td><td>{formatQuantity(x.availableMills)}</td><td>{can("inventory.valuation.view") ? money(x.averageUnitCostMinor) : t("محجوب", "Hidden")}</td></tr>)}</Table></section></>);
  if (mode === "movements") return shell(<section className="panel"><MovementTable movements={data.movements} data={data} showCosts={can("inventory.costs.view")}/></section>);
  if (mode === "material-requests") return shell(<><div className="section-head"><h3>{t("طلبات المواد", "Material requests")}</h3>{can("inventory.requests.create") && <Link className="primary-button small" href="/dashboard/inventory/material-requests/new">{t("طلب جديد", "New request")}</Link>}</div>{submode === "new" ? <NewRequest data={data} onCreate={input => act(() => repo.createRequest({ ...input, organizationId: org, actorId, idempotencyKey: crypto.randomUUID() }), t("تم إنشاء طلب المواد كمسودة", "Material request draft created"))}/> : <section className="panel"><Table headers={[t("الرقم", "Number"), t("المشروع", "Project"), t("الغرض", "Purpose"), t("المطلوب", "Requested"), t("المعتمد", "Approved"), t("المخصص", "Allocated"), t("الموعد", "Required"), t("الحالة", "Status")]}>{data.requests.map(r => <tr key={r.id}><td><Link className="table-link" href={`/dashboard/inventory/material-requests/${r.id}`}>{r.number}</Link></td><td>{r.projectId}</td><td>{r.purpose}</td><td>{formatQuantity(r.lines.reduce((s,x)=>s+x.requestedMills,0n))}</td><td>{formatQuantity(r.lines.reduce((s,x)=>s+x.approvedMills,0n))}</td><td>{formatQuantity(r.lines.reduce((s,x)=>s+x.allocatedMills,0n))}</td><td>{r.lines[0]?.requiredDate}</td><td>{badge(r.status)}</td></tr>)}</Table></section>}</>);
  if (mode === "reservations") return shell(<section className="panel"><Table headers={[t("الرقم", "Number"), t("طلب المواد", "Request"), t("المشروع", "Project"), t("الصنف", "Item"), t("الكمية", "Quantity"), t("الانتهاء", "Expires"), t("الحالة", "Status")]}>{data.reservations.map(r => <tr key={r.id}><td>{r.number}</td><td>{r.materialRequestId}</td><td>{r.projectId}</td><td>{data.items.find(x => x.id === r.lines[0]?.itemId)?.sku}</td><td>{formatQuantity(r.lines.reduce((s,x)=>s+x.quantityMills,0n))}</td><td>{r.expiresAt}</td><td>{badge(r.status)}</td></tr>)}</Table></section>);
  if (["receipts", "issues", "returns", "adjustments"].includes(mode)) { const kind = ({ receipts: "receipt", issues: "issue", returns: "return", adjustments: "adjustment" } as const)[mode as "receipts"|"issues"|"returns"|"adjustments"]; const docs = data.documents.filter(x => x.kind === kind); return shell(<section className="panel"><Table headers={[t("الرقم", "Number"), t("المصدر", "Source"), t("السبب", "Reason"), t("البنود", "Lines"), t("الإصدار", "Version"), t("الحالة", "Status")]}>{docs.map(d => <tr key={d.id}><td><Link className="table-link" href={`/dashboard/inventory/${mode}/${d.id}`}>{d.number}</Link></td><td>{d.sourceType}<small>{d.sourceId}</small></td><td>{d.reason}</td><td>{d.lines.length}</td><td>v{d.recordVersion}</td><td>{badge(d.status)}</td></tr>)}</Table>{!docs.length && <Empty/>}<p className="notice"><AlertTriangle/>{mode === "receipts" ? t("استلام المشتريات لا يزيد الرصيد إلا بعد Posting مستقل؛ فاتورة المورد لا تزيد المخزون.", "Procurement receipt increases stock only through separate posting; supplier bills never increase stock.") : t("الحركات المرحلة غير قابلة للتعديل؛ التصحيح عبر Reversal معتمد.", "Posted movements are immutable; correction requires an approved reversal.")}</p></section>); }
  if (mode === "transfers") return shell(<section className="panel"><Table headers={[t("الرقم", "Number"), t("من", "From"), t("إلى", "To"), t("الكمية", "Quantity"), t("المستلم", "Received"), t("الحالة", "Status")]}>{data.transfers.map(x => <tr key={x.id}><td><Link className="table-link" href={`/dashboard/inventory/transfers/${x.id}`}>{x.number}</Link></td><td>{data.warehouses.find(w => w.id === x.fromWarehouseId)?.code}</td><td>{data.warehouses.find(w => w.id === x.toWarehouseId)?.code}</td><td>{formatQuantity(x.lines.reduce((s,l)=>s+l.quantityMills,0n))}</td><td>{formatQuantity(x.lines.reduce((s,l)=>s+l.receivedMills,0n))}</td><td>{badge(x.status)}</td></tr>)}</Table><p className="notice"><Truck/>{t("التحويل يحافظ على Snapshot التكلفة ولا يمثل تكلفة مشروع أو التزام شراء جديدًا.", "Transfers preserve cost snapshots and create neither project cost nor purchase commitment.")}</p></section>);
  if (mode === "counts") return shell(<section className="panel"><Table headers={[t("الرقم", "Number"), t("المستودع", "Warehouse"), t("جرد أعمى", "Blind count"), t("البنود", "Lines"), t("فروق", "Variances"), t("الحالة", "Status")]}>{data.counts.map(c => <tr key={c.id}><td><Link className="table-link" href={`/dashboard/inventory/counts/${c.id}`}>{c.number}</Link></td><td>{data.warehouses.find(w=>w.id===c.warehouseId)?.name}</td><td>{c.blind ? t("نعم", "Yes") : t("لا", "No")}</td><td>{c.lines.length}</td><td>{c.lines.filter(x=>x.varianceMills && x.varianceMills!==0n).length}</td><td>{badge(c.status)}</td></tr>)}</Table></section>);
  if (mode === "damage") return shell(<section className="panel"><Table headers={[t("الرقم", "Number"), t("الصنف", "Item"), t("الكمية", "Quantity"), t("السبب", "Reason"), t("القرار", "Decision"), t("الدليل", "Evidence"), t("الحالة", "Status")]}>{data.damage.map(d => <tr key={d.id}><td>{d.number}</td><td>{data.items.find(x=>x.id===d.itemId)?.sku}</td><td>{formatQuantity(d.quantityMills)}</td><td>{d.reason}</td><td>{d.decision}</td><td>{d.evidence.map(x=>x.name).join(", ")}</td><td>{badge(d.status)}</td></tr>)}</Table><p className="notice"><AlertTriangle/>{t("واجهة Return to Supplier لا تنشئ Credit Note أو حركة مالية تلقائيًا.", "Return-to-supplier interface never creates a credit note or financial movement automatically.")}</p></section>);
  if (mode === "reorder") return shell(<section className="panel"><Table headers={[t("الصنف", "Item"), t("المتاح", "Available"), t("طلبات مفتوحة", "Open requests"), t("شراء مفتوح", "Open PO"), t("مقبول غير مرحل", "Accepted not posted"), t("في الطريق", "In transit"), t("الحد الأدنى", "Minimum"), t("المقترح", "Suggested")]}>{reorder.map(x => <tr key={`${x.itemId}-${x.warehouseId}`}><td>{data.items.find(i=>i.id===x.itemId)?.sku}<small>{x.explanation}</small></td><td>{formatQuantity(x.availableMills)}</td><td>{formatQuantity(x.openRequestMills)}</td><td>{formatQuantity(x.openPurchaseMills)}</td><td>{formatQuantity(x.acceptedNotPostedMills)}</td><td>{formatQuantity(x.inTransitMills)}</td><td>{formatQuantity(x.minimumMills)}</td><td><strong>{formatQuantity(x.suggestedMills)}</strong></td></tr>)}</Table><p className="notice"><AlertTriangle/>{t("التحليل لا ينشئ طلب شراء تلقائيًا؛ زر المسودة يحتاج صلاحية منفصلة ولم يُفعّل كإرسال أو اعتماد.", "Analysis never creates a purchase request automatically; draft creation requires separate permission and does not submit or approve.")}</p></section>);
  if (mode === "approvals") return shell(<section className="panel"><Table headers={[t("النوع", "Type"), t("المرجع", "Reference"), t("مقدم الطلب", "Maker"), t("التعليق", "Comment"), t("الحالة", "Status")]}>{data.approvals.map(x => <tr key={x.id}><td>{x.entityType}</td><td>{x.entityId}</td><td>{x.requestedBy}</td><td>{x.comment ?? "—"}</td><td>{badge(x.status)}</td></tr>)}</Table></section>);
  if (mode === "reports") return shell(<section className="panel inv-reports"><div className="section-head"><div><small>HTML Print A4</small><h3>{t("تقارير وقوالب المخزون", "Inventory reports and forms")}</h3></div><button className="secondary-button" onClick={() => window.print()}><Printer/>{t("طباعة المتصفح", "Browser print")}</button></div><div>{["Item Master Sheet", "Warehouse Master Sheet", "Material Request", "Reservation Sheet", "Goods / Stock Receipt", "Material Issue Voucher", "Material Return Voucher", "Warehouse Transfer", "Count Sheet", "Count Variance Report", "Adjustment Memo", "Damage / Scrap Report", "Stock Card", "Stock Balance Report", "Operational Valuation Report", "Reorder Report", "Project Material Consumption", "Production Material Availability"].map(x => <article key={x}><Printer/><strong>{x}</strong><small>Snapshot · Internal demo watermark</small></article>)}</div><p className="notice">{t("القيمة تشغيلية غير محاسبية. لا توقيع إلكتروني أو ختم أو QR رسمي أو PDF خادمي.", "Operational, non-accounting value. No e-signature, official stamp, QR, or server PDF.")}</p></section>);
  return shell(<Empty text={t("المسار غير موجود ضمن وحدة المخزون", "Inventory route not found")}/>);
}

function MovementTable({ movements, data, showCosts }: { movements: InventoryMovement[]; data: InventoryData; showCosts: boolean }) { return <Table headers={["#", "Type", "Date", "Item", "Warehouse", "Qty", "Bucket", "Source", "Cost"]}>{movements.flatMap(m => m.lines.map((line, i) => <tr key={line.id}><td>{i === 0 ? m.number : "↳"}</td><td>{badge(m.type)}</td><td>{m.occurredAt.slice(0,10)}</td><td>{data.items.find(x=>x.id===line.itemId)?.sku}</td><td>{data.warehouses.find(x=>x.id===line.warehouseId)?.code}</td><td>{line.direction === -1 ? "−" : "+"}{formatQuantity(line.quantityMills)}</td><td>{badge(line.bucket)}</td><td>{m.sourceType}<small>{m.sourceId}</small></td><td>{showCosts ? money(line.unitCostMinorSnapshot, line.currency) : "Hidden"}</td></tr>))}</Table>; }
function ListTools({ value, setValue, canExport, onExport, newHref }: { value: string; setValue: (v: string) => void; canExport: boolean; onExport: () => void; newHref?: string }) { return <div className="inv-list-tools panel"><label><Search/><input value={value} onChange={e=>setValue(e.target.value)} placeholder="بحث / Search"/></label><select defaultValue="all"><option value="all">كل المستودعات / All warehouses</option><option value="MAIN">MAIN</option><option value="PROD">PROD</option></select>{canExport && <button className="secondary-button small" onClick={onExport}><Download/>CSV</button>}{newHref && <Link className="primary-button small" href={newHref}>+ جديد / New</Link>}</div>; }
function NewItem({ data, onCreate }: { data: InventoryData; onCreate: (input: { sku: string; name: string; nameEn: string; categoryId: string; baseUnitId: string; tracking: "none"|"lot"|"serial"; currency: "SAR"|"EGP"|"USD"; description: string }) => void }) { return <section className="panel inv-form"><h3>إنشاء صنف / New item</h3><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onCreate({sku:String(f.get("sku")),name:String(f.get("name")),nameEn:String(f.get("nameEn")),categoryId:String(f.get("category")),baseUnitId:String(f.get("unit")),tracking:String(f.get("tracking")) as "none"|"lot"|"serial",currency:String(f.get("currency")) as "SAR"|"EGP"|"USD",description:String(f.get("description"))});}}><label>SKU<input required name="sku" placeholder="DEMO-ITEM-001"/></label><label>الاسم<input required name="name"/></label><label>English name<input name="nameEn"/></label><label>الفئة<select name="category">{data.categories.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>الوحدة<select name="unit">{data.units.map(x=><option value={x.id} key={x.id}>{x.code} — {x.name}</option>)}</select></label><label>التتبع<select name="tracking"><option value="none">None</option><option value="lot">Lot</option><option value="serial">Serial</option></select></label><label>العملة<select name="currency"><option>SAR</option><option>EGP</option><option>USD</option></select></label><label className="wide">الوصف<textarea name="description"/></label><button className="primary-button">حفظ كمسودة</button></form></section>; }
function NewRequest({ data, onCreate }: { data: InventoryData; onCreate: (input: { projectId: string; purpose: string; itemId: string; requestedMills: bigint; warehouseId: string; requiredDate: string; productionJobId?: string }) => void }) { return <section className="panel inv-form"><h3>طلب مواد جديد / New material request</h3><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),raw=String(f.get("quantity")),[whole,fraction=""]=raw.split(".");onCreate({projectId:"project-1",purpose:String(f.get("purpose")),itemId:String(f.get("item")),requestedMills:BigInt(whole)*1000n+BigInt(fraction.padEnd(3,"0")),warehouseId:String(f.get("warehouse")),requiredDate:String(f.get("requiredDate")),productionJobId:"prod-1"});}}><label>المشروع<select><option value="project-1">PRJ-2026-00001 — Demo</option></select></label><label>الصنف<select name="item">{data.items.filter(x=>x.status==="active").map(x=><option value={x.id} key={x.id}>{x.sku} — {x.name}</option>)}</select></label><label>المستودع<select name="warehouse">{data.warehouses.filter(x=>x.status==="active").map(x=><option value={x.id} key={x.id}>{x.code} — {x.name}</option>)}</select></label><label>الكمية<input required name="quantity" inputMode="decimal" pattern="\d+(\.\d{1,3})?" defaultValue="1.000"/></label><label>التاريخ المطلوب<input required name="requiredDate" type="date" defaultValue="2026-08-20"/></label><label className="wide">الغرض<textarea required name="purpose" defaultValue="طلب مواد إنتاج تجريبي"/></label><button className="primary-button">حفظ كمسودة</button></form></section>; }
