"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState, type ReactNode } from "react";
import { AlertTriangle, BadgeCheck, BarChart3, Boxes, Building2, CheckCircle2, ClipboardList, Download, FileCheck2, FileText, History, PackageCheck, Printer, RefreshCw, Search, ShoppingCart, Truck, WalletCards } from "lucide-react";
import { useLocale } from "@/components/locale-runtime";
import { formatMoney } from "@/lib/procurement/calculations";
import { getProcurementDemoRepository } from "@/lib/procurement/provider";
import { ProcurementError } from "@/lib/procurement/repository";

export type ProcurementMode = "dashboard" | "suppliers" | "supplier-detail" | "supplier-evaluation" | "cost-codes" | "budgets" | "budget-detail" | "budget-revisions" | "requisitions" | "requisition-detail" | "rfqs" | "rfq-detail" | "quotations" | "comparison" | "purchase-orders" | "purchase-order-detail" | "receipts" | "supplier-bills" | "expenses" | "approvals" | "budget-report" | "cost-report" | "profitability" | "forecast" | "cycle-time" | "supplier-performance" | "exceptions" | "print";
const org = "org-madar-demo";
const labels: Record<string, string> = { draft: "مسودة", pending_review: "بانتظار المراجعة", approved: "معتمد", approved_baseline: "خط أساس معتمد", pending_approval: "بانتظار الاعتماد", issued_internal: "صادر داخليًا", partially_received: "مستلم جزئيًا", fully_received: "مستلم بالكامل", converted: "محوّل", awarded: "تمت الترسية", qualified: "مؤهل", matched: "مطابق", within_tolerance: "ضمن السماحية", recognized_operationally: "معترف تشغيليًا", suspended: "موقوف", rejected: "مرفوض", disputed: "متنازع عليه", voided: "ملغى", reversed: "معكوس" };
function status(value: string) { return <span className={`proc-status ${value}`}>{labels[value] ?? value.replaceAll("_", " ")}</span>; }
function download(name: string, text: string) { const blob = new Blob([text], { type: "text/csv;charset=utf-8" }), url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }
function Table({ headers, children }: { headers: string[]; children: ReactNode }) { return <div className="proc-table-wrap"><table className="proc-table"><thead><tr>{headers.map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Empty({ text = "لا توجد سجلات مطابقة للفلاتر الحالية" }: { text?: string }) { return <div className="proc-empty"><Boxes /><strong>{text}</strong><span>جرّب تعديل البحث أو الفلاتر.</span></div>; }

export function ProcurementWorkspace({ mode, id, documentType }: { mode: ProcurementMode; id?: string; documentType?: string }) {
  const locale = useLocale(), router = useRouter(), params = useSearchParams(), repo = getProcurementDemoRepository(), [actorId, setActor] = useState("u-owner"), [, redraw] = useState(0), [message, setMessage] = useState(""), [error, setError] = useState("");
  const bootstrap = repo.snapshot(org, "u-owner"), actor = bootstrap.users.find(x => x.id === actorId)!, access = (() => { try { return { data: repo.snapshot(org, actorId), denied: "" }; } catch (reason) { return { data: bootstrap, denied: reason instanceof Error ? reason.message : "Access denied" }; } })(), data = access.data, can = (permission: string) => actor.permissions.includes(permission), t = (ar: string, en: string) => locale === "ar" ? ar : en;
  const query = params.get("q") ?? "", page = Number(params.get("page") ?? "1"), viewState = params.get("state"), setQuery = (value: string) => { const next = new URLSearchParams(params.toString()); if (value) next.set("q", value); else next.delete("q"); next.set("page", "1"); router.replace(`?${next}`); };
  const act = (fn: () => unknown, ok: string) => { try { fn(); redraw(x => x + 1); setMessage(ok); setError(""); } catch (reason) { setMessage(""); setError(reason instanceof ProcurementError || reason instanceof Error ? reason.message : "Unknown error"); } };
  const toolbar = <div className="proc-toolbar panel"><span className="demo-badge">{t("تشغيل تجريبي داخلي — لا دفع موردين، لا مخزون، لا دفتر أستاذ", "Internal demo — no supplier payment, inventory, or general ledger")}</span><label>{t("اختبار الدور", "Test role")}<select value={actorId} onChange={e => setActor(e.target.value)}>{bootstrap.users.filter(x => x.organizationId === org).map(x => <option key={x.id} value={x.id}>{x.name} — {x.role}</option>)}</select></label><button className="secondary-button small" onClick={() => router.refresh()}><RefreshCw size={15} />{t("تحديث", "Refresh")}</button></div>;
  const feedback = <>{message && <div className="form-message success"><CheckCircle2 />{message}</div>}{error && <div className="form-message error"><AlertTriangle />{error}</div>}</>;
  if (mode === "print") return <PrintView id={id} documentType={documentType} data={data} />;
  if (access.denied) return <>{toolbar}<div className="proc-locked">{t("لا توجد صلاحية للوصول إلى وحدة المشتريات", "You do not have access to procurement")}: {access.denied}</div></>;
  if (viewState === "loading") return <>{toolbar}<div className="proc-state panel"><span className="proc-spinner" />{t("جارٍ تحميل البيانات…", "Loading data…")}</div></>;
  if (viewState === "error") return <>{toolbar}<div className="proc-state panel error"><AlertTriangle />{t("تعذر تحميل البيانات التجريبية. أعد المحاولة.", "Demo data could not be loaded. Try again.")}</div></>;
  const shell = (content: ReactNode) => <>{toolbar}{feedback}{content}</>;
  const suppliers = data.suppliers.filter(x => !query || `${x.code} ${x.legalName} ${x.city}`.toLowerCase().includes(query.toLowerCase()));
  const summary = (() => { try { return repo.costSummary(org, actorId, "project-1", "SAR"); } catch { return null; } })();

  if (mode === "dashboard") return shell(<><div className="proc-kpis"><Kpi icon={<Building2 />} label={t("الموردون المعتمدون", "Approved suppliers")} value={String(data.suppliers.filter(x => x.status === "approved").length)} hint={t("ضمن الشركة الحالية", "Current organization only")} /><Kpi icon={<ClipboardList />} label={t("طلبات الشراء", "Requisitions")} value={String(data.requisitions.length)} hint={t("جميع الحالات", "All statuses")} /><Kpi icon={<ShoppingCart />} label={t("الالتزامات المفتوحة", "Open commitments")} value={summary ? formatMoney(summary.remainingCommitmentMinor, "SAR") : "—"} hint={t("لا تُعد تكلفة فعلية", "Not actual cost")} /><Kpi icon={<WalletCards />} label={t("التكلفة المعترف بها", "Recognized cost")} value={summary ? formatMoney(summary.recognizedMinor - summary.reversedMinor, "SAR") : "—"} hint={t("تشغيلية فقط", "Operational only")} /></div><div className="proc-grid"><section className="panel"><h3>{t("دورة المشتريات", "Procurement cycle")}</h3><div className="proc-flow">{["طلب شراء", "RFQ", "عروض", "مقارنة", "أمر شراء", "استلام", "مطابقة", "تكلفة"].map((x, i) => <span key={x}><b>{i + 1}</b>{x}</span>)}</div></section><section className="panel"><h3>{t("تنبيهات وضوابط", "Controls")}</h3><ul className="proc-checks"><li><BadgeCheck />Maker‑Checker وتدقيق الصلاحيات</li><li><BadgeCheck />2‑Way / 3‑Way Match</li><li><BadgeCheck />العملات منفصلة دون أسعار صرف</li><li><BadgeCheck />لا دفع ولا مخزون ولا قيد محاسبي</li></ul></section></div><section className="panel"><div className="section-head"><h3>{t("أحدث الأحداث", "Latest events")}</h3><Link href="/dashboard/procurement/approvals">{t("مركز الموافقات", "Approvals")}</Link></div>{data.timeline.length ? data.timeline.slice(-6).reverse().map(x => <div className="proc-timeline" key={x.id}><History /><div><strong>{x.action}</strong><span>{x.summary}</span></div><time>{x.createdAt.slice(0, 16).replace("T", " ")}</time></div>) : <Empty text={t("لا توجد أحداث جديدة بعد", "No new events yet")} />}</section></>);
  if (mode === "suppliers") return shell(<><div className="proc-list-tools panel"><label className="proc-search"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder={t("بحث بالاسم أو الكود أو المدينة", "Search name, code, or city")} /></label><select defaultValue={params.get("status") ?? "all"}><option value="all">{t("كل الحالات", "All statuses")}</option><option value="approved">{t("معتمد", "Approved")}</option><option value="pending_review">{t("قيد المراجعة", "Pending review")}</option></select>{can("suppliers.export") && <button className="secondary-button small" onClick={() => download("suppliers.csv", repo.exportSuppliers(org, actorId))}><Download />CSV</button>}</div>{can("suppliers.create") && <QuickSupplier onCreate={input => act(() => repo.createSupplier({ ...input, organizationId: org, actorId }), t("تم إنشاء المورد كمسودة", "Supplier draft created"))} />}{viewState === "empty" || !suppliers.length ? <Empty /> : <section className="panel"><Table headers={[t("الكود", "Code"), t("المورد", "Supplier"), t("التصنيف", "Category"), t("المدينة", "City"), t("الحالة", "Status"), t("الإجراء", "Action")]}>{suppliers.slice((page - 1) * 10, page * 10).map(s => <tr key={s.id}><td>{s.code}</td><td><strong>{s.legalName}</strong><small>{s.email}</small></td><td>{s.categories.join("، ")}</td><td>{s.city}</td><td>{status(s.status)}</td><td><Link className="table-link" href={`/dashboard/procurement/suppliers/${s.id}`}>{t("فتح", "Open")}</Link></td></tr>)}</Table><Pagination page={page} total={suppliers.length} /></section>}</>);
  if (mode === "supplier-detail") { const supplier = data.suppliers.find(x => x.id === id); if (!supplier) return shell(<Empty text={t("المورد غير موجود أو خارج الشركة", "Supplier not found or outside organization")} />); return shell(<div className="proc-grid"><section className="panel proc-detail"><div className="section-head"><div><span>{supplier.code}</span><h3>{supplier.legalName}</h3></div>{status(supplier.status)}</div><dl><dt>{t("الاسم المختصر", "Display name")}</dt><dd>{supplier.displayName}</dd><dt>{t("المدينة", "City")}</dt><dd>{supplier.city}</dd><dt>{t("جهة الاتصال", "Contact")}</dt><dd>{supplier.contactName} — {supplier.phone}</dd><dt>{t("البريد", "Email")}</dt><dd>{supplier.email}</dd><dt>{t("الإصدار", "Record version")}</dt><dd>v{supplier.recordVersion}</dd></dl><div className="proc-actions">{supplier.status === "pending_review" && can("suppliers.approve") && <button className="primary-button small" onClick={() => act(() => repo.transitionSupplier(org, actorId, supplier.id, "approved"), t("تم اعتماد المورد", "Supplier approved"))}>{t("اعتماد", "Approve")}</button>}{supplier.status === "approved" && can("suppliers.suspend") && <button className="danger-button small" onClick={() => act(() => repo.transitionSupplier(org, actorId, supplier.id, "suspended", "إيقاف تجريبي موثق"), t("تم إيقاف المورد", "Supplier suspended"))}>{t("إيقاف", "Suspend")}</button>}<Link className="secondary-button small" href={`/dashboard/procurement/suppliers/${supplier.id}/evaluation`}>{t("التقييم", "Evaluation")}</Link></div></section><section className="panel"><h3>{t("التزام البيانات", "Data controls")}</h3><ul className="proc-checks"><li><BadgeCheck />Duplicate key: {supplier.duplicateKey}</li><li><BadgeCheck />{t("المرفقات Metadata فقط", "Attachments are metadata only")}</li><li><BadgeCheck />{t("لا تحقق حكومي مباشر", "No direct government verification")}</li></ul></section></div>); }
  if (mode === "supplier-evaluation") { const evaluation = data.evaluations.find(x => x.supplierId === id); return shell(evaluation ? <section className="panel"><div className="section-head"><h3>{t("تقييم المورد", "Supplier evaluation")}</h3>{status(evaluation.status)}</div><div className="score-ring">{evaluation.calculatedScore}<small>/100</small></div><div className="score-grid">{[["الجودة", evaluation.quality], ["الالتزام بالموعد", evaluation.delivery], ["دقة الكميات", evaluation.quantityAccuracy], ["سرعة الاستجابة", evaluation.responsiveness], ["التعاون", evaluation.cooperation], ["الالتزام التجاري", evaluation.commercialCompliance]].map(([name, score]) => <div key={String(name)}><span>{name}</span><progress value={Number(score)} max="100" /><b>{score}</b></div>)}</div><p className="notice"><AlertTriangle />{evaluation.formula}. {evaluation.notes}. لا يتم إيقاف المورد تلقائيًا بناءً على التقييم.</p></section> : <Empty text={t("لا يوجد تقييم معتمد لهذه الفترة", "No approved evaluation for this period")} />); }
  if (mode === "cost-codes") return shell(<div className="proc-grid"><section className="panel"><h3>{t("مراكز التكلفة", "Cost centers")}</h3>{data.costCenters.map(x => <div className="proc-row" key={x.id}><span>{x.code}</span><strong>{x.name}</strong>{status(x.active ? "approved" : "suspended")}</div>)}</section><section className="panel"><h3>{t("أكواد التكلفة", "Cost codes")}</h3>{data.costCodes.map(x => <div className="proc-row" key={x.id}><span>{x.code}</span><strong>{x.name}</strong>{status(x.active ? "approved" : "suspended")}</div>)}</section></div>);
  if (mode === "budgets" || mode === "budget-revisions") return shell(<section className="panel"><Table headers={[t("الرقم", "Number"), t("المشروع", "Project"), t("الإصدار", "Revision"), t("العملة", "Currency"), t("القيمة", "Value"), t("الحالة", "Status")]}>{data.budgets.map(b => <tr key={b.id}><td><Link className="table-link" href={`/dashboard/procurement/budgets/${b.id}`}>{b.number}</Link></td><td>{b.projectName}</td><td>R{b.revision}</td><td>{b.currency}</td><td>{can("budgets.view_financials") ? formatMoney(b.totalMinor, b.currency) : t("محجوب", "Hidden")}</td><td>{status(b.status)}</td></tr>)}</Table></section>);
  if (mode === "budget-detail" || mode === "budget-report") { const budget = data.budgets.find(x => x.id === id) ?? data.budgets[0]; return shell(<section className="panel"><div className="section-head"><div><span>{budget.number}</span><h3>{budget.projectName}</h3></div><Link className="secondary-button small" href={`/dashboard/procurement/print/budget/${budget.id}`}><Printer />{t("طباعة", "Print")}</Link></div>{can("budgets.view_financials") ? <><Table headers={[t("الكود", "Code"), t("الوصف", "Description"), t("القيمة", "Amount")]}>{budget.lines.map(line => <tr key={line.id}><td>{data.costCodes.find(x => x.id === line.costCodeId)?.code}</td><td>{line.description}</td><td>{formatMoney(line.amountMinor, budget.currency)}</td></tr>)}</Table><div className="proc-total"><span>{t("إجمالي خط الأساس", "Baseline total")}</span><strong>{formatMoney(budget.totalMinor, budget.currency)}</strong></div></> : <div className="proc-locked">{t("لا تملك صلاحية عرض القيم المالية", "You cannot view financial values")}</div>}</section>); }
  if (mode === "requisitions") return shell(<><QuickRequisition onCreate={input => act(() => repo.createRequisition({ ...input, organizationId: org, actorId }), t("تم إنشاء طلب الشراء", "Requisition created"))} disabled={!can("purchase_requests.create")} /><section className="panel"><Table headers={[t("الرقم", "Number"), t("المشروع", "Project"), t("تاريخ الاحتياج", "Need by"), t("الإجمالي", "Total"), t("الميزانية", "Budget"), t("الحالة", "Status")]}>{data.requisitions.map(r => <tr key={r.id}><td><Link className="table-link" href={`/dashboard/procurement/requisitions/${r.id}`}>{r.number}</Link></td><td>{r.projectId}</td><td>{r.needByDate}</td><td>{formatMoney(r.totals.totalMinor, r.currency)}</td><td>{r.overBudget ? <span className="danger-text">{t("تجاوز", "Over")}</span> : t("ضمن المتاح", "Available")}</td><td>{status(r.status)}</td></tr>)}</Table></section></>);
  if (mode === "requisition-detail") { const row = data.requisitions.find(x => x.id === id); return shell(row ? <DocumentDetail title={row.number} statusNode={status(row.status)} rows={row.lines.map(x => [x.description, `${x.quantityMills} mills`, formatMoney(x.unitPriceMinor, row.currency)])} total={formatMoney(row.totals.totalMinor, row.currency)} notice={t("طلب داخلي مرتبط بالميزانية ولا ينشئ التزامًا قبل أمر الشراء", "Internal request; no commitment before purchase order")} printHref={`/dashboard/procurement/print/requisition/${row.id}`} /> : <Empty />); }
  if (mode === "rfqs" || mode === "rfq-detail") return shell(<section className="panel"><Table headers={[t("الرقم", "Number"), t("طلب الشراء", "Requisition"), t("الموردون", "Suppliers"), t("الإغلاق", "Closing"), t("الحالة", "Status"), t("الإجراء", "Action")]}>{data.rfqs.map(r => <tr key={r.id}><td>{r.number}</td><td>{data.requisitions.find(x => x.id === r.requisitionId)?.number}</td><td>{r.supplierIds.length}</td><td>{r.closingDate}</td><td>{status(r.status)}</td><td><Link className="table-link" href={`/dashboard/procurement/print/rfq/${r.id}`}>{t("معاينة", "Preview")}</Link></td></tr>)}</Table><p className="notice"><AlertTriangle />{t("الإصدار داخلي فقط؛ لم تُرسل RFQ لأي مورد خارجي.", "Internal issue only; no RFQ was sent externally.")}</p></section>);
  if (mode === "quotations") return shell(<section className="panel"><Table headers={[t("المرجع", "Reference"), t("المورد", "Supplier"), t("العملة", "Currency"), t("الإجمالي", "Total"), t("الفني", "Technical"), t("الحالة", "Status")]}>{data.quotations.map(q => <tr key={q.id}><td>{q.number}</td><td>{data.suppliers.find(x => x.id === q.supplierId)?.displayName}</td><td>{q.currency}</td><td>{formatMoney(q.totals.totalMinor, q.currency)}</td><td>{q.technicalScore}/100</td><td>{status(q.status)}</td></tr>)}</Table></section>);
  if (mode === "comparison") return shell(<section className="panel"><div className="section-head"><h3>{t("المقارنة الفنية والمالية", "Technical and commercial comparison")}</h3><Link className="secondary-button small" href={`/dashboard/procurement/print/comparison/${data.comparisons[0]?.id}`}><Printer />{t("طباعة", "Print")}</Link></div><Table headers={[t("المورد", "Supplier"), t("الإجمالي", "Total"), t("التسليم", "Delivery"), t("التقييم الفني", "Technical score"), t("القرار", "Decision")]}>{data.quotations.map(q => <tr key={q.id}><td>{data.suppliers.find(x => x.id === q.supplierId)?.displayName}</td><td>{formatMoney(q.totals.totalMinor, q.currency)}</td><td>{q.deliveryDays} {t("يوم", "days")}</td><td>{q.technicalScore}</td><td>{q.id === data.comparisons[0]?.recommendedQuotationId ? <span className="recommended"><BadgeCheck />{t("موصى به", "Recommended")}</span> : "—"}</td></tr>)}</Table><p className="notice">{data.comparisons[0]?.rationale}</p></section>);
  if (mode === "purchase-orders") return shell(<section className="panel"><Table headers={[t("الرقم", "Number"), t("المورد", "Supplier"), t("المشروع", "Project"), t("الإجمالي", "Total"), t("المستلم", "Received"), t("الحالة", "Status")]}>{data.purchaseOrders.map(po => <tr key={po.id}><td><Link className="table-link" href={`/dashboard/procurement/purchase-orders/${po.id}`}>{po.number}</Link></td><td>{data.suppliers.find(x => x.id === po.supplierId)?.displayName}</td><td>{po.projectId}</td><td>{can("purchase_orders.view_financials") ? formatMoney(po.totals.totalMinor, po.currency) : t("محجوب", "Hidden")}</td><td>{can("purchase_orders.view_financials") ? formatMoney(po.receivedValueMinor, po.currency) : "—"}</td><td>{status(po.status)}</td></tr>)}</Table></section>);
  if (mode === "purchase-order-detail") { const po = data.purchaseOrders.find(x => x.id === id); return shell(po ? <DocumentDetail title={po.number} statusNode={status(po.status)} rows={po.lines.map(x => [x.description, `${x.quantityMills} mills`, formatMoney(x.unitPriceMinor, po.currency)])} total={formatMoney(po.totals.totalMinor, po.currency)} notice={t("أمر شراء داخلي؛ لا يثبت دفعًا ولا ينشئ مخزونًا.", "Internal PO; it proves neither payment nor inventory.")} printHref={`/dashboard/procurement/print/purchase-order/${po.id}`} /> : <Empty />); }
  if (mode === "receipts") return shell(<section className="panel"><Table headers={[t("السند", "Receipt"), t("أمر الشراء", "PO"), t("التاريخ", "Date"), t("القيمة المستلمة", "Received value"), t("الجودة", "Quality"), t("الحالة", "Status")]}>{data.receipts.map(r => <tr key={r.id}><td>{r.number}</td><td>{data.purchaseOrders.find(x => x.id === r.purchaseOrderId)?.number}</td><td>{r.date}</td><td>{formatMoney(r.receivedValueMinor, "SAR")}</td><td>{r.lines.map(x => status(x.qualityStatus))}</td><td>{status(r.status)}</td></tr>)}</Table><p className="notice"><PackageCheck />{t("الاستلام لا ينشئ رصيد مخزون أو حركة مستودع.", "Receiving creates no inventory balance or warehouse movement.")}</p></section>);
  if (mode === "supplier-bills") return shell(<section className="panel"><Table headers={[t("الرقم الداخلي", "Internal no."), t("فاتورة المورد", "Supplier invoice"), t("المورد", "Supplier"), t("المطابقة", "Match"), t("المؤهل", "Eligible"), t("الحالة", "Status")]}>{data.supplierBills.map(b => <tr key={b.id}><td>{b.number}</td><td>{b.supplierInvoiceNumber}</td><td>{data.suppliers.find(x => x.id === b.supplierId)?.displayName}</td><td>{status(b.matchStatus)}</td><td>{formatMoney(b.eligibleRecognitionMinor, b.currency)}</td><td>{status(b.status)}</td></tr>)}</Table><p className="notice"><FileCheck2 />{t("هذه سجلات داخلية وليست قيودًا محاسبية أو دليل سداد.", "These are internal records, not journal entries or payment evidence.")}</p></section>);
  if (mode === "expenses") return shell(<section className="panel"><Table headers={[t("الرقم", "Number"), t("النوع", "Type"), t("الجهة", "Party"), t("المشروع", "Project"), t("الإجمالي", "Total"), t("الحالة", "Status")]}>{data.expenses.map(e => <tr key={e.id}><td>{e.number}</td><td>{e.expenseType}</td><td>{e.party}</td><td>{e.projectId}</td><td>{formatMoney(e.totals.totalMinor, e.currency)}</td><td>{status(e.status)}</td></tr>)}</Table><p className="notice"><AlertTriangle />{t("وسيلة الدفع وصفية فقط؛ لا تحويل أموال أو تعويض موظف أو Petty Cash Ledger.", "Payment method is descriptive only; no money transfer, reimbursement, or petty-cash ledger.")}</p></section>);
  if (mode === "approvals") return shell(<section className="panel">{data.approvals.length ? <Table headers={[t("الكيان", "Entity"), t("المقدم", "Requester"), t("الحالة", "Status"), t("التاريخ", "Date")]}>{data.approvals.map(a => <tr key={a.id}><td>{a.entityType}</td><td>{data.users.find(x => x.id === a.requestedBy)?.name}</td><td>{status(a.status)}</td><td>{a.createdAt.slice(0, 10)}</td></tr>)}</Table> : <Empty text={t("لا توجد موافقات معلقة", "No pending approvals")} />}</section>);
  if (["cost-report", "forecast", "exceptions"].includes(mode)) return shell(summary ? <><div className="proc-kpis"><Kpi icon={<WalletCards />} label={t("الميزانية الحالية", "Current budget")} value={formatMoney(summary.budgetMinor, summary.currency)} hint="Budget" /><Kpi icon={<ShoppingCart />} label={t("الالتزام المفتوح", "Open commitment")} value={formatMoney(summary.remainingCommitmentMinor, summary.currency)} hint="Commitment" /><Kpi icon={<FileCheck2 />} label={t("التكلفة الفعلية التشغيلية", "Operational actual")} value={formatMoney(summary.recognizedMinor - summary.reversedMinor, summary.currency)} hint="Actual" /><Kpi icon={<BarChart3 />} label="Forecast EAC" value={formatMoney(summary.forecastEacMinor, summary.currency)} hint="Forecast" /></div><section className="panel"><Table headers={[t("المقياس", "Metric"), t("النوع", "Kind"), t("القيمة", "Value"), t("المصدر", "Source")]}>{[["Received Not Billed", "Commitment", summary.receivedNotBilledMinor, "Approved receipts − recognized bills"], ["Bills Under Review", "Commitment", summary.billsUnderReviewMinor, "Supplier bills"], ["Remaining Budget", "Budget", summary.remainingBudgetMinor, "Budget − actual − commitments"], ["Forecast ETC", "Forecast", summary.forecastEtcMinor, "Open commitments"], ["Variance", "Forecast", summary.varianceMinor, "Budget − EAC"]].map(([name, kind, value, source]) => <tr key={String(name)}><td>{name}</td><td><span className={`money-kind ${String(kind).toLowerCase()}`}>{kind}</span></td><td>{formatMoney(value as bigint, summary.currency)}</td><td>{source}</td></tr>)}</Table><p className="notice">{t("آخر تحديث: بيانات Seed محلية بتاريخ 7 أغسطس 2026. لا تجمع العملات.", "Last update: local seed data dated 7 Aug 2026. Currencies are never combined.")}</p></section></> : <Empty />);
  if (mode === "profitability") { const view = repo.profitability(org, actorId, "project-1", "SAR"); return shell(<><div className="proc-kpis"><Kpi icon={<FileText />} label={t("قيمة العقد الحالية", "Current contract value")} value={formatMoney(view.currentContractValueMinor, view.currency)} hint="Contractual" /><Kpi icon={<WalletCards />} label={t("الهامش المخطط", "Budgeted margin")} value={formatMoney(view.budgetedGrossMarginMinor, view.currency)} hint="Budget" /><Kpi icon={<BarChart3 />} label={t("الهامش التشغيلي", "Operational margin")} value={formatMoney(view.operationalGrossMarginMinor, view.currency)} hint="Operational" /><Kpi icon={<Truck />} label={t("هامش التوقع", "Forecast margin")} value={formatMoney(view.forecastMarginMinor, view.currency)} hint="Forecast" /></div><section className="panel"><h3>{t("سياق التحصيل", "Collection context")}</h3><p>{t("الفواتير والتحصيلات المستلمة تعرض كسياق فقط، ولا تسمى صافي تدفق نقدي لأن مدفوعات الموردين غير منفذة.", "Invoices and collections are context only, not net cash flow, because supplier payments are not implemented.")}</p>{view.warning && <p className="notice"><AlertTriangle />{view.warning}</p>}</section></>); }
  if (mode === "supplier-performance") return shell(<section className="panel"><Table headers={[t("المورد", "Supplier"), t("الفترة", "Period"), t("المحسوب", "Calculated"), t("اليدوي", "Manual"), t("رفض", "Rejections"), t("تأخير", "Delays"), t("نزاعات", "Disputes")]}>{data.evaluations.map(e => <tr key={e.id}><td>{data.suppliers.find(x => x.id === e.supplierId)?.displayName}</td><td>{e.periodFrom} — {e.periodTo}</td><td>{e.calculatedScore}</td><td>{e.manualScore}</td><td>{e.rejectionCount}</td><td>{e.delayCount}</td><td>{e.disputeCount}</td></tr>)}</Table></section>);
  if (mode === "cycle-time") return shell(<section className="panel"><h3>{t("زمن دورة المشتريات — بيانات Seed", "Procurement cycle time — seed data")}</h3><div className="cycle-bars">{[["طلب → RFQ", 1], ["RFQ → عروض", 4], ["عروض → ترسية", 3], ["ترسية → أمر شراء", 1], ["أمر شراء → استلام", 15]].map(([name, days]) => <div key={String(name)}><span>{name}</span><div style={{ width: `${Number(days) * 6 + 12}%` }} /><b>{days} {t("يوم", "days")}</b></div>)}</div><p className="notice">{t("لا يوصف المؤشر بأنه ذكي؛ الحساب مبني على تواريخ Seed.", "This is not an AI metric; it is calculated from seed dates.")}</p></section>);
  return shell(<Empty />);
}

function Kpi({ icon, label, value, hint }: { icon: ReactNode; label: string; value: string; hint: string }) { return <article className="proc-kpi panel"><i>{icon}</i><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></article>; }
function Pagination({ page, total }: { page: number; total: number }) { const pages = Math.max(1, Math.ceil(total / 10)); return <div className="proc-pagination"><Link aria-disabled={page <= 1} href={`?page=${Math.max(1, page - 1)}`}>‹</Link><span>{page} / {pages}</span><Link aria-disabled={page >= pages} href={`?page=${Math.min(pages, page + 1)}`}>›</Link></div>; }
function QuickSupplier({ onCreate }: { onCreate: (value: { legalName: string; displayName: string; country: string; city: string; categories: string[]; contactName: string; phone: string; email: string }) => void }) { return <details className="panel proc-quick"><summary>{"+ إضافة مورد تجريبي"}</summary><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); onCreate({ legalName: String(f.get("name")), displayName: String(f.get("name")), country: "السعودية", city: String(f.get("city")), categories: ["مواد"], contactName: "جهة اتصال تجريبية", phone: "0500000000", email: String(f.get("email")) }); e.currentTarget.reset(); }}><input name="name" required placeholder="الاسم القانوني" /><input name="city" required placeholder="المدينة" /><input name="email" required type="email" placeholder="demo@example.com" /><button className="primary-button small">حفظ مسودة</button></form></details>; }
function QuickRequisition({ onCreate, disabled }: { disabled: boolean; onCreate: (value: { projectId: string; contractId: string; costCenterId: string; budgetId: string; currency: "SAR"; needByDate: string; justification: string; description: string; quantityMills: bigint; unitPriceMinor: bigint; costCodeId: string; idempotencyKey: string }) => void }) { if (disabled) return null; return <details className="panel proc-quick"><summary>+ طلب شراء تجريبي</summary><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); onCreate({ projectId: "project-1", contractId: "ctr-1", costCenterId: "center-projects", budgetId: "bud-1", currency: "SAR", needByDate: String(f.get("date")), justification: String(f.get("reason")), description: String(f.get("description")), quantityMills: 1000n, unitPriceMinor: BigInt(String(f.get("amount"))), costCodeId: "cc-materials", idempotencyKey: crypto.randomUUID() }); }}><input name="description" required placeholder="الوصف" /><input name="amount" required type="number" min="1" placeholder="القيمة بالهللات" /><input name="date" required type="date" /><input name="reason" required placeholder="مبرر الشراء" /><button className="primary-button small">حفظ مسودة</button></form></details>; }
function DocumentDetail({ title, statusNode, rows, total, notice, printHref }: { title: string; statusNode: ReactNode; rows: string[][]; total: string; notice: string; printHref: string }) { return <section className="panel"><div className="section-head"><div><span>Internal demo document</span><h3>{title}</h3></div><div className="proc-actions">{statusNode}<Link className="secondary-button small" href={printHref}><Printer />طباعة</Link></div></div><Table headers={["الوصف", "الكمية", "سعر الوحدة"]}>{rows.map((r, i) => <tr key={i}>{r.map((x, j) => <td key={j}>{x}</td>)}</tr>)}</Table><div className="proc-total"><span>الإجمالي</span><strong>{total}</strong></div><p className="notice"><AlertTriangle />{notice}</p></section>; }
function PrintView({ id, documentType, data }: { id?: string; documentType?: string; data: ReturnType<ReturnType<typeof getProcurementDemoRepository>["snapshot"]> }) { const labels: Record<string, string> = { requisition: "طلب شراء", rfq: "طلب عرض سعر", comparison: "مقارنة فنية ومالية", "purchase-order": "أمر شراء", receipt: "سند استلام", "supplier-bill": "ملخص فاتورة مورد داخلية", budget: "تقرير ميزانية", cost: "تقرير تكلفة مشروع", profitability: "تقرير ربحية" }; const title = labels[documentType ?? ""] ?? "مستند داخلي", po = data.purchaseOrders.find(x => x.id === id), budget = data.budgets.find(x => x.id === id), number = po?.number ?? budget?.number ?? data.requisitions.find(x => x.id === id)?.number ?? data.rfqs.find(x => x.id === id)?.number ?? data.comparisons.find(x => x.id === id)?.number ?? id ?? "DEMO"; return <article className="proc-print" dir="rtl"><div className="print-watermark">INTERNAL DEMO</div><header><div><strong>مدار CRM</strong><span>بيانات شركة تجريبية</span></div><div><h1>{title}</h1><p>{number}</p></div></header><section><dl><dt>الإصدار</dt><dd>Record Version 1</dd><dt>التاريخ</dt><dd>2026-08-07</dd><dt>الحالة</dt><dd>معاينة داخلية</dd></dl></section><table><thead><tr><th>#</th><th>الوصف</th><th>المرجع</th><th>الحالة</th></tr></thead><tbody><tr><td>1</td><td>{title}</td><td>{number}</td><td>بيانات Seed</td></tr></tbody></table><footer><p>مستند داخلي تجريبي — لا يمثل فاتورة ضريبية أو إثبات دفع أو توقيعًا أو ختمًا رسميًا.</p><button onClick={() => window.print()}><Printer />طباعة المتصفح</button></footer></article>; }
