"use client";
import Link from "next/link";
import { useMemo, type ReactNode } from "react";
import { AlertTriangle, Boxes, CalendarClock, Factory, PackageCheck, Printer, ShieldCheck, TimerReset, Wrench } from "lucide-react";
import { getProductionDemoRepository } from "@/lib/production/provider";
import type { ProductionData } from "@/lib/production/types";

const org="org-madar-demo",actor="u-owner";
const tabs=["products","boms","routings","work-centers","planning","mrp","orders","job-cards","quality","rework","scrap","downtime","subcontracting","completions","capacity","costs","approvals","reports"];
const labels:Record<string,string>={products:"المنتجات والتجميعات",boms:"BOM",routings:"المسارات", "work-centers":"مراكز العمل",planning:"التخطيط",mrp:"MRP",orders:"أوامر الإنتاج","job-cards":"بطاقات التشغيل",quality:"الجودة",rework:"إعادة التشغيل",scrap:"الهالك",downtime:"التوقفات",subcontracting:"التشغيل الخارجي",completions:"الإتمام",capacity:"الطاقة",costs:"التكلفة",approvals:"الموافقات",reports:"التقارير"};
const qty=(x:bigint)=>`${Number(x/1000n).toLocaleString("ar-SA")}.${String(x%1000n).padStart(3,"0")}`;
const badge=(x:string)=><span className={`project-badge ${/blocked|fail|shortage|overdue/.test(x)?"danger":/active|released|completed|pass|posted|available|issued/.test(x)?"success":"warning"}`}>{x.replaceAll("_"," ")}</span>;
function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="project-table-wrap"><table className="project-table"><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Kpi({icon,label,value,hint}:{icon:ReactNode;label:string;value:string;hint:string}){return <article className="project-kpi"><i>{icon}</i><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></article>}
function Shell({segment,children}:{segment:string;children:ReactNode}){return <div className="production-space"><header className="production-hero"><div><small>ERP / MES · Engineer-to-Order</small><h2>إدارة الإنتاج والتصنيع</h2><p>تخطيط تشغيلي محدود، تنفيذ وجودة وتكلفة تشغيلية مرتبطة بالمشروع والمخزون.</p></div><div><strong>Infinite Capacity</strong><small>ليس APS أو MRP II</small></div></header><nav className="project-tabs"><Link href="/dashboard/production">الرئيسية</Link>{tabs.map(x=><Link key={x} className={segment===x?"active":""} href={`/dashboard/production/${x}`}>{labels[x]}</Link>)}</nav>{children}</div>}
function Empty(){return <section className="panel project-empty"><Boxes/><strong>لا توجد سجلات في هذا العرض</strong><span>بيانات Local Mode مصطنعة، ولا توجد عملية خارجية حقيقية.</span></section>}
export function ProductionWorkspace({segments=[]}:{segments?:string[]}){const repo=useMemo(()=>getProductionDemoRepository(),[]),data=repo.snapshot(org,actor),segment=segments[0]??"dashboard",id=segments[1],orders=data.orders,order=id?orders.find(x=>x.id===id):orders[0];
 if(segment==="dashboard")return <Shell segment="dashboard"><div className="project-kpis"><Kpi icon={<Factory/>} label="أوامر نشطة" value={String(orders.filter(x=>["released","in_progress","partially_completed"].includes(x.status)).length)} hint="Released / In progress"/><Kpi icon={<PackageCheck/>} label="جاهزة ماديًا" value={String(orders.filter(x=>["available","reserved","staged","issued"].includes(x.materialReadiness)).length)} hint="من بيانات فعلية"/><Kpi icon={<AlertTriangle/>} label="نقص مواد" value={String(orders.filter(x=>x.materialReadiness==="shortage").length)} hint="لا ينشئ PO تلقائيًا"/><Kpi icon={<ShieldCheck/>} label="Quality Holds" value={String(data.jobCards.filter(x=>x.inspectionStatus==="fail").length)} hint="تمنع الإتمام"/></div><div className="project-grid"><section className="panel"><h3>أوامر الإنتاج الحالية</h3><Orders data={data}/></section><section className="panel"><h3>تنبيهات تشغيلية</h3><ul className="project-alerts"><li><TimerReset/> {data.downtimes.reduce((s,x)=>s+x.minutes,0)} دقيقة توقف</li><li><Wrench/> {data.scrap.reduce((s,x)=>s+x.quantityMills,0n)/1000n} وحدة هالك</li><li><CalendarClock/> {data.subcontract.filter(x=>x.status!=="received").length} عملية خارجية مفتوحة</li></ul></section></div></Shell>;
 if(segment==="products")return <Shell segment={segment}><section className="panel"><Table headers={["الصنف","النوع","Make/Buy","Stocked","Batch","Lead time","الحالة"]}>{data.profiles.map(x=><tr key={x.id}><td>{x.itemId}</td><td>{x.productionType}</td><td>{x.procurementMode}</td><td>{x.stocked?"نعم":"لا"}</td><td>{qty(x.minimumBatchMills)}</td><td>{x.leadTimeDays} يوم</td><td>{badge(x.status)}</td></tr>)}</Table></section></Shell>;
 if(segment==="boms")return <Shell segment={segment}><section className="panel"><Table headers={["الرقم","الصنف الناتج","Rev","الحالة","المكونات","السريان"]}>{data.boms.map(x=><tr key={x.id}><td><Link className="table-link" href={`/dashboard/production/boms/${x.id}`}>{x.number}</Link></td><td>{x.outputItemId}</td><td>{x.revision}</td><td>{badge(x.status)}</td><td>{x.lines.length}</td><td>{x.effectiveFrom}</td></tr>)}</Table><p className="notice">الإصدار Released لا يُعدّل، وأوامر الإنتاج تحفظ Snapshot ثابتة.</p></section></Shell>;
 if(segment==="routings")return <Shell segment={segment}><section className="panel"><Table headers={["الرقم","الصنف","Rev","العملية","Seq","مركز العمل","Quality Gate"]}>{data.routings.flatMap(x=>x.operations.map(op=><tr key={op.id}><td>{x.number}</td><td>{x.itemId}</td><td>{x.revision}</td><td>{op.name}<small>{op.nameEn}</small></td><td>{op.sequence}</td><td>{data.workCenters.find(w=>w.id===op.workCenterId)?.name}</td><td>{op.inspectionRequired?badge("required"):"—"}</td></tr>))}</Table></section></Shell>;
 if(segment==="work-centers")return <Shell segment={segment}><section className="panel"><Table headers={["الكود","المركز","النوع","الوردية","الموارد","الكفاءة","الحالة"]}>{data.workCenters.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.name}<small>{x.nameEn}</small></td><td>{x.type}</td><td>{x.shiftMinutes/60} ساعة</td><td>{x.parallelResources}</td><td>{x.efficiencyBps/100}%</td><td>{badge(x.status)}</td></tr>)}</Table></section></Shell>;
 if(segment==="orders")return <Shell segment={segment}><section className="panel"><Orders data={data}/></section></Shell>;
 if(segment==="job-cards"||(segment==="orders"&&segments[2]==="operations"))return <Shell segment="job-cards"><section className="panel"><Table headers={["البطاقة","الأمر","Seq","المركز","Good","Scrap","Rework","الوقت","الفحص","الحالة"]}>{data.jobCards.map(x=><tr key={x.id}><td>{x.number}</td><td>{orders.find(o=>o.id===x.orderId)?.number}</td><td>{x.operationSequence}</td><td>{data.workCenters.find(w=>w.id===x.workCenterId)?.name}</td><td>{qty(x.goodMills)}</td><td>{qty(x.scrapMills)}</td><td>{qty(x.reworkMills)}</td><td>{x.runMinutes} د</td><td>{badge(x.inspectionStatus)}</td><td>{badge(x.status)}</td></tr>)}</Table></section></Shell>;
 if(segment==="mrp"||segment==="planning")return <Shell segment={segment}>{data.mrpRuns.length?<section className="panel"><Table headers={["التشغيل","الصنف","Gross","Usable","Reserved","Supply","Net","المقترح","Pegging"]}>{data.mrpRuns.flatMap(run=>run.requirements.map(x=><tr key={x.id}><td>{run.number}</td><td>{x.itemId}</td><td>{qty(x.grossMills)}</td><td>{qty(x.onHandUsableMills)}</td><td>{qty(x.reservedMills)}</td><td>{qty(x.openSupplyMills)}</td><td>{qty(x.netMills)}</td><td>{badge(x.suggestion)}</td><td>{x.pegging.projectId}/{x.pegging.wbsId}</td></tr>))}</Table></section>:<Empty/>}<p className="notice">اقتراحات MRP لا تنشئ Purchase Order أو RFQ أو Release تلقائيًا، ولا تعتبر المخزون المتوقع رصيدًا فعليًا.</p></Shell>;
 if(segment==="capacity")return <Shell segment={segment}><section className="panel"><Table headers={["مركز العمل","المطلوب","المتاح المعدل","الحمل","التجاوز","النمط"]}>{data.workCenters.map(x=>{const c=repo.capacity(org,actor,x.id,5);return <tr key={x.id}><td>{x.name}</td><td>{c.requiredMinutes} د</td><td>{c.availableMinutes} د</td><td>{c.loadBps===null?"N/A":`${c.loadBps/100}%`}</td><td>{c.overloadMinutes} د</td><td>{c.planningMode}</td></tr>})}</Table></section></Shell>;
 if(segment==="completions")return <Shell segment={segment}><section className="panel"><Table headers={["الرقم","الأمر","Good","Scrap","Rework","الجودة","Inventory movement","الحالة"]}>{data.completions.map(x=><tr key={x.id}><td>{x.number}</td><td>{orders.find(o=>o.id===x.orderId)?.number}</td><td>{qty(x.goodMills)}</td><td>{qty(x.scrapMills)}</td><td>{qty(x.reworkMills)}</td><td>{badge(x.qualityStatus)}</td><td>{x.inventoryMovementId??"—"}</td><td>{badge(x.status)}</td></tr>)}</Table></section></Shell>;
 if(segment==="downtime")return <Shell segment={segment}><section className="panel"><Table headers={["الرقم","الأمر","المركز","البداية","النهاية","المدة","السبب"]}>{data.downtimes.map(x=><tr key={x.id}><td>{x.number}</td><td>{orders.find(o=>o.id===x.orderId)?.number}</td><td>{data.workCenters.find(w=>w.id===x.workCenterId)?.name}</td><td>{x.startAt}</td><td>{x.endAt}</td><td>{x.minutes} د</td><td>{x.category}</td></tr>)}</Table></section></Shell>;
 if(segment==="scrap"||segment==="rework")return <Shell segment={segment}><section className="panel"><Table headers={["الرقم","الأمر","الكمية","السبب","قابل للاسترداد","الحالة"]}>{data.scrap.map(x=><tr key={x.id}><td>{x.number}</td><td>{orders.find(o=>o.id===x.orderId)?.number}</td><td>{qty(x.quantityMills)}</td><td>{x.reason}</td><td>{x.recoverable?"نعم":"لا"}</td><td>{badge(x.status)}</td></tr>)}</Table></section></Shell>;
 if(segment==="costs")return <Shell segment={segment}><section className="panel"><h3>التكلفة التشغيلية غير المحاسبية</h3>{order&&<Table headers={["الأمر","Planned material","Actual material","Resource","Subcontract","Variance","Cost / good"]}><tr><td>{order.number}</td><td>غير متاح</td><td>من Issue snapshots</td><td>من Work Center rates</td><td>من مصدر شراء مؤهل</td><td>غير متاح</td><td>{order.completedGoodMills>0n?"يحسب عند اكتمال المصادر":"N/A"}</td></tr></Table>}<p className="notice">لا يوجد GL أو Journal Entries أو WIP Accounting أو Standard Cost Accounting، ولا اعتراف مزدوج بالتكلفة.</p></section></Shell>;
 if(segment==="reports")return <Shell segment={segment}><section className="panel project-reports"><div className="section-head"><div><small>HTML Print A4</small><h3>قوالب الإنتاج الداخلية</h3></div><button className="secondary-button" onClick={()=>window.print()}><Printer/>طباعة</button></div><div>{["Product Sheet","BOM Revision","Routing","Production Order","Job Card","MRP Shortage","Kitting Sheet","Quality Inspection","Scrap","Downtime","Completion","Cost Variance","Capacity Load","Genealogy"].map(x=><article key={x}><Printer/><strong>{x}</strong><small>Snapshot · Internal demo</small></article>)}</div></section></Shell>;
 return <Shell segment={segment}><Empty/></Shell>;
}
function Orders({data}:{data:ProductionData}){return <Table headers={["الرقم","المشروع","المنتج","المخطط","Good","المواد","BOM/RT","الموعد","الحالة"]}>{data.orders.map(x=><tr key={x.id}><td><Link className="table-link" href={`/dashboard/production/orders/${x.id}`}>{x.number}</Link></td><td>{x.projectId}<small>{x.wbsId}/{x.taskId}</small></td><td>{x.finishedItemId}</td><td>{qty(x.plannedQuantityMills)}</td><td>{qty(x.completedGoodMills)}</td><td>{badge(x.materialReadiness)}</td><td>R{x.bomRevision}/R{x.routingRevision}</td><td>{x.requiredDate}</td><td>{badge(x.status)}</td></tr>)}</Table>}
