"use client";
import Link from "next/link";
import { useMemo, useState, type ReactNode } from "react";
import { AlertTriangle, BarChart3, CalendarDays, CheckCircle2, ClipboardList, Clock3, Factory, FileQuestion, Flag, Gauge, Layers3, PackageCheck, Printer, ShieldCheck } from "lucide-react";
import { formatMoney } from "@/lib/procurement/calculations";
import { getProjectDemoRepository } from "@/lib/projects/provider";
import { getInventoryDemoRepository } from "@/lib/inventory/provider";
import { formatQuantity } from "@/lib/inventory/calculations";
import { getProductionDemoRepository } from "@/lib/production/provider";

const org = "org-madar-demo", actor = "u-owner";
const sections = ["charter", "team", "wbs", "schedule", "tasks", "resources", "timesheets", "materials", "production", "site", "daily-reports", "rfis", "submittals", "quality", "ncrs", "snags", "risks", "issues", "progress", "handover", "costs", "reports"] as const;
const labels: Record<string, string> = { charter: "ميثاق المشروع", team: "الفريق", wbs: "WBS", schedule: "الجدول الزمني", tasks: "المهام", resources: "الموارد", timesheets: "سجلات الوقت", materials: "المواد", production: "الإنتاج", site: "الموقع", "daily-reports": "التقارير اليومية", rfis: "RFI", submittals: "الاعتمادات", quality: "الجودة", ncrs: "NCR", snags: "الملاحظات", risks: "المخاطر", issues: "المشكلات", progress: "التقدم", handover: "التسليم", costs: "التكاليف", reports: "التقارير" };
const pct = (bps: number) => `${(bps / 100).toFixed(bps % 100 ? 1 : 0)}%`;
const badge = (value: string) => <span className={`project-badge ${/critical|fail|blocked/.test(value) ? "danger" : /approved|completed|pass|active|ready/.test(value) ? "success" : "warning"}`}>{value.replaceAll("_", " ")}</span>;
function Table({ headers, children }: { headers: string[]; children: ReactNode }) { return <div className="project-table-wrap"><table className="project-table"><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Kpi({ icon, label, value, hint }: { icon: ReactNode; label: string; value: string; hint: string }) { return <article className="project-kpi"><i>{icon}</i><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></article>; }
function Empty({ text = "لا توجد بيانات ضمن هذا النطاق" }: { text?: string }) { return <div className="project-empty"><ClipboardList /><strong>{text}</strong><span>جرّب تغيير الفلتر أو أضف سجلًا بصلاحية مناسبة.</span></div>; }

export function ProjectWorkspace({ mode = "list", projectId = "project-1" }: { mode?: string; projectId?: string }) {
  const repo = useMemo(() => getProjectDemoRepository(), []), inventory = useMemo(() => getInventoryDemoRepository(), []), production = useMemo(() => getProductionDemoRepository(), []), [, setRevision] = useState(0), [query, setQuery] = useState("");
  const data = repo.snapshot(org, actor), projects = data.projects.filter(p => !query || `${p.number} ${p.name} ${p.nameEn}`.toLowerCase().includes(query.toLowerCase())), project = data.projects.find(p => p.id === projectId) ?? data.projects[0];
  const metrics = project ? repo.metrics(org, actor, project.id) : null, materialSummary = project ? inventory.projectMaterials(org, actor, project.id) : null, inventoryData = inventory.snapshot(org, actor), tasks = data.tasks.filter(x => x.projectId === project?.id), tab = mode === "overview" ? "overview" : mode;
  if (mode === "list") return <div className="project-space"><div className="project-toolbar"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="بحث برقم أو اسم المشروع" /><select><option>كل الحالات</option><option>نشط</option><option>متوقف</option></select><Link className="primary-button" href="/dashboard/projects/new">+ مشروع من عقد</Link></div><div className="project-kpis"><Kpi icon={<Layers3 />} label="المشاريع النشطة" value={String(projects.filter(x => x.status === "active").length)} hint="حسب الصلاحية"/><Kpi icon={<Flag />} label="المعالم المتأخرة" value={String(data.milestones.filter(x => x.status === "delayed").length)} hint="Forecast مقابل Baseline"/><Kpi icon={<ClipboardList />} label="المهام المحجوبة" value={String(data.tasks.filter(x => x.status === "blocked").length)} hint="تحتاج إجراء"/><Kpi icon={<ShieldCheck />} label="NCR المفتوحة" value={String(data.ncrs.filter(x => x.status !== "closed").length)} hint="ليست شهادة عميل"/></div><section className="panel"><Table headers={["الرقم", "المشروع", "العقد", "المدير", "البداية", "النهاية", "التقدم", "الحالة"]}>{projects.map(p => <tr key={p.id}><td><Link className="table-link" href={`/dashboard/projects/${p.id}`}>{p.number}</Link></td><td><strong>{p.name}</strong><small>{p.nameEn}</small></td><td>{p.contractId}<small>{p.workOrderIds.join(", ")}</small></td><td>{data.users.find(u => u.id === p.managerId)?.name}</td><td>{p.startDate}</td><td>{p.targetEndDate}</td><td>{p.id === project.id && metrics ? pct(metrics.approvedActualProgressBps) : "—"}</td><td>{badge(p.status)}</td></tr>)}</Table></section></div>;
  if (mode === "new") return <section className="panel project-form"><h3>إنشاء مشروع من عقد وأمر عمل مؤهلين</h3><p className="notice"><AlertTriangle/>لن يُنشأ مشروع مكرر للعقد أو أمر العمل نفسه. البيانات التالية داخل Local Mode فقط.</p><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); try { repo.createProject({ organizationId: org, actorId: actor, name: String(f.get("name")), nameEn: String(f.get("nameEn")), customerId: "customer-demo-2", contractId: "ctr-1", workOrderIds: ["wo-1"], currency: "SAR", location: String(f.get("location")), description: String(f.get("description")), managerId: "u-pm", startDate: String(f.get("start")), targetEndDate: String(f.get("end")), idempotencyKey: crypto.randomUUID() }); setRevision(x => x + 1); alert("تم إنشاء مسودة مشروع محلية"); } catch (error) { alert(error instanceof Error ? error.message : "تعذر الإنشاء"); } }}><label>اسم المشروع<input required name="name" placeholder="اسم تجريبي"/></label><label>الاسم الإنجليزي<input name="nameEn" placeholder="Demo project"/></label><label>العقد<select><option>CTR-2026-00001 — SAR</option></select></label><label>أمر العمل<select><option>WO-2026-00001</option></select></label><label>مدير المشروع<select><option>مدير مشروع تجريبي</option></select></label><label>الموقع<input required name="location" placeholder="موقع تجريبي"/></label><label>تاريخ البداية<input required name="start" type="date" defaultValue="2026-08-10"/></label><label>تاريخ النهاية<input required name="end" type="date" defaultValue="2026-09-30"/></label><label className="wide">الوصف<textarea required name="description" defaultValue="مشروع تجريبي منشأ من عقد وأمر عمل مؤهلين."/></label><div className="wide project-actions"><button className="primary-button">حفظ المسودة</button><Link className="secondary-button" href="/dashboard/projects">إلغاء</Link></div></form></section>;
  if (mode === "approvals") { const rows = [...data.charters.filter(x => x.status === "pending_approval").map(x => ["Project Charter", x.id, x.projectId, x.createdBy, x.status]), ...data.baselines.filter(x => x.status === "pending_approval").map(x => ["Baseline", x.number, x.projectId, x.createdBy, x.status]), ...data.timesheets.filter(x => ["submitted", "under_review"].includes(x.status)).map(x => ["Timesheet", x.id, x.projectId, x.userId, x.status]), ...data.progress.filter(x => x.status === "submitted").map(x => ["Progress", x.id, x.projectId, x.taskId, x.status])]; return <section className="panel"><Table headers={["النوع", "المرجع", "المشروع", "مقدم الطلب", "الحالة"]}>{rows.map((row, index) => <tr key={`${row[0]}-${row[1]}-${index}`}>{row.map((value, cell) => <td key={cell}>{cell === 4 ? badge(value) : value}</td>)}</tr>)}</Table>{rows.length === 0 && <Empty text="لا توجد موافقات مشاريع معلقة"/>}<p className="notice">القرارات داخلية وتخضع لـMaker‑Checker؛ لا تمثل اعتماد العميل.</p></section>; }
  if (!project || !metrics) return <Empty text="المشروع غير موجود أو لا تملك صلاحية عرضه"/>;
  const shell = (content: ReactNode) => <div className="project-space"><header className="project-hero"><div><small>{project.number} · {project.contractId} · {project.workOrderIds.join(", ")}</small><h2>{project.name}</h2><p>{project.description}</p></div><div><span>{badge(project.status)}</span><strong>{pct(metrics.approvedActualProgressBps)}</strong><small>Approved actual</small></div></header><nav className="project-tabs"><Link href={`/dashboard/projects/${project.id}`}>نظرة عامة</Link>{sections.map(section => <Link className={tab === section ? "active" : ""} href={`/dashboard/projects/${project.id}/${section}`} key={section}>{labels[section]}</Link>)}</nav>{content}</div>;
  if (tab === "overview") return shell(<><div className="project-kpis"><Kpi icon={<Gauge/>} label="المخطط" value={pct(metrics.plannedProgressBps)} hint="Approved baseline"/><Kpi icon={<CheckCircle2/>} label="الفعلي المعتمد" value={pct(metrics.approvedActualProgressBps)} hint="Internal approval"/><Kpi icon={<FileQuestion/>} label="RFIs المفتوحة" value={String(metrics.openRfis)} hint="Internal / external"/><Kpi icon={<Factory/>} label="جاهزية المشتريات" value={metrics.procurementReadiness} hint="لا يوجد Stock ledger"/></div><div className="project-grid"><section className="panel"><h3>المهام ذات الأولوية</h3><Table headers={["الكود", "المهمة", "المسؤول", "Forecast", "التقدم", "الحالة"]}>{tasks.map(t => <tr key={t.id}><td>{t.code}</td><td>{t.name}</td><td>{data.users.find(u => u.id === t.assigneeId)?.name}</td><td>{t.forecastFinish}</td><td>{pct(t.progressBps)}</td><td>{badge(t.status)}</td></tr>)}</Table></section><section className="panel"><h3>التنبيهات والبوابات</h3><ul className="project-alerts"><li><AlertTriangle/> {metrics.openNcrs} NCR مفتوحة</li><li><ClipboardList/> {metrics.openSnags} Snag مفتوحة</li><li><Clock3/> {metrics.overdueSubmittals} مراجعات متأخرة</li><li><Factory/> {metrics.delayedProductionJobs} أعمال إنتاج متأخرة</li></ul></section></div></>);
  if (tab === "charter") { const c = data.charters.find(x => x.projectId === project.id); return shell(c ? <section className="panel project-charter"><div className="section-head"><div><small>Revision {c.revision}</small><h3>ميثاق المشروع</h3></div>{badge(c.status)}</div><h4>النطاق</h4><p>{c.scope}</p><div className="project-columns"><div><h4>الأهداف</h4><ul>{c.objectives.map(x => <li key={x}>{x}</li>)}</ul><h4>المخرجات</h4><ul>{c.deliverables.map(x => <li key={x}>{x}</li>)}</ul></div><div><h4>معايير القبول الداخلية</h4><ul>{c.acceptanceCriteria.map(x => <li key={x}>{x}</li>)}</ul><h4>الاستثناءات</h4><ul>{c.exclusions.map(x => <li key={x}>{x}</li>)}</ul></div></div><p className="notice">الاعتماد الظاهر داخلي ولا يمثل قبولًا أو توقيعًا من العميل.</p></section> : <Empty/>); }
  if (tab === "team") return shell(<section className="panel"><Table headers={["العضو", "الدور", "الطاقة الأسبوعية", "الصلاحيات"]}>{data.users.filter(x => x.id !== "u-owner").map(u => <tr key={u.id}><td>{u.name}</td><td>{badge(u.role)}</td><td>{u.weeklyCapacityMinutes / 60} ساعة</td><td>{u.permissions.length} صلاحية محددة</td></tr>)}</Table></section>);
  if (tab === "wbs") return shell(<section className="panel"><Table headers={["الكود", "البند", "الوصف", "الوزن", "Cost Code"]}>{data.wbs.filter(x => x.projectId === project.id).map(w => <tr key={w.id}><td>{w.code}</td><td>{w.name}</td><td>{w.description}</td><td>{pct(w.weightBps)}</td><td>{w.costCodeId ?? "—"}</td></tr>)}</Table><p className="notice">مجموع أوزان WBS الفعالة: {pct(data.wbs.filter(x => x.projectId === project.id).reduce((s, x) => s + x.weightBps, 0))}</p></section>);
  if (tab === "schedule") return shell(<><section className="panel"><div className="section-head"><h3>Baseline وForecast</h3>{badge(data.baselines.find(x => x.projectId === project.id)?.status ?? "missing")}</div><div className="gantt" role="img" aria-label="جدول زمني مبسط مبني على تواريخ المهام الحقيقية">{tasks.map((t, i) => <div key={t.id}><span>{t.code} {t.name}</span><i style={{ marginInlineStart: `${i * 12}%`, width: `${Math.max(18, t.durationDays)}%` }}><b style={{ width: pct(t.progressBps) }}/></i><small>{t.plannedStart} ← {t.forecastFinish}</small></div>)}</div></section><section className="panel"><Table headers={["السابق", "اللاحق", "النوع", "Lag"]}>{data.dependencies.map(d => <tr key={d.id}><td>{tasks.find(x => x.id === d.predecessorTaskId)?.code}</td><td>{tasks.find(x => x.id === d.successorTaskId)?.code}</td><td>{d.type}</td><td>{d.lagDays} يوم</td></tr>)}</Table></section></>);
  if (tab === "tasks") return shell(<section className="panel"><Table headers={["الكود", "المهمة", "التخصص", "المسؤول", "الأولوية", "التقدم", "الحالة"]}>{tasks.map(t => <tr key={t.id}><td>{t.code}</td><td>{t.name}{t.blocker && <small>{t.blocker}</small>}</td><td>{t.discipline}</td><td>{data.users.find(x => x.id === t.assigneeId)?.name}</td><td>{badge(t.priority)}</td><td>{pct(t.progressBps)}</td><td>{badge(t.status)}</td></tr>)}</Table></section>);
  if (tab === "resources") return shell(<section className="panel"><Table headers={["المستخدم", "المهمة", "الأسبوع", "المخطط", "الطاقة", "الاستخدام"]}>{data.assignments.map(a => { const c = repo.capacity(org, actor, a.userId, a.weekStart); return <tr key={a.id}><td>{data.users.find(x => x.id === a.userId)?.name}</td><td>{tasks.find(x => x.id === a.taskId)?.name}</td><td>{a.weekStart}</td><td>{a.plannedMinutes / 60} ساعة</td><td>{c.capacityMinutes / 60} ساعة</td><td>{badge(c.overAllocated ? `critical ${pct(c.utilizationBps ?? 0)}` : pct(c.utilizationBps ?? 0))}</td></tr>; })}</Table><p className="notice">التجاوز تحذير تخطيطي؛ لا توجد رواتب أو حضور حيوي.</p></section>);
  if (tab === "timesheets") return shell(<section className="panel"><Table headers={["الفترة", "المستخدم", "الساعات", "المهمة", "الحالة", "Cost snapshot"]}>{data.timesheets.map(s => <tr key={s.id}><td>{s.periodStart} — {s.periodEnd}</td><td>{data.users.find(x => x.id === s.userId)?.name}</td><td>{s.totalMinutes / 60}</td><td>{tasks.find(x => x.id === s.entries[0]?.taskId)?.name}</td><td>{badge(s.status)}</td><td>{s.entries[0]?.laborRateMinorSnapshot ? "محفوظ ومقيد" : "محجوب"}</td></tr>)}</Table><p className="notice">سجل الوقت ليس Payroll ولا ينشئ دفعة موظف. الاعتراف التشغيلي يمنع التكرار.</p></section>);
  if (tab === "materials" && materialSummary) return shell(<><div className="project-kpis"><Kpi icon={<PackageCheck/>} label="المطلوب" value={formatQuantity(materialSummary.requestedMills)} hint="Approved material requirements"/><Kpi icon={<Layers3/>} label="المحجوز" value={formatQuantity(materialSummary.reservedMills)} hint="Active reservations"/><Kpi icon={<Factory/>} label="المستهلك الصافي" value={formatQuantity(materialSummary.netConsumptionMills)} hint="Posted issues − posted returns"/><Kpi icon={<AlertTriangle/>} label="النواقص" value={String(materialSummary.shortages)} hint={materialSummary.readiness}/></div><section className="panel"><Table headers={["الطلب", "الصنف", "WBS", "Task", "Production Job", "المطلوب", "المعتمد", "المخصص", "المصروف", "Required"]}>{inventoryData.requests.filter(x=>x.projectId===project.id).flatMap(r=>r.lines.map(l=><tr key={l.id}><td>{r.number}</td><td>{inventoryData.items.find(i=>i.id===l.itemId)?.sku}</td><td>{l.wbsId ?? "—"}</td><td>{l.taskId ?? "—"}</td><td>{l.productionJobId ?? "—"}</td><td>{formatQuantity(l.requestedMills)}</td><td>{formatQuantity(l.approvedMills)}</td><td>{formatQuantity(l.allocatedMills)}</td><td>{formatQuantity(l.issuedMills)}</td><td>{l.requiredDate}</td></tr>))}</Table><p className="notice">تكلفة المواد التشغيلية: {formatMoney(materialSummary.operationalCostMinor,"SAR")}. لا تعتبر جاهزية الإنتاج مكتملة ما لم تتوفر المواد الإلزامية وتُصرف، إلا عبر Override موثق وصلاحية صريحة.</p></section></>);
  if (tab === "production") { const productionData=production.snapshot(org,actor),orders=productionData.orders.filter(x=>x.projectId===project.id); return shell(<section className="panel"><Table headers={["Production Job", "أمر الإنتاج", "المنتج", "BOM/Route", "Material Readiness", "Good/Planned", "الموعد", "الحالة"]}>{orders.map(o => <tr key={o.id}><td>{o.productionJobId}</td><td><Link className="table-link" href={`/dashboard/production/orders/${o.id}`}>{o.number}</Link></td><td>{o.finishedItemId}</td><td>R{o.bomRevision}/R{o.routingRevision}</td><td>{badge(o.materialReadiness)}</td><td>{formatQuantity(o.completedGoodMills)}/{formatQuantity(o.plannedQuantityMills)}</td><td>{o.requiredDate}</td><td>{badge(o.status)}</td></tr>)}</Table><p className="notice"><PackageCheck/> أوامر الإنتاج مرتبطة بالمشروع وWBS والمهمة وProduction Job؛ النسبة لا تعدل تقدم المشروع تلقائيًا.</p></section>); }
  if (tab === "site" || tab === "daily-reports") return shell(<section className="panel"><Table headers={["التقرير", "التاريخ", "الوردية", "النشاط", "العمالة", "المعدات", "الحالة"]}>{data.dailyReports.map(r => <tr key={r.id}><td>{r.number}</td><td>{r.reportDate}</td><td>{r.shift}</td><td>{r.activities.join("، ")}</td><td>{r.labor.reduce((s, x) => s + x.count, 0)}</td><td>{r.equipment.length}</td><td>{badge(r.status)}</td></tr>)}</Table></section>);
  if (tab === "rfis") return shell(<section className="panel"><Table headers={["الرقم", "الموضوع", "التخصص", "المرجع", "الرد المطلوب", "التصنيف", "الحالة"]}>{data.rfis.map(r => <tr key={r.id}><td>{r.number}</td><td>{r.subject}<small>{r.question}</small></td><td>{r.discipline}</td><td>{r.documentReference}</td><td>{r.responseDueDate}</td><td>{r.classification}</td><td>{badge(r.status)}</td></tr>)}</Table></section>);
  if (tab === "submittals") return shell(<section className="panel"><Table headers={["الرقم", "العنوان", "Rev", "المراجع", "الموعد", "الحالة", "For use"]}>{data.submittals.map(s => <tr key={s.id}><td>{s.number}</td><td>{s.title}</td><td>{s.revision}</td><td>{data.users.find(x => x.id === s.reviewerId)?.name}</td><td>{s.reviewDueDate}</td><td>{badge(s.status)}</td><td>{s.approvedForUseInternal ? "داخلي" : "لا"}</td></tr>)}</Table><p className="notice">Approved Internally لا يعني اعتماد العميل، ولا يوجد إرسال بريد خارجي.</p></section>);
  if (tab === "quality") return shell(<section className="panel"><Table headers={["النوع", "المهمة", "المرجع", "المفتش", "النتيجة", "الإجراء", "الحماية"]}>{data.inspections.map(i => <tr key={i.id}><td>{i.type}</td><td>{tasks.find(x => x.id === i.taskId)?.name}</td><td>{i.specificationReference} / {i.drawingRevision}</td><td>{data.users.find(x => x.id === i.inspectorId)?.name}</td><td>{badge(i.result)}</td><td>{i.requiredAction ?? "—"}</td><td>{i.immutable ? "Immutable" : "Draft"}</td></tr>)}</Table></section>);
  if (tab === "ncrs") return shell(<section className="panel"><Table headers={["الرقم", "الوصف", "المتطلب", "الخطورة", "المسؤول", "الموعد", "الحالة"]}>{data.ncrs.map(n => <tr key={n.id}><td>{n.number}</td><td>{n.description}</td><td>{n.violatedRequirement}</td><td>{badge(n.severity)}</td><td>{data.users.find(x => x.id === n.ownerId)?.name}</td><td>{n.dueDate}</td><td>{badge(n.status)}</td></tr>)}</Table></section>);
  if (tab === "snags") return shell(<section className="panel"><Table headers={["القائمة", "المنطقة", "الوصف", "الأولوية", "المسؤول", "الموعد", "الحالة"]}>{data.snagLists.flatMap(l => l.items.map(i => <tr key={i.id}><td>{l.number}</td><td>{i.area} / {i.location}</td><td>{i.description}</td><td>{badge(i.priority)}</td><td>{data.users.find(x => x.id === i.ownerId)?.name}</td><td>{i.dueDate}</td><td>{badge(i.status)}</td></tr>))}</Table></section>);
  if (tab === "risks") return shell(<section className="panel"><Table headers={["الخطر", "الفئة", "P", "I", "Score", "المعالجة", "Residual", "الحالة"]}>{data.risks.map(r => <tr key={r.id}><td>{r.description}</td><td>{r.category}</td><td>{r.probability}</td><td>{r.impact}</td><td>{r.score}</td><td>{r.mitigation}</td><td>{r.residualScore}</td><td>{badge(r.status)}</td></tr>)}</Table></section>);
  if (tab === "issues") return shell(<section className="panel"><Table headers={["المصدر", "المشكلة", "الأولوية", "الأثر", "المسؤول", "الهدف", "الحالة"]}>{data.issues.map(i => <tr key={i.id}><td>{i.source}</td><td>{i.description}</td><td>{badge(i.priority)}</td><td>{i.impact}</td><td>{data.users.find(x => x.id === i.ownerId)?.name}</td><td>{i.targetResolution}</td><td>{badge(i.status)}</td></tr>)}</Table></section>);
  if (tab === "progress") return shell(<><div className="project-kpis"><Kpi icon={<CalendarDays/>} label="Planned" value={pct(metrics.plannedProgressBps)} hint="Baseline"/><Kpi icon={<Gauge/>} label="Approved Actual" value={pct(metrics.approvedActualProgressBps)} hint="Progress snapshots"/><Kpi icon={<BarChart3/>} label="Schedule Variance" value={pct(metrics.scheduleVarianceBps)} hint="Actual − Planned"/><Kpi icon={<Clock3/>} label="Approved Time" value={`${metrics.approvedMinutes / 60} h`} hint="Not payroll"/></div><section className="panel"><Table headers={["الفترة", "المهمة", "المخطط", "المبلغ", "المعتمد", "الزيادة", "الطريقة", "الحالة"]}>{data.progress.map(p => <tr key={p.id}><td>{p.periodDate}</td><td>{tasks.find(x => x.id === p.taskId)?.code}</td><td>{pct(p.plannedBps)}</td><td>{pct(p.reportedBps)}</td><td>{pct(p.approvedBps)}</td><td>{pct(p.incrementBps)}</td><td>{p.method}</td><td>{badge(p.status)}</td></tr>)}</Table></section></>);
  if (tab === "costs") return shell(<><div className="project-kpis"><Kpi icon={<Layers3/>} label="Budget" value={formatMoney(metrics.budgetMinor, metrics.currency)} hint="Approved current budget"/><Kpi icon={<PackageCheck/>} label="Commitment" value={formatMoney(metrics.commitmentMinor, metrics.currency)} hint="Purchase orders"/><Kpi icon={<CheckCircle2/>} label="Recognized Cost" value={formatMoney(metrics.recognizedCostMinor, metrics.currency)} hint="Phase 7 source"/><Kpi icon={<BarChart3/>} label="EAC" value={formatMoney(metrics.eacMinor, metrics.currency)} hint="Central cost source"/></div><section className="panel"><Table headers={["المؤشر", "القيمة", "الأساس"]}><tr><td>PV</td><td>{formatMoney(metrics.pvMinor, metrics.currency)}</td><td>BAC × Baseline planned</td></tr><tr><td>EV</td><td>{formatMoney(metrics.evMinor, metrics.currency)}</td><td>BAC × Approved actual</td></tr><tr><td>AC</td><td>{formatMoney(metrics.acMinor, metrics.currency)}</td><td>Recognized cost — Phase 7</td></tr><tr><td>SPI</td><td>{metrics.spiBps === null ? "N/A" : (metrics.spiBps / 10000).toFixed(2)}</td><td>EV / PV</td></tr><tr><td>CPI</td><td>{metrics.cpiBps === null ? "N/A" : (metrics.cpiBps / 10000).toFixed(2)}</td><td>EV / AC</td></tr><tr><td>Forecast Margin</td><td>{formatMoney(metrics.forecastMarginMinor, metrics.currency)}</td><td>Contract − EAC</td></tr></Table><p className="notice">لا تُجمع العملات، ولا تنشأ فواتير أو قيود محاسبية من التقدم.</p></section></>);
  if (tab === "handover") { const h = data.handovers.find(x => x.projectId === project.id), gate = repo.closureEligibility(org, actor, project.id); return shell(h ? <><div className="project-kpis"><Kpi icon={<CheckCircle2/>} label="جاهزية التسليم" value={h.readiness} hint="Internal readiness"/><Kpi icon={<ShieldCheck/>} label="بوابة الإغلاق" value={gate.eligible ? "مؤهلة" : "محجوبة"} hint={`${gate.blockers.length} blockers`}/></div><section className="panel"><h3>{h.number} — {h.scope}</h3><Table headers={["البند", "الحالة"]}>{h.checklist.map(i => <tr key={i.label}><td>{i.label}</td><td>{badge(i.complete ? "completed" : "blocked")}</td></tr>)}</Table>{gate.blockers.length > 0 && <ul className="project-blockers">{gate.blockers.map(x => <li key={x}>{x}</li>)}</ul>}<p className="notice">الحزمة داخلية ولا تمثل استلامًا قانونيًا أو ماليًا أو بدء ضمان أو توقيع عميل.</p></section></> : <Empty/>); }
  if (tab === "reports") return shell(<section className="panel project-reports"><div className="section-head"><div><small>HTML Print A4</small><h3>قوالب الطباعة الداخلية</h3></div><button className="secondary-button" onClick={() => window.print()}><Printer/>طباعة الصفحة</button></div><div>{["Project Charter", "Project Summary", "WBS Report", "Baseline Schedule", "Look-ahead Plan", "Task Status", "Daily Report", "Timesheet Summary", "Production Job Card", "RFI", "Submittal Review", "Quality Inspection", "NCR", "Snag List", "Progress Report", "Risk Register", "Handover Checklist", "Closeout Report"].map(x => <article key={x}><Printer/><strong>{x}</strong><small>Snapshot · Internal demo watermark</small></article>)}</div><p className="notice">الطباعة عبر المتصفح فقط؛ لا يوجد زر PDF Server-Side أو توقيع أو ختم أو QR رسمي.</p></section>);
  return shell(<Empty/>);
}
