import { describe, expect, it } from "vitest";
import { LocalProjectRepository, ProjectError, SupabaseProjectRepository } from "./repository";
import { createProjectSeed } from "./seed";

const org = "org-madar-demo";
describe("phase eight project repository", () => {
  it("isolates organization snapshots", () => { const repo = new LocalProjectRepository(); expect(repo.snapshot(org, "u-owner").projects.some(x => x.id === "project-other")).toBe(false); });
  it("denies cross-tenant actor access", () => { const repo = new LocalProjectRepository(); expect(() => repo.snapshot(org, "u-other")).toThrowError(ProjectError); });
  it("hides labor rates from project managers", () => { const repo = new LocalProjectRepository(); expect(repo.snapshot(org, "u-pm").timesheets[0].entries[0].laborRateMinorSnapshot).toBeUndefined(); });
  it("keeps labor rates for authorized cost controller", () => { const repo = new LocalProjectRepository(); expect(repo.snapshot(org, "u-fin").timesheets[0].entries[0].laborRateMinorSnapshot).toBe(7500n); });
  it("prevents a duplicate project for contract or work order", () => { const repo = new LocalProjectRepository(); expect(() => repo.createProject({ organizationId: org, actorId: "u-owner", name: "مشروع مكرر", nameEn: "Duplicate", customerId: "customer-demo-2", contractId: "ctr-1", workOrderIds: ["wo-1"], currency: "SAR", location: "جدة", description: "Duplicate project", managerId: "u-pm", startDate: "2026-08-10", targetEndDate: "2026-09-10", idempotencyKey: "duplicate-project-key" })).toThrowError(/already exists/); });
  it("creates a project only from an eligible source handover", () => { const seed = createProjectSeed(); seed.projects = seed.projects.filter(x => x.id !== "project-1"); seed.idempotencyKeys = seed.idempotencyKeys.filter(x => x !== "seed-project-1"); const repo = new LocalProjectRepository(seed); const row = repo.createProject({ organizationId: org, actorId: "u-owner", name: "مشروع جديد تجريبي", nameEn: "New Demo Project", customerId: "customer-demo-2", contractId: "ctr-1", workOrderIds: ["wo-1"], currency: "SAR", location: "جدة", description: "Eligible source handover", managerId: "u-pm", startDate: "2026-08-10", targetEndDate: "2026-09-10", idempotencyKey: "new-project-key" }); expect(row.status).toBe("draft"); expect(row.number).toBe("PRJ-2026-00002"); });
  it("returns the same record for a repeated idempotent create", () => { const seed = createProjectSeed(); seed.projects = seed.projects.filter(x => x.id !== "project-1"); seed.idempotencyKeys = seed.idempotencyKeys.filter(x => x !== "seed-project-1"); const repo = new LocalProjectRepository(seed), input = { organizationId: org, actorId: "u-owner", name: "مشروع جديد تجريبي", nameEn: "New Demo Project", customerId: "customer-demo-2", contractId: "ctr-1", workOrderIds: ["wo-1"], currency: "SAR", location: "جدة", description: "Eligible source handover", managerId: "u-pm", startDate: "2026-08-10", targetEndDate: "2026-09-10", idempotencyKey: "stable-project-key" }; expect(repo.createProject(input).id).toBe(repo.createProject(input).id); });
  it("enforces optimistic concurrency", () => { const repo = new LocalProjectRepository(); expect(() => repo.transitionProject(org, "u-owner", "project-1", "on_hold", 99, "test")).toThrowError(/version conflict/); });
  it("requires a hold reason", () => { const repo = new LocalProjectRepository(); expect(() => repo.transitionProject(org, "u-owner", "project-1", "on_hold", 4)).toThrowError(/Reason/); });
  it("prevents dependency cycles", () => { const repo = new LocalProjectRepository(); expect(() => repo.addDependency(org, "u-owner", { projectId: "project-1", predecessorTaskId: "task-3", successorTaskId: "task-1", type: "FS", lagDays: 0 })).toThrowError(/cycle/); });
  it("prevents cross-project dependencies", () => { const seed = createProjectSeed(); seed.tasks.push({ ...seed.tasks[0], id: "task-other", organizationId: "org-other-demo", projectId: "project-other" }); const repo = new LocalProjectRepository(seed); expect(() => repo.addDependency(org, "u-owner", { projectId: "project-1", predecessorTaskId: "task-1", successorTaskId: "task-other", type: "FS", lagDays: 0 })).toThrowError(ProjectError); });
  it("detects capacity over-allocation", () => { const repo = new LocalProjectRepository(); expect(repo.capacity(org, "u-owner", "u-site", "2026-08-03").overAllocated).toBe(true); });
  it("blocks closing an unfinished project", () => { const repo = new LocalProjectRepository(); const gate = repo.closureEligibility(org, "u-owner", "project-1"); expect(gate.eligible).toBe(false); expect(gate.blockers).toContain("Approved progress is below 100%"); });
  it("does not close without override when blockers exist", () => { const seed = createProjectSeed(); seed.projects[0].status = "ready_for_handover"; const repo = new LocalProjectRepository(seed); expect(() => repo.closeProject(org, "u-owner", "project-1", 4)).toThrowError(/Critical tasks/); });
  it("records an authorized closure override without claiming client acceptance", () => { const seed = createProjectSeed(); seed.projects[0].status = "ready_for_handover"; const repo = new LocalProjectRepository(seed); const row = repo.closeProject(org, "u-owner", "project-1", 4, "Internal executive override for demo"); expect(row.status).toBe("closed"); expect(row.closureOverride).toContain("Internal"); });
  it("uses the phase-seven financial source for EVM", () => { const repo = new LocalProjectRepository(); const value = repo.metrics(org, "u-owner", "project-1"); expect(value.currency).toBe("SAR"); expect(value.budgetMinor).toBe(20_000_000n); expect(value.pvMinor).toBeGreaterThan(0n); });
  it("shows N/A semantics when a denominator is zero", () => { const repo = new LocalProjectRepository(); const value = repo.metrics(org, "u-owner", "project-1", "2026-06-01"); expect(value.spiBps).toBeNull(); });
  it("makes the Supabase adapter fail honestly", () => expect(() => new SupabaseProjectRepository().snapshot()).toThrowError(/contract stub/));
});
