import type { ProjectData, ProjectRole, ProjectUser } from "./types";

export const PROJECT_PERMISSIONS = [
  "projects.view", "projects.create", "projects.update", "projects.charter.approve", "projects.team.manage", "projects.wbs.manage", "projects.schedule.manage", "projects.baseline.approve", "projects.baseline.revise", "projects.tasks.manage", "projects.tasks.assign", "projects.tasks.update_own", "projects.tasks.approve_completion", "projects.resources.view", "projects.resources.manage", "projects.timesheets.submit", "projects.timesheets.review", "projects.timesheets.approve", "projects.labor_rates.view", "projects.production.manage", "projects.production.release", "projects.site.manage", "projects.daily_reports.approve", "projects.rfis.manage", "projects.submittals.manage", "projects.submittals.review", "projects.quality.manage", "projects.ncr.manage", "projects.ncr.close", "projects.snags.manage", "projects.snags.approve_closure", "projects.risks.manage", "projects.issues.manage", "projects.progress.submit", "projects.progress.approve", "projects.costs.view", "projects.profitability.view", "projects.handover.manage", "projects.closure.approve", "projects.reopen", "projects.export", "projects.print",
] as const;
const read = ["projects.view", "projects.resources.view", "projects.rfis.manage", "projects.submittals.manage", "projects.risks.manage", "projects.issues.manage", "projects.print"];
const operations = PROJECT_PERMISSIONS.filter(x => !["projects.labor_rates.view", "projects.profitability.view", "projects.closure.approve", "projects.reopen"].includes(x));
export const projectPermissionsByRole: Record<ProjectRole, string[]> = {
  owner: [...PROJECT_PERMISSIONS], system_admin: [...PROJECT_PERMISSIONS], operations_manager: [...operations, "projects.profitability.view", "projects.closure.approve", "projects.reopen"], project_manager: [...operations, "projects.costs.view"], planning_engineer: [...read, "projects.wbs.manage", "projects.schedule.manage", "projects.baseline.revise", "projects.progress.submit"], production_manager: [...read, "projects.production.manage", "projects.production.release", "projects.quality.manage"], production_supervisor: [...read, "projects.production.manage", "projects.quality.manage"], site_engineer: [...read, "projects.site.manage", "projects.timesheets.submit", "projects.progress.submit", "projects.snags.manage"], qa_qc: [...read, "projects.quality.manage", "projects.ncr.manage", "projects.ncr.close", "projects.snags.approve_closure"], team_member: ["projects.view", "projects.tasks.update_own", "projects.timesheets.submit", "projects.progress.submit"], finance_cost_controller: ["projects.view", "projects.resources.view", "projects.timesheets.review", "projects.timesheets.approve", "projects.labor_rates.view", "projects.costs.view", "projects.profitability.view", "projects.export", "projects.print"], viewer: read,
};
const org = "org-madar-demo", other = "org-other-demo", createdAt = "2026-08-07T12:00:00.000Z";
const user = (id: string, name: string, role: ProjectRole, weeklyCapacityMinutes = 2400): ProjectUser => ({ id, organizationId: org, name, role, permissions: projectPermissionsByRole[role], weeklyCapacityMinutes });
export function createProjectSeed(): ProjectData {
  const users = [user("u-owner", "مالك تجريبي", "owner"), user("u-pm", "مدير مشروع تجريبي", "project_manager"), user("u-plan", "مخطط تجريبي", "planning_engineer"), user("u-prod", "مسؤول إنتاج تجريبي", "production_manager"), user("u-site", "مهندس موقع تجريبي", "site_engineer"), user("u-qa", "مفتش جودة تجريبي", "qa_qc"), user("u-member", "عضو فريق تجريبي", "team_member"), user("u-fin", "مراقب تكلفة تجريبي", "finance_cost_controller")];
  users.push({ id: "u-other", organizationId: other, name: "مستخدم شركة أخرى", role: "owner", permissions: projectPermissionsByRole.owner, weeklyCapacityMinutes: 2400 });
  return {
    users,
    projects: [
      { id: "project-1", organizationId: org, number: "PRJ-2026-00001", name: "مشروع جناح المعرض التجريبي", nameEn: "Demo Exhibition Booth Project", customerId: "customer-demo-2", contractId: "ctr-1", workOrderIds: ["wo-1"], currency: "SAR", location: "جدة — موقع تجريبي", description: "تصميم وإنتاج وتركيب جناح معرض ببيانات مصطنعة.", managerId: "u-pm", startDate: "2026-07-01", targetEndDate: "2026-09-30", status: "active", recordVersion: 4, idempotencyKey: "seed-project-1", createdBy: "u-owner", approvedBy: "u-owner", createdAt },
      { id: "project-other", organizationId: other, number: "PRJ-OTHER", name: "مشروع شركة أخرى", nameEn: "Other tenant", customerId: "customer-other", contractId: "ctr-other", workOrderIds: ["wo-other"], currency: "SAR", location: "Other", description: "Isolation fixture", managerId: "u-other", startDate: "2026-01-01", targetEndDate: "2026-12-31", status: "active", recordVersion: 1, idempotencyKey: "seed-other", createdBy: "u-other", createdAt },
    ],
    charters: [{ id: "charter-1", organizationId: org, projectId: "project-1", scope: "التصميم والإنتاج والتركيب الداخلي التجريبي", objectives: ["التسليم في الموعد", "اجتياز بوابات الجودة"], deliverables: ["مخططات داخلية", "مكونات مصنعة", "تركيب موثق"], assumptions: ["توفر الموقع حسب الخطة"], constraints: ["موعد افتتاح ثابت"], acceptanceCriteria: ["اكتمال الفحص الداخلي", "إغلاق العناصر الحرجة"], stakeholders: ["العميل التجريبي", "فريق المشروع"], exclusions: ["التوقيع القانوني", "اعتماد العميل الحقيقي"], status: "approved", revision: 1, recordVersion: 2, createdBy: "u-pm", approvedBy: "u-owner", approvedAt: "2026-07-02T10:00:00.000Z" }],
    wbs: [
      { id: "wbs-1", organizationId: org, projectId: "project-1", code: "1", name: "التصميم", description: "حزمة التصميم", weightBps: 2500, sortOrder: 1, active: true },
      { id: "wbs-2", organizationId: org, projectId: "project-1", code: "2", name: "المشتريات والإنتاج", description: "التجهيز والإنتاج", weightBps: 4500, costCodeId: "cc-materials", sortOrder: 2, active: true },
      { id: "wbs-3", organizationId: org, projectId: "project-1", code: "3", name: "التركيب والتسليم", description: "الموقع والإغلاق", weightBps: 3000, sortOrder: 3, active: true },
    ],
    milestones: [{ id: "ms-1", organizationId: org, projectId: "project-1", wbsId: "wbs-1", name: "اعتماد التصميم داخليًا", plannedDate: "2026-07-15", forecastDate: "2026-07-16", actualDate: "2026-07-16", status: "achieved" }, { id: "ms-2", organizationId: org, projectId: "project-1", wbsId: "wbs-3", name: "جاهزية التسليم الداخلي", plannedDate: "2026-09-25", forecastDate: "2026-09-28", status: "planned" }],
    tasks: [
      { id: "task-1", organizationId: org, projectId: "project-1", wbsId: "wbs-1", code: "1.1", name: "إعداد المخططات التنفيذية", discipline: "Design", assigneeId: "u-member", plannedStart: "2026-07-01", plannedFinish: "2026-07-15", forecastFinish: "2026-07-16", actualStart: "2026-07-01", actualFinish: "2026-07-16", durationDays: 15, weightBps: 2500, progressBps: 10000, status: "completed", priority: "high", qualityHold: false, recordVersion: 3, createdBy: "u-pm", completionApprovedBy: "u-pm" },
      { id: "task-2", organizationId: org, projectId: "project-1", wbsId: "wbs-2", code: "2.1", name: "تصنيع الهيكل", discipline: "Production", assigneeId: "u-prod", plannedStart: "2026-07-16", plannedFinish: "2026-08-20", forecastFinish: "2026-08-22", actualStart: "2026-07-17", durationDays: 36, weightBps: 4500, progressBps: 6000, status: "in_progress", priority: "critical", qualityHold: false, recordVersion: 5, createdBy: "u-pm" },
      { id: "task-3", organizationId: org, projectId: "project-1", wbsId: "wbs-3", code: "3.1", name: "التركيب والفحص النهائي", discipline: "Site", assigneeId: "u-site", plannedStart: "2026-08-21", plannedFinish: "2026-09-25", forecastFinish: "2026-09-28", durationDays: 36, weightBps: 3000, progressBps: 0, status: "blocked", priority: "critical", blocker: "انتظار جاهزية الإنتاج", qualityHold: false, recordVersion: 2, createdBy: "u-pm" },
    ],
    dependencies: [{ id: "dep-1", organizationId: org, projectId: "project-1", predecessorTaskId: "task-1", successorTaskId: "task-2", type: "FS", lagDays: 0 }, { id: "dep-2", organizationId: org, projectId: "project-1", predecessorTaskId: "task-2", successorTaskId: "task-3", type: "FS", lagDays: 0 }],
    baselines: [{ id: "base-1", organizationId: org, projectId: "project-1", number: "BL-2026-00001-R1", revision: 1, status: "approved", items: [{ taskId: "task-1", plannedStart: "2026-07-01", plannedFinish: "2026-07-15", durationDays: 15, weightBps: 2500 }, { taskId: "task-2", plannedStart: "2026-07-16", plannedFinish: "2026-08-20", durationDays: 36, weightBps: 4500 }, { taskId: "task-3", plannedStart: "2026-08-21", plannedFinish: "2026-09-25", durationDays: 36, weightBps: 3000 }], snapshot: [{ taskId: "task-1", plannedStart: "2026-07-01", plannedFinish: "2026-07-15", durationDays: 15, weightBps: 2500 }, { taskId: "task-2", plannedStart: "2026-07-16", plannedFinish: "2026-08-20", durationDays: 36, weightBps: 4500 }, { taskId: "task-3", plannedStart: "2026-08-21", plannedFinish: "2026-09-25", durationDays: 36, weightBps: 3000 }], recordVersion: 2, createdBy: "u-plan", approvedBy: "u-owner", approvedAt: "2026-07-03T10:00:00.000Z", reason: "خط الأساس الأول" }],
    assignments: [{ id: "ra-1", organizationId: org, projectId: "project-1", taskId: "task-2", userId: "u-prod", plannedMinutes: 1800, weekStart: "2026-08-03", role: "Production lead" }, { id: "ra-2", organizationId: org, projectId: "project-1", taskId: "task-3", userId: "u-site", plannedMinutes: 2700, weekStart: "2026-08-03", role: "Site lead" }],
    timesheets: [{ id: "ts-1", organizationId: org, projectId: "project-1", userId: "u-prod", periodStart: "2026-08-03", periodEnd: "2026-08-09", entries: [{ id: "te-1", taskId: "task-2", workDate: "2026-08-03", minutes: 480, description: "تجميع الهيكل — تجريبي", billable: false, laborRateMinorSnapshot: 7500n, recognizedCostEventId: "labor-cost-ts-1" }], totalMinutes: 480, status: "approved", recordVersion: 3, submittedAt: "2026-08-04T08:00:00.000Z", approvedBy: "u-fin", approvedAt: "2026-08-04T10:00:00.000Z" }],
    productionJobs: [{ id: "prod-1", organizationId: org, projectId: "project-1", taskId: "task-2", number: "PJ-2026-00001", title: "تصنيع الهيكل الرئيسي", quantityMills: 1000n, unit: "Job", drawingRevision: "Rev.1", requiredMaterials: ["ألواح تشطيب مصطنعة", "قطاعات معدنية مصطنعة"], purchaseRequisitionIds: ["pr-1"], procurementReadiness: "partial", steps: [{ id: "ps-1", name: "القص", sequence: 1, status: "completed", completedBy: "u-prod", completedAt: "2026-08-01T12:00:00.000Z" }, { id: "ps-2", name: "التجميع", sequence: 2, status: "in_progress" }, { id: "ps-3", name: "الفحص", sequence: 3, status: "pending" }], status: "in_production", recordVersion: 4, createdBy: "u-prod", releasedBy: "u-pm" }],
    dailyReports: [{ id: "dr-1", organizationId: org, projectId: "project-1", number: "DR-2026-00001", reportDate: "2026-08-06", shift: "نهاري", weatherText: "بيان يدوي تجريبي", activities: ["تجميع أجزاء الهيكل"], labor: [{ trade: "فني تركيب", count: 4 }], equipment: [{ name: "عدة يدوية", hours: 6 }], delays: [], safetyNotes: ["اجتماع توجيهي داخلي"], attachments: [], status: "approved", createdBy: "u-site", approvedBy: "u-pm" }],
    rfis: [{ id: "rfi-1", organizationId: org, projectId: "project-1", number: "RFI-2026-00001", subject: "تفصيلة اتصال داخلية", question: "تأكيد تفصيلة الاتصال حسب Rev.1", discipline: "Design", documentReference: "DEMO-DWG-001", priority: "High", responseDueDate: "2026-08-10", responsibleParty: "فريق التصميم الداخلي", classification: "internal", impact: true, taskId: "task-2", status: "open" }],
    submittals: [{ id: "sub-1", organizationId: org, projectId: "project-1", number: "SUB-2026-00001", type: "Drawing", title: "Shop Drawing داخلي", discipline: "Production", documentReference: "DEMO-SD-001", revision: "Rev.1", submittedBy: "u-prod", submittedDate: "2026-08-02", reviewDueDate: "2026-08-08", reviewerId: "u-pm", comments: "مراجعة داخلية فقط", status: "under_review", approvedForUseInternal: false }],
    inspections: [{ id: "ins-1", organizationId: org, projectId: "project-1", taskId: "task-2", productionJobId: "prod-1", type: "In-process", checklist: [{ item: "الأبعاد", passed: true, note: "ضمن التفاوت الداخلي" }], specificationReference: "DEMO-SPEC-01", drawingRevision: "Rev.1", inspectorId: "u-qa", inspectionDate: "2026-08-05", result: "pass_with_comments", observations: "استكمال تنظيف نقاط اللحام", evidence: ["metadata://demo/inspection-1"], requiredAction: "تنظيف قبل الطلاء", immutable: true, approvedBy: "u-pm" }],
    ncrs: [{ id: "ncr-1", organizationId: org, projectId: "project-1", number: "NCR-2026-00001", source: "Inspection", location: "منطقة إنتاج تجريبية", discipline: "Production", description: "انحراف تجريبي قابل للإصلاح", violatedRequirement: "DEMO-SPEC-01", classification: "Internal", severity: "minor", rootCause: "إعداد غير مكتمل", containmentAction: "إيقاف الجزء المتأثر", correctiveAction: "إعادة الضبط", preventiveAction: "فحص أول قطعة", ownerId: "u-prod", dueDate: "2026-08-12", evidence: [], status: "under_correction" }],
    snagLists: [{ id: "snl-1", organizationId: org, projectId: "project-1", number: "SNAG-2026-00001", title: "قائمة ملاحظات داخلية", items: [{ id: "sni-1", area: "الواجهة", location: "زاوية تجريبية", discipline: "Finishes", description: "استكمال تشطيب", priority: "medium", ownerId: "u-site", dueDate: "2026-09-20", status: "open", beforeEvidence: [], afterEvidence: [] }], status: "open" }],
    risks: [{ id: "risk-1", organizationId: org, projectId: "project-1", description: "تأخر توريد مادة تجريبية", probability: 4, impact: 4, category: "Procurement", score: 16, ownerId: "u-pm", trigger: "تجاوز موعد الاحتياج", mitigation: "متابعة readiness", contingency: "بديل داخلي معتمد", dueDate: "2026-08-15", residualScore: 8, status: "monitoring" }],
    issues: [{ id: "issue-1", organizationId: org, projectId: "project-1", source: "Production", description: "تعارض مؤقت في تسلسل التصنيع", priority: "High", impact: "يومان محتملان", ownerId: "u-prod", targetResolution: "2026-08-11", decision: "إعادة ترتيب الخطوات", actions: ["تحديث look-ahead"], status: "in_progress", links: { productionJobId: "prod-1", taskId: "task-2" } }],
    progress: [{ id: "pm-1", organizationId: org, projectId: "project-1", taskId: "task-1", periodDate: "2026-07-31", plannedBps: 10000, reportedBps: 10000, approvedBps: 10000, previousApprovedBps: 0, incrementBps: 10000, method: "milestone", source: "Approved internal task completion", status: "approved", reviewerId: "u-pm", approvedAt: "2026-08-01T09:00:00.000Z", snapshot: { taskCode: "1.1", progressBps: 10000 } }, { id: "pm-2", organizationId: org, projectId: "project-1", taskId: "task-2", periodDate: "2026-08-07", plannedBps: 6500, reportedBps: 6000, approvedBps: 6000, previousApprovedBps: 0, incrementBps: 6000, method: "quantity", source: "Production checklist quantities", status: "approved", reviewerId: "u-pm", approvedAt: createdAt, snapshot: { taskCode: "2.1", progressBps: 6000 } }],
    handovers: [{ id: "ho-1", organizationId: org, projectId: "project-1", number: "HO-2026-00001", scope: "حزمة تسليم داخلية تجريبية", contractualDeliverables: ["نطاق العقد التجريبي"], technicalDeliverables: ["المخططات الداخلية"], drawings: ["DEMO-SD-001 Rev.1"], internalApprovals: ["Charter Rev.1"], inspectionIds: ["ins-1"], omManualMetadata: ["O&M metadata placeholder"], trainingReferences: [], warrantyMetadata: ["Warranty metadata placeholder"], clientCommentsInternal: [], readiness: "not_ready", conditionalHandover: false, finalHandover: false, checklist: [{ label: "إغلاق NCRs الحرجة", complete: true }, { label: "اكتمال التقدم المعتمد", complete: false }], lessonsLearned: [], status: "draft" }],
    timeline: [], notifications: [], idempotencyKeys: ["seed-project-1", "seed-other"], sequences: { [`${org}:project`]: 1 },
  };
}
