import type { CurrencyCode } from "@/lib/sales/types";

export type ProjectRole = "owner" | "system_admin" | "operations_manager" | "project_manager" | "planning_engineer" | "production_manager" | "production_supervisor" | "site_engineer" | "qa_qc" | "team_member" | "finance_cost_controller" | "viewer";
export type ProjectStatus = "draft" | "pending_approval" | "approved" | "active" | "on_hold" | "ready_for_handover" | "closed" | "cancelled" | "reopened";
export type TaskStatus = "not_started" | "ready" | "in_progress" | "blocked" | "ready_for_review" | "completed" | "cancelled" | "reopened";
export type BaselineStatus = "draft" | "pending_approval" | "approved" | "rejected" | "superseded";
export type TimesheetStatus = "draft" | "submitted" | "under_review" | "approved" | "rejected" | "returned" | "corrected";
export type ProductionStatus = "planned" | "released" | "in_production" | "quality_hold" | "ready_for_site" | "installed" | "completed" | "cancelled";
export type InspectionResult = "pass" | "pass_with_comments" | "hold" | "fail" | "not_applicable";
export type NcrStatus = "draft" | "open" | "action_proposed" | "action_approved" | "under_correction" | "ready_for_verification" | "closed" | "rejected" | "reopened" | "cancelled";
export type SnagStatus = "open" | "in_progress" | "ready_for_review" | "closed" | "reopened" | "cancelled";
export type DependencyType = "FS" | "SS" | "FF" | "SF";

export interface ProjectUser { id: string; organizationId: string; name: string; role: ProjectRole; permissions: string[]; weeklyCapacityMinutes: number }
export interface Project { id: string; organizationId: string; number: string; name: string; nameEn: string; customerId: string; contractId: string; workOrderIds: string[]; currency: CurrencyCode; location: string; description: string; managerId: string; startDate: string; targetEndDate: string; status: ProjectStatus; recordVersion: number; idempotencyKey: string; createdBy: string; approvedBy?: string; createdAt: string; closedAt?: string; closureOverride?: string }
export interface ProjectCharter { id: string; organizationId: string; projectId: string; scope: string; objectives: string[]; deliverables: string[]; assumptions: string[]; constraints: string[]; acceptanceCriteria: string[]; stakeholders: string[]; exclusions: string[]; status: "draft" | "pending_approval" | "approved" | "rejected"; revision: number; recordVersion: number; createdBy: string; approvedBy?: string; approvedAt?: string }
export interface WbsItem { id: string; organizationId: string; projectId: string; parentId?: string; code: string; name: string; description: string; weightBps: number; costCodeId?: string; sortOrder: number; active: boolean }
export interface ProjectMilestone { id: string; organizationId: string; projectId: string; wbsId: string; name: string; plannedDate: string; forecastDate: string; actualDate?: string; status: "planned" | "achieved" | "delayed" }
export interface ProjectTask { id: string; organizationId: string; projectId: string; wbsId: string; code: string; name: string; discipline: string; assigneeId: string; plannedStart: string; plannedFinish: string; forecastFinish: string; actualStart?: string; actualFinish?: string; durationDays: number; weightBps: number; progressBps: number; status: TaskStatus; priority: "low" | "medium" | "high" | "critical"; blocker?: string; qualityHold: boolean; recordVersion: number; createdBy: string; completionApprovedBy?: string }
export interface TaskDependency { id: string; organizationId: string; projectId: string; predecessorTaskId: string; successorTaskId: string; type: DependencyType; lagDays: number }
export interface BaselineItem { taskId: string; plannedStart: string; plannedFinish: string; durationDays: number; weightBps: number }
export interface ProjectBaseline { id: string; organizationId: string; projectId: string; number: string; revision: number; status: BaselineStatus; items: BaselineItem[]; snapshot?: BaselineItem[]; recordVersion: number; createdBy: string; approvedBy?: string; approvedAt?: string; reason: string }
export interface ResourceAssignment { id: string; organizationId: string; projectId: string; taskId: string; userId: string; plannedMinutes: number; weekStart: string; role: string }
export interface TimesheetEntry { id: string; taskId: string; workDate: string; minutes: number; description: string; billable: boolean; laborRateMinorSnapshot?: bigint; recognizedCostEventId?: string }
export interface Timesheet { id: string; organizationId: string; projectId: string; userId: string; periodStart: string; periodEnd: string; entries: TimesheetEntry[]; totalMinutes: number; status: TimesheetStatus; recordVersion: number; submittedAt?: string; approvedBy?: string; approvedAt?: string; correctionOfId?: string }
export interface ProductionStep { id: string; name: string; sequence: number; status: "pending" | "in_progress" | "completed" | "held"; completedBy?: string; completedAt?: string }
export interface ProductionJob { id: string; organizationId: string; projectId: string; taskId: string; number: string; title: string; quantityMills: bigint; unit: string; drawingRevision: string; requiredMaterials: string[]; purchaseRequisitionIds: string[]; procurementReadiness: "not_ready" | "partial" | "ready"; steps: ProductionStep[]; status: ProductionStatus; recordVersion: number; createdBy: string; releasedBy?: string }
export interface DailyReport { id: string; organizationId: string; projectId: string; number: string; reportDate: string; shift: string; weatherText: string; activities: string[]; labor: Array<{ trade: string; count: number }>; equipment: Array<{ name: string; hours: number }>; delays: string[]; safetyNotes: string[]; attachments: string[]; status: "draft" | "submitted" | "approved" | "rejected"; createdBy: string; approvedBy?: string }
export interface Rfi { id: string; organizationId: string; projectId: string; number: string; subject: string; question: string; discipline: string; documentReference: string; priority: string; responseDueDate: string; responsibleParty: string; classification: "internal" | "external"; response?: string; responseDate?: string; impact: boolean; taskId?: string; status: "draft" | "open" | "answered" | "closed" | "cancelled" }
export interface Submittal { id: string; organizationId: string; projectId: string; number: string; type: string; title: string; discipline: string; documentReference: string; revision: string; submittedBy: string; submittedDate: string; reviewDueDate: string; reviewerId: string; comments: string; status: "draft" | "submitted_internally" | "under_review" | "approved_internally" | "approved_with_comments" | "revise_and_resubmit" | "rejected" | "superseded"; approvedForUseInternal: boolean }
export interface QualityInspection { id: string; organizationId: string; projectId: string; taskId: string; productionJobId?: string; type: string; checklist: Array<{ item: string; passed: boolean; note: string }>; specificationReference: string; drawingRevision: string; inspectorId: string; inspectionDate: string; result: InspectionResult; observations: string; evidence: string[]; requiredAction?: string; reinspectionOfId?: string; approvedBy?: string; immutable: boolean }
export interface Ncr { id: string; organizationId: string; projectId: string; number: string; source: string; location: string; discipline: string; description: string; violatedRequirement: string; classification: string; severity: "minor" | "major" | "critical"; rootCause: string; containmentAction: string; correctiveAction: string; preventiveAction: string; ownerId: string; dueDate: string; evidence: string[]; verification?: string; closureApprovedBy?: string; status: NcrStatus; reopenReason?: string }
export interface SnagItem { id: string; area: string; location: string; discipline: string; description: string; priority: "low" | "medium" | "high" | "critical"; ownerId: string; dueDate: string; status: SnagStatus; beforeEvidence: string[]; afterEvidence: string[]; closureApprovedBy?: string; reopenReason?: string }
export interface SnagList { id: string; organizationId: string; projectId: string; number: string; title: string; items: SnagItem[]; status: "open" | "ready_for_review" | "closed" }
export interface ProjectRisk { id: string; organizationId: string; projectId: string; description: string; probability: number; impact: number; category: string; score: number; ownerId: string; trigger: string; mitigation: string; contingency: string; dueDate: string; residualScore: number; status: "open" | "monitoring" | "closed" | "escalated" }
export interface ProjectIssue { id: string; organizationId: string; projectId: string; source: string; description: string; priority: string; impact: string; ownerId: string; targetResolution: string; decision: string; actions: string[]; status: "open" | "in_progress" | "resolved" | "closed" | "escalated"; links: Record<string, string> }
export interface ProgressMeasurement { id: string; organizationId: string; projectId: string; taskId: string; periodDate: string; plannedBps: number; reportedBps: number; approvedBps: number; previousApprovedBps: number; incrementBps: number; method: "quantity" | "milestone" | "manual"; source: string; reason?: string; status: "draft" | "submitted" | "approved" | "rejected" | "reversed"; reviewerId?: string; approvedAt?: string; snapshot?: Record<string, string | number> }
export interface HandoverPackage { id: string; organizationId: string; projectId: string; number: string; scope: string; contractualDeliverables: string[]; technicalDeliverables: string[]; drawings: string[]; internalApprovals: string[]; inspectionIds: string[]; omManualMetadata: string[]; trainingReferences: string[]; warrantyMetadata: string[]; clientCommentsInternal: string[]; readiness: "not_ready" | "conditional" | "ready"; handoverDate?: string; conditionalHandover: boolean; finalHandover: boolean; checklist: Array<{ label: string; complete: boolean }>; lessonsLearned: string[]; status: "draft" | "under_review" | "ready" | "closed"; closureApprovedBy?: string }
export interface ProjectEvent { id: string; organizationId: string; entityType: string; entityId: string; action: string; summary: string; createdBy: string; createdAt: string; links: Record<string, string> }
export interface ProjectNotification { id: string; organizationId: string; userId: string; type: string; entityType: string; entityId: string; title: string; dedupeKey: string; read: boolean; createdAt: string }
export interface ProjectData { users: ProjectUser[]; projects: Project[]; charters: ProjectCharter[]; wbs: WbsItem[]; milestones: ProjectMilestone[]; tasks: ProjectTask[]; dependencies: TaskDependency[]; baselines: ProjectBaseline[]; assignments: ResourceAssignment[]; timesheets: Timesheet[]; productionJobs: ProductionJob[]; dailyReports: DailyReport[]; rfis: Rfi[]; submittals: Submittal[]; inspections: QualityInspection[]; ncrs: Ncr[]; snagLists: SnagList[]; risks: ProjectRisk[]; issues: ProjectIssue[]; progress: ProgressMeasurement[]; handovers: HandoverPackage[]; timeline: ProjectEvent[]; notifications: ProjectNotification[]; idempotencyKeys: string[]; sequences: Record<string, number> }
export interface ProjectMetrics { plannedProgressBps: number; approvedActualProgressBps: number; scheduleVarianceBps: number; openRfis: number; overdueSubmittals: number; openNcrs: number; openSnags: number; approvedMinutes: number; delayedProductionJobs: number; procurementReadiness: string; currency: CurrencyCode; budgetMinor: bigint; commitmentMinor: bigint; recognizedCostMinor: bigint; eacMinor: bigint; forecastMarginMinor: bigint; pvMinor: bigint; evMinor: bigint; acMinor: bigint; spiBps: number | null; cpiBps: number | null }
