-- Migration contract — not applied or integration-tested.
-- Phase 5 contracts/work orders. Review on an isolated PostgreSQL/Supabase project only.
create type public.contract_status as enum('draft','under_review','changes_requested','approved','active','suspended','completed','cancelled','terminated','expired','superseded');
create type public.contract_approval_status as enum('pending','approved','rejected','changes_requested');
create type public.change_order_status as enum('draft','under_review','changes_requested','approved','rejected','applied','cancelled');
create type public.work_order_status as enum('draft','planned','ready','in_progress','on_hold','completed','cancelled','reopened');

create table public.contract_sequences(organization_id uuid not null references public.organizations(id),sequence_type text not null check(sequence_type in('contract','change_order','work_order')),sequence_year integer not null,last_value bigint not null default 0 check(last_value>=0),prefix text not null,primary key(organization_id,sequence_type,sequence_year));
create table public.contracts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contract_number text not null,quotation_id uuid not null,quotation_version_id uuid not null,sales_request_id uuid not null,customer_id uuid not null,owner_id uuid not null references public.profiles(id),department_id uuid references public.departments(id),contract_type text not null,start_date date not null,end_date date not null check(end_date>=start_date),currency char(3) not null,contract_value numeric(20,3) not null check(contract_value>=0),current_version_id uuid,record_version integer not null default 1,created_by uuid not null references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,foreign key(quotation_id,organization_id) references public.quotations(id,organization_id),foreign key(quotation_version_id,organization_id) references public.quotation_versions(id,organization_id),foreign key(sales_request_id,organization_id) references public.sales_requests(id,organization_id),foreign key(customer_id,organization_id) references public.customer_accounts(id,organization_id),unique(organization_id,contract_number),unique(id,organization_id));
create unique index one_original_contract_per_quote on public.contracts(organization_id,quotation_version_id) where archived_at is null;
create table public.contract_versions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contract_id uuid not null,version_number integer not null check(version_number>0),display_number text not null,status public.contract_status not null default 'draft',language text not null check(language in('ar','en','bilingual')),quotation_snapshot jsonb not null,customer_snapshot jsonb not null,contract_snapshot jsonb not null,reason text,comparison_summary text,record_version integer not null default 1,approved_at timestamptz,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),foreign key(contract_id,organization_id) references public.contracts(id,organization_id),unique(contract_id,version_number),unique(organization_id,display_number),unique(id,organization_id));
alter table public.contracts add constraint contracts_current_version_fk foreign key(current_version_id,organization_id) references public.contract_versions(id,organization_id);
create table public.contract_parties(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contract_version_id uuid not null,party_type text not null check(party_type in('company','customer','other')),name text not null,registration_number text,address text,email text,phone text,snapshot jsonb not null default '{}',foreign key(contract_version_id,organization_id) references public.contract_versions(id,organization_id),unique(id,organization_id));
create table public.contract_sections(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contract_version_id uuid not null,title_ar text,title_en text,body_ar text not null default '',body_en text not null default '',sort_order integer not null check(sort_order>0),foreign key(contract_version_id,organization_id) references public.contract_versions(id,organization_id),unique(contract_version_id,sort_order),unique(id,organization_id));
create table public.contract_deliverables(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contract_version_id uuid not null,title text not null,description text not null default '',due_date date not null,owner_id uuid not null references public.profiles(id),status text not null check(status in('pending','in_progress','completed','waived')),is_mandatory boolean not null default true,completed_at timestamptz,foreign key(contract_version_id,organization_id) references public.contract_versions(id,organization_id),unique(id,organization_id));
create table public.contract_milestones(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contract_version_id uuid not null,title text not null,due_date date not null,status text not null check(status in('pending','completed')),amount numeric(20,3) check(amount>=0),foreign key(contract_version_id,organization_id) references public.contract_versions(id,organization_id),unique(id,organization_id));
create table public.contract_payment_schedules(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contract_version_id uuid not null,milestone_id uuid,label text not null,percentage numeric(7,4) not null check(percentage between 0 and 100),amount numeric(20,3) not null check(amount>=0),due_rule text not null,status text not null check(status in('planned','due','paid_demo','cancelled')),foreign key(contract_version_id,organization_id) references public.contract_versions(id,organization_id),foreign key(milestone_id,organization_id) references public.contract_milestones(id,organization_id),unique(id,organization_id));
create table public.contract_obligations(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contract_version_id uuid not null,party text not null check(party in('company','customer')),title text not null,due_date date not null,owner_id uuid not null references public.profiles(id),status text not null check(status in('open','completed','waived')),is_mandatory boolean not null default true,foreign key(contract_version_id,organization_id) references public.contract_versions(id,organization_id),unique(id,organization_id));
create table public.contract_attachments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contract_id uuid not null,file_name text not null check(file_name!~'[\\/]'),mime_type text not null,size_bytes bigint not null check(size_bytes between 1 and 10485760),category text not null,file_version integer not null default 1 check(file_version>0),confidentiality text not null check(confidentiality in('internal','confidential','public')),storage_path text not null,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),archived_at timestamptz,foreign key(contract_id,organization_id) references public.contracts(id,organization_id),unique(id,organization_id));
create table public.contract_approvals(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contract_version_id uuid not null,status public.contract_approval_status not null default 'pending',idempotency_key text not null,requested_by uuid not null references public.profiles(id),requested_at timestamptz not null default now(),decided_by uuid references public.profiles(id),decided_at timestamptz,comment text,foreign key(contract_version_id,organization_id) references public.contract_versions(id,organization_id),unique(organization_id,idempotency_key),unique(id,organization_id),check(decided_by is null or decided_by<>requested_by));
create table public.contract_change_orders(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contract_id uuid not null,change_order_number text not null,change_type text not null,reason text not null,description text not null,value_impact numeric(20,3) not null default 0,duration_impact_days integer not null default 0,currency char(3) not null,requested_by uuid not null references public.profiles(id),requested_at timestamptz not null default now(),status public.change_order_status not null default 'draft',before_snapshot jsonb not null,after_snapshot jsonb,record_version integer not null default 1,applied_at timestamptz,created_at timestamptz not null default now(),archived_at timestamptz,foreign key(contract_id,organization_id) references public.contracts(id,organization_id),unique(organization_id,change_order_number),unique(id,organization_id));
create table public.contract_change_order_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),change_order_id uuid not null,item_type text not null,description text not null,value_impact numeric(20,3) not null default 0,duration_impact_days integer not null default 0,sort_order integer not null default 0,foreign key(change_order_id,organization_id) references public.contract_change_orders(id,organization_id),unique(id,organization_id));
create table public.work_orders(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),contract_id uuid not null,deliverable_id uuid,milestone_id uuid,work_order_number text not null,title text not null,description text not null default '',work_order_type text not null,priority public.lead_priority not null default 'medium',department_id uuid references public.departments(id),owner_id uuid not null references public.profiles(id),start_date date not null,due_date date not null check(due_date>=start_date),status public.work_order_status not null default 'draft',progress numeric(5,2) not null default 0 check(progress between 0 and 100),notes text not null default '',hold_reason text,cancel_reason text,completed_at timestamptz,closure_approved_at timestamptz,closure_approved_by uuid references public.profiles(id),record_version integer not null default 1,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,foreign key(contract_id,organization_id) references public.contracts(id,organization_id),foreign key(deliverable_id,organization_id) references public.contract_deliverables(id,organization_id),foreign key(milestone_id,organization_id) references public.contract_milestones(id,organization_id),unique(organization_id,work_order_number),unique(id,organization_id));
create table public.work_order_assignees(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),work_order_id uuid not null,user_id uuid not null references public.profiles(id),assignment_role text not null default 'participant',foreign key(work_order_id,organization_id) references public.work_orders(id,organization_id),unique(work_order_id,user_id));
create table public.work_order_checklist_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),work_order_id uuid not null,title text not null,is_mandatory boolean not null default true,is_completed boolean not null default false,completed_at timestamptz,completed_by uuid references public.profiles(id),sort_order integer not null default 0,foreign key(work_order_id,organization_id) references public.work_orders(id,organization_id));
create table public.work_order_activities(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),work_order_id uuid not null,actor_id uuid not null references public.profiles(id),action text not null,details jsonb not null default '{}',created_at timestamptz not null default now(),foreign key(work_order_id,organization_id) references public.work_orders(id,organization_id));

create index contracts_org_status_idx on public.contracts(organization_id,end_date) where archived_at is null;create index contract_versions_status_idx on public.contract_versions(organization_id,status);create index obligations_due_idx on public.contract_obligations(organization_id,due_date) where status='open';create index change_orders_status_idx on public.contract_change_orders(organization_id,status) where archived_at is null;create index work_orders_due_idx on public.work_orders(organization_id,due_date,status) where archived_at is null;
insert into public.permissions(code,module,action,name_ar,description) select code,'contracts',split_part(code,'.',2),name_ar,'Phase five permission' from(values('contracts.view','عرض العقود'),('contracts.create','إنشاء العقود'),('contracts.update_draft','تعديل المسودة'),('contracts.submit_for_approval','إرسال العقد للموافقة'),('contracts.approve','اعتماد العقد'),('contracts.activate','تفعيل العقد'),('contracts.suspend','تعليق العقد'),('contracts.terminate','إنهاء العقد'),('contracts.complete','إكمال العقد'),('contracts.create_revision','إنشاء إصدار عقد'),('contracts.view_financials','عرض ماليات العقد'),('contracts.export','تصدير العقود'),('change_orders.create','إنشاء أمر تغييري'),('change_orders.approve','اعتماد أمر تغييري'),('work_orders.view','عرض أوامر العمل'),('work_orders.create','إنشاء أمر عمل'),('work_orders.assign','إسناد أمر عمل'),('work_orders.update','تحديث أمر عمل'),('work_orders.start','بدء أمر عمل'),('work_orders.complete','إكمال أمر عمل'),('work_orders.approve_closure','اعتماد إغلاق أمر عمل'),('work_orders.reopen','إعادة فتح أمر عمل'),('work_orders.export','تصدير أوامر العمل'))v(code,name_ar) on conflict(code) do nothing;
do $$ declare t text;begin foreach t in array array['contract_sequences','contracts','contract_versions','contract_parties','contract_sections','contract_deliverables','contract_milestones','contract_payment_schedules','contract_obligations','contract_attachments','contract_approvals','contract_change_orders','contract_change_order_items','work_orders','work_order_assignees','work_order_checklist_items','work_order_activities'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
create policy contracts_read on public.contracts for select using(public.is_org_member(organization_id) and public.has_permission(organization_id,'contracts.view'));create policy contract_versions_read on public.contract_versions for select using(public.is_org_member(organization_id) and public.has_permission(organization_id,'contracts.view'));create policy work_orders_read on public.work_orders for select using(public.is_org_member(organization_id) and public.has_permission(organization_id,'work_orders.view'));create policy change_orders_read on public.contract_change_orders for select using(public.is_org_member(organization_id) and public.has_permission(organization_id,'contracts.view'));create policy contract_approvals_read on public.contract_approvals for select using(public.is_org_member(organization_id) and public.has_permission(organization_id,'contracts.view'));
-- No direct write policies: reviewed SECURITY DEFINER RPCs must derive organization_id from
-- active membership, verify permissions/relationships/idempotency/record_version, lock rows,
-- enforce state machines and separation of duties, then write audit/timeline atomically.
create or replace function public.next_contract_number(target_org uuid,target_type text)returns text language plpgsql security definer set search_path=public as $$declare y int:=extract(year from now());n bigint;p text;begin if not public.is_org_member(target_org) then raise exception 'Forbidden';end if;if target_type not in('contract','change_order','work_order')then raise exception 'Invalid type';end if;insert into public.contract_sequences(organization_id,sequence_type,sequence_year,last_value,prefix)values(target_org,target_type,y,1,case target_type when 'contract'then'CTR' when'change_order'then'CO' else'WO'end)on conflict(organization_id,sequence_type,sequence_year)do update set last_value=public.contract_sequences.last_value+1 returning last_value,prefix into n,p;return p||'-'||y||'-'||lpad(n::text,5,'0');end$$;revoke all on function public.next_contract_number(uuid,text) from public;grant execute on function public.next_contract_number(uuid,text) to authenticated;
-- Required future atomic RPC contracts: create_contract_from_quotation,
-- submit/decide_contract_approval, create/apply_change_order, create/update/transition_work_order,
-- approve_work_order_closure. This file intentionally does not claim those bindings exist.
