-- Phase nine: inventory, warehouses and materials.
-- Migration contract — not applied or integration-tested.
-- Run only against an isolated PostgreSQL/Supabase project after review.

create table public.inventory_item_categories (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), parent_id uuid, code text not null, name text not null, name_en text not null default '', active boolean not null default true, deleted_at timestamptz, unique(organization_id,id), unique(organization_id,code), foreign key(organization_id,parent_id) references public.inventory_item_categories(organization_id,id));
create table public.inventory_units (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), code text not null, name text not null, name_en text not null default '', precision smallint not null default 3 check(precision between 0 and 3), active boolean not null default true, unique(organization_id,id), unique(organization_id,code));
create table public.inventory_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), sku text not null, name text not null, name_en text not null default '', category_id uuid not null, base_unit_id uuid not null, tracking text not null default 'none' check(tracking in('none','lot','serial')), currency text not null, status text not null default 'draft' check(status in('draft','active','blocked','archived')), description text not null default '', record_version integer not null default 1 check(record_version>0), created_by uuid not null, created_at timestamptz not null default now(), deleted_at timestamptz, unique(organization_id,id), unique(organization_id,sku), foreign key(organization_id,category_id) references public.inventory_item_categories(organization_id,id), foreign key(organization_id,base_unit_id) references public.inventory_units(organization_id,id));
create table public.inventory_unit_conversions (id uuid primary key default gen_random_uuid(), organization_id uuid not null, item_id uuid not null, from_unit_id uuid not null, to_unit_id uuid not null, numerator numeric(24,0) not null check(numerator>0), denominator numeric(24,0) not null check(denominator>0), rounding text not null check(rounding in('half_up','down')), unique(organization_id,item_id,from_unit_id,to_unit_id), foreign key(organization_id,item_id) references public.inventory_items(organization_id,id), foreign key(organization_id,from_unit_id) references public.inventory_units(organization_id,id), foreign key(organization_id,to_unit_id) references public.inventory_units(organization_id,id), check(from_unit_id<>to_unit_id));

create table public.inventory_warehouses (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), code text not null, name text not null, name_en text not null default '', warehouse_type text not null check(warehouse_type in('main','production','site','quarantine')), status text not null default 'active' check(status in('active','blocked','archived')), record_version integer not null default 1, deleted_at timestamptz, unique(organization_id,id), unique(organization_id,code));
create table public.inventory_warehouse_zones (id uuid primary key default gen_random_uuid(), organization_id uuid not null, warehouse_id uuid not null, code text not null, name text not null, status text not null default 'active', unique(organization_id,id), unique(organization_id,warehouse_id,code), foreign key(organization_id,warehouse_id) references public.inventory_warehouses(organization_id,id));
create table public.inventory_storage_bins (id uuid primary key default gen_random_uuid(), organization_id uuid not null, warehouse_id uuid not null, zone_id uuid not null, code text not null, name text not null, bucket text not null check(bucket in('available','reserved','quarantine','damaged','in_transit')), status text not null default 'active', unique(organization_id,id), unique(organization_id,warehouse_id,code), foreign key(organization_id,warehouse_id) references public.inventory_warehouses(organization_id,id), foreign key(organization_id,zone_id) references public.inventory_warehouse_zones(organization_id,id));
create table public.inventory_item_warehouse_settings (id uuid primary key default gen_random_uuid(), organization_id uuid not null, item_id uuid not null, warehouse_id uuid not null, minimum_qty numeric(24,3) not null default 0 check(minimum_qty>=0), maximum_qty numeric(24,3) not null default 0 check(maximum_qty>=minimum_qty), safety_qty numeric(24,3) not null default 0 check(safety_qty>=0), lead_time_days integer not null default 0 check(lead_time_days>=0), reorder_enabled boolean not null default false, record_version integer not null default 1, unique(organization_id,item_id,warehouse_id), foreign key(organization_id,item_id) references public.inventory_items(organization_id,id), foreign key(organization_id,warehouse_id) references public.inventory_warehouses(organization_id,id));
create table public.inventory_stock_lots (id uuid primary key default gen_random_uuid(), organization_id uuid not null, item_id uuid not null, lot_number text not null, manufactured_at date, expires_at date, status text not null check(status in('active','quality_hold','expired','closed')), unique(organization_id,id), unique(organization_id,item_id,lot_number), foreign key(organization_id,item_id) references public.inventory_items(organization_id,id), check(expires_at is null or manufactured_at is null or expires_at>=manufactured_at));
create table public.inventory_serial_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null, item_id uuid not null, serial_number text not null, status text not null check(status in('available','reserved','issued','returned','damaged')), unique(organization_id,id), unique(organization_id,item_id,serial_number), foreign key(organization_id,item_id) references public.inventory_items(organization_id,id));

create table public.inventory_movements (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), number text not null, movement_type text not null check(movement_type in('opening','receipt','issue','return','transfer_out','transfer_in','adjustment_in','adjustment_out','damage','scrap','reversal')), status text not null default 'posted' check(status in('posted','reversed')), occurred_at timestamptz not null default now(), source_type text not null, source_id uuid, idempotency_key text not null, record_version integer not null default 1, created_by uuid not null, approved_by uuid, reversal_of_id uuid, unique(organization_id,id), unique(organization_id,number), unique(organization_id,idempotency_key), foreign key(organization_id,reversal_of_id) references public.inventory_movements(organization_id,id));
create table public.inventory_movement_lines (id uuid primary key default gen_random_uuid(), organization_id uuid not null, movement_id uuid not null, item_id uuid not null, warehouse_id uuid not null, bin_id uuid not null, quantity numeric(24,3) not null check(quantity>0), direction smallint not null check(direction in(-1,1)), bucket text not null check(bucket in('available','reserved','quarantine','damaged','in_transit')), unit_cost_minor_snapshot bigint not null check(unit_cost_minor_snapshot>=0), currency text not null, lot_id uuid, serial_ids uuid[] not null default '{}', project_id uuid, wbs_id uuid, task_id uuid, production_job_id uuid, source_movement_line_id uuid, unique(organization_id,id), foreign key(organization_id,movement_id) references public.inventory_movements(organization_id,id), foreign key(organization_id,item_id) references public.inventory_items(organization_id,id), foreign key(organization_id,warehouse_id) references public.inventory_warehouses(organization_id,id), foreign key(organization_id,bin_id) references public.inventory_storage_bins(organization_id,id), foreign key(organization_id,lot_id) references public.inventory_stock_lots(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id), foreign key(organization_id,wbs_id) references public.project_wbs_items(organization_id,id), foreign key(organization_id,task_id) references public.project_tasks(organization_id,id), foreign key(organization_id,production_job_id) references public.production_jobs(organization_id,id), foreign key(organization_id,source_movement_line_id) references public.inventory_movement_lines(organization_id,id));

-- Stock balance is a read model derived solely from immutable posted movement lines.
create view public.inventory_stock_balances as select l.organization_id,l.item_id,l.warehouse_id,l.bin_id,l.bucket,l.currency,sum(l.quantity*l.direction)::numeric(24,3) as on_hand_qty from public.inventory_movement_lines l join public.inventory_movements m on m.organization_id=l.organization_id and m.id=l.movement_id where m.status='posted' group by l.organization_id,l.item_id,l.warehouse_id,l.bin_id,l.bucket,l.currency;

create table public.material_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null, number text not null, project_id uuid not null, status text not null, purpose text not null, record_version integer not null default 1, idempotency_key text not null, created_by uuid not null, approved_by uuid, created_at timestamptz not null default now(), unique(organization_id,id), unique(organization_id,number), unique(organization_id,idempotency_key), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.material_request_lines (id uuid primary key default gen_random_uuid(), organization_id uuid not null, request_id uuid not null, item_id uuid not null, warehouse_id uuid not null, requested_qty numeric(24,3) not null check(requested_qty>0), approved_qty numeric(24,3) not null default 0 check(approved_qty>=0 and approved_qty<=requested_qty), allocated_qty numeric(24,3) not null default 0 check(allocated_qty>=0 and allocated_qty<=approved_qty), issued_qty numeric(24,3) not null default 0 check(issued_qty>=0 and issued_qty<=approved_qty), required_date date not null, wbs_id uuid, task_id uuid, production_job_id uuid, unique(organization_id,id), foreign key(organization_id,request_id) references public.material_requests(organization_id,id), foreign key(organization_id,item_id) references public.inventory_items(organization_id,id), foreign key(organization_id,warehouse_id) references public.inventory_warehouses(organization_id,id), foreign key(organization_id,wbs_id) references public.project_wbs_items(organization_id,id), foreign key(organization_id,task_id) references public.project_tasks(organization_id,id), foreign key(organization_id,production_job_id) references public.production_jobs(organization_id,id));
create table public.inventory_reservations (id uuid primary key default gen_random_uuid(), organization_id uuid not null, number text not null, material_request_id uuid not null, project_id uuid not null, expires_at date not null, status text not null, record_version integer not null default 1, created_by uuid not null, unique(organization_id,id), unique(organization_id,number), foreign key(organization_id,material_request_id) references public.material_requests(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.inventory_reservation_lines (id uuid primary key default gen_random_uuid(), organization_id uuid not null, reservation_id uuid not null, item_id uuid not null, warehouse_id uuid not null, bin_id uuid not null, quantity numeric(24,3) not null check(quantity>0), released_qty numeric(24,3) not null default 0 check(released_qty>=0), issued_qty numeric(24,3) not null default 0 check(issued_qty>=0), lot_id uuid, serial_ids uuid[] not null default '{}', unique(organization_id,id), foreign key(organization_id,reservation_id) references public.inventory_reservations(organization_id,id), foreign key(organization_id,item_id) references public.inventory_items(organization_id,id), foreign key(organization_id,warehouse_id) references public.inventory_warehouses(organization_id,id), foreign key(organization_id,bin_id) references public.inventory_storage_bins(organization_id,id), check(released_qty+issued_qty<=quantity));

-- Document headers store workflow state; their lines are normalized in inventory_document_lines.
create table public.inventory_documents (id uuid primary key default gen_random_uuid(), organization_id uuid not null, number text not null, document_kind text not null check(document_kind in('receipt','issue','return','adjustment','damage','reversal')), status text not null, source_type text not null, source_id uuid, reason text not null default '', record_version integer not null default 1, idempotency_key text not null, created_by uuid not null, approved_by uuid, posted_movement_id uuid, created_at timestamptz not null default now(), unique(organization_id,id), unique(organization_id,number), unique(organization_id,idempotency_key), foreign key(organization_id,posted_movement_id) references public.inventory_movements(organization_id,id));
create table public.inventory_document_lines (id uuid primary key default gen_random_uuid(), organization_id uuid not null, document_id uuid not null, item_id uuid not null, quantity numeric(24,3) not null check(quantity>0), warehouse_id uuid not null, bin_id uuid not null, unit_cost_minor_snapshot bigint not null check(unit_cost_minor_snapshot>=0), currency text not null, lot_id uuid, serial_ids uuid[] not null default '{}', project_id uuid, wbs_id uuid, task_id uuid, production_job_id uuid, source_line_id uuid, unique(organization_id,id), foreign key(organization_id,document_id) references public.inventory_documents(organization_id,id), foreign key(organization_id,item_id) references public.inventory_items(organization_id,id), foreign key(organization_id,warehouse_id) references public.inventory_warehouses(organization_id,id), foreign key(organization_id,bin_id) references public.inventory_storage_bins(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.inventory_stock_transfers (id uuid primary key default gen_random_uuid(), organization_id uuid not null, number text not null, from_warehouse_id uuid not null, to_warehouse_id uuid not null, status text not null, record_version integer not null default 1, idempotency_key text not null, created_by uuid not null, approved_by uuid, dispatch_movement_id uuid, receipt_movement_id uuid, unique(organization_id,id), unique(organization_id,number), unique(organization_id,idempotency_key), foreign key(organization_id,from_warehouse_id) references public.inventory_warehouses(organization_id,id), foreign key(organization_id,to_warehouse_id) references public.inventory_warehouses(organization_id,id), check(from_warehouse_id<>to_warehouse_id));
create table public.inventory_transfer_lines (id uuid primary key default gen_random_uuid(), organization_id uuid not null, transfer_id uuid not null, item_id uuid not null, quantity numeric(24,3) not null check(quantity>0), received_qty numeric(24,3) not null default 0 check(received_qty>=0 and received_qty<=quantity), payload jsonb not null default '{}'::jsonb, unique(organization_id,id), foreign key(organization_id,transfer_id) references public.inventory_stock_transfers(organization_id,id), foreign key(organization_id,item_id) references public.inventory_items(organization_id,id));
create table public.inventory_count_sessions (id uuid primary key default gen_random_uuid(), organization_id uuid not null, number text not null, warehouse_id uuid not null, blind boolean not null default true, status text not null, record_version integer not null default 1, created_by uuid not null, approved_by uuid, unique(organization_id,id), unique(organization_id,number), foreign key(organization_id,warehouse_id) references public.inventory_warehouses(organization_id,id));
create table public.inventory_count_lines (id uuid primary key default gen_random_uuid(), organization_id uuid not null, count_id uuid not null, item_id uuid not null, warehouse_id uuid not null, bin_id uuid not null, system_qty_snapshot numeric(24,3), counted_qty numeric(24,3), recount_qty numeric(24,3), variance_qty numeric(24,3), unit_cost_minor_snapshot bigint not null, currency text not null, unique(organization_id,id), unique(organization_id,count_id,item_id,bin_id), foreign key(organization_id,count_id) references public.inventory_count_sessions(organization_id,id), foreign key(organization_id,item_id) references public.inventory_items(organization_id,id));
create table public.inventory_damage_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null, number text not null, item_id uuid not null, warehouse_id uuid not null, bin_id uuid not null, quantity numeric(24,3) not null check(quantity>0), reason text not null, evidence_metadata jsonb not null default '[]'::jsonb, decision text not null check(decision in('rework','return_interface','scrap','hold','release')), status text not null, cost_minor_snapshot bigint not null check(cost_minor_snapshot>=0), currency text not null, responsible_id uuid not null, record_version integer not null default 1, unique(organization_id,id), unique(organization_id,number), foreign key(organization_id,item_id) references public.inventory_items(organization_id,id));
create table public.inventory_reorder_policies (id uuid primary key default gen_random_uuid(), organization_id uuid not null, item_id uuid not null, warehouse_id uuid not null, policy jsonb not null, active boolean not null default true, unique(organization_id,item_id,warehouse_id), foreign key(organization_id,item_id) references public.inventory_items(organization_id,id), foreign key(organization_id,warehouse_id) references public.inventory_warehouses(organization_id,id));
create table public.inventory_approval_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), entity_type text not null, entity_id uuid not null, requested_by uuid not null, status text not null, decided_by uuid, comment text, created_at timestamptz not null default now(), decided_at timestamptz);

create index inventory_item_active_idx on public.inventory_items(organization_id,status) where deleted_at is null;
create index inventory_item_category_idx on public.inventory_items(organization_id,category_id,status);
create index inventory_warehouse_status_idx on public.inventory_warehouses(organization_id,status) where deleted_at is null;
create index inventory_bin_lookup_idx on public.inventory_storage_bins(organization_id,warehouse_id,bucket,status);
create index inventory_movement_date_idx on public.inventory_movements(organization_id,occurred_at desc);
create index inventory_movement_reference_idx on public.inventory_movements(organization_id,source_type,source_id);
create index inventory_line_item_idx on public.inventory_movement_lines(organization_id,item_id,warehouse_id,bin_id);
create index inventory_line_project_idx on public.inventory_movement_lines(organization_id,project_id,item_id) where project_id is not null;
create index inventory_line_job_idx on public.inventory_movement_lines(organization_id,production_job_id) where production_job_id is not null;
create index inventory_lot_expiry_idx on public.inventory_stock_lots(organization_id,expires_at) where status='active' and expires_at is not null;
create index inventory_serial_lookup_idx on public.inventory_serial_records(organization_id,serial_number,status);
create index material_request_status_idx on public.material_requests(organization_id,status,created_at desc);
create index material_request_due_idx on public.material_request_lines(organization_id,required_date) where issued_qty<approved_qty;
create index inventory_reservation_expiry_idx on public.inventory_reservations(organization_id,expires_at) where status in('active','partially_issued');
create index inventory_transfer_transit_idx on public.inventory_stock_transfers(organization_id,status) where status in('dispatched','partially_received');
create index inventory_reorder_active_idx on public.inventory_reorder_policies(organization_id,item_id) where active;

create or replace function public.inventory_posted_immutable_guard() returns trigger language plpgsql as $$ begin raise exception 'Posted inventory movements are immutable; create an approved reversal'; end $$;
create trigger inventory_movement_immutable before update or delete on public.inventory_movements for each row when (old.status='posted') execute function public.inventory_posted_immutable_guard();
create trigger inventory_movement_line_immutable before update or delete on public.inventory_movement_lines for each row execute function public.inventory_posted_immutable_guard();

-- Atomic operations are contracts only. They deliberately fail until transaction bodies,
-- authorization, concurrency and rollback behavior are integration-tested on PostgreSQL.
create or replace function public.phase_nine_inventory_rpc_contract(operation text, payload jsonb) returns jsonb language plpgsql security invoker as $$ begin raise exception 'Phase nine inventory RPC contract % is not implemented or integration-tested',operation; end $$;
comment on function public.phase_nine_inventory_rpc_contract(text,jsonb) is 'Contract for atomic numbering, receipt/issue/return posting, transfer dispatch/receipt, count/adjustment posting and reversal. Deliberately non-operational.';

do $$ declare t text; begin foreach t in array array['inventory_item_categories','inventory_units','inventory_items','inventory_unit_conversions','inventory_warehouses','inventory_warehouse_zones','inventory_storage_bins','inventory_item_warehouse_settings','inventory_stock_lots','inventory_serial_records','inventory_movements','inventory_movement_lines','material_requests','material_request_lines','inventory_reservations','inventory_reservation_lines','inventory_documents','inventory_document_lines','inventory_stock_transfers','inventory_transfer_lines','inventory_count_sessions','inventory_count_lines','inventory_damage_records','inventory_reorder_policies','inventory_approval_records'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy %I on public.%I for select using (organization_id in (select organization_id from public.organization_members where user_id=auth.uid() and status=''active''))',t||'_tenant_select',t); end loop; end $$;

insert into public.permissions(code,module,action,name_ar,description) select code,'inventory',split_part(code,'.',2),code,'Phase nine inventory permission' from unnest(array[
  'inventory.view','inventory.items.view','inventory.items.manage','inventory.warehouses.view','inventory.warehouses.manage','inventory.stock.view','inventory.costs.view','inventory.valuation.view','inventory.requests.create','inventory.requests.review','inventory.requests.approve','inventory.reservations.manage','inventory.receipts.view','inventory.receipts.post','inventory.issues.create','inventory.issues.approve','inventory.issues.pick','inventory.issues.post','inventory.returns.create','inventory.returns.approve','inventory.returns.post','inventory.transfers.create','inventory.transfers.approve','inventory.transfers.dispatch','inventory.transfers.receive','inventory.counts.create','inventory.counts.perform','inventory.counts.approve','inventory.adjustments.create','inventory.adjustments.approve','inventory.adjustments.post','inventory.damage.manage','inventory.reorder.view','inventory.requisitions.create_draft','inventory.reversal.approve','inventory.export','inventory.print','inventory.audit.view'
]) code on conflict(code) do nothing;

-- Write policies are intentionally absent from this contract. Server-side permission-aware RPCs
-- must be implemented and tested before any production integration. No migration is applied here.
