-- Phase six billing and collections
-- Migration contract — not applied or integration-tested
-- Internal operational documents only. No ZATCA clearance, reporting, cryptographic stamp, or official QR.

create table if not exists public.billing_settings (
  organization_id uuid primary key references public.organizations(id) on delete cascade,
  default_language text not null default 'bilingual' check(default_language in('ar','en','bilingual')),
  invoice_prefix text not null default 'INV', receipt_prefix text not null default 'REC', adjustment_prefix text not null default 'ADJ',
  default_due_days integer not null default 30 check(default_due_days between 0 and 3650), default_tax_bps integer not null default 0 check(default_tax_bps between 0 and 10000),
  payment_instructions text not null default '', internal_document_notice text not null,
  record_version integer not null default 1 check(record_version>0), updated_at timestamptz not null default now()
);
create table if not exists public.billing_document_sequences (
  organization_id uuid not null references public.organizations(id) on delete cascade, document_type text not null check(document_type in('invoice','receipt','adjustment')),
  document_year integer not null check(document_year between 2000 and 9999), last_number bigint not null default 0 check(last_number>=0), updated_at timestamptz not null default now(),
  primary key(organization_id,document_type,document_year)
);
create table if not exists public.invoice_templates (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,language text not null check(language in('ar','en','bilingual')),body jsonb not null default '{}'::jsonb,active boolean not null default true,created_at timestamptz not null default now(),unique(organization_id,id));
create table if not exists public.invoices (
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,invoice_number text not null,customer_id uuid not null,contract_id uuid not null,currency char(3) not null,
 workflow_status text not null default 'draft' check(workflow_status in('draft','under_review','changes_requested','approved','issued','voided')),settlement_status text not null default 'unpaid' check(settlement_status in('unpaid','partially_paid','paid','overpaid_adjustment')),delivery_status text not null default 'not_sent' check(delivery_status in('not_sent','queued_demo','delivered_demo','failed_demo')),
 issue_date date not null,due_date date not null check(due_date>=issue_date),subtotal_minor bigint not null check(subtotal_minor>=0),discount_minor bigint not null default 0 check(discount_minor>=0),tax_minor bigint not null default 0 check(tax_minor>=0),fees_minor bigint not null default 0 check(fees_minor>=0),total_minor bigint not null check(total_minor>=0),allocated_minor bigint not null default 0 check(allocated_minor>=0),credit_applied_minor bigint not null default 0 check(credit_applied_minor>=0),debit_applied_minor bigint not null default 0 check(debit_applied_minor>=0),open_balance_minor bigint not null,
 snapshot jsonb,record_version integer not null default 1 check(record_version>0),idempotency_key text,created_by uuid not null,approved_by uuid,issued_at timestamptz,void_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,
 unique(organization_id,id),unique(organization_id,invoice_number),unique(organization_id,idempotency_key)
);
create table if not exists public.invoice_lines(id uuid primary key default gen_random_uuid(),organization_id uuid not null,invoice_id uuid not null,sort_order integer not null,description text not null,quantity_mills bigint not null check(quantity_mills>0),unit text not null,unit_price_minor bigint not null check(unit_price_minor>=0),discount_bps integer not null default 0 check(discount_bps between 0 and 10000),tax_bps integer not null default 0 check(tax_bps between 0 and 10000),fee_minor bigint not null default 0 check(fee_minor>=0),foreign key(organization_id,invoice_id) references public.invoices(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.invoice_source_links(id uuid primary key default gen_random_uuid(),organization_id uuid not null,invoice_id uuid not null,contract_id uuid not null,contract_version_id uuid not null,payment_schedule_item_id text not null,change_order_id uuid,source_snapshot jsonb not null,created_at timestamptz not null default now(),foreign key(organization_id,invoice_id) references public.invoices(organization_id,id) on delete restrict,unique(organization_id,payment_schedule_item_id));
create table if not exists public.invoice_approvals(id uuid primary key default gen_random_uuid(),organization_id uuid not null,invoice_id uuid not null,status text not null check(status in('pending','approved','rejected','changes_requested')),requested_by uuid not null,requested_at timestamptz not null default now(),decided_by uuid,decided_at timestamptz,comment text,foreign key(organization_id,invoice_id) references public.invoices(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.invoice_attachments(id uuid primary key default gen_random_uuid(),organization_id uuid not null,invoice_id uuid not null,file_name text not null,mime_type text not null,size_bytes bigint not null check(size_bytes between 0 and 26214400),storage_metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),foreign key(organization_id,invoice_id) references public.invoices(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.invoice_delivery_attempts(id uuid primary key default gen_random_uuid(),organization_id uuid not null,invoice_id uuid not null,channel text not null,status text not null check(status in('draft','queued_demo','delivered_demo','failed_demo')),recipient_masked text,external_reference text,error_safe text,created_at timestamptz not null default now(),foreign key(organization_id,invoice_id) references public.invoices(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.payment_receipts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,receipt_number text not null,customer_id uuid not null,receipt_date date not null,currency char(3) not null,amount_minor bigint not null check(amount_minor>0),payment_method text not null check(payment_method in('bank_transfer','cash','card','cheque','other')),reference text,account_label text,notes text,attachment_metadata jsonb,status text not null default 'draft' check(status in('draft','pending_confirmation','confirmed_internal','reversed')),allocated_minor bigint not null default 0 check(allocated_minor>=0),unallocated_minor bigint not null check(unallocated_minor>=0),record_version integer not null default 1 check(record_version>0),idempotency_key text,created_by uuid not null,confirmed_by uuid,reversal_reason text,created_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,receipt_number),unique(organization_id,idempotency_key),check(allocated_minor+unallocated_minor=amount_minor));
create table if not exists public.payment_allocations(id uuid primary key default gen_random_uuid(),organization_id uuid not null,receipt_id uuid not null,invoice_id uuid not null,amount_minor bigint not null check(amount_minor>0),status text not null default 'active' check(status in('active','reversed')),allocation_snapshot jsonb not null,idempotency_key text not null,created_by uuid not null,created_at timestamptz not null default now(),reversed_at timestamptz,foreign key(organization_id,receipt_id) references public.payment_receipts(organization_id,id) on delete restrict,foreign key(organization_id,invoice_id) references public.invoices(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,idempotency_key));
create table if not exists public.billing_adjustments(id uuid primary key default gen_random_uuid(),organization_id uuid not null,adjustment_number text not null,invoice_id uuid not null,customer_id uuid not null,currency char(3) not null,adjustment_type text not null check(adjustment_type in('credit_note','debit_note')),reason text not null,status text not null default 'draft' check(status in('draft','under_review','approved','issued','rejected','voided')),subtotal_minor bigint not null check(subtotal_minor>0),tax_minor bigint not null default 0 check(tax_minor>=0),total_minor bigint not null check(total_minor>0),before_balance_minor bigint not null,after_balance_minor bigint,snapshot jsonb,record_version integer not null default 1 check(record_version>0),created_by uuid not null,approved_by uuid,issued_at timestamptz,created_at timestamptz not null default now(),foreign key(organization_id,invoice_id) references public.invoices(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,adjustment_number));
create table if not exists public.billing_adjustment_lines(id uuid primary key default gen_random_uuid(),organization_id uuid not null,adjustment_id uuid not null,description text not null,quantity_mills bigint not null check(quantity_mills>0),unit_price_minor bigint not null check(unit_price_minor>=0),tax_bps integer not null default 0 check(tax_bps between 0 and 10000),foreign key(organization_id,adjustment_id) references public.billing_adjustments(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.billing_adjustment_approvals(id uuid primary key default gen_random_uuid(),organization_id uuid not null,adjustment_id uuid not null,status text not null check(status in('pending','approved','rejected','changes_requested')),requested_by uuid not null,decided_by uuid,comment text,requested_at timestamptz not null default now(),decided_at timestamptz,foreign key(organization_id,adjustment_id) references public.billing_adjustments(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.collection_followups(id uuid primary key default gen_random_uuid(),organization_id uuid not null,invoice_id uuid not null,customer_id uuid not null,owner_id uuid not null,followup_date date not null,channel text not null,outcome text not null,promised boolean not null default false,expected_payment_date date,expected_amount_minor bigint check(expected_amount_minor>0),next_action text not null,next_action_date date not null,notes text,status text not null check(status in('new','contacted','promise_to_pay','disputed','escalated','resolved','closed')),attachment_metadata jsonb,created_by uuid not null,created_at timestamptz not null default now(),foreign key(organization_id,invoice_id) references public.invoices(organization_id,id) on delete restrict,unique(organization_id,id));

create index if not exists invoices_org_status_due_idx on public.invoices(organization_id,workflow_status,due_date) where deleted_at is null;
create index if not exists invoices_org_customer_balance_idx on public.invoices(organization_id,customer_id,currency,open_balance_minor) where workflow_status='issued';
create index if not exists receipts_org_status_date_idx on public.payment_receipts(organization_id,status,receipt_date);
create index if not exists allocations_invoice_active_idx on public.payment_allocations(organization_id,invoice_id) where status='active';
create index if not exists followups_next_action_idx on public.collection_followups(organization_id,next_action_date,status);

-- All mutations derive organization_id from authenticated active membership; clients must not be trusted to select it.
alter table public.billing_settings enable row level security;alter table public.billing_document_sequences enable row level security;alter table public.invoice_templates enable row level security;alter table public.invoices enable row level security;alter table public.invoice_lines enable row level security;alter table public.invoice_source_links enable row level security;alter table public.invoice_approvals enable row level security;alter table public.invoice_attachments enable row level security;alter table public.invoice_delivery_attempts enable row level security;alter table public.payment_receipts enable row level security;alter table public.payment_allocations enable row level security;alter table public.billing_adjustments enable row level security;alter table public.billing_adjustment_lines enable row level security;alter table public.billing_adjustment_approvals enable row level security;alter table public.collection_followups enable row level security;
-- Contract only: implement policies using the repository's canonical active-membership and permission helpers before applying.
-- Required SECURITY DEFINER RPC contracts (not implemented here):
-- billing_next_document_number(document_type, document_year) -> atomic scoped number
-- billing_issue_invoice(invoice_id, expected_version, idempotency_key) -> immutable snapshot transition
-- billing_allocate_receipt(receipt_id, invoice_id, amount_minor, expected versions, idempotency_key) -> row locks + consistency checks
-- billing_reverse_receipt(receipt_id, expected_version, reason, idempotency_key) -> reverse all allocations atomically
-- billing_issue_adjustment(adjustment_id, expected_version, idempotency_key) -> one-time balance effect
-- Revoke direct writes from authenticated; grant only audited application/RPC paths after integration review.
