-- Phase seven procurement, supplier, expense, and project-cost contract.
-- Migration contract — not applied or integration-tested.
-- Operational records only: no General Ledger, Accounts Payable ledger, supplier payment, bank posting, or inventory ledger.

create table if not exists public.suppliers (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete restrict,
 supplier_code text not null, legal_name text not null, display_name text not null, tax_number text, country text not null, city text not null,
 duplicate_key text not null, status text not null default 'draft' check(status in('draft','pending_review','approved','suspended','rejected','archived')),
 suspension_reason text, record_version integer not null default 1 check(record_version>0), created_by uuid not null, approved_by uuid,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz,
 unique(organization_id,id), unique(organization_id,supplier_code), unique(organization_id,duplicate_key)
);
create table if not exists public.supplier_contacts (id uuid primary key default gen_random_uuid(),organization_id uuid not null,supplier_id uuid not null,name text not null,email text,phone text,record_version integer not null default 1,foreign key(organization_id,supplier_id) references public.suppliers(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.supplier_categories (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,code text not null,name text not null,active boolean not null default true,unique(organization_id,id),unique(organization_id,code));
create table if not exists public.supplier_documents (id uuid primary key default gen_random_uuid(),organization_id uuid not null,supplier_id uuid not null,file_name text not null check(file_name!~'[\\/]'),mime_type text not null check(mime_type in('application/pdf','image/png','image/jpeg')),size_bytes bigint not null check(size_bytes between 0 and 26214400),storage_metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),foreign key(organization_id,supplier_id) references public.suppliers(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.supplier_evaluations (id uuid primary key default gen_random_uuid(),organization_id uuid not null,supplier_id uuid not null,period_from date not null,period_to date not null check(period_to>=period_from),scores jsonb not null,calculated_score integer not null check(calculated_score between 0 and 100),manual_score integer not null check(manual_score between 0 and 100),formula text not null,rejection_count integer not null default 0,delay_count integer not null default 0,dispute_count integer not null default 0,status text not null check(status in('draft','approved','revised')),revision integer not null default 1,evaluated_by uuid not null,approved_by uuid,record_version integer not null default 1,foreign key(organization_id,supplier_id) references public.suppliers(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,supplier_id,period_from,period_to,revision));

create table if not exists public.cost_centers (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,code text not null,name text not null,active boolean not null default true,record_version integer not null default 1,unique(organization_id,id),unique(organization_id,code));
create table if not exists public.cost_codes (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,parent_id uuid,code text not null,name text not null,active boolean not null default true,record_version integer not null default 1,unique(organization_id,id),unique(organization_id,code),foreign key(organization_id,parent_id) references public.cost_codes(organization_id,id) on delete restrict);
create table if not exists public.project_budgets (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,budget_number text not null,project_id uuid not null,contract_id uuid not null,currency char(3) not null,status text not null check(status in('draft','pending_approval','approved_baseline','superseded')),revision integer not null default 1,total_minor bigint not null check(total_minor>=0),snapshot jsonb,record_version integer not null default 1,created_by uuid not null,approved_by uuid,created_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,budget_number),unique(organization_id,project_id,currency,revision));
create table if not exists public.project_budget_lines (id uuid primary key default gen_random_uuid(),organization_id uuid not null,budget_id uuid not null,cost_code_id uuid not null,description text not null,amount_minor bigint not null check(amount_minor>=0),foreign key(organization_id,budget_id) references public.project_budgets(organization_id,id) on delete restrict,foreign key(organization_id,cost_code_id) references public.cost_codes(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.budget_revisions (id uuid primary key default gen_random_uuid(),organization_id uuid not null,budget_id uuid not null,revision integer not null,reason text not null,status text not null check(status in('draft','pending_approval','approved','rejected')),snapshot jsonb not null,record_version integer not null default 1,created_by uuid not null,approved_by uuid,created_at timestamptz not null default now(),foreign key(organization_id,budget_id) references public.project_budgets(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,budget_id,revision));
create table if not exists public.budget_revision_lines (id uuid primary key default gen_random_uuid(),organization_id uuid not null,budget_revision_id uuid not null,cost_code_id uuid not null,amount_minor bigint not null check(amount_minor>=0),foreign key(organization_id,budget_revision_id) references public.budget_revisions(organization_id,id) on delete restrict,foreign key(organization_id,cost_code_id) references public.cost_codes(organization_id,id) on delete restrict,unique(organization_id,id));

create table if not exists public.purchase_requisitions (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,requisition_number text not null,project_id uuid not null,contract_id uuid not null,work_order_id uuid,cost_center_id uuid not null,budget_id uuid not null,currency char(3) not null,need_by_date date not null,justification text not null,status text not null check(status in('draft','submitted','pending_approval','approved','rejected','converted','cancelled')),subtotal_minor bigint not null,tax_minor bigint not null,total_minor bigint not null,over_budget boolean not null default false,override_reason text,idempotency_key text not null,record_version integer not null default 1,created_by uuid not null,approved_by uuid,created_at timestamptz not null default now(),foreign key(organization_id,cost_center_id) references public.cost_centers(organization_id,id) on delete restrict,foreign key(organization_id,budget_id) references public.project_budgets(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,requisition_number),unique(organization_id,idempotency_key));
create table if not exists public.purchase_requisition_lines (id uuid primary key default gen_random_uuid(),organization_id uuid not null,requisition_id uuid not null,cost_code_id uuid not null,description text not null,quantity_mills bigint not null check(quantity_mills>0),unit text not null,unit_price_minor bigint not null check(unit_price_minor>=0),discount_bps integer not null default 0 check(discount_bps between 0 and 10000),tax_bps integer not null default 0 check(tax_bps between 0 and 10000),fees_minor bigint not null default 0,foreign key(organization_id,requisition_id) references public.purchase_requisitions(organization_id,id) on delete restrict,foreign key(organization_id,cost_code_id) references public.cost_codes(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.purchase_requisition_approvals (id uuid primary key default gen_random_uuid(),organization_id uuid not null,requisition_id uuid not null,status text not null check(status in('pending','approved','rejected','returned')),requested_by uuid not null,decided_by uuid,comment text,created_at timestamptz not null default now(),decided_at timestamptz,foreign key(organization_id,requisition_id) references public.purchase_requisitions(organization_id,id) on delete restrict,unique(organization_id,id));

create table if not exists public.procurement_rfqs (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,rfq_number text not null,requisition_id uuid not null,currency char(3) not null,closing_date date not null,terms text not null,status text not null check(status in('draft','approved','issued_internal','quotes_received','evaluated','awarded','cancelled')),record_version integer not null default 1,created_by uuid not null,created_at timestamptz not null default now(),foreign key(organization_id,requisition_id) references public.purchase_requisitions(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,rfq_number));
create table if not exists public.procurement_rfq_suppliers (id uuid primary key default gen_random_uuid(),organization_id uuid not null,rfq_id uuid not null,supplier_id uuid not null,status text not null default 'invited_internal',foreign key(organization_id,rfq_id) references public.procurement_rfqs(organization_id,id) on delete restrict,foreign key(organization_id,supplier_id) references public.suppliers(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,rfq_id,supplier_id));
create table if not exists public.supplier_quotations (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,quotation_number text not null,rfq_id uuid not null,supplier_id uuid not null,currency char(3) not null,valid_until date not null,delivery_days integer not null check(delivery_days>=0),payment_terms text not null,subtotal_minor bigint not null,tax_minor bigint not null,total_minor bigint not null,technical_score integer not null check(technical_score between 0 and 100),status text not null check(status in('draft','submitted','qualified','disqualified')),record_version integer not null default 1,created_by uuid not null,created_at timestamptz not null default now(),foreign key(organization_id,rfq_id) references public.procurement_rfqs(organization_id,id) on delete restrict,foreign key(organization_id,supplier_id) references public.suppliers(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,rfq_id,supplier_id,quotation_number));
create table if not exists public.supplier_quotation_lines (id uuid primary key default gen_random_uuid(),organization_id uuid not null,supplier_quotation_id uuid not null,description text not null,quantity_mills bigint not null check(quantity_mills>0),unit_price_minor bigint not null check(unit_price_minor>=0),discount_bps integer not null default 0,tax_bps integer not null default 0,fees_minor bigint not null default 0,cost_code_id uuid not null,foreign key(organization_id,supplier_quotation_id) references public.supplier_quotations(organization_id,id) on delete restrict,foreign key(organization_id,cost_code_id) references public.cost_codes(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.bid_comparisons (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,comparison_number text not null,rfq_id uuid not null,currency char(3) not null,award_type text not null check(award_type in('full','partial')),status text not null check(status in('draft','pending_approval','approved','rejected')),snapshot jsonb not null,record_version integer not null default 1,created_by uuid not null,approved_by uuid,created_at timestamptz not null default now(),foreign key(organization_id,rfq_id) references public.procurement_rfqs(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,comparison_number));
create table if not exists public.bid_comparison_decisions (id uuid primary key default gen_random_uuid(),organization_id uuid not null,comparison_id uuid not null,supplier_quotation_id uuid not null,award_amount_minor bigint not null check(award_amount_minor>=0),rationale text not null,selected boolean not null default false,foreign key(organization_id,comparison_id) references public.bid_comparisons(organization_id,id) on delete restrict,foreign key(organization_id,supplier_quotation_id) references public.supplier_quotations(organization_id,id) on delete restrict,unique(organization_id,id));

create table if not exists public.purchase_orders (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,purchase_order_number text not null,requisition_id uuid not null,rfq_id uuid not null,comparison_id uuid not null,supplier_quotation_id uuid not null,supplier_id uuid not null,project_id uuid not null,contract_id uuid not null,currency char(3) not null,status text not null check(status in('draft','pending_approval','approved','issued_internal','partially_received','fully_received','closed','cancelled')),subtotal_minor bigint not null,tax_minor bigint not null,total_minor bigint not null,received_value_minor bigint not null default 0,billed_value_minor bigint not null default 0,recognized_value_minor bigint not null default 0,revision integer not null default 1,snapshot jsonb not null,record_version integer not null default 1,idempotency_key text,created_by uuid not null,approved_by uuid,issued_at timestamptz,created_at timestamptz not null default now(),foreign key(organization_id,requisition_id) references public.purchase_requisitions(organization_id,id) on delete restrict,foreign key(organization_id,rfq_id) references public.procurement_rfqs(organization_id,id) on delete restrict,foreign key(organization_id,comparison_id) references public.bid_comparisons(organization_id,id) on delete restrict,foreign key(organization_id,supplier_quotation_id) references public.supplier_quotations(organization_id,id) on delete restrict,foreign key(organization_id,supplier_id) references public.suppliers(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,purchase_order_number),unique(organization_id,idempotency_key));
create table if not exists public.purchase_order_lines (id uuid primary key default gen_random_uuid(),organization_id uuid not null,purchase_order_id uuid not null,cost_code_id uuid not null,description text not null,quantity_mills bigint not null check(quantity_mills>0),unit_price_minor bigint not null check(unit_price_minor>=0),discount_bps integer not null default 0,tax_bps integer not null default 0,fees_minor bigint not null default 0,foreign key(organization_id,purchase_order_id) references public.purchase_orders(organization_id,id) on delete restrict,foreign key(organization_id,cost_code_id) references public.cost_codes(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.purchase_order_revisions (id uuid primary key default gen_random_uuid(),organization_id uuid not null,purchase_order_id uuid not null,revision integer not null,reason text not null,snapshot jsonb not null,created_by uuid not null,created_at timestamptz not null default now(),foreign key(organization_id,purchase_order_id) references public.purchase_orders(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,purchase_order_id,revision));
create table if not exists public.purchase_order_approvals (id uuid primary key default gen_random_uuid(),organization_id uuid not null,purchase_order_id uuid not null,status text not null check(status in('pending','approved','rejected','returned')),requested_by uuid not null,decided_by uuid,comment text,created_at timestamptz not null default now(),decided_at timestamptz,foreign key(organization_id,purchase_order_id) references public.purchase_orders(organization_id,id) on delete restrict,unique(organization_id,id));

create table if not exists public.procurement_receipts (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,receipt_number text not null,purchase_order_id uuid not null,supplier_id uuid not null,project_id uuid not null,receipt_date date not null,receiver_id uuid not null,status text not null check(status in('draft','pending_approval','approved','reversed')),received_value_minor bigint not null default 0,record_version integer not null default 1,idempotency_key text,approved_by uuid,reversal_reason text,created_at timestamptz not null default now(),foreign key(organization_id,purchase_order_id) references public.purchase_orders(organization_id,id) on delete restrict,foreign key(organization_id,supplier_id) references public.suppliers(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,receipt_number),unique(organization_id,idempotency_key));
create table if not exists public.procurement_receipt_lines (id uuid primary key default gen_random_uuid(),organization_id uuid not null,receipt_id uuid not null,purchase_order_line_id uuid not null,quantity_mills bigint not null check(quantity_mills>0),quality_status text not null check(quality_status in('accepted','conditionally_accepted','rejected')),notes text not null default '',foreign key(organization_id,receipt_id) references public.procurement_receipts(organization_id,id) on delete restrict,foreign key(organization_id,purchase_order_line_id) references public.purchase_order_lines(organization_id,id) on delete restrict,unique(organization_id,id));

create table if not exists public.supplier_bills (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,bill_number text not null,supplier_invoice_number text not null,supplier_id uuid not null,purchase_order_id uuid not null,project_id uuid not null,contract_id uuid not null,currency char(3) not null,invoice_date date not null,due_date date not null,subtotal_minor bigint not null,tax_minor bigint not null,total_minor bigint not null,eligible_recognition_minor bigint not null default 0,match_type text not null check(match_type in('two_way','three_way')),match_status text not null check(match_status in('not_checked','matched','within_tolerance','mismatch')),dispute boolean not null default false,status text not null check(status in('draft','submitted','matching','pending_approval','approved_internal','recognized_operationally','returned_for_changes','rejected','disputed','voided')),snapshot jsonb not null default '{}'::jsonb,record_version integer not null default 1,idempotency_key text not null,created_by uuid not null,approved_by uuid,recognized_at timestamptz,created_at timestamptz not null default now(),foreign key(organization_id,supplier_id) references public.suppliers(organization_id,id) on delete restrict,foreign key(organization_id,purchase_order_id) references public.purchase_orders(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,bill_number),unique(organization_id,supplier_id,supplier_invoice_number),unique(organization_id,idempotency_key));
create table if not exists public.supplier_bill_lines (id uuid primary key default gen_random_uuid(),organization_id uuid not null,supplier_bill_id uuid not null,purchase_order_line_id uuid,description text not null,quantity_mills bigint not null check(quantity_mills>0),unit_price_minor bigint not null check(unit_price_minor>=0),discount_bps integer not null default 0,tax_bps integer not null default 0,fees_minor bigint not null default 0,cost_code_id uuid not null,foreign key(organization_id,supplier_bill_id) references public.supplier_bills(organization_id,id) on delete restrict,foreign key(organization_id,cost_code_id) references public.cost_codes(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.supplier_bill_matches (id uuid primary key default gen_random_uuid(),organization_id uuid not null,supplier_bill_id uuid not null,purchase_order_id uuid not null,receipt_id uuid,match_type text not null,match_status text not null,quantity_variance_mills bigint not null default 0,price_variance_minor bigint not null default 0,tolerance_snapshot jsonb not null,created_at timestamptz not null default now(),foreign key(organization_id,supplier_bill_id) references public.supplier_bills(organization_id,id) on delete restrict,foreign key(organization_id,purchase_order_id) references public.purchase_orders(organization_id,id) on delete restrict,foreign key(organization_id,receipt_id) references public.procurement_receipts(organization_id,id) on delete restrict,unique(organization_id,id));

create table if not exists public.direct_expenses (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,expense_number text not null,expense_type text not null,project_id uuid not null,contract_id uuid not null,work_order_id uuid,cost_center_id uuid not null,cost_code_id uuid not null,supplier_id uuid,expense_date date not null,currency char(3) not null,party text not null,description text not null,payment_method_label text not null,reference text not null,direct_purchase_reason text not null,subtotal_minor bigint not null,tax_minor bigint not null,total_minor bigint not null,status text not null check(status in('draft','submitted','pending_review','approved','recognized_operationally','returned_for_changes','rejected','voided')),record_version integer not null default 1,idempotency_key text not null,created_by uuid not null,approved_by uuid,recognized_at timestamptz,reversal_reason text,created_at timestamptz not null default now(),foreign key(organization_id,cost_center_id) references public.cost_centers(organization_id,id) on delete restrict,foreign key(organization_id,cost_code_id) references public.cost_codes(organization_id,id) on delete restrict,foreign key(organization_id,supplier_id) references public.suppliers(organization_id,id) on delete restrict,unique(organization_id,id),unique(organization_id,expense_number),unique(organization_id,idempotency_key));
create table if not exists public.direct_expense_lines (id uuid primary key default gen_random_uuid(),organization_id uuid not null,direct_expense_id uuid not null,description text not null,quantity_mills bigint not null check(quantity_mills>0),unit_price_minor bigint not null check(unit_price_minor>=0),tax_bps integer not null default 0,fees_minor bigint not null default 0,cost_code_id uuid not null,foreign key(organization_id,direct_expense_id) references public.direct_expenses(organization_id,id) on delete restrict,foreign key(organization_id,cost_code_id) references public.cost_codes(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.direct_expense_approvals (id uuid primary key default gen_random_uuid(),organization_id uuid not null,direct_expense_id uuid not null,status text not null check(status in('pending','approved','rejected','returned')),requested_by uuid not null,decided_by uuid,comment text,created_at timestamptz not null default now(),decided_at timestamptz,foreign key(organization_id,direct_expense_id) references public.direct_expenses(organization_id,id) on delete restrict,unique(organization_id,id));
create table if not exists public.operational_cost_events (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,project_id uuid not null,contract_id uuid not null,currency char(3) not null,source_type text not null check(source_type in('supplier_bill','direct_expense','reversal')),source_id uuid not null,amount_minor bigint not null check(amount_minor>=0),event_kind text not null check(event_kind in('recognized','reversed')),idempotency_key text not null,occurred_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,idempotency_key));

create index if not exists suppliers_org_status_idx on public.suppliers(organization_id,status) where deleted_at is null;
create index if not exists supplier_evaluations_supplier_period_idx on public.supplier_evaluations(organization_id,supplier_id,period_to desc);
create index if not exists budgets_project_status_idx on public.project_budgets(organization_id,project_id,currency,status);
create index if not exists requisitions_project_status_idx on public.purchase_requisitions(organization_id,project_id,status);
create index if not exists rfqs_status_closing_idx on public.procurement_rfqs(organization_id,status,closing_date);
create index if not exists supplier_quotes_supplier_idx on public.supplier_quotations(organization_id,supplier_id,status);
create index if not exists purchase_orders_project_status_idx on public.purchase_orders(organization_id,project_id,status);
create index if not exists purchase_orders_supplier_idx on public.purchase_orders(organization_id,supplier_id,status);
create index if not exists receipts_po_status_idx on public.procurement_receipts(organization_id,purchase_order_id,status);
create index if not exists supplier_bills_supplier_status_idx on public.supplier_bills(organization_id,supplier_id,status);
create index if not exists supplier_bills_project_due_idx on public.supplier_bills(organization_id,project_id,due_date,status);
create index if not exists direct_expenses_project_status_idx on public.direct_expenses(organization_id,project_id,status);
create index if not exists cost_events_project_currency_idx on public.operational_cost_events(organization_id,project_id,currency,occurred_at);

insert into public.permissions(code,module,action,name_ar,description)
select code,split_part(code,'.',1),split_part(code,'.',2),code,'Phase seven procurement permission' from (values
('procurement.dashboard.view'),('suppliers.view'),('suppliers.create'),('suppliers.update'),('suppliers.submit'),('suppliers.approve'),('suppliers.suspend'),('suppliers.export'),
('cost_codes.view'),('cost_codes.manage'),('budgets.view'),('budgets.create'),('budgets.update_draft'),('budgets.submit'),('budgets.approve'),('budgets.revise'),('budgets.view_financials'),
('purchase_requests.view'),('purchase_requests.create'),('purchase_requests.submit'),('purchase_requests.approve'),('purchase_requests.cancel'),
('rfqs.view'),('rfqs.create'),('rfqs.approve'),('rfqs.issue_internal'),('supplier_quotes.view'),('supplier_quotes.create'),('supplier_quotes.evaluate'),
('bid_comparisons.view'),('bid_comparisons.create'),('bid_comparisons.approve'),('purchase_orders.view'),('purchase_orders.create'),('purchase_orders.approve'),('purchase_orders.issue_internal'),('purchase_orders.revise'),('purchase_orders.cancel'),('purchase_orders.view_financials'),
('receipts.view'),('receipts.create'),('receipts.approve'),('receipts.reverse'),('supplier_bills.view'),('supplier_bills.create'),('supplier_bills.match'),('supplier_bills.approve'),('supplier_bills.recognize'),
('expenses.view'),('expenses.create'),('expenses.submit'),('expenses.approve'),('expenses.recognize'),('cost_reports.view'),('cost_reports.export'),('profitability.view'),('profitability.view_sensitive'),('procurement.override_budget'),('procurement.override_tolerance')) v(code)
on conflict(code) do nothing;

-- Default role mapping for existing organizations. Custom roles remain explicit.
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.description='Phase seven procurement permission'
where r.code='owner' on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.description='Phase seven procurement permission'
where r.code='admin' and p.code not in('procurement.override_budget','procurement.override_tolerance') on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in('procurement.dashboard.view','suppliers.view','cost_codes.view','budgets.view','purchase_requests.view','rfqs.view','supplier_quotes.view','bid_comparisons.view','purchase_orders.view','receipts.view','supplier_bills.view','supplier_bills.create','supplier_bills.match','supplier_bills.approve','supplier_bills.recognize','expenses.view','expenses.create','expenses.submit','expenses.approve','expenses.recognize','cost_reports.view','cost_reports.export')
where r.code='accountant' on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in('procurement.dashboard.view','suppliers.view','budgets.view','purchase_requests.view','rfqs.view','supplier_quotes.view','bid_comparisons.view','purchase_orders.view','receipts.view','supplier_bills.view','expenses.view','cost_reports.view','profitability.view')
where r.code='sales_manager' on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in('suppliers.view','purchase_requests.view','profitability.view')
where r.code='sales_agent' on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in('procurement.dashboard.view','suppliers.view','cost_codes.view','budgets.view','purchase_requests.view','rfqs.view','supplier_quotes.view','bid_comparisons.view','purchase_orders.view','receipts.view','supplier_bills.view','expenses.view','cost_reports.view')
where r.code='viewer' on conflict do nothing;

alter table public.suppliers enable row level security; alter table public.supplier_contacts enable row level security; alter table public.supplier_categories enable row level security; alter table public.supplier_documents enable row level security; alter table public.supplier_evaluations enable row level security;
alter table public.cost_centers enable row level security; alter table public.cost_codes enable row level security; alter table public.project_budgets enable row level security; alter table public.project_budget_lines enable row level security; alter table public.budget_revisions enable row level security; alter table public.budget_revision_lines enable row level security;
alter table public.purchase_requisitions enable row level security; alter table public.purchase_requisition_lines enable row level security; alter table public.purchase_requisition_approvals enable row level security;
alter table public.procurement_rfqs enable row level security; alter table public.procurement_rfq_suppliers enable row level security; alter table public.supplier_quotations enable row level security; alter table public.supplier_quotation_lines enable row level security; alter table public.bid_comparisons enable row level security; alter table public.bid_comparison_decisions enable row level security;
alter table public.purchase_orders enable row level security; alter table public.purchase_order_lines enable row level security; alter table public.purchase_order_revisions enable row level security; alter table public.purchase_order_approvals enable row level security;
alter table public.procurement_receipts enable row level security; alter table public.procurement_receipt_lines enable row level security; alter table public.supplier_bills enable row level security; alter table public.supplier_bill_lines enable row level security; alter table public.supplier_bill_matches enable row level security;
alter table public.direct_expenses enable row level security; alter table public.direct_expense_lines enable row level security; alter table public.direct_expense_approvals enable row level security; alter table public.operational_cost_events enable row level security;

-- RLS contract: every policy derives organization_id from authenticated active membership and checks the exact permission.
-- Never accept organization_id from the browser. Revoke direct financial mutations from authenticated before integration.
-- Required SECURITY DEFINER RPC contracts (not implemented or integration-tested here):
-- procurement_next_number(document_type, document_year) -> atomic organization-scoped number.
-- procurement_reserve_budget(requisition_id, expected_budget_version, idempotency_key) -> lock and reserve.
-- procurement_release_budget(requisition_id, reason, idempotency_key) -> counter-operation only.
-- procurement_approve_receipt(receipt_id, expected_version, idempotency_key) -> prevent over-receipt atomically.
-- procurement_match_supplier_bill(bill_id, expected versions, tolerance snapshot) -> 2-way/3-way match.
-- procurement_recognize_cost(source_type, source_id, expected_version, idempotency_key) -> one recognized event.
-- procurement_reverse_cost(source_type, source_id, reason, idempotency_key) -> immutable counter-event.
