-- Phase 4 contract. DO NOT apply to a real project in this phase.
-- Money uses numeric(20,3) in PostgreSQL; application Local Adapter uses integer minor units.
create type public.sales_request_status as enum ('new','qualified','needs_pricing','quotation_in_progress','quotation_sent','negotiation','won','lost','cancelled');
create type public.quotation_status as enum ('draft','under_review','changes_requested','approved','rejected_internally','ready_to_send','sent','viewed_demo','accepted_demo','rejected_by_customer_demo','expired','superseded','cancelled');
create type public.approval_status as enum ('pending','approved','rejected','changes_requested','bypassed');

create table public.service_categories(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),code text not null,name_ar text not null,name_en text not null,is_active boolean not null default true,created_by uuid not null references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,unique(organization_id,code),unique(id,organization_id));
create table public.catalog_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),category_id uuid not null,code text not null,name_ar text not null,name_en text not null,description_ar text not null default '',description_en text not null default '',unit text not null,currency char(3) not null,unit_price numeric(20,3) not null check(unit_price>=0),internal_cost numeric(20,3) check(internal_cost>=0),tax_rate numeric(7,4) not null default 0 check(tax_rate between 0 and 100),is_active boolean not null default true,record_version integer not null default 1,created_by uuid not null references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,foreign key(category_id,organization_id) references public.service_categories(id,organization_id),unique(organization_id,code),unique(id,organization_id));
create table public.catalog_packages(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),code text not null,name_ar text not null,name_en text not null,currency char(3) not null,package_price numeric(20,3) not null check(package_price>=0),is_active boolean not null default true,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,unique(organization_id,code),unique(id,organization_id));
create table public.package_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),package_id uuid not null,catalog_item_id uuid not null,quantity numeric(20,3) not null check(quantity>=0),sort_order integer not null default 0,foreign key(package_id,organization_id) references public.catalog_packages(id,organization_id),foreign key(catalog_item_id,organization_id) references public.catalog_items(id,organization_id),unique(package_id,catalog_item_id));

create table public.sales_sequences(organization_id uuid not null references public.organizations(id),sequence_type text not null check(sequence_type in ('request','quotation')),sequence_year integer not null,last_value bigint not null default 0 check(last_value>=0),prefix text not null,primary key(organization_id,sequence_type,sequence_year));
create table public.sales_requests(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),request_number text not null,title text not null,description text not null,customer_id uuid not null,contact_id uuid,lead_id uuid,conversation_id uuid,source text not null,status public.sales_request_status not null default 'new',priority public.lead_priority not null default 'medium',owner_id uuid not null references public.profiles(id),expected_value numeric(20,3) check(expected_value>=0),currency char(3) not null default 'SAR',required_by date,internal_notes text,record_version integer not null default 1,created_by uuid not null references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,foreign key(customer_id,organization_id) references public.customer_accounts(id,organization_id),foreign key(contact_id,organization_id) references public.contacts(id,organization_id),foreign key(lead_id,organization_id) references public.leads(id,organization_id),foreign key(conversation_id,organization_id) references public.conversations(id,organization_id),unique(organization_id,request_number),unique(id,organization_id));
create unique index one_request_per_conversation on public.sales_requests(organization_id,conversation_id) where conversation_id is not null and archived_at is null;
create table public.sales_request_attachments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),sales_request_id uuid not null,file_name text not null,mime_type text not null,size_bytes bigint not null check(size_bytes between 1 and 10485760),storage_path text not null,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),archived_at timestamptz,foreign key(sales_request_id,organization_id) references public.sales_requests(id,organization_id));
create table public.sales_request_status_history(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),sales_request_id uuid not null,old_status public.sales_request_status,new_status public.sales_request_status not null,reason text,actor_id uuid not null references public.profiles(id),created_at timestamptz not null default now(),foreign key(sales_request_id,organization_id) references public.sales_requests(id,organization_id));

create table public.quotation_templates(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name_ar text not null,name_en text not null,language text not null check(language in ('ar','en','bilingual')),logo_path text,company_snapshot jsonb not null default '{}',introduction text not null default '',scope text not null default '',exclusions text not null default '',assumptions text not null default '',payment_terms text not null default '',terms text not null default '',brand_color text not null default '#0f766e',allowed_variables text[] not null default '{}',is_active boolean not null default true,is_default boolean not null default false,created_by uuid not null references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,unique(id,organization_id));
create unique index one_default_quote_template on public.quotation_templates(organization_id) where is_default and archived_at is null;
create table public.quotations(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),quotation_number text not null,sales_request_id uuid not null,customer_id uuid not null,contact_id uuid,conversation_id uuid,current_version_id uuid,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,foreign key(sales_request_id,organization_id) references public.sales_requests(id,organization_id),foreign key(customer_id,organization_id) references public.customer_accounts(id,organization_id),foreign key(contact_id,organization_id) references public.contacts(id,organization_id),foreign key(conversation_id,organization_id) references public.conversations(id,organization_id),unique(organization_id,quotation_number),unique(id,organization_id));
create table public.quotation_versions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),quotation_id uuid not null,version_number integer not null check(version_number>0),display_number text not null,status public.quotation_status not null default 'draft',currency char(3) not null,language text not null check(language in ('ar','en','bilingual')),issue_date date not null,expiry_date date not null check(expiry_date>=issue_date),sales_representative_id uuid not null references public.profiles(id),title text not null,reference text,duration text,quote_discount_rate numeric(7,4) not null default 0 check(quote_discount_rate between 0 and 100),rounding_adjustment numeric(20,3) not null default 0,subtotal numeric(20,3) not null default 0,line_discount_total numeric(20,3) not null default 0,quote_discount_total numeric(20,3) not null default 0,charges_total numeric(20,3) not null default 0,tax_total numeric(20,3) not null default 0,grand_total numeric(20,3) not null default 0,internal_cost_total numeric(20,3) not null default 0,margin_total numeric(20,3) not null default 0,margin_rate numeric(7,4) not null default 0,customer_snapshot jsonb not null,company_snapshot jsonb not null,terms_snapshot jsonb not null,template_snapshot jsonb not null,record_version integer not null default 1,approved_at timestamptz,sent_at timestamptz,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),foreign key(quotation_id,organization_id) references public.quotations(id,organization_id),unique(quotation_id,version_number),unique(organization_id,display_number),unique(id,organization_id));
alter table public.quotations add constraint quotations_current_version_fk foreign key(current_version_id,organization_id) references public.quotation_versions(id,organization_id);
create table public.quotation_sections(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),quotation_version_id uuid not null,title_ar text,title_en text,sort_order integer not null,foreign key(quotation_version_id,organization_id) references public.quotation_versions(id,organization_id),unique(id,organization_id));
create table public.quotation_line_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),quotation_version_id uuid not null,section_id uuid,catalog_item_id uuid,code text not null,description text not null,quantity numeric(20,3) not null check(quantity>=0),unit text not null,unit_price numeric(20,3) not null check(unit_price>=0),internal_cost numeric(20,3) check(internal_cost>=0),discount_rate numeric(7,4) not null default 0 check(discount_rate between 0 and 100),tax_rate numeric(7,4) not null default 0 check(tax_rate between 0 and 100),is_optional boolean not null default false,is_selected boolean not null default true,sort_order integer not null,notes text,foreign key(quotation_version_id,organization_id) references public.quotation_versions(id,organization_id),foreign key(section_id,organization_id) references public.quotation_sections(id,organization_id),foreign key(catalog_item_id,organization_id) references public.catalog_items(id,organization_id),unique(id,organization_id));
create table public.quotation_charges(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),quotation_version_id uuid not null,label text not null,amount numeric(20,3) not null check(amount>=0),tax_rate numeric(7,4) not null default 0 check(tax_rate between 0 and 100),sort_order integer not null default 0,foreign key(quotation_version_id,organization_id) references public.quotation_versions(id,organization_id));
create table public.quotation_terms(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),quotation_version_id uuid not null,term_type text not null,content text not null,sort_order integer not null default 0,foreign key(quotation_version_id,organization_id) references public.quotation_versions(id,organization_id));

create table public.approval_policies(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null,min_total numeric(20,3),min_discount_rate numeric(7,4),min_margin_rate numeric(7,4),currency char(3),service_category_id uuid,is_sequential boolean not null default true,is_active boolean not null default true,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,unique(id,organization_id));
create table public.approval_steps(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),policy_id uuid not null,step_order integer not null check(step_order>0),approver_role_id uuid references public.roles(id),approver_user_id uuid references public.profiles(id),foreign key(policy_id,organization_id) references public.approval_policies(id,organization_id),check(approver_role_id is not null or approver_user_id is not null),unique(policy_id,step_order),unique(id,organization_id));
create table public.approval_requests(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),quotation_version_id uuid not null,policy_id uuid not null,status public.approval_status not null default 'pending',current_step integer not null default 1,idempotency_key text not null,requested_by uuid not null references public.profiles(id),requested_at timestamptz not null default now(),completed_at timestamptz,foreign key(quotation_version_id,organization_id) references public.quotation_versions(id,organization_id),foreign key(policy_id,organization_id) references public.approval_policies(id,organization_id),unique(organization_id,idempotency_key),unique(id,organization_id));
create table public.approval_decisions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),approval_request_id uuid not null,step_order integer not null,actor_id uuid not null references public.profiles(id),decision public.approval_status not null check(decision<>'pending'),comment text not null,created_at timestamptz not null default now(),foreign key(approval_request_id,organization_id) references public.approval_requests(id,organization_id),unique(approval_request_id,step_order,actor_id));

create table public.quotation_dispatches(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),quotation_version_id uuid not null,channel text not null check(channel in ('email_demo','whatsapp_demo','manual')),recipient text not null,subject text not null,body text not null,status text not null check(status in ('draft','queued','sent','delivered','failed')),failure_reason text,idempotency_key text not null,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),foreign key(quotation_version_id,organization_id) references public.quotation_versions(id,organization_id),unique(organization_id,idempotency_key));
create table public.quotation_customer_responses(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),quotation_version_id uuid not null,action text not null check(action in ('viewed','accepted','rejected','changes_requested')),responder_name text not null,reason text,notes text,accepted_optional_item_ids uuid[] not null default '{}',is_legal_acceptance boolean not null default false check(is_legal_acceptance=false),response_snapshot jsonb not null,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),foreign key(quotation_version_id,organization_id) references public.quotation_versions(id,organization_id));
create table public.quotation_status_history(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),quotation_version_id uuid not null,old_status public.quotation_status,new_status public.quotation_status not null,reason text,actor_id uuid not null references public.profiles(id),created_at timestamptz not null default now(),foreign key(quotation_version_id,organization_id) references public.quotation_versions(id,organization_id));

insert into public.permissions(code,name_ar,name_en,module) values
('sales.dashboard.view','عرض لوحة المبيعات','View sales dashboard','sales'),('sales_requests.view','عرض طلبات المبيعات','View sales requests','sales'),('sales_requests.create','إنشاء طلب مبيعات','Create sales request','sales'),('sales_requests.update','تعديل طلب مبيعات','Update sales request','sales'),('sales_requests.assign','إسناد طلب مبيعات','Assign sales request','sales'),('sales_requests.change_status','تغيير حالة الطلب','Change request status','sales'),('sales_requests.close','إغلاق طلب','Close sales request','sales'),('sales_requests.export','تصدير طلبات المبيعات','Export visible sales requests','sales'),('catalog.view','عرض دليل الخدمات','View catalog','sales'),('catalog.manage','إدارة دليل الخدمات','Manage catalog','sales'),('catalog.import','استيراد الدليل','Import catalog','sales'),('catalog.export','تصدير الدليل','Export catalog','sales'),('quotations.view','عرض عروض الأسعار','View quotations','sales'),('quotations.create','إنشاء عرض','Create quotation','sales'),('quotations.update_draft','تعديل مسودة العرض','Update quotation draft','sales'),('quotations.create_revision','إنشاء إصدار جديد','Create quotation revision','sales'),('quotations.view_cost','عرض التكلفة','View quotation cost','sales'),('quotations.view_margin','عرض الهامش','View quotation margin','sales'),('quotations.override_price','تجاوز السعر','Override price','sales'),('quotations.override_discount','تجاوز الخصم','Override discount','sales'),('quotations.submit_for_approval','إرسال للموافقة','Submit quotation for approval','sales'),('quotations.approve','اعتماد العرض','Approve quotation','sales'),('quotations.reject','رفض العرض','Reject quotation','sales'),('quotations.bypass_approval','تجاوز الموافقة','Bypass approval','sales'),('quotations.mark_sent','تسجيل الإرسال','Mark quotation sent','sales'),('quotations.record_customer_response','تسجيل رد العميل','Record customer response','sales'),('quotations.export','تصدير CSV للعروض','Export visible quotations to CSV','sales'),('quotations.export_pdf','تصدير العرض','Export quotation','sales'),('quotation_templates.view','عرض القوالب','View quotation templates','sales'),('quotation_templates.manage','إدارة القوالب','Manage quotation templates','sales'),('sales_reports.view','عرض تقارير المبيعات','View sales reports','sales') on conflict(code) do nothing;

-- Read policies expose internal cost/margin only through a restricted view/RPC in integration.
do $$ declare t text; begin foreach t in array array['service_categories','catalog_items','catalog_packages','package_items','sales_sequences','sales_requests','sales_request_attachments','sales_request_status_history','quotation_templates','quotations','quotation_versions','quotation_sections','quotation_line_items','quotation_charges','quotation_terms','approval_policies','approval_steps','approval_requests','approval_decisions','quotation_dispatches','quotation_customer_responses','quotation_status_history'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy sales_requests_read on public.sales_requests for select using(public.is_org_member(organization_id) and public.has_permission(organization_id,'sales_requests.view'));
create policy quotations_read on public.quotations for select using(public.is_org_member(organization_id) and public.has_permission(organization_id,'quotations.view'));
create policy quotation_versions_read on public.quotation_versions for select using(public.is_org_member(organization_id) and public.has_permission(organization_id,'quotations.view'));
create policy catalog_categories_read on public.service_categories for select using(public.is_org_member(organization_id) and public.has_permission(organization_id,'catalog.view'));
create policy catalog_items_read on public.catalog_items for select using(public.is_org_member(organization_id) and public.has_permission(organization_id,'catalog.view'));
create policy catalog_packages_read on public.catalog_packages for select using(public.is_org_member(organization_id) and public.has_permission(organization_id,'catalog.view'));
create policy quotation_templates_read on public.quotation_templates for select using(public.is_org_member(organization_id) and public.has_permission(organization_id,'quotation_templates.view'));
create policy approval_requests_read on public.approval_requests for select using(public.is_org_member(organization_id) and public.has_permission(organization_id,'quotations.view'));
-- No direct INSERT/UPDATE/DELETE policies: sensitive writes must use reviewed security-definer RPCs.

create or replace function public.next_sales_number(target_org uuid,target_type text) returns text language plpgsql security definer set search_path=public as $$ declare y int:=extract(year from now());n bigint;p text;begin if not public.is_org_member(target_org) then raise exception 'Forbidden';end if;if target_type not in('request','quotation') then raise exception 'Invalid sequence type';end if;insert into public.sales_sequences(organization_id,sequence_type,sequence_year,last_value,prefix) values(target_org,target_type,y,1,case when target_type='request' then 'RFQ' else 'QUO' end) on conflict(organization_id,sequence_type,sequence_year) do update set last_value=public.sales_sequences.last_value+1 returning last_value,prefix into n,p;return p||'-'||y||'-'||lpad(n::text,5,'0');end $$;
revoke all on function public.next_sales_number(uuid,text) from public;grant execute on function public.next_sales_number(uuid,text) to authenticated;
-- Future RPC contracts: create_sales_request_from_conversation, create_quotation_version,
-- submit_quotation_for_approval, decide_quotation_approval, dispatch_quotation_demo,
-- and record_quotation_customer_response must lock rows, derive organization membership,
-- verify record_version/idempotency, write history/timeline/audit, and commit atomically.
