-- Phase eight: project operations, production, quality, progress and handover.
-- Migration contract — not applied or integration-tested.
-- This file must be exercised on an isolated PostgreSQL/Supabase project before merge.

create table public.projects (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), number text not null,
  name text not null, name_en text not null default '', customer_id uuid not null, contract_id uuid not null, currency text not null,
  location text not null default '', description text not null default '', manager_id uuid not null, start_date date not null, target_end_date date not null,
  status text not null default 'draft' check(status in('draft','pending_approval','approved','active','on_hold','ready_for_handover','closed','cancelled','reopened')),
  record_version integer not null default 1 check(record_version>0), idempotency_key text not null, created_by uuid not null, approved_by uuid, created_at timestamptz not null default now(), closed_at timestamptz, deleted_at timestamptz,
  unique(organization_id,id), unique(organization_id,number), unique(organization_id,idempotency_key), check(target_end_date>=start_date)
);
create table public.project_members (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, user_id uuid not null, project_role text not null, active boolean not null default true, created_at timestamptz not null default now(), unique(organization_id,project_id,user_id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.project_charters (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, revision integer not null, status text not null, content jsonb not null default '{}'::jsonb, snapshot jsonb, record_version integer not null default 1, created_by uuid not null, approved_by uuid, approved_at timestamptz, unique(organization_id,project_id,revision), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.project_phases (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, code text not null, name text not null, sort_order integer not null, status text not null default 'planned', unique(organization_id,project_id,code), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.project_wbs_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, parent_id uuid, code text not null, name text not null, description text not null default '', weight_bps integer not null check(weight_bps between 0 and 10000), cost_code_id uuid, sort_order integer not null, active boolean not null default true, record_version integer not null default 1, unique(organization_id,project_id,code), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id), foreign key(organization_id,parent_id) references public.project_wbs_items(organization_id,id));
create table public.project_milestones (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, wbs_id uuid not null, name text not null, planned_date date not null, forecast_date date not null, actual_date date, status text not null, unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id), foreign key(organization_id,wbs_id) references public.project_wbs_items(organization_id,id));
create table public.project_calendars (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, name text not null, timezone text not null, working_week jsonb not null, unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.project_calendar_exceptions (id uuid primary key default gen_random_uuid(), organization_id uuid not null, calendar_id uuid not null, exception_date date not null, working boolean not null, minutes integer not null default 0 check(minutes between 0 and 1440), unique(organization_id,calendar_id,exception_date), foreign key(organization_id,calendar_id) references public.project_calendars(organization_id,id));
create table public.project_schedule_versions (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, revision integer not null, status text not null, reason text not null, snapshot jsonb, record_version integer not null default 1, unique(organization_id,project_id,revision), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.project_baselines (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, number text not null, revision integer not null, status text not null check(status in('draft','pending_approval','approved','rejected','superseded')), reason text not null, snapshot jsonb, record_version integer not null default 1, created_by uuid not null, approved_by uuid, approved_at timestamptz, unique(organization_id,number), unique(organization_id,project_id,revision), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.project_tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, wbs_id uuid not null, code text not null, name text not null, discipline text not null, assignee_id uuid not null, planned_start date not null, planned_finish date not null, forecast_finish date not null, actual_start date, actual_finish date, duration_days integer not null check(duration_days>=0), weight_bps integer not null check(weight_bps between 0 and 10000), progress_bps integer not null default 0 check(progress_bps between 0 and 10000), status text not null, priority text not null, blocker text, quality_hold boolean not null default false, record_version integer not null default 1, created_by uuid not null, unique(organization_id,project_id,code), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id), foreign key(organization_id,wbs_id) references public.project_wbs_items(organization_id,id), check(planned_finish>=planned_start));
create table public.project_baseline_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null, baseline_id uuid not null, task_id uuid not null, planned_start date not null, planned_finish date not null, duration_days integer not null, weight_bps integer not null check(weight_bps between 0 and 10000), unique(organization_id,baseline_id,task_id), foreign key(organization_id,baseline_id) references public.project_baselines(organization_id,id), foreign key(organization_id,task_id) references public.project_tasks(organization_id,id));
create table public.project_task_dependencies (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, predecessor_task_id uuid not null, successor_task_id uuid not null, dependency_type text not null check(dependency_type in('FS','SS','FF','SF')), lag_days integer not null default 0, unique(organization_id,predecessor_task_id,successor_task_id,dependency_type), foreign key(organization_id,project_id) references public.projects(organization_id,id), foreign key(organization_id,predecessor_task_id) references public.project_tasks(organization_id,id), foreign key(organization_id,successor_task_id) references public.project_tasks(organization_id,id), check(predecessor_task_id<>successor_task_id));
create table public.project_task_checklist_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null, task_id uuid not null, label text not null, mandatory boolean not null default false, completed boolean not null default false, completed_by uuid, completed_at timestamptz, foreign key(organization_id,task_id) references public.project_tasks(organization_id,id));
create table public.project_resource_assignments (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, task_id uuid not null, user_id uuid not null, week_start date not null, planned_minutes integer not null check(planned_minutes>=0), role text not null, unique(organization_id,task_id,user_id,week_start), foreign key(organization_id,project_id) references public.projects(organization_id,id), foreign key(organization_id,task_id) references public.project_tasks(organization_id,id));
create table public.timesheets (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, user_id uuid not null, period_start date not null, period_end date not null, status text not null, total_minutes integer not null default 0 check(total_minutes>=0), record_version integer not null default 1, submitted_at timestamptz, approved_by uuid, approved_at timestamptz, correction_of_id uuid, unique(organization_id,project_id,user_id,period_start), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id), foreign key(correction_of_id) references public.timesheets(id), check(period_end>=period_start));
create table public.timesheet_entries (id uuid primary key default gen_random_uuid(), organization_id uuid not null, timesheet_id uuid not null, task_id uuid not null, work_date date not null, minutes integer not null check(minutes between 1 and 1440), description text not null, billable boolean not null default false, labor_rate_minor_snapshot bigint, recognized_cost_event_id uuid, unique(organization_id,timesheet_id,task_id,work_date), foreign key(organization_id,timesheet_id) references public.timesheets(organization_id,id), foreign key(organization_id,task_id) references public.project_tasks(organization_id,id));
create table public.timesheet_approvals (id uuid primary key default gen_random_uuid(), organization_id uuid not null, timesheet_id uuid not null, status text not null, requested_by uuid not null, decided_by uuid, comment text, created_at timestamptz not null default now(), decided_at timestamptz, foreign key(organization_id,timesheet_id) references public.timesheets(organization_id,id));

-- Operational documents share strict organization/project ownership. Attachments are metadata only.
create table public.production_jobs (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, task_id uuid not null, number text not null, title text not null, quantity_mills bigint not null check(quantity_mills>=0), unit text not null, drawing_revision text not null, procurement_readiness text not null, status text not null, record_version integer not null default 1, created_by uuid not null, released_by uuid, unique(organization_id,number), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id), foreign key(organization_id,task_id) references public.project_tasks(organization_id,id));
create table public.production_job_steps (id uuid primary key default gen_random_uuid(), organization_id uuid not null, production_job_id uuid not null, name text not null, sequence integer not null, status text not null, completed_by uuid, completed_at timestamptz, unique(organization_id,production_job_id,sequence), foreign key(organization_id,production_job_id) references public.production_jobs(organization_id,id));
create table public.production_checklist_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null, production_job_id uuid not null, label text not null, mandatory boolean not null, completed boolean not null default false, foreign key(organization_id,production_job_id) references public.production_jobs(organization_id,id));
create table public.site_activities (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, task_id uuid, activity_date date not null, activity_type text not null, details jsonb not null default '{}'::jsonb, status text not null, unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id), foreign key(organization_id,task_id) references public.project_tasks(organization_id,id));
create table public.project_daily_reports (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, number text not null, report_date date not null, shift text not null, weather_text text not null, content jsonb not null default '{}'::jsonb, status text not null, created_by uuid not null, approved_by uuid, unique(organization_id,number), unique(organization_id,id), unique(organization_id,project_id,report_date,shift), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.project_daily_report_labor (id uuid primary key default gen_random_uuid(), organization_id uuid not null, report_id uuid not null, trade text not null, headcount integer not null check(headcount>=0), foreign key(organization_id,report_id) references public.project_daily_reports(organization_id,id));
create table public.project_daily_report_equipment (id uuid primary key default gen_random_uuid(), organization_id uuid not null, report_id uuid not null, equipment text not null, hours numeric(8,2) not null check(hours>=0 and hours<=24), foreign key(organization_id,report_id) references public.project_daily_reports(organization_id,id));

create table public.project_rfis (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, number text not null, subject text not null, question text not null, discipline text not null, document_reference text not null, priority text not null, response_due_date date not null, responsible_party text not null, classification text not null check(classification in('internal','external')), impact boolean not null default false, task_id uuid, status text not null, created_by uuid not null, unique(organization_id,number), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id), foreign key(organization_id,task_id) references public.project_tasks(organization_id,id));
create table public.project_rfi_responses (id uuid primary key default gen_random_uuid(), organization_id uuid not null, rfi_id uuid not null, response text not null, response_date date not null, created_by uuid not null, created_at timestamptz not null default now(), foreign key(organization_id,rfi_id) references public.project_rfis(organization_id,id));
create table public.project_submittals (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, number text not null, type text not null, title text not null, discipline text not null, document_reference text not null, revision text not null, submitted_by uuid not null, submitted_date date not null, review_due_date date not null, reviewer_id uuid not null, status text not null, approved_for_use_internal boolean not null default false, unique(organization_id,number,revision), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.project_submittal_reviews (id uuid primary key default gen_random_uuid(), organization_id uuid not null, submittal_id uuid not null, reviewer_id uuid not null, decision text not null, comments text not null, created_at timestamptz not null default now(), foreign key(organization_id,submittal_id) references public.project_submittals(organization_id,id));
create table public.quality_inspections (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, task_id uuid not null, production_job_id uuid, inspection_type text not null, specification_reference text not null, drawing_revision text not null, inspector_id uuid not null, inspection_date date not null, result text not null, observations text not null, evidence_metadata jsonb not null default '[]'::jsonb, required_action text, reinspection_of_id uuid, approved_by uuid, approved_at timestamptz, immutable boolean not null default false, unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id), foreign key(organization_id,task_id) references public.project_tasks(organization_id,id), foreign key(organization_id,production_job_id) references public.production_jobs(organization_id,id), foreign key(reinspection_of_id) references public.quality_inspections(id));
create table public.quality_inspection_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null, inspection_id uuid not null, item text not null, passed boolean not null, note text not null default '', foreign key(organization_id,inspection_id) references public.quality_inspections(organization_id,id));
create table public.nonconformance_reports (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, number text not null, source text not null, location text not null, discipline text not null, description text not null, violated_requirement text not null, classification text not null, severity text not null check(severity in('minor','major','critical')), root_cause text not null default '', owner_id uuid not null, due_date date not null, status text not null, verification text, closure_approved_by uuid, record_version integer not null default 1, unique(organization_id,number), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.ncr_actions (id uuid primary key default gen_random_uuid(), organization_id uuid not null, ncr_id uuid not null, action_type text not null, description text not null, owner_id uuid not null, due_date date not null, status text not null, evidence_metadata jsonb not null default '[]'::jsonb, foreign key(organization_id,ncr_id) references public.nonconformance_reports(organization_id,id));
create table public.project_snag_lists (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, number text not null, title text not null, status text not null, unique(organization_id,number), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.project_snag_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null, snag_list_id uuid not null, area text not null, location text not null, discipline text not null, description text not null, priority text not null, owner_id uuid not null, due_date date not null, status text not null, before_evidence jsonb not null default '[]'::jsonb, after_evidence jsonb not null default '[]'::jsonb, closure_approved_by uuid, reopen_reason text, foreign key(organization_id,snag_list_id) references public.project_snag_lists(organization_id,id));

create table public.project_risks (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, description text not null, probability integer not null check(probability between 1 and 5), impact integer not null check(impact between 1 and 5), category text not null, score integer generated always as (probability*impact) stored, owner_id uuid not null, trigger_text text not null, mitigation text not null, contingency text not null, due_date date not null, residual_score integer not null check(residual_score between 1 and 25), status text not null, unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.project_issues (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, source text not null, description text not null, priority text not null, impact text not null, owner_id uuid not null, target_resolution date not null, decision text not null default '', actions jsonb not null default '[]'::jsonb, links jsonb not null default '{}'::jsonb, status text not null, unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.project_progress_measurements (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, task_id uuid not null, period_date date not null, planned_bps integer not null check(planned_bps between 0 and 10000), reported_bps integer not null check(reported_bps between 0 and 10000), approved_bps integer not null check(approved_bps between 0 and 10000), previous_approved_bps integer not null check(previous_approved_bps between 0 and 10000), increment_bps integer not null check(increment_bps between -10000 and 10000), method text not null, source text not null, reason text, status text not null, reviewer_id uuid, approved_at timestamptz, snapshot jsonb, idempotency_key text, unique(organization_id,task_id,period_date), unique(organization_id,idempotency_key), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id), foreign key(organization_id,task_id) references public.project_tasks(organization_id,id));
create table public.project_change_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, number text not null, change_type text not null, description text not null, schedule_impact_days integer not null default 0, cost_impact_minor bigint not null default 0, currency text not null, status text not null, record_version integer not null default 1, unique(organization_id,number), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.handover_packages (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, number text not null, scope text not null, readiness text not null, handover_date date, conditional_handover boolean not null default false, final_handover boolean not null default false, lessons_learned jsonb not null default '[]'::jsonb, status text not null, closure_approved_by uuid, record_version integer not null default 1, unique(organization_id,number), unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id));
create table public.handover_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null, handover_id uuid not null, category text not null, label text not null, mandatory boolean not null, complete boolean not null default false, reference_metadata jsonb not null default '{}'::jsonb, foreign key(organization_id,handover_id) references public.handover_packages(organization_id,id));
create table public.project_closeout_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null, project_id uuid not null, handover_id uuid not null, gate_snapshot jsonb not null, override_reason text, approved_by uuid not null, closed_at timestamptz not null default now(), reversal_of_id uuid, unique(organization_id,id), foreign key(organization_id,project_id) references public.projects(organization_id,id), foreign key(organization_id,handover_id) references public.handover_packages(organization_id,id), foreign key(reversal_of_id) references public.project_closeout_records(id));

create index project_status_idx on public.projects(organization_id,status) where deleted_at is null;
create index project_due_idx on public.projects(organization_id,target_end_date) where status in('active','on_hold');
create index project_task_status_idx on public.project_tasks(organization_id,project_id,status);
create index project_task_assignee_idx on public.project_tasks(organization_id,assignee_id,status);
create index project_task_due_idx on public.project_tasks(organization_id,forecast_finish) where status not in('completed','cancelled');
create index project_milestone_due_idx on public.project_milestones(organization_id,forecast_date) where status<>'achieved';
create index timesheet_review_idx on public.timesheets(organization_id,status,period_start) where status in('submitted','under_review');
create index ncr_due_idx on public.nonconformance_reports(organization_id,due_date) where status not in('closed','cancelled');
create index snag_due_idx on public.project_snag_items(organization_id,due_date) where status not in('closed','cancelled');

-- Approved snapshots and inspections are append-only; correction uses a revision/reversal record.
create or replace function public.phase_eight_immutable_guard() returns trigger language plpgsql as $$ begin
  if (tg_table_name='project_baselines' and old.status='approved') or (tg_table_name='quality_inspections' and old.immutable) or (tg_table_name='project_progress_measurements' and old.status='approved') then raise exception 'Approved phase-eight record is immutable; use revision or reversal'; end if; return new;
end $$;
create trigger project_baseline_immutable before update or delete on public.project_baselines for each row execute function public.phase_eight_immutable_guard();
create trigger inspection_immutable before update or delete on public.quality_inspections for each row execute function public.phase_eight_immutable_guard();
create trigger progress_immutable before update or delete on public.project_progress_measurements for each row execute function public.phase_eight_immutable_guard();

-- RPC contracts are intentionally non-operational until their transaction bodies and authorization are integration-tested.
create or replace function public.phase_eight_rpc_contract(operation text, payload jsonb) returns jsonb language plpgsql security invoker as $$ begin raise exception 'Phase eight RPC contract % is not implemented or integration-tested', operation; end $$;
comment on function public.phase_eight_rpc_contract(text,jsonb) is 'Contract entrypoint for atomic numbering, baseline/progress/timesheet approval, labor-cost recognition, closure and reversals. Deliberately fails until implemented and tested.';

do $$ declare t text; begin
  foreach t in array array['projects','project_members','project_charters','project_phases','project_wbs_items','project_milestones','project_calendars','project_calendar_exceptions','project_schedule_versions','project_baselines','project_baseline_items','project_tasks','project_task_dependencies','project_task_checklist_items','project_resource_assignments','timesheets','timesheet_entries','timesheet_approvals','production_jobs','production_job_steps','production_checklist_items','site_activities','project_daily_reports','project_daily_report_labor','project_daily_report_equipment','project_rfis','project_rfi_responses','project_submittals','project_submittal_reviews','quality_inspections','quality_inspection_items','nonconformance_reports','ncr_actions','project_snag_lists','project_snag_items','project_risks','project_issues','project_progress_measurements','project_change_requests','handover_packages','handover_items','project_closeout_records'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('create policy %I on public.%I for select using (organization_id in (select organization_id from public.organization_members where user_id=auth.uid() and status=''active''))',t||'_tenant_select',t);
  end loop;
end $$;

insert into public.permissions(code,module,action,name_ar,description) select code,'projects',split_part(code,'.',3),code,'Phase eight project-operations permission' from unnest(array[
  'projects.view','projects.create','projects.update','projects.charter.approve','projects.team.manage','projects.wbs.manage','projects.schedule.manage','projects.baseline.approve','projects.baseline.revise','projects.tasks.manage','projects.tasks.assign','projects.tasks.update_own','projects.tasks.approve_completion','projects.resources.view','projects.resources.manage','projects.timesheets.submit','projects.timesheets.review','projects.timesheets.approve','projects.labor_rates.view','projects.production.manage','projects.production.release','projects.site.manage','projects.daily_reports.approve','projects.rfis.manage','projects.submittals.manage','projects.submittals.review','projects.quality.manage','projects.ncr.manage','projects.ncr.close','projects.snags.manage','projects.snags.approve_closure','projects.risks.manage','projects.issues.manage','projects.progress.submit','projects.progress.approve','projects.costs.view','projects.profitability.view','projects.handover.manage','projects.closure.approve','projects.reopen','projects.export','projects.print'
]) code on conflict(code) do nothing;

-- No migration is applied by this repository change. No payroll, inventory, GL, client signature or external sending is created.
