import { describe, expect, it } from "vitest";
import { calculateDocument, formatMoney, matchSupplierBill, profitability, roundHalfUp, summarizeCosts, withinTolerance } from "./calculations";
import { createProcurementSeed } from "./seed";

describe("procurement financial calculations", () => {
  it("uses bigint and round-half-up for fractional quantities", () => { expect(roundHalfUp(101n, 500n, 1000n)).toBe(51n); const total = calculateDocument([{ id: "1", description: "x", quantityMills: 1500n, unit: "u", unitPriceMinor: 101n, discountBps: 1000, taxBps: 1500, feesMinor: 2n, costCodeId: "c" }]); expect(total).toEqual({ subtotalMinor: 152n, discountMinor: 15n, taxableMinor: 137n, taxMinor: 21n, feesMinor: 2n, shippingMinor: 0n, totalMinor: 160n }); });
  it("supports zero, large values, and currency decimals", () => { expect(calculateDocument([]).totalMinor).toBe(0n); expect(calculateDocument([{ id: "1", description: "x", quantityMills: 1_000_000n, unit: "u", unitPriceMinor: 9_000_000_000_000n, discountBps: 0, taxBps: 0, feesMinor: 0n, costCodeId: "c" }]).totalMinor).toBe(9_000_000_000_000_000n); expect(formatMoney(123n, "JPY")).toBe("123 JPY"); expect(formatMoney(123n, "SAR")).toBe("1.23 SAR"); expect(formatMoney(123n, "KWD")).toBe("0.123 KWD"); });
  it("enforces central tolerance", () => { expect(withinTolerance(10_000n, 10_100n, 100, 0n)).toBe(true); expect(withinTolerance(10_000n, 10_101n, 100, 0n)).toBe(false); });
  it("matches PO, receipt, and supplier bill without mixing currency", () => { const d = createProcurementSeed(), po = d.purchaseOrders[0], bill = d.supplierBills[0], policy = d.tolerances[0]; expect(matchSupplierBill(po, d.receipts[0].receivedValueMinor, bill, policy).status).toBe("matched"); expect(matchSupplierBill(po, d.receipts[0].receivedValueMinor, { ...bill, currency: "USD" }, policy).status).toBe("mismatch"); });
  it("avoids double-counting commitments, billed receipts, and actuals", () => { const d = createProcurementSeed(), budget = d.budgets[0]; const summary = summarizeCosts({ currency: "SAR", budget, purchaseOrders: d.purchaseOrders, receipts: d.receipts, bills: d.supplierBills, expenses: d.expenses, events: [{ id: "e", organizationId: budget.organizationId, projectId: budget.projectId, contractId: budget.contractId, currency: "SAR", sourceType: "supplier_bill", sourceId: "sb-1", amountMinor: d.supplierBills[0].totals.totalMinor, kind: "recognized", idempotencyKey: "e", occurredAt: "2026-08-01" }] }); expect(summary.recognizedMinor).toBe(d.supplierBills[0].totals.totalMinor); expect(summary.committedMinor).toBe(d.purchaseOrders[0].totals.totalMinor); expect(summary.receivedNotBilledMinor).toBe(0n); expect(summary.forecastEacMinor).toBe(summary.recognizedMinor + summary.remainingCommitmentMinor); });
  it("calculates profitability only in one currency", () => { const d = createProcurementSeed(), budget = d.budgets[0], summary = summarizeCosts({ currency: "SAR", budget, purchaseOrders: d.purchaseOrders, receipts: d.receipts, bills: d.supplierBills, expenses: d.expenses, events: [] }); expect(profitability({ currency: "SAR", currentContractValueMinor: 30_000_000n, customerInvoicesMinor: 5_000_000n, budget, summary }).marginBps).not.toBeNull(); expect(profitability({ currency: "USD", currentContractValueMinor: 30_000_000n, customerInvoicesMinor: 5_000_000n, budget, summary }).warning).toMatch(/Cross-currency/); });
});
