import type { ExpenseStatus, PurchaseOrderStatus, ReceiptStatus, RequisitionStatus, RfqStatus, SupplierBillStatus, SupplierStatus } from "./types";

const transitions = <T extends string>(map: Record<T, readonly T[]>) => ({ can(from: T, to: T) { return map[from]?.includes(to) ?? false; }, assert(from: T, to: T) { if (!this.can(from, to)) throw new Error(`Invalid transition: ${from} -> ${to}`); } });
export const supplierStateMachine = transitions<SupplierStatus>({ draft: ["pending_review", "archived"], pending_review: ["approved", "rejected", "draft"], approved: ["suspended", "archived"], suspended: ["approved", "archived"], rejected: ["draft", "archived"], archived: [] });
export const requisitionStateMachine = transitions<RequisitionStatus>({ draft: ["submitted", "cancelled"], submitted: ["pending_approval", "cancelled"], pending_approval: ["approved", "rejected", "draft"], approved: ["converted", "cancelled"], rejected: ["draft"], converted: [], cancelled: [] });
export const rfqStateMachine = transitions<RfqStatus>({ draft: ["approved", "cancelled"], approved: ["issued_internal", "cancelled"], issued_internal: ["quotes_received", "cancelled"], quotes_received: ["evaluated", "cancelled"], evaluated: ["awarded", "cancelled"], awarded: [], cancelled: [] });
export const purchaseOrderStateMachine = transitions<PurchaseOrderStatus>({ draft: ["pending_approval", "cancelled"], pending_approval: ["approved", "draft", "cancelled"], approved: ["issued_internal", "cancelled"], issued_internal: ["partially_received", "fully_received", "cancelled"], partially_received: ["fully_received", "closed", "cancelled"], fully_received: ["closed"], closed: [], cancelled: [] });
export const receiptStateMachine = transitions<ReceiptStatus>({ draft: ["pending_approval"], pending_approval: ["approved", "draft"], approved: ["reversed"], reversed: [] });
export const supplierBillStateMachine = transitions<SupplierBillStatus>({ draft: ["submitted", "voided"], submitted: ["matching", "returned_for_changes", "rejected", "disputed"], matching: ["pending_approval", "returned_for_changes", "disputed"], pending_approval: ["approved_internal", "returned_for_changes", "rejected", "disputed"], approved_internal: ["recognized_operationally", "disputed", "voided"], recognized_operationally: ["voided"], returned_for_changes: ["draft", "voided"], rejected: ["draft", "voided"], disputed: ["matching", "voided"], voided: [] });
export const expenseStateMachine = transitions<ExpenseStatus>({ draft: ["submitted", "voided"], submitted: ["pending_review", "returned_for_changes", "rejected"], pending_review: ["approved", "returned_for_changes", "rejected"], approved: ["recognized_operationally", "voided"], recognized_operationally: ["voided"], returned_for_changes: ["draft", "voided"], rejected: ["draft", "voided"], voided: [] });
