import { calculateDocument, matchSupplierBill, profitability, summarizeCosts } from "./calculations";
import { expenseStateMachine, purchaseOrderStateMachine, receiptStateMachine, requisitionStateMachine, supplierBillStateMachine, supplierStateMachine } from "./domain";
import { toSafeCsv } from "./csv";
import { expenseCreateSchema, requisitionCreateSchema, supplierBillCreateSchema, supplierCreateSchema } from "./schemas";
import { createProcurementSeed } from "./seed";
import type { Approval, CostSummary, DirectExpense, ExpenseStatus, Paged, ProcurementData, ProcurementReceipt, ProfitabilityView, PurchaseOrder, PurchaseOrderStatus, PurchaseRequisition, RequisitionStatus, Supplier, SupplierBill, SupplierBillStatus, SupplierStatus } from "./types";

export class ProcurementError extends Error { constructor(public code: "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CROSS_TENANT" | "INVALID" | "CONFLICT" | "DUPLICATE" | "OVER_BUDGET", message: string) { super(message); } }
const clean = (value: string) => value.replace(/[<>]/g, "").trim();
const now = () => new Date().toISOString();

export interface ProcurementRepository {
  snapshot(org: string, actor: string): ProcurementData;
  listSuppliers(org: string, actor: string, query?: string, page?: number, pageSize?: number): Paged<Supplier>;
  createSupplier(input: { organizationId: string; actorId: string; legalName: string; displayName: string; taxNumber?: string; country: string; city: string; categories: string[]; contactName: string; phone: string; email: string }): Supplier;
  transitionSupplier(org: string, actor: string, id: string, to: SupplierStatus, reason?: string): Supplier;
  createRequisition(input: { organizationId: string; actorId: string; projectId: string; contractId: string; workOrderId?: string; costCenterId: string; budgetId: string; currency: string; needByDate: string; justification: string; description: string; quantityMills: bigint; unitPriceMinor: bigint; costCodeId: string; overrideReason?: string; idempotencyKey: string }): PurchaseRequisition;
  transitionRequisition(org: string, actor: string, id: string, to: RequisitionStatus): PurchaseRequisition;
  createPurchaseOrder(org: string, actor: string, comparisonId: string, idempotencyKey: string): PurchaseOrder;
  transitionPurchaseOrder(org: string, actor: string, id: string, to: PurchaseOrderStatus): PurchaseOrder;
  receive(input: { organizationId: string; actorId: string; purchaseOrderId: string; lineQuantityMills: bigint; qualityStatus: "accepted" | "conditionally_accepted" | "rejected"; idempotencyKey: string }): ProcurementReceipt;
  transitionReceipt(org: string, actor: string, id: string, to: "pending_approval" | "approved" | "reversed", reason?: string): ProcurementReceipt;
  createSupplierBill(input: { organizationId: string; actorId: string; supplierId: string; purchaseOrderId: string; receiptIds: string[]; supplierInvoiceNumber: string; invoiceDate: string; dueDate: string; matchType: "two_way" | "three_way"; idempotencyKey: string }): SupplierBill;
  transitionSupplierBill(org: string, actor: string, id: string, to: SupplierBillStatus): SupplierBill;
  createExpense(input: { organizationId: string; actorId: string; projectId: string; contractId: string; costCenterId: string; costCodeId: string; expenseType: string; party: string; date: string; currency: string; description: string; amountMinor: bigint; directPurchaseReason: string; paymentMethodLabel: string; reference: string; idempotencyKey: string }): DirectExpense;
  transitionExpense(org: string, actor: string, id: string, to: ExpenseStatus, reason?: string): DirectExpense;
  costSummary(org: string, actor: string, projectId: string, currency: string): CostSummary;
  profitability(org: string, actor: string, projectId: string, currency: string): ProfitabilityView;
  exportSuppliers(org: string, actor: string): string;
}

export class LocalProcurementRepository implements ProcurementRepository {
  private data: ProcurementData;
  constructor(seed: ProcurementData = createProcurementSeed()) { this.data = structuredClone(seed); }
  private user(org: string, actor: string, permission?: string) { const user = this.data.users.find(x => x.id === actor); if (!user) throw new ProcurementError("UNAUTHORIZED", "Unknown user"); if (user.organizationId !== org) throw new ProcurementError("CROSS_TENANT", "Cross-organization actor denied"); if (permission && !user.permissions.includes(permission)) throw new ProcurementError("FORBIDDEN", `Missing permission: ${permission}`); return user; }
  private owned<T extends { id: string; organizationId: string }>(rows: T[], org: string, id: string) { const row = rows.find(x => x.id === id); if (!row) throw new ProcurementError("NOT_FOUND", "Record not found"); if (row.organizationId !== org) throw new ProcurementError("CROSS_TENANT", "Cross-organization access denied"); return row; }
  private page<T>(rows: T[], page = 1, pageSize = 20): Paged<T> { const size = Math.min(100, Math.max(1, pageSize)), total = rows.length, pages = Math.max(1, Math.ceil(total / size)), safe = Math.min(Math.max(1, page), pages); return { rows: rows.slice((safe - 1) * size, safe * size), page: safe, pageSize: size, total, pages }; }
  private next(org: string, type: "supplier" | "requisition" | "po" | "receipt" | "bill" | "expense") { const key = `${org}:${type}`, value = (this.data.sequences[key] ?? 0) + 1; this.data.sequences[key] = value; const prefix = { supplier: "SUP", requisition: "PR", po: "PO", receipt: "REC-P", bill: "SB", expense: "EXP" }[type]; return `${prefix}-${new Date().getUTCFullYear()}-${String(value).padStart(5, "0")}`; }
  private trace(org: string, actor: string, entityType: string, entityId: string, action: string, summary: string, links: Record<string, string> = {}) { this.data.timeline.push({ id: `pe-${crypto.randomUUID()}`, organizationId: org, entityType, entityId, action, summary: clean(summary).slice(0, 500), createdBy: actor, createdAt: now(), links }); }
  private notify(org: string, userId: string, type: string, entityType: string, entityId: string, title: string) { const dedupeKey = `${type}:${entityId}`; if (!this.data.notifications.some(x => x.organizationId === org && x.dedupeKey === dedupeKey)) this.data.notifications.push({ id: `pn-${crypto.randomUUID()}`, organizationId: org, userId, type, entityType, entityId, title, dedupeKey, read: false, createdAt: now() }); }
  private idempotent(key: string) { if (this.data.idempotencyKeys.includes(key)) throw new ProcurementError("DUPLICATE", "Duplicate idempotency key"); this.data.idempotencyKeys.push(key); }
  private approval(org: string, entityType: string, entityId: string, requestedBy: string): Approval { const approval = { id: `pa-${crypto.randomUUID()}`, organizationId: org, entityType, entityId, requestedBy, status: "pending" as const, createdAt: now() }; this.data.approvals.push(approval); return approval; }

  snapshot(org: string, actor: string) {
    const user = this.user(org, actor); if (!user.permissions.some(permission => permission.startsWith("procurement.") || permission.startsWith("suppliers.") || permission.startsWith("cost_codes.") || permission.startsWith("budgets.") || permission.startsWith("purchase_requests.") || permission.startsWith("rfqs.") || permission.startsWith("supplier_quotes.") || permission.startsWith("bid_comparisons.") || permission.startsWith("purchase_orders.") || permission.startsWith("receipts.") || permission.startsWith("supplier_bills.") || permission.startsWith("expenses.") || permission.startsWith("cost_reports.") || permission.startsWith("profitability."))) throw new ProcurementError("FORBIDDEN", "Procurement access denied"); const clone = structuredClone(this.data);
    for (const key of Object.keys(clone) as (keyof ProcurementData)[]) { const value = clone[key]; if (Array.isArray(value)) (clone[key] as unknown[]) = value.filter((x: unknown) => typeof x !== "object" || x === null || !("organizationId" in x) || (x as { organizationId: string }).organizationId === org) as never; }
    if (!user.permissions.includes("budgets.view_financials")) for (const b of clone.budgets) { b.totalMinor = 0n; b.lines = []; b.snapshot = undefined; }
    if (!user.permissions.includes("purchase_orders.view_financials")) for (const po of clone.purchaseOrders) { po.lines = []; po.totals = calculateDocument([]); po.receivedValueMinor = 0n; po.billedValueMinor = 0n; po.recognizedValueMinor = 0n; }
    if (!user.permissions.includes("profitability.view_sensitive")) clone.costEvents = [];
    return clone;
  }
  listSuppliers(org: string, actor: string, query = "", page = 1, pageSize = 20) { this.user(org, actor, "suppliers.view"); const q = query.trim().toLowerCase(), rows = this.data.suppliers.filter(x => x.organizationId === org && (!q || `${x.code} ${x.legalName} ${x.displayName} ${x.email}`.toLowerCase().includes(q))).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); return this.page(rows.map(x => structuredClone(x)), page, pageSize); }
  createSupplier(raw: Parameters<ProcurementRepository["createSupplier"]>[0]) { const input = supplierCreateSchema.parse(raw); this.user(input.organizationId, input.actorId, "suppliers.create"); const duplicateKey = `${input.legalName.toLowerCase().replace(/\s/g, "-")}|${(input.taxNumber || input.email).toLowerCase()}`; if (this.data.suppliers.some(x => x.organizationId === input.organizationId && x.duplicateKey === duplicateKey && x.status !== "archived")) throw new ProcurementError("DUPLICATE", "Potential duplicate supplier"); const supplier: Supplier = { id: `sup-${crypto.randomUUID()}`, organizationId: input.organizationId, code: this.next(input.organizationId, "supplier"), legalName: clean(input.legalName), displayName: clean(input.displayName), taxNumber: input.taxNumber, country: clean(input.country), city: clean(input.city), categories: input.categories.map(clean), contactName: clean(input.contactName), phone: clean(input.phone), email: input.email.toLowerCase(), status: "draft", duplicateKey, recordVersion: 1, createdBy: input.actorId, createdAt: now(), attachments: [] }; this.data.suppliers.push(supplier); this.trace(input.organizationId, input.actorId, "supplier", supplier.id, "created", supplier.displayName); this.notify(input.organizationId, "u-owner", "supplier_created", "supplier", supplier.id, "تم إنشاء مورد جديد"); return structuredClone(supplier); }
  transitionSupplier(org: string, actor: string, id: string, to: SupplierStatus, reason = "") { const supplier = this.owned(this.data.suppliers, org, id); const permission = to === "pending_review" ? "suppliers.submit" : to === "suspended" ? "suppliers.suspend" : ["approved", "rejected"].includes(to) ? "suppliers.approve" : "suppliers.update"; this.user(org, actor, permission); supplierStateMachine.assert(supplier.status, to); if (["approved", "rejected", "suspended"].includes(to) && supplier.createdBy === actor) throw new ProcurementError("FORBIDDEN", "Maker-checker separation required"); if (to === "suspended" && !clean(reason)) throw new ProcurementError("INVALID", "Suspension reason is required"); supplier.status = to; supplier.recordVersion++; if (to === "approved") supplier.approvedBy = actor; if (to === "suspended") supplier.suspensionReason = clean(reason); this.trace(org, actor, "supplier", id, to, reason || supplier.displayName); return structuredClone(supplier); }
  createRequisition(raw: Parameters<ProcurementRepository["createRequisition"]>[0]) { const input = requisitionCreateSchema.parse(raw); const user = this.user(input.organizationId, input.actorId, "purchase_requests.create"); this.idempotent(input.idempotencyKey); const budget = this.owned(this.data.budgets, input.organizationId, input.budgetId); if (budget.status !== "approved_baseline" || budget.projectId !== input.projectId || budget.contractId !== input.contractId || budget.currency !== input.currency) throw new ProcurementError("INVALID", "Approved matching budget is required"); const line = { id: `prl-${crypto.randomUUID()}`, description: clean(input.description), quantityMills: input.quantityMills, unit: "وحدة", unitPriceMinor: input.unitPriceMinor, discountBps: 0, taxBps: 1500, feesMinor: 0n, costCodeId: input.costCodeId }, totals = calculateDocument([line]); const existing = this.data.requisitions.filter(x => x.organizationId === input.organizationId && x.budgetId === budget.id && x.status !== "cancelled").reduce((sum, x) => sum + x.totals.totalMinor, 0n), available = budget.totalMinor - existing, overBudget = totals.totalMinor > available; if (overBudget && !user.permissions.includes("procurement.override_budget")) throw new ProcurementError("OVER_BUDGET", "Budget exceeded and override permission is missing"); if (overBudget && !input.overrideReason) throw new ProcurementError("INVALID", "Override reason is required"); const requisition: PurchaseRequisition = { id: `pr-${crypto.randomUUID()}`, organizationId: input.organizationId, number: this.next(input.organizationId, "requisition"), projectId: input.projectId, contractId: input.contractId, workOrderId: input.workOrderId, costCenterId: input.costCenterId, currency: input.currency, requestedBy: input.actorId, needByDate: input.needByDate, justification: clean(input.justification), status: "draft", lines: [line], totals, budgetId: budget.id, budgetAvailableMinor: available, overBudget, overrideReason: input.overrideReason && clean(input.overrideReason), recordVersion: 1, createdBy: input.actorId, createdAt: now() }; this.data.requisitions.push(requisition); this.trace(input.organizationId, input.actorId, "purchase_requisition", requisition.id, "created", requisition.number, { projectId: input.projectId, contractId: input.contractId, workOrderId: input.workOrderId || "" }); if (overBudget) this.notify(input.organizationId, "u-owner", "over_budget", "purchase_requisition", requisition.id, "طلب شراء يتجاوز الميزانية"); return structuredClone(requisition); }
  transitionRequisition(org: string, actor: string, id: string, to: RequisitionStatus) { const row = this.owned(this.data.requisitions, org, id); const permission = to === "submitted" ? "purchase_requests.submit" : to === "approved" || to === "rejected" ? "purchase_requests.approve" : to === "cancelled" ? "purchase_requests.cancel" : "purchase_requests.create"; this.user(org, actor, permission); requisitionStateMachine.assert(row.status, to); if (["approved", "rejected"].includes(to) && row.createdBy === actor) throw new ProcurementError("FORBIDDEN", "Maker-checker separation required"); if (to === "submitted") { row.status = "submitted"; this.approval(org, "purchase_requisition", id, actor); row.status = "pending_approval"; } else { row.status = to; } if (to === "approved") row.approvedBy = actor; row.recordVersion++; this.trace(org, actor, "purchase_requisition", id, to, row.number, { projectId: row.projectId, contractId: row.contractId }); return structuredClone(row); }
  createPurchaseOrder(org: string, actor: string, comparisonId: string, idempotencyKey: string) { this.user(org, actor, "purchase_orders.create"); this.idempotent(idempotencyKey); const comparison = this.owned(this.data.comparisons, org, comparisonId); if (comparison.status !== "approved" || !comparison.recommendedQuotationId) throw new ProcurementError("INVALID", "Approved award decision is required"); if (this.data.purchaseOrders.some(x => x.organizationId === org && x.comparisonId === comparisonId && x.status !== "cancelled")) throw new ProcurementError("DUPLICATE", "Purchase order already created from this award"); const quote = this.owned(this.data.quotations, org, comparison.recommendedQuotationId), rfq = this.owned(this.data.rfqs, org, comparison.rfqId), requisition = this.owned(this.data.requisitions, org, rfq.requisitionId), supplier = this.owned(this.data.suppliers, org, quote.supplierId); if (supplier.status !== "approved" || quote.currency !== comparison.currency || requisition.currency !== quote.currency) throw new ProcurementError("INVALID", "Approved supplier and matching currency are required"); const po: PurchaseOrder = { id: `po-${crypto.randomUUID()}`, organizationId: org, number: `${this.next(org, "po")}-R1`, requisitionId: requisition.id, rfqId: rfq.id, comparisonId, supplierQuotationId: quote.id, supplierId: supplier.id, projectId: requisition.projectId, contractId: requisition.contractId, currency: quote.currency, status: "draft", lines: structuredClone(quote.lines), totals: structuredClone(quote.totals), receivedValueMinor: 0n, billedValueMinor: 0n, recognizedValueMinor: 0n, revision: 1, snapshot: { supplier: supplier.displayName, requisition: requisition.number, comparison: comparison.number, notice: "Internal demo purchase order" }, recordVersion: 1, createdBy: actor, createdAt: now() }; this.data.purchaseOrders.push(po); requisition.status = "converted"; requisition.recordVersion++; this.trace(org, actor, "purchase_order", po.id, "created", po.number, { projectId: po.projectId, contractId: po.contractId, supplierId: po.supplierId }); return structuredClone(po); }
  transitionPurchaseOrder(org: string, actor: string, id: string, to: PurchaseOrderStatus) { const po = this.owned(this.data.purchaseOrders, org, id), permission = to === "pending_approval" ? "purchase_orders.create" : to === "approved" ? "purchase_orders.approve" : to === "issued_internal" ? "purchase_orders.issue_internal" : to === "cancelled" ? "purchase_orders.cancel" : "purchase_orders.revise"; this.user(org, actor, permission); purchaseOrderStateMachine.assert(po.status, to); if (["approved", "issued_internal"].includes(to) && po.createdBy === actor) throw new ProcurementError("FORBIDDEN", "Maker-checker separation required"); po.status = to; po.recordVersion++; if (to === "approved") po.approvedBy = actor; if (to === "issued_internal") po.issuedAt = now(); this.trace(org, actor, "purchase_order", id, to, po.number, { projectId: po.projectId, contractId: po.contractId, supplierId: po.supplierId }); return structuredClone(po); }
  receive(input: Parameters<ProcurementRepository["receive"]>[0]) { this.user(input.organizationId, input.actorId, "receipts.create"); this.idempotent(input.idempotencyKey); const po = this.owned(this.data.purchaseOrders, input.organizationId, input.purchaseOrderId); if (!["issued_internal", "partially_received"].includes(po.status)) throw new ProcurementError("INVALID", "Issued purchase order is required"); if (input.lineQuantityMills <= 0n) throw new ProcurementError("INVALID", "Receipt quantity must be positive"); const ordered = po.lines[0]?.quantityMills ?? 0n, prior = this.data.receipts.filter(x => x.organizationId === input.organizationId && x.purchaseOrderId === po.id && x.status !== "reversed").reduce((sum, x) => sum + (x.lines[0]?.quantityMills ?? 0n), 0n); if (prior + input.lineQuantityMills > ordered) throw new ProcurementError("INVALID", "Receipt exceeds remaining purchase order quantity"); const value = calculateDocument([{ ...po.lines[0], quantityMills: input.lineQuantityMills }]).totalMinor, receipt: ProcurementReceipt = { id: `grn-${crypto.randomUUID()}`, organizationId: input.organizationId, number: this.next(input.organizationId, "receipt"), purchaseOrderId: po.id, supplierId: po.supplierId, projectId: po.projectId, date: now().slice(0, 10), receiverId: input.actorId, status: "draft", lines: [{ id: `grnl-${crypto.randomUUID()}`, purchaseOrderLineId: po.lines[0].id, quantityMills: input.lineQuantityMills, qualityStatus: input.qualityStatus, notes: "" }], receivedValueMinor: input.qualityStatus === "rejected" ? 0n : value, attachments: [], recordVersion: 1, createdAt: now() }; this.data.receipts.push(receipt); this.trace(input.organizationId, input.actorId, "procurement_receipt", receipt.id, "created", receipt.number, { purchaseOrderId: po.id, projectId: po.projectId, supplierId: po.supplierId }); return structuredClone(receipt); }
  transitionReceipt(org: string, actor: string, id: string, to: "pending_approval" | "approved" | "reversed", reason = "") { const receipt = this.owned(this.data.receipts, org, id), permission = to === "approved" ? "receipts.approve" : to === "reversed" ? "receipts.reverse" : "receipts.create"; this.user(org, actor, permission); receiptStateMachine.assert(receipt.status, to); if (to === "approved" && receipt.receiverId === actor) throw new ProcurementError("FORBIDDEN", "Receiver cannot approve the same receipt"); if (to === "reversed" && !clean(reason)) throw new ProcurementError("INVALID", "Reversal reason is required"); const po = this.owned(this.data.purchaseOrders, org, receipt.purchaseOrderId); if (to === "approved") { receipt.approvedBy = actor; po.receivedValueMinor += receipt.receivedValueMinor; const ordered = po.lines[0]?.quantityMills ?? 0n, approved = this.data.receipts.filter(x => x.organizationId === org && x.purchaseOrderId === po.id && (x.status === "approved" || x.id === receipt.id)).reduce((s, x) => s + (x.lines[0]?.quantityMills ?? 0n), 0n); po.status = approved >= ordered ? "fully_received" : "partially_received"; } if (to === "reversed") { receipt.reversalReason = clean(reason); po.receivedValueMinor -= receipt.receivedValueMinor; po.status = "partially_received"; } receipt.status = to; receipt.recordVersion++; po.recordVersion++; this.trace(org, actor, "procurement_receipt", id, to, reason || receipt.number, { purchaseOrderId: po.id, projectId: po.projectId, supplierId: po.supplierId }); return structuredClone(receipt); }
  createSupplierBill(raw: Parameters<ProcurementRepository["createSupplierBill"]>[0]) { const input = supplierBillCreateSchema.parse(raw); this.user(input.organizationId, input.actorId, "supplier_bills.create"); this.idempotent(input.idempotencyKey); if (this.data.supplierBills.some(x => x.organizationId === input.organizationId && x.supplierId === input.supplierId && x.supplierInvoiceNumber.toLowerCase() === input.supplierInvoiceNumber.toLowerCase() && x.status !== "voided")) throw new ProcurementError("DUPLICATE", "Duplicate supplier invoice number"); const po = this.owned(this.data.purchaseOrders, input.organizationId, input.purchaseOrderId), supplier = this.owned(this.data.suppliers, input.organizationId, input.supplierId); if (supplier.status !== "approved" || po.supplierId !== supplier.id) throw new ProcurementError("INVALID", "Approved matching supplier is required"); const receipts = input.receiptIds.map(id => this.owned(this.data.receipts, input.organizationId, id)); if (receipts.some(x => x.purchaseOrderId !== po.id || x.supplierId !== supplier.id || x.status !== "approved")) throw new ProcurementError("INVALID", "Approved matching receipts are required"); const receivedValue = receipts.reduce((s, x) => s + x.receivedValueMinor, 0n), ratioQuantity = receivedValue > 0n && po.totals.totalMinor > 0n ? (po.lines[0].quantityMills * receivedValue) / po.totals.totalMinor : po.lines[0].quantityMills, line = { ...po.lines[0], id: `sbl-${crypto.randomUUID()}`, quantityMills: input.matchType === "three_way" ? ratioQuantity : po.lines[0].quantityMills }, totals = calculateDocument([line]); const bill: SupplierBill = { id: `sb-${crypto.randomUUID()}`, organizationId: input.organizationId, number: this.next(input.organizationId, "bill"), supplierInvoiceNumber: clean(input.supplierInvoiceNumber), supplierId: supplier.id, purchaseOrderId: po.id, receiptIds: input.receiptIds, projectId: po.projectId, contractId: po.contractId, currency: po.currency, invoiceDate: input.invoiceDate, dueDate: input.dueDate, lines: [line], totals, eligibleRecognitionMinor: 0n, matchType: input.matchType, matchStatus: "not_checked", dispute: false, status: "draft", recordVersion: 1, idempotencyKey: input.idempotencyKey, createdBy: input.actorId, createdAt: now() }; this.data.supplierBills.push(bill); this.trace(input.organizationId, input.actorId, "supplier_bill", bill.id, "created", bill.number, { purchaseOrderId: po.id, projectId: po.projectId, supplierId: supplier.id }); return structuredClone(bill); }
  transitionSupplierBill(org: string, actor: string, id: string, to: SupplierBillStatus) { const bill = this.owned(this.data.supplierBills, org, id), permission = to === "matching" ? "supplier_bills.match" : to === "approved_internal" ? "supplier_bills.approve" : to === "recognized_operationally" ? "supplier_bills.recognize" : "supplier_bills.create"; this.user(org, actor, permission); supplierBillStateMachine.assert(bill.status, to); if (["approved_internal", "recognized_operationally"].includes(to) && bill.createdBy === actor) throw new ProcurementError("FORBIDDEN", "Maker-checker separation required"); const po = this.owned(this.data.purchaseOrders, org, bill.purchaseOrderId); if (to === "matching") { const received = bill.receiptIds.map(rid => this.owned(this.data.receipts, org, rid)).filter(x => x.status === "approved").reduce((s, x) => s + x.receivedValueMinor, 0n), policy = this.data.tolerances.find(x => x.organizationId === org)!; const result = matchSupplierBill(po, received, bill, policy); bill.matchStatus = result.status; if (result.status === "mismatch") { bill.dispute = true; bill.status = "disputed"; } else { bill.eligibleRecognitionMinor = bill.totals.totalMinor; bill.status = "pending_approval"; } } else if (to === "approved_internal") { if (!["matched", "within_tolerance"].includes(bill.matchStatus)) throw new ProcurementError("INVALID", "Successful match is required"); bill.status = to; bill.approvedBy = actor; po.billedValueMinor += bill.totals.totalMinor; po.recordVersion++; } else if (to === "recognized_operationally") { if (this.data.costEvents.some(x => x.organizationId === org && x.sourceType === "supplier_bill" && x.sourceId === bill.id && x.kind === "recognized")) throw new ProcurementError("DUPLICATE", "Supplier bill already recognized"); bill.status = to; bill.recognizedAt = now(); this.data.costEvents.push({ id: `ce-${crypto.randomUUID()}`, organizationId: org, projectId: bill.projectId, contractId: bill.contractId, currency: bill.currency, sourceType: "supplier_bill", sourceId: bill.id, amountMinor: bill.eligibleRecognitionMinor, kind: "recognized", idempotencyKey: `recognize:${bill.id}`, occurredAt: now() }); po.recognizedValueMinor += bill.eligibleRecognitionMinor; po.recordVersion++; } else bill.status = to; bill.recordVersion++; this.trace(org, actor, "supplier_bill", id, bill.status, bill.number, { purchaseOrderId: po.id, projectId: po.projectId, supplierId: po.supplierId }); return structuredClone(bill); }
  createExpense(raw: Parameters<ProcurementRepository["createExpense"]>[0]) { const input = expenseCreateSchema.parse(raw); this.user(input.organizationId, input.actorId, "expenses.create"); this.idempotent(input.idempotencyKey); const budget = this.data.budgets.find(x => x.organizationId === input.organizationId && x.projectId === input.projectId && x.contractId === input.contractId && x.currency === input.currency && x.status === "approved_baseline"); if (!budget) throw new ProcurementError("INVALID", "Matching approved budget is required"); const line = { id: `exl-${crypto.randomUUID()}`, description: clean(input.description), quantityMills: 1000n, unit: "مصروف", unitPriceMinor: input.amountMinor, discountBps: 0, taxBps: 0, feesMinor: 0n, costCodeId: input.costCodeId }, expense: DirectExpense = { id: `exp-${crypto.randomUUID()}`, organizationId: input.organizationId, number: this.next(input.organizationId, "expense"), expenseType: clean(input.expenseType), projectId: input.projectId, contractId: input.contractId, costCenterId: input.costCenterId, costCodeId: input.costCodeId, party: clean(input.party), date: input.date, currency: input.currency, description: clean(input.description), paymentMethodLabel: clean(input.paymentMethodLabel), reference: clean(input.reference), directPurchaseReason: clean(input.directPurchaseReason), lines: [line], totals: calculateDocument([line]), status: "draft", recordVersion: 1, idempotencyKey: input.idempotencyKey, createdBy: input.actorId, attachments: [], createdAt: now() }; this.data.expenses.push(expense); this.trace(input.organizationId, input.actorId, "direct_expense", expense.id, "created", expense.number, { projectId: expense.projectId, contractId: expense.contractId }); return structuredClone(expense); }
  transitionExpense(org: string, actor: string, id: string, to: ExpenseStatus, reason = "") { const expense = this.owned(this.data.expenses, org, id), permission = to === "submitted" ? "expenses.submit" : to === "approved" ? "expenses.approve" : to === "recognized_operationally" ? "expenses.recognize" : "expenses.create"; this.user(org, actor, permission); expenseStateMachine.assert(expense.status, to); if (["approved", "recognized_operationally"].includes(to) && expense.createdBy === actor) throw new ProcurementError("FORBIDDEN", "Maker-checker separation required"); if (to === "recognized_operationally") { if (this.data.costEvents.some(x => x.organizationId === org && x.sourceType === "direct_expense" && x.sourceId === expense.id && x.kind === "recognized")) throw new ProcurementError("DUPLICATE", "Expense already recognized"); expense.recognizedAt = now(); this.data.costEvents.push({ id: `ce-${crypto.randomUUID()}`, organizationId: org, projectId: expense.projectId, contractId: expense.contractId, currency: expense.currency, sourceType: "direct_expense", sourceId: expense.id, amountMinor: expense.totals.totalMinor, kind: "recognized", idempotencyKey: `recognize:${expense.id}`, occurredAt: now() }); } if (to === "voided" && expense.status === "recognized_operationally") { if (!clean(reason)) throw new ProcurementError("INVALID", "Reversal reason is required"); expense.reversalReason = clean(reason); this.data.costEvents.push({ id: `ce-${crypto.randomUUID()}`, organizationId: org, projectId: expense.projectId, contractId: expense.contractId, currency: expense.currency, sourceType: "reversal", sourceId: expense.id, amountMinor: expense.totals.totalMinor, kind: "reversed", idempotencyKey: `reverse:${expense.id}`, occurredAt: now() }); } expense.status = to; if (to === "approved") expense.approvedBy = actor; expense.recordVersion++; this.trace(org, actor, "direct_expense", id, to, reason || expense.number, { projectId: expense.projectId, contractId: expense.contractId }); return structuredClone(expense); }
  costSummary(org: string, actor: string, projectId: string, currency: string) { this.user(org, actor, "cost_reports.view"); const budget = this.data.budgets.find(x => x.organizationId === org && x.projectId === projectId && x.currency === currency && x.status === "approved_baseline"); if (!budget) throw new ProcurementError("NOT_FOUND", "Budget not found"); return summarizeCosts({ currency: budget.currency, budget, purchaseOrders: this.data.purchaseOrders.filter(x => x.organizationId === org && x.projectId === projectId), receipts: this.data.receipts.filter(x => x.organizationId === org && x.projectId === projectId), bills: this.data.supplierBills.filter(x => x.organizationId === org && x.projectId === projectId), expenses: this.data.expenses.filter(x => x.organizationId === org && x.projectId === projectId), events: this.data.costEvents.filter(x => x.organizationId === org && x.projectId === projectId) }); }
  profitability(org: string, actor: string, projectId: string, currency: string) { this.user(org, actor, "profitability.view"); const summary = this.costSummary(org, actor, projectId, currency), budget = this.data.budgets.find(x => x.organizationId === org && x.projectId === projectId && x.currency === currency)!; return profitability({ currency: budget.currency, currentContractValueMinor: 30_000_000n, customerInvoicesMinor: 5_520_000n, budget, summary }); }
  exportSuppliers(org: string, actor: string) { this.user(org, actor, "suppliers.export"); const rows = this.data.suppliers.filter(x => x.organizationId === org).map(x => [x.code, x.legalName, x.city, x.status, x.email]); return toSafeCsv(["Code", "Legal name", "City", "Status", "Email"], rows); }
}

export class SupabaseProcurementRepository implements ProcurementRepository {
  private fail(): never { throw new ProcurementError("INVALID", "Supabase procurement adapter contract exists but is not implemented or integration-tested"); }
  snapshot(): ProcurementData { return this.fail(); } listSuppliers(): Paged<Supplier> { return this.fail(); } createSupplier(): Supplier { return this.fail(); } transitionSupplier(): Supplier { return this.fail(); } createRequisition(): PurchaseRequisition { return this.fail(); } transitionRequisition(): PurchaseRequisition { return this.fail(); } createPurchaseOrder(): PurchaseOrder { return this.fail(); } transitionPurchaseOrder(): PurchaseOrder { return this.fail(); } receive(): ProcurementReceipt { return this.fail(); } transitionReceipt(): ProcurementReceipt { return this.fail(); } createSupplierBill(): SupplierBill { return this.fail(); } transitionSupplierBill(): SupplierBill { return this.fail(); } createExpense(): DirectExpense { return this.fail(); } transitionExpense(): DirectExpense { return this.fail(); } costSummary(): CostSummary { return this.fail(); } profitability(): ProfitabilityView { return this.fail(); } exportSuppliers(): string { return this.fail(); }
}
