import { beforeEach, describe, expect, it } from "vitest";
import { LocalProcurementRepository, ProcurementError, SupabaseProcurementRepository } from "./repository";

let repo: LocalProcurementRepository;
const org = "org-madar-demo";
beforeEach(() => { repo = new LocalProcurementRepository(); });
const supplierInput = { organizationId: org, actorId: "u-admin", legalName: "مورد اختباري جديد", displayName: "مورد اختباري", country: "السعودية", city: "جدة", categories: ["اختبار"], contactName: "شخص تجريبي", phone: "0500000000", email: "new-supplier@example.com" };

describe("local procurement repository", () => {
  it("isolates organizations and blocks IDOR", () => { expect(() => repo.snapshot(org, "u-other")).toThrowError(ProcurementError); expect(() => repo.transitionSupplier(org, "u-owner", "sup-other", "suspended", "x")).toThrowError(/Cross-organization/); });
  it("applies role permissions and hides sensitive financials", () => { expect(() => repo.createSupplier({ ...supplierInput, actorId: "u-viewer" })).toThrowError(/Missing permission/); expect(() => repo.snapshot(org, "u-service")).toThrowError(/access denied/i); const view = repo.snapshot(org, "u-sales"); expect(view.budgets[0].totalMinor).toBe(0n); expect(view.purchaseOrders[0].lines).toEqual([]); });
  it("detects duplicate suppliers", () => { repo.createSupplier(supplierInput); expect(() => repo.createSupplier(supplierInput)).toThrowError(/duplicate/i); });
  it("requires maker-checker for supplier approval", () => { const supplier = repo.createSupplier(supplierInput); repo.transitionSupplier(org, "u-admin", supplier.id, "pending_review"); expect(() => repo.transitionSupplier(org, "u-admin", supplier.id, "approved")).toThrowError(/Maker-checker/); expect(repo.transitionSupplier(org, "u-owner", supplier.id, "approved").status).toBe("approved"); });
  it("prevents over-budget requisitions without override", () => { expect(() => repo.createRequisition({ organizationId: org, actorId: "u-admin", projectId: "project-1", contractId: "ctr-1", costCenterId: "center-projects", budgetId: "bud-1", currency: "SAR", needByDate: "2026-09-01", justification: "اختبار ميزانية", description: "قيمة تتجاوز المتاح", quantityMills: 1000n, unitPriceMinor: 100_000_000n, costCodeId: "cc-materials", idempotencyKey: "over-budget" })).toThrowError(/Budget exceeded/); });
  it("allows documented budget override only with permission", () => { const row = repo.createRequisition({ organizationId: org, actorId: "u-owner", projectId: "project-1", contractId: "ctr-1", costCenterId: "center-projects", budgetId: "bud-1", currency: "SAR", needByDate: "2026-09-01", justification: "اختبار تجاوز معتمد", description: "قيمة تتجاوز المتاح", quantityMills: 1000n, unitPriceMinor: 100_000_000n, costCodeId: "cc-materials", overrideReason: "اعتماد استثنائي تجريبي", idempotencyKey: "over-budget-owner" }); expect(row.overBudget).toBe(true); });
  it("enforces idempotency", () => { const input = { organizationId: org, actorId: "u-owner", projectId: "project-1", contractId: "ctr-1", costCenterId: "center-projects", budgetId: "bud-1", currency: "SAR", needByDate: "2026-09-01", justification: "اختبار تكرار", description: "بند جديد", quantityMills: 1000n, unitPriceMinor: 1000n, costCodeId: "cc-materials", idempotencyKey: "same-key" }; repo.createRequisition(input); expect(() => repo.createRequisition(input)).toThrowError(/Duplicate idempotency/); });
  it("prevents duplicate purchase orders from one award", () => { expect(() => repo.createPurchaseOrder(org, "u-admin", "cmp-1", "new-po")).toThrowError(/already created/); });
  it("prevents over-receipt", () => { expect(() => repo.receive({ organizationId: org, actorId: "u-admin", purchaseOrderId: "po-1", lineQuantityMills: 70_000n, qualityStatus: "accepted", idempotencyKey: "over-receipt" })).toThrowError(/exceeds remaining/); });
  it("separates receiver and receipt approver", () => { const receipt = repo.receive({ organizationId: org, actorId: "u-admin", purchaseOrderId: "po-1", lineQuantityMills: 10_000n, qualityStatus: "accepted", idempotencyKey: "receipt-ok" }); repo.transitionReceipt(org, "u-admin", receipt.id, "pending_approval"); expect(() => repo.transitionReceipt(org, "u-admin", receipt.id, "approved")).toThrowError(/Receiver cannot approve/); expect(repo.transitionReceipt(org, "u-owner", receipt.id, "approved").status).toBe("approved"); });
  it("detects duplicate supplier invoices", () => { const input = { organizationId: org, actorId: "u-accountant", supplierId: "sup-1", purchaseOrderId: "po-1", receiptIds: ["grn-1"], supplierInvoiceNumber: "DEMO-INV-1001", invoiceDate: "2026-08-02", dueDate: "2026-09-01", matchType: "three_way" as const, idempotencyKey: "new-duplicate-bill" }; expect(() => repo.createSupplierBill(input)).toThrowError(/Duplicate supplier invoice/); });
  it("runs 3-way matching and recognizes cost once", () => { repo.transitionSupplierBill(org, "u-owner", "sb-1", "approved_internal"); const recognized = repo.transitionSupplierBill(org, "u-owner", "sb-1", "recognized_operationally"); expect(recognized.status).toBe("recognized_operationally"); expect(() => repo.transitionSupplierBill(org, "u-owner", "sb-1", "recognized_operationally")).toThrowError(); expect(repo.costSummary(org, "u-owner", "project-1", "SAR").recognizedMinor).toBe(recognized.eligibleRecognitionMinor); });
  it("recognizes and reverses direct expense through counter-events", () => { repo.transitionExpense(org, "u-owner", "exp-1", "recognized_operationally"); repo.transitionExpense(org, "u-owner", "exp-1", "voided", "إلغاء موثق"); const summary = repo.costSummary(org, "u-owner", "project-1", "SAR"); expect(summary.recognizedMinor).toBe(summary.reversedMinor); });
  it("exports CSV safely", () => { const created = repo.createSupplier({ ...supplierInput, legalName: "=2+2", displayName: "=2+2", email: "formula@example.com" }); expect(created.legalName).toBe("=2+2"); expect(repo.exportSuppliers(org, "u-owner")).toContain("'=2+2"); });
  it("does not claim Supabase implementation", () => { expect(() => new SupabaseProcurementRepository().snapshot()).toThrowError(/not implemented or integration-tested/); });
});
