import { calculateDocument } from "./calculations";
import type { MoneyLine, ProcurementData, ProcurementRole, ProcurementUser } from "./types";

export const PROCUREMENT_PERMISSIONS = [
  "procurement.dashboard.view", "suppliers.view", "suppliers.create", "suppliers.update", "suppliers.submit", "suppliers.approve", "suppliers.suspend", "suppliers.export", "cost_codes.view", "cost_codes.manage", "budgets.view", "budgets.create", "budgets.update_draft", "budgets.submit", "budgets.approve", "budgets.revise", "budgets.view_financials", "purchase_requests.view", "purchase_requests.create", "purchase_requests.submit", "purchase_requests.approve", "purchase_requests.cancel", "rfqs.view", "rfqs.create", "rfqs.approve", "rfqs.issue_internal", "supplier_quotes.view", "supplier_quotes.create", "supplier_quotes.evaluate", "bid_comparisons.view", "bid_comparisons.create", "bid_comparisons.approve", "purchase_orders.view", "purchase_orders.create", "purchase_orders.approve", "purchase_orders.issue_internal", "purchase_orders.revise", "purchase_orders.cancel", "purchase_orders.view_financials", "receipts.view", "receipts.create", "receipts.approve", "receipts.reverse", "supplier_bills.view", "supplier_bills.create", "supplier_bills.match", "supplier_bills.approve", "supplier_bills.recognize", "expenses.view", "expenses.create", "expenses.submit", "expenses.approve", "expenses.recognize", "cost_reports.view", "cost_reports.export", "profitability.view", "profitability.view_sensitive", "procurement.override_budget", "procurement.override_tolerance",
] as const;
const read = ["procurement.dashboard.view", "suppliers.view", "cost_codes.view", "budgets.view", "purchase_requests.view", "rfqs.view", "supplier_quotes.view", "bid_comparisons.view", "purchase_orders.view", "receipts.view", "supplier_bills.view", "expenses.view", "cost_reports.view"];
const without = (...blocked: string[]) => PROCUREMENT_PERMISSIONS.filter(x => !blocked.includes(x));
export const procurementPermissionsByRole: Record<ProcurementRole, string[]> = {
  owner: [...PROCUREMENT_PERMISSIONS], admin: without("procurement.override_budget", "procurement.override_tolerance"), accountant: [...read, "supplier_bills.create", "supplier_bills.match", "supplier_bills.approve", "supplier_bills.recognize", "expenses.create", "expenses.submit", "expenses.approve", "expenses.recognize", "cost_reports.export"], sales_manager: [...read, "profitability.view"], sales_agent: ["suppliers.view", "purchase_requests.view", "profitability.view"], customer_service: [], marketing: [], viewer: read,
};
const org = "org-madar-demo", other = "org-other-demo", now = "2026-08-07T12:00:00.000Z";
const roleUsers = { "u-owner": ["عبدالعزيز الجندي", "owner"], "u-admin": ["مدير النظام التجريبي", "admin"], "u-accountant": ["أحمد فؤاد", "accountant"], "u-sales": ["محمد علي", "sales_manager"], "u-agent": ["ريم خالد", "sales_agent"], "u-service": ["سارة أحمد", "customer_service"], "u-viewer": ["مشاهد تجريبي", "viewer"], "u-marketing": ["مسوق تجريبي", "marketing"] } as const;
const users: ProcurementUser[] = Object.entries(roleUsers).map(([id, [name, role]]) => ({ id, organizationId: org, name, role, permissions: procurementPermissionsByRole[role] }));
users.push({ id: "u-other", organizationId: other, name: "مالك شركة أخرى", role: "owner", permissions: procurementPermissionsByRole.owner });
const line: MoneyLine = { id: "pol-1", description: "توريد ألواح تشطيب داخلية — بيانات تجريبية", quantityMills: 100_000n, unit: "م²", unitPriceMinor: 120_000n, discountBps: 0, taxBps: 1500, feesMinor: 0n, costCodeId: "cc-materials" };
const poTotals = calculateDocument([line]);
const billLine: MoneyLine = { ...line, id: "sbl-1", quantityMills: 40_000n };
const billTotals = calculateDocument([billLine]);
const expenseLine: MoneyLine = { id: "exl-1", description: "نقل عاجل للموقع — تجريبي", quantityMills: 1000n, unit: "خدمة", unitPriceMinor: 35_000n, discountBps: 0, taxBps: 1500, feesMinor: 0n, costCodeId: "cc-logistics" };
const expenseTotals = calculateDocument([expenseLine]);

export function createProcurementSeed(): ProcurementData {
  return {
    users,
    suppliers: [
      { id: "sup-1", organizationId: org, code: "SUP-2026-00001", legalName: "شركة التوريدات النموذجية", displayName: "التوريدات النموذجية", taxNumber: "DEMO-TAX-001", country: "السعودية", city: "جدة", categories: ["مواد تشطيب"], contactName: "مسؤول تجريبي", phone: "+966500000000", email: "demo-supplier@example.com", status: "approved", duplicateKey: "التوريدات-النموذجية|demo-tax-001", recordVersion: 2, createdBy: "u-accountant", approvedBy: "u-owner", createdAt: "2026-07-01T09:00:00.000Z", attachments: [] },
      { id: "sup-2", organizationId: org, code: "SUP-2026-00002", legalName: "مورد أعمال الكهرباء التجريبي", displayName: "مورد الكهرباء", country: "السعودية", city: "الرياض", categories: ["كهرباء"], contactName: "ممثل تجريبي", phone: "+966500000001", email: "electrical-demo@example.com", status: "pending_review", duplicateKey: "مورد-الكهرباء|electrical-demo@example.com", recordVersion: 1, createdBy: "u-admin", createdAt: "2026-08-02T09:00:00.000Z", attachments: [] },
      { id: "sup-other", organizationId: other, code: "SUP-OTHER", legalName: "Other tenant supplier", displayName: "Other tenant", country: "KSA", city: "Riyadh", categories: ["Other"], contactName: "Other", phone: "000", email: "other@example.com", status: "approved", duplicateKey: "other", recordVersion: 1, createdBy: "u-other", createdAt: now, attachments: [] },
    ],
    evaluations: [{ id: "eval-1", organizationId: org, supplierId: "sup-1", periodFrom: "2026-01-01", periodTo: "2026-06-30", quality: 88, delivery: 82, quantityAccuracy: 95, responsiveness: 84, cooperation: 90, commercialCompliance: 86, rejectionCount: 1, delayCount: 2, disputeCount: 0, manualScore: 87, calculatedScore: 87, formula: "متوسط 6 محاور، ثم عرض التقييم اليدوي مستقلًا", notes: "تقييم Seed تجريبي وليس تقييمًا ذكيًا", status: "approved", revision: 1, evaluatedBy: "u-accountant", approvedBy: "u-owner" }],
    costCenters: [{ id: "center-projects", organizationId: org, code: "CC-PRJ", name: "المشاريع", active: true }],
    costCodes: [{ id: "cc-materials", organizationId: org, code: "MAT-100", name: "مواد مباشرة", active: true }, { id: "cc-logistics", organizationId: org, code: "LOG-200", name: "النقل والخدمات اللوجستية", active: true }],
    budgets: [{ id: "bud-1", organizationId: org, number: "BUD-2026-00001-R1", projectId: "project-1", projectName: "مشروع جناح المعرض التجريبي", contractId: "ctr-1", currency: "SAR", status: "approved_baseline", revision: 1, lines: [{ id: "bl-1", costCodeId: "cc-materials", description: "مواد مباشرة", amountMinor: 18_000_000n }, { id: "bl-2", costCodeId: "cc-logistics", description: "نقل وخدمات", amountMinor: 2_000_000n }], totalMinor: 20_000_000n, snapshot: [{ id: "bl-1", costCodeId: "cc-materials", description: "مواد مباشرة", amountMinor: 18_000_000n }, { id: "bl-2", costCodeId: "cc-logistics", description: "نقل وخدمات", amountMinor: 2_000_000n }], recordVersion: 2, createdBy: "u-accountant", approvedBy: "u-owner", createdAt: "2026-06-20T09:00:00.000Z" }],
    requisitions: [{ id: "pr-1", organizationId: org, number: "PR-2026-00001", projectId: "project-1", contractId: "ctr-1", workOrderId: "wo-1", costCenterId: "center-projects", currency: "SAR", requestedBy: "u-admin", needByDate: "2026-08-20", justification: "احتياج معتمد لتنفيذ نطاق تجريبي", status: "converted", lines: [line], totals: poTotals, budgetId: "bud-1", budgetAvailableMinor: 20_000_000n, overBudget: false, recordVersion: 4, createdBy: "u-admin", approvedBy: "u-owner", createdAt: "2026-07-05T09:00:00.000Z" }],
    rfqs: [{ id: "rfq-1", organizationId: org, number: "RFQ-2026-00001", requisitionId: "pr-1", currency: "SAR", supplierIds: ["sup-1"], lines: [line], status: "awarded", closingDate: "2026-07-12", terms: "طلب داخلي تجريبي — لم يرسل خارجيًا", recordVersion: 5, createdBy: "u-admin", createdAt: "2026-07-06T09:00:00.000Z" }],
    quotations: [{ id: "sq-1", organizationId: org, number: "SQ-DEMO-001", rfqId: "rfq-1", supplierId: "sup-1", currency: "SAR", validUntil: "2026-08-31", deliveryDays: 14, paymentTerms: "بيانات وصفية فقط — لا دفع", lines: [line], totals: poTotals, technicalScore: 88, commercialNotes: "عرض مورد Seed", status: "qualified", attachments: [], recordVersion: 2, createdBy: "u-admin", createdAt: "2026-07-10T09:00:00.000Z" }],
    comparisons: [{ id: "cmp-1", organizationId: org, number: "BC-2026-00001", rfqId: "rfq-1", quotationIds: ["sq-1"], currency: "SAR", recommendedQuotationId: "sq-1", awardType: "full", rationale: "مطابقة فنية وسعر ضمن الميزانية — بيانات تجريبية", status: "approved", recordVersion: 2, createdBy: "u-admin", approvedBy: "u-owner", createdAt: "2026-07-13T09:00:00.000Z" }],
    purchaseOrders: [{ id: "po-1", organizationId: org, number: "PO-2026-00001-R1", requisitionId: "pr-1", rfqId: "rfq-1", comparisonId: "cmp-1", supplierQuotationId: "sq-1", supplierId: "sup-1", projectId: "project-1", contractId: "ctr-1", currency: "SAR", status: "partially_received", lines: [line], totals: poTotals, receivedValueMinor: billTotals.totalMinor, billedValueMinor: billTotals.totalMinor, recognizedValueMinor: 0n, revision: 1, snapshot: { supplier: "التوريدات النموذجية", project: "مشروع جناح المعرض التجريبي", notice: "أمر شراء داخلي تجريبي" }, recordVersion: 4, createdBy: "u-admin", approvedBy: "u-owner", issuedAt: "2026-07-15T09:00:00.000Z", createdAt: "2026-07-14T09:00:00.000Z" }],
    receipts: [{ id: "grn-1", organizationId: org, number: "REC-P-2026-00001", purchaseOrderId: "po-1", supplierId: "sup-1", projectId: "project-1", date: "2026-07-30", receiverId: "u-admin", status: "approved", lines: [{ id: "grnl-1", purchaseOrderLineId: "pol-1", quantityMills: 40_000n, qualityStatus: "accepted", notes: "استلام جزئي تجريبي" }], receivedValueMinor: billTotals.totalMinor, attachments: [], recordVersion: 2, approvedBy: "u-owner", createdAt: "2026-07-30T09:00:00.000Z" }],
    supplierBills: [{ id: "sb-1", organizationId: org, number: "SB-2026-00001", supplierInvoiceNumber: "DEMO-INV-1001", supplierId: "sup-1", purchaseOrderId: "po-1", receiptIds: ["grn-1"], projectId: "project-1", contractId: "ctr-1", currency: "SAR", invoiceDate: "2026-08-01", dueDate: "2026-08-31", lines: [billLine], totals: billTotals, eligibleRecognitionMinor: billTotals.totalMinor, matchType: "three_way", matchStatus: "matched", dispute: false, status: "pending_approval", recordVersion: 3, idempotencyKey: "seed-supplier-bill", createdBy: "u-accountant", createdAt: "2026-08-01T09:00:00.000Z" }],
    expenses: [{ id: "exp-1", organizationId: org, number: "EXP-2026-00001", expenseType: "خدمات نقل", projectId: "project-1", contractId: "ctr-1", workOrderId: "wo-1", costCenterId: "center-projects", costCodeId: "cc-logistics", party: "مقدم خدمة تجريبي", date: "2026-08-03", currency: "SAR", description: "نقل عاجل للموقع", paymentMethodLabel: "بيان وصفي فقط", reference: "DEMO-EXP-REF", directPurchaseReason: "قيمة محدودة وحاجة عاجلة", lines: [expenseLine], totals: expenseTotals, status: "approved", recordVersion: 3, idempotencyKey: "seed-expense", createdBy: "u-admin", approvedBy: "u-owner", attachments: [], createdAt: "2026-08-03T09:00:00.000Z" }],
    costEvents: [], approvals: [], timeline: [], notifications: [], tolerances: [{ organizationId: org, quantityBps: 0, priceBps: 100, roundingMinor: 5n, requireThreeWayMatch: true }], sequences: { [`${org}:supplier`]: 2, [`${org}:requisition`]: 1, [`${org}:bill`]: 1, [`${org}:expense`]: 1 }, idempotencyKeys: ["seed-supplier-bill", "seed-expense"],
  };
}
