import type { CurrencyCode, SalesRole } from "@/lib/sales/types";

export type ProcurementRole = SalesRole;
export type SupplierStatus = "draft" | "pending_review" | "approved" | "suspended" | "rejected" | "archived";
export type RequisitionStatus = "draft" | "submitted" | "pending_approval" | "approved" | "rejected" | "converted" | "cancelled";
export type RfqStatus = "draft" | "approved" | "issued_internal" | "quotes_received" | "evaluated" | "awarded" | "cancelled";
export type PurchaseOrderStatus = "draft" | "pending_approval" | "approved" | "issued_internal" | "partially_received" | "fully_received" | "closed" | "cancelled";
export type ReceiptStatus = "draft" | "pending_approval" | "approved" | "reversed";
export type SupplierBillStatus = "draft" | "submitted" | "matching" | "pending_approval" | "approved_internal" | "recognized_operationally" | "returned_for_changes" | "rejected" | "disputed" | "voided";
export type ExpenseStatus = "draft" | "submitted" | "pending_review" | "approved" | "recognized_operationally" | "returned_for_changes" | "rejected" | "voided";
export type MatchStatus = "not_checked" | "matched" | "within_tolerance" | "mismatch";
export type QualityStatus = "accepted" | "conditionally_accepted" | "rejected";
export type MoneyKind = "budget" | "commitment" | "actual" | "forecast";

export interface ProcurementUser { id: string; organizationId: string; name: string; role: ProcurementRole; permissions: string[] }
export interface AttachmentMetadata { name: string; mimeType: string; sizeBytes: number; storageKey?: string }
export interface MoneyLine { id: string; description: string; quantityMills: bigint; unit: string; unitPriceMinor: bigint; discountBps: number; taxBps: number; feesMinor: bigint; costCodeId: string }
export interface DocumentTotals { subtotalMinor: bigint; discountMinor: bigint; taxableMinor: bigint; taxMinor: bigint; feesMinor: bigint; shippingMinor: bigint; totalMinor: bigint }
export interface Supplier { id: string; organizationId: string; code: string; legalName: string; displayName: string; taxNumber?: string; country: string; city: string; categories: string[]; contactName: string; phone: string; email: string; status: SupplierStatus; suspensionReason?: string; duplicateKey: string; recordVersion: number; createdBy: string; approvedBy?: string; createdAt: string; attachments: AttachmentMetadata[] }
export interface SupplierEvaluation { id: string; organizationId: string; supplierId: string; periodFrom: string; periodTo: string; quality: number; delivery: number; quantityAccuracy: number; responsiveness: number; cooperation: number; commercialCompliance: number; rejectionCount: number; delayCount: number; disputeCount: number; manualScore: number; calculatedScore: number; formula: string; notes: string; status: "draft" | "approved" | "revised"; revision: number; evaluatedBy: string; approvedBy?: string }
export interface CostCenter { id: string; organizationId: string; code: string; name: string; active: boolean }
export interface CostCode { id: string; organizationId: string; code: string; name: string; parentId?: string; active: boolean }
export interface BudgetLine { id: string; costCodeId: string; description: string; amountMinor: bigint }
export interface ProjectBudget { id: string; organizationId: string; number: string; projectId: string; projectName: string; contractId: string; currency: CurrencyCode; status: "draft" | "pending_approval" | "approved_baseline" | "superseded"; revision: number; lines: BudgetLine[]; totalMinor: bigint; snapshot?: BudgetLine[]; recordVersion: number; createdBy: string; approvedBy?: string; createdAt: string }
export interface PurchaseRequisition { id: string; organizationId: string; number: string; projectId: string; contractId: string; workOrderId?: string; costCenterId: string; currency: CurrencyCode; requestedBy: string; needByDate: string; justification: string; status: RequisitionStatus; lines: MoneyLine[]; totals: DocumentTotals; budgetId: string; budgetAvailableMinor: bigint; overBudget: boolean; overrideReason?: string; recordVersion: number; createdBy: string; approvedBy?: string; createdAt: string }
export interface ProcurementRfq { id: string; organizationId: string; number: string; requisitionId: string; currency: CurrencyCode; supplierIds: string[]; lines: MoneyLine[]; status: RfqStatus; closingDate: string; terms: string; recordVersion: number; createdBy: string; createdAt: string }
export interface SupplierQuotation { id: string; organizationId: string; number: string; rfqId: string; supplierId: string; currency: CurrencyCode; validUntil: string; deliveryDays: number; paymentTerms: string; lines: MoneyLine[]; totals: DocumentTotals; technicalScore: number; commercialNotes: string; status: "draft" | "submitted" | "qualified" | "disqualified"; attachments: AttachmentMetadata[]; recordVersion: number; createdBy: string; createdAt: string }
export interface BidComparison { id: string; organizationId: string; number: string; rfqId: string; quotationIds: string[]; currency: CurrencyCode; recommendedQuotationId?: string; awardType: "full" | "partial"; rationale: string; status: "draft" | "pending_approval" | "approved" | "rejected"; recordVersion: number; createdBy: string; approvedBy?: string; createdAt: string }
export interface PurchaseOrder { id: string; organizationId: string; number: string; requisitionId: string; rfqId: string; comparisonId: string; supplierQuotationId: string; supplierId: string; projectId: string; contractId: string; currency: CurrencyCode; status: PurchaseOrderStatus; lines: MoneyLine[]; totals: DocumentTotals; receivedValueMinor: bigint; billedValueMinor: bigint; recognizedValueMinor: bigint; revision: number; snapshot: Record<string, string>; recordVersion: number; createdBy: string; approvedBy?: string; issuedAt?: string; createdAt: string }
export interface ProcurementReceiptLine { id: string; purchaseOrderLineId: string; quantityMills: bigint; qualityStatus: QualityStatus; notes: string }
export interface ProcurementReceipt { id: string; organizationId: string; number: string; purchaseOrderId: string; supplierId: string; projectId: string; date: string; receiverId: string; status: ReceiptStatus; lines: ProcurementReceiptLine[]; receivedValueMinor: bigint; attachments: AttachmentMetadata[]; recordVersion: number; approvedBy?: string; reversalReason?: string; createdAt: string }
export interface SupplierBill { id: string; organizationId: string; number: string; supplierInvoiceNumber: string; supplierId: string; purchaseOrderId: string; receiptIds: string[]; projectId: string; contractId: string; currency: CurrencyCode; invoiceDate: string; dueDate: string; lines: MoneyLine[]; totals: DocumentTotals; eligibleRecognitionMinor: bigint; matchType: "two_way" | "three_way"; matchStatus: MatchStatus; dispute: boolean; status: SupplierBillStatus; recordVersion: number; idempotencyKey: string; createdBy: string; approvedBy?: string; recognizedAt?: string; createdAt: string }
export interface DirectExpense { id: string; organizationId: string; number: string; expenseType: string; projectId: string; contractId: string; workOrderId?: string; costCenterId: string; costCodeId: string; party: string; supplierId?: string; date: string; currency: CurrencyCode; description: string; paymentMethodLabel: string; reference: string; directPurchaseReason: string; lines: MoneyLine[]; totals: DocumentTotals; status: ExpenseStatus; recordVersion: number; idempotencyKey: string; createdBy: string; approvedBy?: string; recognizedAt?: string; reversalReason?: string; attachments: AttachmentMetadata[]; createdAt: string }
export interface OperationalCostEvent { id: string; organizationId: string; projectId: string; contractId: string; currency: CurrencyCode; sourceType: "supplier_bill" | "direct_expense" | "reversal"; sourceId: string; amountMinor: bigint; kind: "recognized" | "reversed"; idempotencyKey: string; occurredAt: string }
export interface Approval { id: string; organizationId: string; entityType: string; entityId: string; requestedBy: string; status: "pending" | "approved" | "rejected" | "returned"; decidedBy?: string; comment?: string; createdAt: string; decidedAt?: string }
export interface ProcurementEvent { id: string; organizationId: string; entityType: string; entityId: string; action: string; summary: string; createdBy: string; createdAt: string; links: Record<string, string> }
export interface ProcurementNotification { id: string; organizationId: string; userId: string; type: string; entityType: string; entityId: string; title: string; dedupeKey: string; read: boolean; createdAt: string }
export interface TolerancePolicy { organizationId: string; quantityBps: number; priceBps: number; roundingMinor: bigint; requireThreeWayMatch: boolean }
export interface ProcurementData { users: ProcurementUser[]; suppliers: Supplier[]; evaluations: SupplierEvaluation[]; costCenters: CostCenter[]; costCodes: CostCode[]; budgets: ProjectBudget[]; requisitions: PurchaseRequisition[]; rfqs: ProcurementRfq[]; quotations: SupplierQuotation[]; comparisons: BidComparison[]; purchaseOrders: PurchaseOrder[]; receipts: ProcurementReceipt[]; supplierBills: SupplierBill[]; expenses: DirectExpense[]; costEvents: OperationalCostEvent[]; approvals: Approval[]; timeline: ProcurementEvent[]; notifications: ProcurementNotification[]; tolerances: TolerancePolicy[]; sequences: Record<string, number>; idempotencyKeys: string[] }
export interface CostSummary { currency: CurrencyCode; budgetMinor: bigint; committedMinor: bigint; receivedNotBilledMinor: bigint; billsUnderReviewMinor: bigint; recognizedMinor: bigint; reversedMinor: bigint; remainingCommitmentMinor: bigint; remainingBudgetMinor: bigint; forecastEtcMinor: bigint; forecastEacMinor: bigint; varianceMinor: bigint }
export interface ProfitabilityView { currency: CurrencyCode; currentContractValueMinor: bigint; currentCostBudgetMinor: bigint; recognizedCostMinor: bigint; openCommitmentsMinor: bigint; forecastEtcMinor: bigint; forecastEacMinor: bigint; budgetedGrossMarginMinor: bigint; operationalGrossMarginMinor: bigint; forecastMarginMinor: bigint; marginBps: number | null; warning?: string }
export interface Paged<T> { rows: T[]; page: number; pageSize: number; total: number; pages: number }
